### PR TITLE
[strings] fix czech about page string translations

### PR DESCRIPTION
**Pull request by Grreby**
Signed-off-by: Jan Podhorsky <grreby@proton.me>

### CODE REVIEW

**Comment by biodranik** [comment]
1. Did you edit the file on Windows? Please save it with unix line endings and add another commit on top. 
2. Can you please sign your commit? Check failed action check to see how.

**Comment by Grreby** [comment]
I did save the file locally on Linux and made another commit with one string edited, but I still don't understand how to sign my commits after i made them. When I copy-paste the commands from the DCO failed action, it gives me errors that I cannot solve.

**Comment by biodranik** [comment]
Add DCO signature like in other commits to pr description.

**Review by rtsisyk — APPROVED** [review]

**Comment by rtsisyk** [comment]
I've rebased this PR and pushed as 501ca11ada47cf281586186a45b5d539c48e19a2. Thanks for fixing line endings and adding DCO!

**Pull request closed without merging**
