### PR TITLE
fix linkage with freetype/icu twice on linux

### PR DESCRIPTION
**Pull request by Dushistov**
On linux Qt library depend on icu and freetype,
so OMaps linked with freetype/icu twice:
- static libraries 3rdparty/icu|freetype
- dynamic dependencies from libQtCore/libQtWidgets

this is undefined behavior because of one-definition-rule violation
comment #395

Signed-off-by: Evgeniy A. Dushistov <dushistov@mail.ru>

### CODE REVIEW

**Comment by biodranik** [comment]
Our code uses and loads icu70 dat file. Ubuntu 20, for example, ships with icu66. How it will work?

P.S. There are build errors in Android check.

**Comment by biodranik** [comment]
Also using system libraries, we can't count on specific functions there (if necessary).

Why do you think that the current static + Qt (dynamic) linkage creates undefined behavior? It should be quite defined: our code uses static versions, Qt uses dynamic versions.

**Comment by fgaz** [comment]
> Also using system libraries, we can't count on specific functions there (if necessary).

You could require a minimum version to be present, and distro packagers would take care of that

**Comment by biodranik** [comment]
> > Also using system libraries, we can't count on specific functions there (if necessary).
> 
> You could require a minimum version to be present, and distro packagers would take care of that

No, that won't work. We aim to use the latest versions possible, and it's not the case for many distros.

I don't see any issue with compiling libs statically into the binary. Linker can throw out unused stuff (and we usually don't use many functions from 3party libs).

@Dushistov Any comments about my points in the above comments?

**Pull request closed without merging**
