### PR TITLE
[styles] Change natural=cave_entrance icon

### PR DESCRIPTION
**Pull request by dvdmrtnz**
Using the OSM Carto cave icon for `natural=cave_entrance` icons.

* Closes https://github.com/organicmaps/organicmaps/issues/949

https://www.openstreetmap.org/#map=17/48.01180/16.23009

| Before | After |
|-|-|
|  |  |
|  |  |
|  |  |

### CODE REVIEW

**Review by RedAuburn — APPROVED** [review]
looks good :)

**Review by pastk — APPROVED** [review]

**Comment by map-per** [comment]
No need to do that in this PR, of course, but I think that caves show up way to early. With z11 they even come before mountain peaks. I would suggest z15 as a good starting zoom level

**Comment by biodranik** [comment]
Before mountain peaks is not good, but at the same level should be ok. Caves are a great orienteering point.

**Comment by map-per** [comment]
You are not a hiker are you? Most cave entrances are rather inconspicuous, so I don't know how you can use them for orientation. I've never used one so far.

**Comment by dvdmrtnz** [comment]
I agree that cave_entrances should at least not show up before mountain peaks. Removed caves from z11. Moving them lower can be done later if there is consensus.

**Comment by pastk** [comment]
> I agree that cave_entrances should at least not show up before mountain peaks. Removed caves from z11. Moving them lower can be done later if there is consensus.

Moving caves to z12 is good IMO.

Note that they are shown very early not because of their prominence, but because they're touristic attractions often.
E.g. waterfalls are z11- also and also much less useful for orientation than mountain peaks (but better than caves).

This makes sense for the main style as its more about sight seeing, etc. than for orienteering while hiking. For the latter we'll have an outdoors style.

**Comment by map-per** [comment]
> Note that they are shown very early not because of their prominence, but because they're touristic attractions often.

I wouldn't say that most caves are tourist attractions and according to taginfo only 2.6% of them are tagged with tourism=attraction

> E.g. waterfalls are z11- also and also much less useful for orientation than mountain peaks (but better than caves).

I would reduce the zoom level of waterfalls as well

**Comment by pastk** [comment]
@vng merge?

**Review by vng — APPROVED** [review]

**Comment by biodranik** [comment]
> I wouldn't say that most caves are tourist attractions and according to taginfo only 2.6% of them are tagged with tourism=attraction

In the real world, many caves are interesting objects for tourists.

> I would reduce the zoom level of waterfalls as well

No, that is an important sightseeing landmark. Have you ever traveled and discovered new interesting objects around you with Organic Maps?

**Pull request merged**
