### PR TITLE
better singapore metro icon

### PR DESCRIPTION
**Pull request by RedAuburn**
fixes https://github.com/organicmaps/organicmaps/issues/6928

image1

### CODE REVIEW

**Comment by biodranik** [comment]
Is the circle really needed? It looks like a POI, like a business.

**Comment by hoizan** [comment]
The round icon is bigger and more consistent with the official logo with a green background though in a rectangular shape. Also, it makes the logo stands out more on the map. As Singaporean, I definitely find it well representing the actual signage in SG metro system.

**Comment by RedAuburn** [comment]
There are also aready plenty of other metro icons in OM which are in circles :)

**Comment by biodranik** [comment]
What is the source of icons and their license? Should it be mentioned in our copyright.html?

**Comment by RedAuburn** [comment]
Self drawn after discussion abt licence here: https://github.com/organicmaps/organicmaps/issues/6235

**Review by biodranik — APPROVED** [review]
Thanks! Let it be.

**Comment by hoizan** [comment]
Devs @biodranik @RedAuburn 
It's very much appreciated.
 Happy New Year !

**Pull request merged**
