### PR TITLE
[iOS] 24 vs 12 hour

### LINKED ISSUE #3272: 24 vs 12 hour time
Preferred time system should be consistent.

image
image

### PR DESCRIPTION
**Pull request by lauren1117**
Change time format to be dependent on locale instead of hardcoded to 24 hour system in response to issue #3272

Fixes  #3272

### CODE REVIEW

**Comment by lauren1117** [comment]
Hello, I wanted to apologize for the amount of commits and just overall messiness. I am a student who is still new to using GitHub so I didn't realize my commits were going through as I attempted to add the signoff that I originally forgot. Please let me know if there is any way that I can tidy this up. At this point, I don't want to keep trying things out in case I just make a bigger mess.

**Comment by arnaudvergnet** [comment]
You can use Git's interactive rebase feature from within Android studio to clean up your Git history: https://www.jetbrains.com/idea/guide/tutorials/git-interactive-rebase/introduction/. You can also use it from the command line but using Android Studio is easier if you are a beginner.

Essentially this allows you to move, merge and rename commits to recreate a cleaner history. Once you are happy with the way your history looks, you will need to force push (git push -f) to replace the content of your branch on GitHub with your new local history.

But as your Pull Request (PR) here is small, this is not mandatory. The maintainers can merge your PR using the "Squash commits" feature, and all your commits will be merged as one.

If in the future you work on larger PR, interactive rebase will be very useful so I would recommend you give it a try here to learn how to use it on a simple case.

If you want to learn more on how to use Git, I highly recommend this website: https://learngitbranching.js.org/

**Comment by biodranik** [comment]
Thanks for the contribution! Did you test it? How it looks now? Can you attach a screenshot, please?

**Comment by lauren1117** [comment]
I did test it in the XCode simulator by changing the region to different regions with different time formatting settings, like the US for 12-hour format and France for 24-hour format. I wasn't able to test a user personally toggling from 12 to 24 hrs because that was not an option in the simulation settings. I've attached a screenshot of when the phone is set to the US region which shows that all times show up in the 12-hour format. 
ScreenShot

**Review by biodranik — APPROVED** [review]
Thank you for your contribution!

**Pull request merged**
