### PR TITLE
[android] Ban Vulkan for Mali-T* devices with a custom ROM.

### PR DESCRIPTION
**Pull request by vng**
Follow up https://github.com/organicmaps/organicmaps/pull/9309

- Keep Vulkan renderer for SM-G930F (S7) with the stock Android.
- Ban Vulkan for old Androids (Mali-T*) like S7, S6 and lower with custom Androids (Lineage, Cyanogen).

"Custom ROM" means something not in stock for the device (was rooted and installed something else). ROMUtils.isCustomROM code is heuristic and was inspired by ChatGPT.

### CODE REVIEW

**Comment by pastk** [comment]
What cases does it solve?
In the changes I see only one ref 
> Crash on LineageOS, stock Android works ok (with same api = 1.0.82; driver = 28.0.0).

IMO it doesn't justify a blanket ban for many devices/chipsets and "custom" ROMs (is it Lineage only or indeed for all "custom" ROMs? please define what is a "custom" ROM - any aftermarket?)..

What are the downsides of having some false positives where Vulkan could have been used but is banned by OM? Performance degradation?

**Comment by vng** [comment]
Updated PRs description.
Ideally, we should keep the Vulkan renderer where possible. App UX is better when Vulkan rather than OGL (surface is not recreated when switching Activities).

**Comment by pastk** [comment]
> @todo UPD: Crash on Android 14 (LineageOS), stock Android 12 works ok (with same api = 1.0.82; driver = 28.0.0)

Given that api & driver versions are the same its likely the issue is caused by a different firmware supplied with stock vs Lineage. Some ROMs supply firmware as a part of the distribution, some don't. E.g. a device vendor might supply different firmware versions for the same GPU found in an "etalon" Google device.
Maybe this Lineage version for this device had been updated already and the bug might be gone already..

> "Custom ROM" means something not in stock for the device (was rooted and installed something else).

"Custom" or "stock" isn't really a root cause here. Probably we can say that aftermarket ROMs are somewhat more likely to have bugs as they have smaller user bases and less testing. But it doesn't justify a blanket ban.

> Ideally, we should keep the Vulkan renderer where possible. App UX is better when Vulkan rather than OGL (surface is not recreated when switching Activities).

Then it'd be better to narrow it down as much as possible to this specific Lineage and GPU version, is it possible?

**Comment by vng** [comment]
```"Custom" or "stock" isn't really a root cause here``` It is. I have a bunch of logs for the same devices with different Androids from users. Investigating different ROMs with their ability to work with OM (Vulkan) is not possible at any reasonable time-efforts.

**Review by biodranik — APPROVED** [review]

**Comment by matkoniecz** [comment]
> Crash on LineageOS, stock Android works ok (with same api = 1.0.82; driver = 28.0.0).

is it reported to LineageOS? Or is it pointless as previous bugs were not acted on or that version is EOLed by them?

**Pull request merged**
