### PR TITLE
[android] removed duplicating top panel for place page

### LINKED ISSUE #447: Remove a duplicate top panel in the place page
A feedback from GPlay user:

Screenshot_20210524-113720_Organic Maps (Beta)

### PR DESCRIPTION
**Pull request by Endem10n**
[android]
closes #447 
Signed-off-by: Dzmitry Yarmolenka <dzmitry.yarmolenka.1986@gmail.com>

### CODE REVIEW

**Comment by Endem10n** [comment]
Possibly, some time ago some additional info about the object was displayed at top panel, or planned to display. But it's only my suggestion. Now this toolbar just shows completely duplicating info from bottom sheet and user has a little bit less map on the screen because of it.

**Review by vng — APPROVED** [review]

**Comment by vng** [comment]
Probably, it is left from ancient API times .. I'd test here:
- Open shared links
- Basic search

**Comment by biodranik** [comment]
@vng it would be great to support the API again. You're right, that could be the case: to show a different text at the top + a back button which returns into the calling app.

**Comment by biodranik** [comment]
In any case, the top panel should not be visible in normal situations.

**Comment by vng** [comment]
Когда (если) будет АПИ я бы возвращал это заново кодируя. Теперь это анахронизм и даже непонятно как его проверить.

**Comment by rtsisyk** [comment]
@Endem10n thanks for the contribution!

**Comment by kikuok** [comment]
Hello, why hasn't this been fixed yet? When to expect a version without a top duplicate panel? 
I also really want to ask you to swap the search button and the button for creating a route, please !!! It was in the old version and very handy. If this is not possible, then tell me how to do it (what change)

**Comment by biodranik** [comment]
Updates with this PR are already in stores.

Are you left-handed? Which button do you use more often?

The XML with buttons should be somewhere in android/res/layout

**Comment by kikuok** [comment]
Thanks for the answer. I'm left-handed. Now I tried again and this search location is also very good, maybe I was wrong. I would like to ask if it is possible to remove the darkening of the top of the map. It would be very helpful. Also is it possible to remove the compass and scale button? It can be distinguished as separate functions and people can turn it on at will in settings. It would be great because many people and I love the full size map without unnecessary labels.If this is not possible, can you tell me where the file with the scale and compass is so that I can delete it? Thank you.

**Comment by biodranik** [comment]
That's not as simple, but can be done if the code which hides other elements will also hide the system toolbar, ruler, and compass. Please create a separate issue for that.

**Pull request merged**
