### PR TITLE
Add missing string amenity.events_venue #2872

### PR DESCRIPTION
**Pull request by csidirop**
Added missing strings for amenity.events_venue like asked in issue #2872 .

Not sure if I insert it correctly, but I added english, german and greek translations. 

Signed-off-by: Christos Sidiropoulos csidirop@runbox.com

### CODE REVIEW

**Comment by csidirop** [comment]
I have no idea why DCO failed again. In case I don't forget, i'll commit with -s through cli instead VS Code git integration next time.

**Comment by biodranik** [comment]
Better translations are generated with "Events Venue" instead of "Event Venue". Also, if you have time, please try to double-check them with DeepL, it has better results, plus it has a proper support for pt and pt-BR:

```
en:Events Venue
ar:ﺙﺍﺪﺣﻷﺍ ﻥﺎﻜﻣ
be:Месца правядзення мерапрыемстваў
bg:Място на провеждане на събития
cs:Místo konání akcí
da:Arrangementssted
de:Veranstaltungsort
el:Χώρος Διεξαγωγής Εκδηλώσεων
es:Lugar de eventos
eu:Ekitaldien Lekua
fa:ﺎﻫﺩﺍﺪﯾﻭﺭ ﯼﺭﺍﺰﮔﺮﺑ ﻞﺤﻣ
fi:Tapahtumapaikka
fr:Lieu d'événements
he:םיעוריא םוקמ
hu:Rendezvények helyszíne
id:Tempat Acara
it:Sede degli eventi
ja:イベント会場
ko:"행사장"
nb:Arrangementssted
nl:Evenementenlocatie
pl:Miejsce wydarzeń
pt:Local de eventos
pt-BR:Local de eventos
ro:Locul evenimentelor
ru:Место проведения мероприятий
sk:Miesto konania podujatí
sv:Evenemangsplats
sw:Ukumbi wa Matukio
th:สถานที่จัดงาน
tr:Etkinlik Mekanı
uk:Місце проведення подій
vi:Địa điểm tổ chức sự kiện
zh-Hans:活动场地
zh-Hant:活動場地
```

**Comment by csidirop** [comment]
DCO check is still failing after letting git sign the commit with -s.  Do you have any idea why this is the case?

**Comment by csidirop** [comment]
> I updated the translations above

And I updated my commits with your corrections. Thanks! Anything more?

**Comment by biodranik** [comment]
I think DCO fails because this commit doesn't have `<>` in the email: https://github.com/organicmaps/organicmaps/pull/2932/commits/96e70d9f8be2ef5ca4fd2145a45ff36146ce69fb
AUTHOR should also match with commit's one. It is possible to edit commits and modify their messages and author, but it's better to make a backup branch before doing it.

**Review by biodranik — APPROVED** [review]
The search can be improved by adding synonyms and a number of letters to hint after. But let's merge it first.

**Pull request merged**
