### PR TITLE
[android] Menu lines made larger and bolder

### LINKED ISSUE #3406: [android] Update map buttons icons
Following https://github.com/organicmaps/organicmaps/pull/3398#issuecomment-1245545063

0. THE IMPORTANT ONE! Location button icons changed and become non-intuitive/different from what it was before. Users will highly likely be confused. Previous icons (non-vertical filled arrow and vertical filled arrow with a vertical line) were very intuitive for corresponding modes. We need to find corresponding icons in vector form or ask someone to draw them.
1. In the market version zoom buttons are brighter in the night mode, but layers and crosshair are a bit darker.
2. `+` and `-` in zoom buttons should be slightly larger.
3. Menu lines should be slightly larger and bolder.
4. Star icon has different shape now, it would be great to find a similar shape :)

### PR DESCRIPTION
**Pull request by pratyaksh1610**
fixes #3406 ( 3. Menu lines should be slightly larger and bolder )

 Menu lines made larger and bolder.

## Before
b

## After
a

### CODE REVIEW

**Comment by arnaudvergnet** [comment]
Can you please test your fix against latest master? https://github.com/organicmaps/organicmaps/pull/3398 changed the menu icon so your fix may not work anymore.

**Comment by biodranik** [comment]
Isn't it _too_ large now?
@arnaudvergnet WDYT?

**Comment by arnaudvergnet** [comment]
Yes I tested I and it only makes the icon bigger. But with the last PR the icon is already big enough, only the lines needs to get bolder. IMO the icon itself should be edited but the size should remain the same to be in line with the other bottom buttons.

**Comment by biodranik** [comment]
@pratyaksh1610 can you please try to edit the icon?

**Comment by pratyaksh1610** [comment]
## Before
WhatsApp Image 2022-09-16 at 12 19 34 AM

## After
WhatsApp Image 2022-09-16 at 12 19 33 AM

**Comment by pratyaksh1610** [comment]
@biodranik I have updated the size , I think it should work.
PTAL.
Thanks.

**Comment by pratyaksh1610** [comment]
Is it ready for merge ?

**Comment by biodranik** [comment]
With the recent changes, it already looks more or less OK. And increasing the image size is not the best way to go anyway. Let's see if our users complain about the menu icon.

**Pull request closed without merging**
