### PR TITLE
Updated Hindi release notes.

### PR DESCRIPTION
**Pull request by ANS-UXI**
#4631: Translated English release notes to Hindi

### CODE REVIEW

**Comment by biodranik** [comment]
Thanks! Can you please reduce a bit the description?
```
❌ android/src/fdroid/play/release-notes/hi-IN/default.txt: too long: got=521, expected=499
```

**Comment by ANS-UXI** [comment]
> Thanks! Can you please reduce a bit the description?
> 
> ```
> ❌ android/src/fdroid/play/release-notes/hi-IN/default.txt: too long: got=521, expected=499
> ```

It's done!

**Comment by biodranik** [comment]
You can check it locally using `tools/python/check_store_metadata.py android` command.

**Comment by ANS-UXI** [comment]
> You can check it locally using `tools/python/check_store_metadata.py android` command.

Oh I see, thanks for informing!

**Review by biodranik — APPROVED** [review]
[🙏](https://emojipedia.org/folded-hands/)

**Pull request merged**
