### PR TITLE
[ios] Undo for the bookmark and tracks deletion

### LINKED ISSUE #4547: [android][ios] Deleting a bookmark needs an undo
**Is your feature request related to a problem? Please describe.**
When accidentally mispressing the screen and deleting a bookmark, I may have no clue what I just deleted. Or I may have deleted something that I put a lot of work in, figuring out whatever it is I need to write in the description field to help me on my way.

The bookmark will be deleted without confirmation, and permanently without the possibility to undo it. This is an antipattern - a destructive operation needs at least either.

In short - a bookmark is silently and permanently deleted. Everyone knows the feeling of accidentally deleting something without the possibility of ever getting it back without recreating it. It's a horrible feeling.

**Describe the solution you would like**
Either or both:
* Confirmation before deleting
* Undo deleting a bookmark

**Describe alternatives you have considered**
* Don't use the app while on the move, when it's easier to mis-tap the screen.
* Don't use the app while feeling weary, drunk, having a headache, with blurry vision, or when distracted.
* When consciously NOT tapping the delete button, be very particulate about staying well away from it, as touchscreens can register a tap at the lightest possible touch that a human would not register one at.

**Additional context**
This is a problem in both contexts:
* In the bookmarks list, holding a bookmark, a menu appears: share, edit, delete. Here, the delete button is close to edit, but also close to the Android back button.
* When selecting a bookmark on the map, a menu appears: route from, delete, route to, share. Here, the delete button can be pressed accidentally from all 4 sides.

In both these situations, a bookmark is silently and permanently deleted. So from a UX perspective, I would almost outright call this a bug, and a pretty severe one at that. But technically it's a feature. But I would probably register it as a pretty darn critical one still.

### PR DESCRIPTION
**Pull request by kirylkaveryn**
Closes #4547 

This PR contains the implementation of Undo for the bookmarks and tracks deletion.
The Undo button was added to the Toast message so the user has 3 seconds to undo deletion.
When a bookmark is created from the map, a deleted list is checked first. If there's already a bookmark at the same coordinates, its info is taken to fill a new bookmark, and it is removed from a "deleted" list.

### Todo:
- [x] Bookmark deletion undo
- [x] Track deletion undo
- [x] Toast message redesign to support Undo button
- [ ] Localize the toast texts
- [ ] ~~When a bookmark is created from the map, a deleted list is checked first. If there's already a bookmark at the same coordinates, its info is taken to fill a new bookmark, and it is removed from a "deleted" list.~~
- [x] Reload the Collections list, Bookmarks list and Place Page when the undo happens

### Screnrecords:

Simulator Screen Recording - iPhone 15 Pro - 2024-05-30 at 14 47 06
Simulator Screen Recording - iPhone 15 Pro - 2024-05-30 at 14 47 23
Simulator Screen Recording - iPhone 15 Pro - 2024-05-30 at 14 47 33
Simulator Screen Recording - iPhone 15 Pro - 2024-05-30 at 14 48 26

### CODE REVIEW

**Comment by biodranik** [comment]
Thanks! How does it work when bookmark is deleted on the map? This is the main case of issues.

**Comment by kirylkaveryn** [comment]
> Thanks! How does it work when bookmark is deleted on the map? This is the main case of issues.

To generalise the BM deletion may be tricky, because we need to store the deleted bookmarks somewhere in code. I'll try to move the undo manager into the bookmarks manager and to add an observer for adding the bookmark.

Should we store them only for some seconds? On during the whole session?

**Comment by biodranik** [comment]
It would be great if the same approach/code could also be reused on Android without many changes. 

One of the ideas was to save all the recently deleted bookmark info so it will be automatically restored back when it's bookmarked again. Then, for example, after someone deletes a bookmark from the map, a toast with the hint "bookmark it again to restore" can be displayed 2 or 3 times. In this case, the bookmark can stay in memory until the app is restarted.

Storing only for some seconds may be more complex than storing for the whole session.

**Comment by kirylkaveryn** [comment]
> Then, for example, after someone deletes a bookmark from the map, a toast with the hint "bookmark it again to restore" can be displayed 2 or 3 times

Maybe do not distract users with additional toasts? It may be annoyng. I think that one with the Undo will be enogh.

> it will be automatically restored back when it's bookmarked again
Such kind of restoring requires == operator to the bookmarks (as we discussed in several topics) to find the bookmark in the recently deleted list (by cooordinates?) and additional logic in the code... Maybe we can skip the "bookmark it again to restore" in the first implementation of this feature?

**Comment by biodranik** [comment]
WDYT about about the following approach?

1. When a bookmark is deleted (on the map or the list, doesn't matter), it is placed into a memory-only list of deleted bookmarks in the C++ core.
2. This memory-only list will be cleared on the app restart.
3. Bookmarks deleted when a whole list is removed should not be cached in this way. Deleted lists should have a different undo mechanism.
4. When a bookmark is created from the map, a deleted list is checked first. If there's already a bookmark at the same coordinates, its info is taken to fill a new bookmark, and it is removed from a "deleted" list.

There are no any UI changes here, it should just work on both platforms.

**Comment by kirylkaveryn** [comment]
@biodranik @vng  can you please chek the RP?
I've implemented all related to recovery code in c++.

**Comment by biodranik** [comment]
How will it look if the toast message is removed on the map, and the "Save" text on the bottom button changes to "Restore" after a bookmark is deleted (until the selection stays active)?

I'm not sure yet about the undo in the lists. While it looks cool, nobody complained yet so far about it. This deletion requires 2 explicit actions or an explicit Delete button press, so it is highly unlikely to happen accidentally.

Is it possible to review/merge the on-the-map undo part separately?

**Comment by kirylkaveryn** [comment]
> How will it look if the toast message is removed on the map, and the "Save" text on the bottom button changes to "Restore" after a bookmark is deleted (until the selection stays active)?

This feature requires a huge refactoring of the action bar and place page data in the core... I can try to implement it.

**Comment by oleg-rswll** [comment]
@kirylkaveryn the approach with the bookmark delete undo in the toast looks like a great approach!  It preserves the existing flow, and the toast is unintrusive and helpful.

**Comment by oleg-rswll** [comment]
@kirylkaveryn can we do the same thing in the Place Page?

**Review by biodranik — CHANGES_REQUESTED** [review]
Note that https://github.com/organicmaps/organicmaps/pull/8352 implements Undo for accidental bookmarks deletion in the Place Page in a better/simpler way.

The higher priority task is to avoid accidental deletion (or implement undo) for a whole list of bookmarks.

After it is implemented, we can come back to this issue and re-evaluate it, considering that there were _no_ any user complaints about accidentally deleting bookmarks or tracks from lists (it requires an explicit user action, so the chance of doing it accidentally is extremely low, compared to accidental removal of a list or accidental removal of a bookmark on the Place Page).

**Comment by biodranik** [comment]
While the idea looks good, in reality, we didn't have any complaints about it. This PR is not rejected, it is postponed until we get a better understanding of the real user needs.

**Comment by oleg-rswll** [comment]
Doing undo by adding a bookmark again is essentially hiding the functionality, there is no way to discover that this is actually intended as an undo feature.  Even if someone does discover it by accident, the behavior is more similar to a bug rather than a feature.

The thinking process may be "I deleted an old bookmark because I didn't need it anymore.  Then wanted to add it, just in case, but for some reason it did't clear my old notes."

**Comment by biodranik** [comment]
We discussed with Kiryl that using undo toasts is not a common pattern on iOS. The toast makes information under it inaccessible, and elements untappable. And there is a higher priority issue when a whole list of tracks and bookmarks is deleted accidentally.

We can return to this PR when the priority of this issue will change.

**Comment by kirylkaveryn** [comment]
> Let's decide whether to merge this PR or close it. I am fine with closing it as long as deleted items will move to the Recently Deleted screen,

@rtsisyk I agree - lets close this one. It seems like the approach with the toasts isn't the best.

**Pull request closed without merging**
