### PR TITLE
better farmyard & garage landuse styles

### PR DESCRIPTION
**Pull request by RedAuburn**
Fixes https://github.com/organicmaps/organicmaps/issues/4694 & https://github.com/organicmaps/organicmaps/issues/3766

landuse=garages
before | clear | vehicle
image1

landuse=farmyard
before | clear | vehicle
image2

### CODE REVIEW

**Comment by dvdmrtnz** [comment]
Looks good! Can you add rendering for `landuse=residential` too? https://github.com/organicmaps/organicmaps/issues/2873

**Review by biodranik — APPROVED** [review]
Cool! LGTM

**Review by pastk — APPROVED** [review]

**Comment by RedAuburn** [comment]
rebased

**Comment by RedAuburn** [comment]
rebased

**Review by biodranik — APPROVED** [review]

**Pull request merged**
