### PR TITLE
Removed Windows 10 manual boost library initialization from INSTALL.md

### PR DESCRIPTION
**Pull request by ANS-UXI**
Removed Windows 10: Manual Boost library initialization from INSTALL.md

### CODE REVIEW

**Comment by biodranik** [comment]
I do not understand why it shows an already made change. Are you familiar with `git rebase` tool? Can you please learn it, and rebase your branch on top of our master branch, so your change will have only one commit with a relevant change?

**Comment by biodranik** [comment]
Also, please learn how to `git commit -s` or `git commit --signoff` your commits by reading failed Github DCO Check for this PR.

**Comment by ANS-UXI** [comment]
> I do not understand why it shows an already made change. Are you familiar with `git rebase` tool? Can you please learn it, and rebase your branch on top of our master branch, so your change will have only one commit with a relevant change?

On my way!

**Review by biodranik — COMMENTED** [review]
Did you learn how to rebase your branch on top of the master?

**Comment by ANS-UXI** [comment]
> Did you learn how to rebase your branch on top of the master?

Im learning and I guess I did something wrong. I'm really confused right now!
When I try to rebase merge conflicts arises and in interactive mode I was squashing some commits into one but I don't know how everyones commit got added here, what should I do next?

**Comment by biodranik** [comment]
Try to remove all unnecessary commits in the interactive mode except the useful one.

**Comment by ANS-UXI** [comment]
> This pull request shows 12 commits. It should show only one. Did you try to get the latest master of the main repo, and `git rebase organicmaps/master` (where organicmaps is our repo/remote name)?

Is it fine now?

**Comment by ANS-UXI** [comment]
> Thanks! Now you've learnt how we are working with our code in Organic Maps :)

Your welcome🙏🏻, even I look forward to learning and contributing more to the org!

**Pull request merged**
