### PR TITLE
[strings] translate all strings to Hebrew

### PR DESCRIPTION
**Pull request by NeatNit**
Went over all of strings.txt and translate pretty much all untranslated strings, as well as corrected a bunch of existing ones. I had to skip a small few - color names in particular are well beyond my abilities!

As I went through the whole file, I wrote down some notes, comments, suggestions, and childish nitpicks I noticed throughout. I'll open an issue for that soon.

### CODE REVIEW

**Comment by NeatNit** [comment]
Ah... I see my choice to spell out "one bookmark" instead of "1 bookmark" etc. didn't pass testing. Unfortunate, as it doesn't feel right with digit 1.

**Comment by biodranik** [comment]
Using %d looks more succinct and consistent for users. You can add a commit on top of this one with your changes, or edit the existing commit if you're familiar with git rebase.

**Comment by NeatNit** [comment]
> Using %d looks more succinct and consistent for users (they see `1 bookmark` and then they see in the same place `2 bookmarks`). You can add a commit on top of this one with your changes, or edit the existing commit if you're familiar with git rebase/amend.

Done, with a new commit.

Part of my dislike of it is that in Hebrew grammar, 1 is an exception - in the phrase "one thing" the "one" comes after "thing" (i.e. "thing one"), but for all other numbers the number comes before ("%d things"). So the position of the number is already slightly off from where it would be in other cases. But nevermind, I see the reasoning.

**Review by biodranik — APPROVED** [review]
Thank you for your contribution! That's a lot of work, and a great New Year present to all Hebrew-speaking users of Organic Maps.

**Pull request merged**
