### PR TITLE
Add drinking water icons to place page

### PR DESCRIPTION
**Pull request by dvdmrtnz**
This PR adds `drinking_water-yes`/ `drinking_water-no` types. This prevents drinking water from showing as the main type when it is not. Also I added an icon to the place page to know if water is drinkable or not.

* Fixes https://github.com/organicmaps/organicmaps/issues/7431
* Related to https://github.com/organicmaps/organicmaps/issues/7127
* Related to https://github.com/organicmaps/organicmaps/issues/4953

Before/After:

https://osm.org/go/xcXjyjJo-?m=

 

https://osm.org/go/xcW9ntIn-?m=

### CODE REVIEW

**Comment by biodranik** [comment]
@vng isn't it a _kostyl_ instead of sorting types and providing the main one as the first one?

**Comment by vng** [comment]
Well, this solution is ok, because it gives an additional bounty like storing drinking_water=no flag (for toilets, fountains, wells, ...)

Also, we still should distinguish _main_ and _other_ types.

Once we already go with toilet=yes/no, drinking_water is similar to it.

**Comment by biodranik** [comment]
> Once we already go with toilet=yes/no, drinking_water is similar to it.

There is always a way back, to do it properly.

> IDK, honestly. On the one hand, it looks reasonable, on the other hand, we make types duplicating (drinking_water=yes and amenity=drinking_water). Next will be atm=yes/no? :)

Exactly. Supporting many duplicate types everywhere in styles instead of simply adding sorting... ridiculous!

**Comment by pastk** [comment]
Types sorting is not a solution here as it doesn't allow distinguishing between potable / non-potable water.

The only downside of this PR is that it doesn't allow different map icons for potable / non-potable.

**Review by pastk — APPROVED** [review]

**Review by vng — APPROVED** [review]

**Comment by biodranik** [comment]
What is the value of drinking_water=no for our users? Should it be visible on the map or searchable?

**Comment by pastk** [comment]
> What is the value of drinking_water=no for our users? Should it be visible on the map or searchable?

It should be visible (with a different icon) and searchable in the Outdoors style for sure. When drinking water is scarce then non-potable one comes in very handy to clean dishes, equipment, etc. And sometimes one has no other choice than to turn non-potable water into drinkable somehow :)

For the main style non-potable water sources could be displayed with reduced visibility (e.g. a water well as a landmark).

**Pull request merged**
