### PR TITLE
[strings] Spanish (es) translation update

### PR DESCRIPTION
**Pull request by gpesquero**

### CODE REVIEW

**Review by biodranik — APPROVED** [review]
¡Gracias for your contribution!

**Comment by biodranik** [comment]
@gpesquero can you please either sign the commit, or (if you can't), sign the Pull Request description with DCO, by adding a comment line like this one:

`Signed-off-by: Your Name <your@email.com>`

**Comment by gpesquero** [comment]
Hello @biodranik ... I've already signed the commit...

**Comment by biodranik** [comment]
Thank you for the fast reaction )

**Pull request merged**
