### PR TITLE
[styles] Make ford-m.svg more visible

### PR DESCRIPTION
**Pull request by dvdmrtnz**
Make ford-m.svg more visible

* Fixes https://github.com/organicmaps/organicmaps/issues/8898

---

Before/after:

### CODE REVIEW

**Review by biodranik — APPROVED** [review]
Thanks! Did you correct icons yourself?

**Comment by dvdmrtnz** [comment]
Yes! The new icon was created by me.

**Review by vng — APPROVED** [review]
Please, rebase.

**Comment by dvdmrtnz** [comment]
Rebased

**Pull request merged**
