### PR TITLE
Translated to Turkish

### PR DESCRIPTION
**Pull request by MetehanOzyurek**
Signed-off-by: MetehanOzyurek <metehanc8s9@hotmail.com>

### CODE REVIEW

**Comment by biodranik** [comment]
Why en file/symlink is deleted?

**Comment by MetehanOzyurek** [comment]
Ohh, sorry :'(

**Review by biodranik — COMMENTED** [review]
Here also en-US is deleted. Why?

**Comment by MetehanOzyurek** [comment]
I made some mistakes. (I am on mobile) I will translate again.

**Pull request closed without merging**
