### PR TITLE
Make water lines the same colour as area

### PR DESCRIPTION
**Pull request by endim8**
Before/after
signal-2022-11-29-201013_002

before/after
signal-2022-11-29-212942_002

### CODE REVIEW

**Comment by endim8** [comment]
(changed to all types of water line)

**Comment by vng** [comment]
- Can't say is it really needed or not, but we've lost middle (core) blue river line.
- How contrast will be small steams that are defined by OSM way only with this new light-blue color? Please add some screenshots.

**Comment by endim8** [comment]
> * Can't say is it really needed or not, but we've lost middle (core) blue river line.

yes, i think it isn't really needed when mapped as an area. The labels are still there though which is the useful bit

> * How contrast will be small steams that are defined by OSM way only with this new light-blue color? Please add some screenshots.

mmm, way-only contrast isn't good :/ is there a way to mark ways within areas in the generator? then the darker colour could be used for way-only waterways

Before / After
signal-2022-12-03-154352_002

**Comment by endim8** [comment]
Note to self: render waterline lowerthan area instead of change colour

**Comment by vng** [comment]
> Note to self: render waterline lower than area instead of change colour

Well, I think it's possible, but may be _very_ tricky (probably need to modify styles generating tool). We have a basic constraint that area objects a much lower in priority than all others ..

**Comment by endim8** [comment]
closing because possibly more effort than it's worth :(

**Pull request closed without merging**
