### PR TITLE
[WIP] Fixed QT deprecation warnings

### PR DESCRIPTION
**Pull request by biodranik**

### CODE REVIEW

**Review by vng — APPROVED** [review]

**Comment by vng** [comment]
Did you compile your changes? :)

**Comment by biodranik** [comment]
Yes, but there are older QT versions everywhere, including Github CI :( So our options are:
1. Require at least QT version 6.4
2. Silence this warning locally with pragma
3. Silence this warning globally for whole qt project
4. Rewrite the code without a warning but with more lines of code/a bit uglier way.

**Comment by Ferenc-** [comment]
> older QT versions everywhere, including Github CI

Since https://github.com/organicmaps/organicmaps/pull/8193 the CI has Qt `6.4.2`, so you could consider a rebase.

**Comment by biodranik** [comment]
@alkino @Ferenc- @pastk PTAL, can you please also update INSTALL.md with min Qt 6.4 requirement and appropriate link to the PPA?

**Comment by pastk** [comment]
There is no qt6.4 ppa for my aged Ubuntu 18.04 (only qt6.2). But I'll upgrade to 24.04 soon anyway.

**Pull request merged**
