### PR TITLE
[strings] Fixed sound.txt

### PR DESCRIPTION
**Pull request by Nimausfi**

### CODE REVIEW

**Comment by Jean-BaptisteC** [comment]
Please update translations in this file https://github.com/organicmaps/organicmaps/blob/master/data/strings/sound.txt
Json file is only update with regeneration script, more information here https://github.com/organicmaps/organicmaps/blob/master/docs/TRANSLATIONS.md

**Comment by Jean-BaptisteC** [comment]
Can you remove change in JSON file ?

**Comment by Nimausfi** [comment]
> Can you remove change in JSON file ?

Sure, would it be okay to undo changes to the JSON file and commit?

**Comment by Jean-BaptisteC** [comment]
You can amend your commit, remove changes in JSON file push changes and rebase

**Comment by biodranik** [comment]
You can add a new commit where you remove a file. We will squash it.

**Comment by Nimausfi** [comment]
This PR is closed accidentally, I will create a new PR and commit from a new branch

**Comment by biodranik** [comment]
Please try to avoid creating new PRs. Update the branch, force-push it and reopen PR.

**Review by biodranik — APPROVED** [review]
You've just done that. Thank you for your contribution!

@Jean-BaptisteC thank you too for your guidance and support!

**Pull request merged**
