### PR TITLE
Separate Icon for parcel_locker

### PR DESCRIPTION
**Pull request by map-per**
I changed the rendering of parcel_locer form the mail-m Icon to the vending-m icon.
I think that the current mail Icon isn't intuitive as a parcel_locker has nothing to do with letters. Is using the vending icon a good idea or would it be better to use a new/separate icon?

Thanks for reviewing this PR!

#### Rendering examples:
 
Screenshot_20230501_115132
Screenshot_20230501_115216
Screenshot_20230501_115235
Screenshot_20230501_115304

### CODE REVIEW

**Review by biodranik — COMMENTED** [review]
1. Vending icon is not perfect for vending machines. Can it be improved ?
2. Vending icon doesn't fit for locker too. What are other maps using?

**Comment by map-per** [comment]
Maybe something like this as an icon for parcel_locker?
Design ohne Titel

**Comment by map-per** [comment]
Here is a svg version that fits to the other OM icons:

parcel_locker-m

parcel_locker-m(2)

**Comment by biodranik** [comment]
Isn't it too detailed for 18x18 pixel icons? Maybe make it simpler?

**Comment by map-per** [comment]
Simpler version:

parcel_locker-m
parcel_locker-m

**Comment by biodranik** [comment]
Is it recognizable? Looks like a fortress, no? :)

image

**Comment by map-per** [comment]
I think it's recognizable, I can't see a fortress in this icon. :smile:

**Comment by map-per** [comment]
#### New rendering examples:
For this resolution the icon is too small. But on a phone it should look good, similar to the vending icon.

Screenshot_20230506_204445
Screenshot_20230506_204420
Screenshot_20230506_204508
Screenshot_20230506_204532

**Comment by biodranik** [comment]
1. Why is it in a circle? We usually use circles for businesses with several exceptions.
2. The PR should be rebased (don't forget to delete the regenerated commit before the rebase and then regenerate it back again).
3. Icon is not recognizable, but I understand that it's hard to find a good one.

Maybe something like this, but simpler? 2 or 4 lockers?
image

**Comment by map-per** [comment]
1) I considered parcel_locker to be in the "[others](https://github.com/organicmaps/organicmaps/wiki/Icons)" categorey. And most other icons there have a circle. But if you don't want a circle I can remove it as well.

2) Ok, will do that next time

3) What do you mean with not recognizable? That the Icon can't be identified as a parcel_locker or that the icon is too small and therefore not cognizable?
The problem I see with your suggestion is that it rather looks like an amenity=locker

**Comment by biodranik** [comment]
(1) "Most other icons have a circle" — because they are some kind of businesses with employees. Lockers are autonomous machines, and they don't need a circle.
(3) You're right. I would suggest to use a completely different type of icon, similar to OSMCarto (or even to reuse it):
image

**Comment by map-per** [comment]
Yes, a different icon is probably the best. 
How about carto with rounded linecap:
parcel_locker
parcel_locker

**Comment by biodranik** [comment]
Looks good! Let's try it, so everyone can build this branch and test it on different devices.

**Comment by map-per** [comment]
New rendering examples:

Screenshot_20230507_175222
Screenshot_20230507_175239
Screenshot_20230507_175258
Screenshot_20230507_175320

**Comment by map-per** [comment]
OK, synced the fork and updated the icon. The OSMcarto icon looks really nice!

**Comment by biodranik** [comment]
Thanks! Colors are exactly the same as for other similar icons without a circle, right?

**Comment by map-per** [comment]
Yes, I copied the colours from vending-m.svg

**Comment by biodranik** [comment]
Looks great! Can you please sign-off commits properly?

**Comment by map-per** [comment]
Ok, signed off with a valid Email address.

**Review by biodranik — APPROVED** [review]
Thank you very much!
LGTM
@vng merge?

**Comment by map-per** [comment]
Two more questions:
- should OSMCarto be mentioned as an icon source in copyright.html? OSMCarto is CC0 but giving credit is always good.
- Wouldn't it be better do display brand and ref instead of the name
(OSMCarto does it this way: `CONCAT_WS(E'\n', COALESCE(tags->'brand', tags->'operator', name), ref)` 
So the first not null out of {brand, operator, name} ist taken and concatenated with ref)

**Review by vng — APPROVED** [review]

**Comment by map-per** [comment]
🎉

**Pull request merged**
