### PR TITLE
[Linux] Allow to change source directory name

### LINKED ISSUE #3058: [Linux Desktop] Application crashes if name of source code directory differs from default value
The bug occurs in the following circumstances:
- source directory has name, different from 'organicmaps' ('source' in my case);
- application is launched outside of the source code folder.

Log is attached
log
Application was built from [[98c5c1b1]](https://github.com/organicmaps/organicmaps/commit/98c5c1b1c05ae3e963a5e0637c246589ed23b736)
OS: Ubuntu 22.04

### PR DESCRIPTION
**Pull request by trueTatar**
CMake provides info about source directory at the configuration stage, information is stored in the corresponding header file.
these commits fix #3058

### CODE REVIEW

**Comment by biodranik** [comment]
I don't like the additional cmake dependency in context of other, non-linux platforms.

1. Current implementation copies resources to OMaps.app/Contents/Resources dir (like on Mac). The folder can be either reused or renamed for "resources" dir.
2. I realized that the writable dir should be chosen properly even if no source dir is present. Can you please check the current code and see why it fails?

**Comment by trueTatar** [comment]
- It is actually possible to wrap `configure_file` in if-linux check to make solution platform specific and then source_dir.hpp will be generated only if Linux is detected.
- Possibly you meant this `if` block in platform_linux.cpp, that should assign value to writable dir, but it is skipped because resource dir is also not found in current implementation.


.

**Comment by biodranik** [comment]
Yes, so the proper fix probably should:
1. Copy resources (or maybe even better symlink them, to avoid unnecessary copy operations on each build) in a Linux-friendly way (maybe reuse the current Mac OS code).
2. Use the repo as a writable dir if resources are used from the repo (local development case), and use an external Linux-friendly dir otherwise.

What do you think?

**Comment by trueTatar** [comment]
Indeed, workaround that involves symlink looks acceptable in these circumstances.

**Pull request closed without merging**
