### PR TITLE
Cursor disappears in the input field when the keyboard is hidden on he search page

### PR DESCRIPTION
**Pull request by Lampotrias**
I created KeyboardVisibilityHelper and placed it in the utils package. This class is responsible for tracking keyboard show and hide events. Now, in SearchFragment, the keyboard hide event is caught, and the cursor is hidden accordingly.

issue: https://github.com/organicmaps/organicmaps/issues/3564

https://github.com/user-attachments/assets/612a068a-df52-42e0-8e3a-24141ec09934

### CODE REVIEW

**Review by biodranik — COMMENTED** [review]
Thanks! Is it the best/cleanest way for such issue? 

Introducing a generic helper with some math calculations looks like an overkill. Is there an event when:
- a back button is pressed (that hides the keyboard)
- a keyboard is hidden

?

Maybe resetting the edit field focus at that moment would be enough?

**Comment by Lampotrias** [comment]
>Is it the best/cleanest way for such issue?

Unfortunately, there's no better solution for this task.

> A back button is pressed (that hides the keyboard)

EditText has a callback—onKeyPreIme()—where you can catch the BACK button, but it only receives the actual BACK press, not the one that closes the keyboard.

> A keyboard is hidden

This is exactly the solution I proposed. Starting from Android 11, the code could be more concise, but our minimum SDK version is 21. If you try to google something like "android detect keyboard show/hide," you'll see many variations of this approach.

> Maybe resetting the edit field focus at that moment would be enough?

The main problem is figuring out when the keyboard has hidden from its expanded state.

**Comment by biodranik** [comment]
I've checked other Android apps, and it looks like a consistent system behavior, different to iOS.

Looks like changing this behavior will be unexpected for Android users, and it may make sense to leave it as is. WDYT?

**Comment by Lampotrias** [comment]
> I've checked other Android apps, and it looks like a consistent system behavior, different to iOS.
> 
> Looks like changing this behavior will be unexpected for Android users, and it may make sense to leave it as is. WDYT?

I agree with you, that's exactly how it is—in Android, the focus on the input field is not connected to the visibility of the keyboard, unlike iOS.
It will be fine if we don't change this behavior.

**Comment by biodranik** [comment]
Thanks for the feedback, and sorry for the time spent. I've added a comment in https://github.com/organicmaps/organicmaps/issues/3564#issuecomment-2316899832

**Comment by Lampotrias** [comment]
> Thanks for the feedback, and sorry for the time spent. I've added a comment in [#3564 (comment)](https://github.com/organicmaps/organicmaps/issues/3564#issuecomment-2316899832)

np

**Pull request closed without merging**
