### PR TITLE
[strings] - Adding and improving metadata pt-BR

### PR DESCRIPTION
**Pull request by matheusgomesms**
Hi,

I just added and improved metadata for Portuguese-Brazil (and tried to keep same translations between iPhone and Android strings).

For _what's new_ I already used PR #3003. You can ping me there if there's something else to add (and on next updates, of course).

I couldn't add Symlinked URLs, but feel free to add!

Best,

Signed-off-by: Matheus Correia matheus.gomes03@hotmail.com

### CODE REVIEW

**Review by biodranik — CHANGES_REQUESTED** [review]
❌ iphone/metadata/pt-BR/keywords.txt: too long: got=123, expected=100
❌ android/src/fdroid/play/listings/pt-BR/short-description.txt: too long: got=87, expected=80
❌ android/src/google/play/listings/pt-BR/short-description.txt: too long: got=87, expected=80

**Comment by matheusgomesms** [comment]
> ❌ iphone/metadata/pt-BR/keywords.txt: too long: got=123, expected=100
> ❌ android/src/fdroid/play/listings/pt-BR/short-description.txt: too long: got=87, expected=80
> ❌ android/src/google/play/listings/pt-BR/short-description.txt: too long: got=87, expected=80

Thanks, I fixed those files. Unfortunately I forgot to sign-off all commits, not sure this would be a problem.

**Comment by biodranik** [comment]
Please sync with slightly updated #3003

**Comment by biodranik** [comment]
I added a line about the API. Also, keep in mind that there is a 500 characters limit for release_notes.txt, so the last line was removed.

**Comment by matheusgomesms** [comment]
Great, I updated the release notes per #3303 and kept it to a maximum of 500 chars.

**Review by biodranik — APPROVED** [review]
Thank you for the contribution!

**Pull request merged**
