### PR TITLE
Fix place page corner rounding

### PR DESCRIPTION
**Pull request by tanuva**
Hi, here's my second attempt at fixing place page corners. :)

Apart from the action bar (bottom) corners mentioned in #1675, this also fixes top corners on iPhone-size devices. It also fixes visual glitches within the place page that were caused by corners that actually should not be rounded.

One thing I couldn't conclude so far: I have added code sections that set `view.layer.maskedCorners` to configure which corners don't need rounding. I feel like this *may* be part of the theme (`PlacePageStyleSheet.swift`) to keep all styling configuration in one place. May also lead to even more, very specific styles though. Also that would need extension of the theming code of course.

What do you think?

### CODE REVIEW

**Comment by biodranik** [comment]
Did you test it on X-Max and above devices/simulators, and also on iPads? In dark and light themes?

**Comment by tanuva** [comment]
I did test (both dark and light modes):
- iPhones: 12 mini, 12 Pro Max, SE 3
- iPads: mini 6, Air 5

The build for Xs Max wouldn't compile because it was missing x64 libraries of some components. Not sure what that's about... (I'm on an arm Mac.)

Besides I noticed that OM wouldn't switch between dark and light modes when I toggled them in the simulator (Cmd-Shift-A), even though it was set to 'automatic'. Is that expected?

**Comment by biodranik** [comment]
> The build for Xs Max wouldn't compile because it was missing x64 libraries of some components. Not sure what that's about... (I'm on an arm Mac.)

Can you please share your error? It's strange that you could build for other devices but not for this one.

> Besides I noticed that OM wouldn't switch between dark and light modes when I toggled them in the simulator (Cmd-Shift-A), even though it was set to 'automatic'. Is that expected?

There is a big GitHub issue for that :)

**Review by biodranik — APPROVED** [review]

**Review by vng — APPROVED** [review]

**Comment by tanuva** [comment]
> > The build for Xs Max wouldn't compile because it was missing x64 libraries of some components. Not sure what that's about... (I'm on an arm Mac.)
> 
> Can you please share your error? It's strange that you could build for other devices but not for this one.

Strange. I rebuilt from current master and the build works just fine now. Maybe there was a stray electron messing with my RAM yesterday... So I can say these changes are fine on Xs Max, too.

> > Besides I noticed that OM wouldn't switch between dark and light modes when I toggled them in the simulator (Cmd-Shift-A), even though it was set to 'automatic'. Is that expected?
> 
> There is a big GitHub issue for that :)

Found it. Not a trivial problem as it seems. :)

**Pull request merged**
