### PR TITLE
Make "text-optional: true" default behavior

### LINKED ISSUE #4507: Make "text-optional: true" default behaviour
By default POI's caption is "linked" to its icon and if the caption is displaced this makes the icon disappear too.
This kind of implies that an icon alone is useless without a caption. At the same time, if the same POI type has no text to display, then a lonely icon will be displayed anyway :)
It used by various types, e.g. `aeroway-gate`, `aeroway-terminal`, `amenity-bank`, `amenity-childcare`, `amenity-driving_school`,	`amenity-marketplace`, `barrier-gate` - I see no logic here, looks random.

There is a `text-optional: true` attribute in styles that makes the icon stay in those cases (i.e. only caption disappears). Still, if the icon is displaced, then the caption will go away too. This behavior makes sense. I think we should make all POIs behave like this and there is no need for a "text-optional" attribute at all.
(reasons to add it as an optional attribute instead of default behaviour are unclear https://github.com/mapsme/omim/pull/496)

@biodranik @vng 

Needed-for: #4317

### PR DESCRIPTION
**Pull request by pastk**
Closes #4507.
The kothic change needs to be merged first: https://github.com/organicmaps/kothic/pull/11

I left non-optional behavior for capitals with a star icon only (if capital's caption will be displaced then the icon will disappear too).
main

Any idea why in vehicle style no captions were optional at all?
Maybe to keep less objects on the screen but with more info on them? But anyway there could be an icon w/o a caption if the feature doesn't have a name.

I made them same as in the base style, the change looks good to me. WDYT?
vehicle

### CODE REVIEW

**Comment by biodranik** [comment]
1. I don't see any diff on the right pair of screenshots.
2. Current approach does not pollute the map so much. Was it the original reasoning? Did you check `git blame`?

**Comment by pastk** [comment]
> 1. I don't see any diff on the right pair of screenshots.

There are a few more icons and street names.

> 
>     2. Current approach does not pollute the map so much. Was it the original reasoning? Did you check `git blame`?

I did:
> (reasons to add it as an optional attribute instead of default behaviour are unclear https://github.com/mapsme/omim/pull/496)

**Comment by pastk** [comment]
Rebased.

**Comment by pastk** [comment]
>     2. Current approach does not pollute the map so much. 

If it's of concern then we can always set/increase a default `min-icon-distance` param to ensure icons are not placed too densely to each other.

**Review by vng — APPROVED** [review]

**Comment by biodranik** [comment]
I'm generally ok with this change. But merging it may make the map polluted and less usable than before. Are we ready to proceed with other improvements for the general style in this case?

Did you test it on different devices? How it will look on the highest modern DPI ones?

**Comment by pastk** [comment]
> I'm generally ok with this change. But merging it may make the map polluted and less usable than before. Are we ready to proceed with other improvements for the general style in this case?

Yes, setting a default `min-icon-distance` will be easy.

> 
> Did you test it on different devices? How it will look on the highest modern DPI ones?

This is xxhdpi, visual scale 3:
optional-captions-mia2lite

**Review by biodranik — APPROVED** [review]
Thanks! Not a big difference. Is kothik already merged?

**Comment by pastk** [comment]
> Thanks! Not a big difference. Is kothik already merged?

Yes, so this PR is ready to merge too!

**Pull request merged**
