### PR TITLE
[ios] Add more time in recent track

### PR DESCRIPTION
**Pull request by itfarrier**
This PR implements https://github.com/organicmaps/organicmaps/issues/6462 only for iOS:

- added 3 days duration;
- added 1 week duration;
- added Belarusian, English and Russian translations for them;
- renamed `Day` duration as `OneDay`.

Fix: #6462

### CODE REVIEW

**Comment by biodranik** [comment]
Thanks! Did you test:
1. How much data will it take to store 3 days or a week of points?
2. How is the app slowed down with a week of points present/rendered on the screen?
3. Is the map still usable if you travel/move a lot? Won't points cover all the screen and distract you from everything else on the map?

**Comment by biodranik** [comment]
1. The size can be estimated from existing data size. You can check/log it programmatically on a device or simulator and then multiply by a number of seconds/minutes/hours etc.
2. Battery usage can be tracked/compared on the release build on the same device.
3. By knowing how many points will be stored there (I assume that in the worst case 1 point for 1 second, meaning 60*60*24*7 = 604K points, theoretical maximum for 7 days), you can generate/simulate these points in different coordinates nearby. I think 100-200K points would be enough. And check if the app is still usable (I highly doubt it).

Check the underlying code that stores data to better understand how to simulate a lot of data there.

It would be also great to profile how CPU/GPU usage increases depending on a number of points, and where is the issue in the code that consumes a lot of CPU/GPU, which can be improved.

**Comment by Jean-BaptisteC** [comment]
Can you remove merge branch commits and rebase your branch?

**Comment by Jean-BaptisteC** [comment]
@itfarrier did you check the last commentary of biodranik?

**Comment by biodranik** [comment]
Storing and rendering 36Mb of points can be a huge overhead. A solution could be to apply some kind of simplification algorithm that will remove unnecessary intermediate points and reduce their count.

By the way, did you observe any issues with the app? Was it killed by the system for any reason or was the recent track recorded reliably during the whole week?

**Comment by biodranik** [comment]
So at the moment one point takes 65 bytes of size. Not too bad, but likely could be better.

Rendering each point is a huge overhead, obviously. The way the track is drawn should be changed, maybe we need to render a line instead of points, and also "smooth" the line by removing a lot of points there.

Any additional results would be interesting. Especially comparing OM's battery consumption with and without recording a track.

**Comment by biodranik** [comment]
Thanks! Considering that the DEBUG build may use 5x-20x more CPU, the results are great :) To compare with production a release build should be used...

**Comment by itfarrier** [comment]
> Thanks! Considering that the DEBUG build may use 5x-20x more CPU, the results are great :) To compare with production a release build should be used...

Hello, @biodranik, these are production app battery usage from iPhone 12 mini, iPhone 6s and iPad 6th:
IMG_0003 2
IMG_7632
IMG_7631
IMG_0005
IMG_0004 2
IMG_0004

**Comment by biodranik** [comment]
Thanks! So what are your conclusions and estimates for a weekly long recording? Would 3 days be enough/better?

**Comment by itfarrier** [comment]
> Thanks! So what are your conclusions and estimates for a weekly long recording? Would 3 days be enough/better?

@biodranik, I believe everything is functioning well with the application's performance overall. However, there are a couple of notable issues:

- with the one-week file with data points recorded every second;
- with the device tends to overheat, causing the app to freeze even without recent track recording.

In my opinion, a recent track record of one day is sufficient (this is what I use personally). I only implemented the request for seven days based on an issue that was raised.

Thank you.

P. S. Perhaps we should implement a recent track history feature with the capability to render or export each item from it.

**Comment by biodranik** [comment]
Overheating? Did you observe it in Debug or Release? Only with 7 days of points or also with 1 day of points?

I think that adding 2 days history can be more or less safe. Maybe we can add 3 later.

It is important to filter out many unnecessary points at the same place at least before drawing them, and make the recording stable (does the system kill the app on its own?)

And important to see if the file size can be reduced by analyzing the current format.

Exporting/saving the recent track would be great too.

Please let me know in which area are you interested )

**Comment by itfarrier** [comment]
> Overheating? Did you observe it in Debug or Release? Only with 7 days of points or also with 1 day of points?

Hello, @biodranik, I'm sorry for the inconvenience. My iPhone 12 mini overheats every time I use it in the car, regardless of the app: Waze, Yandex, Google, Apple Maps, or OM. So, the overheating issue is not specific to OM.

> And important to see if the file size can be reduced by analyzing the current format.
> 
> Exporting/saving the recent track would be great too.
> 
> Please let me know in which area are you interested )

I've noticed that we're currently saving a lot of unnecessary information in the file. I'm considering investigating how much we could reduce the file size by only saving essential information such as latitude, longitude, and time.

P.S. I'm new to the OM project and Swift as well, so I'm unsure if I can quickly implement the file export.

**Comment by biodranik** [comment]
We're here to help, don't worry about the complexity, we all love to learn here )

> I've noticed that we're currently saving a lot of unnecessary information in the file.

What exactly is currently stored there? In the context of the upcoming "Track Recorder" feature, we'll need precise track data.

**Comment by itfarrier** [comment]
> We're here to help, don't worry about the complexity, we all love to learn here )
> 
> > I've noticed that we're currently saving a lot of unnecessary information in the file.
> 
> What exactly is currently stored there? In the context of the upcoming "Track Recorder" feature, we'll need precise track data.

App writes to file to each point these parameters: timestamp, latitude, longitude, altitude, speedMpS, bearing, horizontalAccuracy, verticalAccuracy, source. But for render

**Review by biodranik — COMMENTED** [review]
Thanks! This is how points are stored in C++:

```C++
void Pack(char * p, location::GpsInfo const & info)
{  
  MemWrite<double>(p + 0 * sizeof(double), info.m_timestamp);
  MemWrite<double>(p + 1 * sizeof(double), info.m_latitude);
  MemWrite<double>(p + 2 * sizeof(double), info.m_longitude);
  MemWrite<double>(p + 3 * sizeof(double), info.m_altitude);
  MemWrite<double>(p + 4 * sizeof(double), info.m_speedMpS);
  MemWrite<double>(p + 5 * sizeof(double), info.m_bearing);
  MemWrite<double>(p + 6 * sizeof(double), info.m_horizontalAccuracy);
  MemWrite<double>(p + 7 * sizeof(double), info.m_verticalAccuracy);
  ASSERT_LESS_OR_EQUAL(static_cast<int>(info.m_source), 255, ());
  uint8_t const source = static_cast<uint8_t>(info.m_source);
  MemWrite<uint8_t>(p + 8 * sizeof(double), source);
}

void Unpack(char const * p, location::GpsInfo & info)
{
  info.m_timestamp = MemRead<double>(p + 0 * sizeof(double));
  info.m_latitude = MemRead<double>(p + 1 * sizeof(double));
  info.m_longitude = MemRead<double>(p + 2 * sizeof(double));
  info.m_altitude = MemRead<double>(p + 3 * sizeof(double));
  info.m_speedMpS = MemRead<double>(p + 4 * sizeof(double));
  info.m_bearing = MemRead<double>(p + 5 * sizeof(double));
  info.m_horizontalAccuracy = MemRead<double>(p + 6 * sizeof(double));
  info.m_verticalAccuracy = MemRead<double>(p + 7 * sizeof(double));
  uint8_t const source = MemRead<uint8_t>(p + 8 * sizeof(double));
  info.m_source = static_cast<location::TLocationSource>(source);
}

```

Each point takes 65 bytes. The data can be packed more tightly to be always stored also in memory and to be processed more efficiently. Saving a track from these already collected points can be as simple as marking start and end points on it.

Which fields are required to be stored/supported in GPX and KML formats? 
CC @cyber-toad @kavikhalique @rtsisyk

**Comment by biodranik** [comment]
@rtsisyk slow rendering has also been reported during the tests. Did you miss it?

**Comment by biodranik** [comment]
@rtsisyk it was mentioned here: https://github.com/organicmaps/organicmaps/pull/7951#issuecomment-2105681018

**Comment by itfarrier** [comment]
@biodranik and @rtsisyk, given the performance issues discussed above, I kindly suggest that we close this PR and the related issue for now.

**Comment by biodranik** [comment]
This PR can stay as a base for performance-testing. It would be great to record a long track and describe how to put it locally to measure the performance.

After we fix the performance, this change can be introduced.

@itfarrier are there other apps that can record/display a similar recent track for a week? How is it rendered?

Regarding the performance:
- Drawing circles takes more resources than drawing squares or rectangles (less triangles to render)
- Drawing less objects should be faster than drawing many objects (circles)
- While all original, unfiltered points can be stored in a file, rendering may use only a limited filtered number of points to draw less objects.

CC @kavikhalique @rtsisyk @vng

**Comment by itfarrier** [comment]
> This PR can stay as a base for performance-testing. It would be great to record a long track and describe how to put it locally to measure the performance.
> 
> After we fix the performance, this change can be introduced.
> 
> @itfarrier are there other apps that can record/display a similar recent track for a week? How is it rendered?
> 
> Regarding the performance:
> 
> * Drawing circles takes more resources than drawing squares or rectangles (less triangles to render)
> * Drawing less objects should be faster than drawing many objects (circles)
> * While all original, unfiltered points can be stored in a file, rendering may use only a limited filtered number of points to draw less objects.
> 
> CC @kavikhalique @rtsisyk @vng

OK, I've started checking some apps. Later write the result.

**Comment by vng** [comment]
Not actual after adding track recording.

**Pull request closed without merging**
