### PR TITLE
Add support for `outdoor_seating` tag

### PR DESCRIPTION
**Pull request by Arthur-GYT**
All is in the title ^^

Related to #2119

Screenshot_20240707_184552

### CODE REVIEW

**Comment by Arthur-GYT** [comment]
Do I need to add editor support ? Android editor need more work for switch input :/.

**Comment by RedAuburn** [comment]
would be cool to also support indoor_seating=*, so the text would change to "Indoor & Outdoor Seating", or just "Indoor Seating", or "no seating"

**Comment by Arthur-GYT** [comment]
Ready for review !

**Comment by Arthur-GYT** [comment]
> would be cool to also support indoor_seating=*, so the text would change to "Indoor & Outdoor Seating", or just "Indoor Seating", or "no seating"

That's a good idea. But I think for this PR, I'll just do this tag. Then if others ask, I'll see what I can do.

**Comment by Arthur-GYT** [comment]
@biodranik Do you see any changes needed?

**Comment by Misalf-git** [comment]
By the way, I think the icon you used for the PP looks better than what's currently displayed on the map for `outdoor_seating` areas, which look like the letters `hT`.

**Comment by Misalf-git** [comment]
> * See discussion at https://github.com/organicmaps/organicmaps/pull/6050#discussion_r1328100082

@pastk was wrong? ;)

**Comment by vng** [comment]
@Arthur-GYT I've merged self_service. Please rebase this and I will merge.

**Comment by Arthur-GYT** [comment]
@vng Merge conflicts resolved ^^.

**Review by vng — APPROVED** [review]

**Comment by biodranik** [comment]
@Arthur-GYT there is a regression, can you please take a look and fix it? https://github.com/organicmaps/organicmaps/issues/9049

**Pull request merged**
