### PR TITLE
[android] RTL improvements.

### PR DESCRIPTION
**Pull request by Endem10n**
Partially resolves https://github.com/organicmaps/organicmaps/issues/817

1. Switched on RTL in manifest (have no idea, why it was switched off).
2. Fixed some RTL mistakes I found, refactored some places with old pre-RTL tags.

As a result, users with Arabian and Persian locales will have better UX. In ideal we should add later Hebrew translations.

### CODE REVIEW

**Review by biodranik — APPROVED** [review]

**Review by biodranik — APPROVED** [review]

**Comment by biodranik** [comment]
Please allow partially translated RTL layouts too, like Hebrew.

**Comment by Endem10n** [comment]
@biodranik but we do not have Hebrew translation. At least in android platform generated strings. Currently users with Hebrew locale will see English UI.

**Comment by biodranik** [comment]
We have it partially translated. Should your code be modified later to enable Hebrew?

**Comment by Endem10n** [comment]
@biodranik Yes, we definitely should enable layout mirroring for Hebrew, when we have translations for it in android resources, but for now it will look quite weirdly with all UI in English and mirrored layouts like for RTL languages, i think.

**Comment by rtsisyk** [comment]
> @biodranik Yes, we definitely should enable layout mirroring for Hebrew, when we have translations for it in android resources, but for now it will look quite weirdly with all UI in English and mirrored layouts like for RTL languages, i think. Hebrew is not disabled now, layout mirroring disabled if locale is Hebrew.

Sounds reasonable. 

P.S. Folks, please use threaded comments: Files -> select any line -> add comment.

**Review by rtsisyk — APPROVED** [review]
LGTM, but I am not an expert in Farsi or Arabic. Let's push and get some feedback from users.

**Pull request merged**
