### PR TITLE
Properly activate added Devanagari font

### PR DESCRIPTION
**Pull request by biodranik**
It was added but not used on iOS and Android, see #2597

### CODE REVIEW

**Comment by vng** [comment]
AFAIR, we have a priority when searching a font for a code point. So I'd consider adding new Noto fonts like 00_Noto... or check the code for priority/order.

**Comment by biodranik** [comment]
Explicitly specified Unicode blocks in fonts_whitelist.txt win over other fonts.

|Master|This PR|
|---|---|
|image|image|

**Comment by biodranik** [comment]
@vng what's wrong here?
```
Running world_feed_tests.cpp::Transit_GTFS_ProjectStopToLine_Simple
FAILED
world_feed_tests/world_feed_tests.cpp:237 TEST(ResT(5, false) == PrepareNearestPointOnTrack(point_C, std::nullopt, shape.size() , Direction::Backward, shape)) (5, 0) (6, 0) 
```

**Comment by vng** [comment]
- Yes, anyway I'd prefer to enumerate Noto fronts from 00_
- This test fails sometimes, I can't say about GTFS

**Comment by biodranik** [comment]
@vng PTAL

**Review by vng — APPROVED** [review]

**Pull request merged**
