### PR TITLE
[classif] Exclude service=* from railway-rail-highspeed

### PR DESCRIPTION
**Pull request by pastk**
A combination of `highspeed=yes service=*` produces two types `railway-rail-highspeed railway-rail-service` - 5K cases.
Fixed such cases to produce `railway-rail-service` only.

### CODE REVIEW

**Review by vng — APPROVED** [review]

**Review by biodranik — APPROVED** [review]

**Comment by biodranik** [comment]
@vng can we generate fresh data with it?

**Comment by vng** [comment]
@pastk Update OsmType_RailwayRail tests ?

**Comment by pastk** [comment]
> @pastk Update OsmType_RailwayRail tests ?

It'll be basically the same case as existing
`{{"railway", "rail", "service"}, {{"railway", "rail"}, {"usage", "main"}, {"service", "siding"}}},`
I didn't duplicate it for `usage=branch` also..
Does it make sense to test every single little variation?

**Comment by vng** [comment]
According to the PR's description, the test may look like:
```
{{"railway", "rail", "service"}, {{"railway", "rail"}, {"highspeed", "yes"}, {"service", "siding"}}}
```

**Pull request merged**
