### PR TITLE
[android-auto] NavigationScreen loading fix.

### LINKED ISSUE #7034: Android Auto (AA): Indefinite loading
**Describe the issue**
First day of using Android Auto. The navigation loads forever (couldn't get it to load at least).

**Steps to reproduce**
1. Set a bookmark on the phone
2. Open the bookmark in android auto
3. hit start to route to the destination
4. loads infinitely 

**Expected behaviour**
I didn't try to drive tho, so maybe it only loads when the location changes a bit.
It should say something like "Start driving" or directly show where to go.

**Screenshots**
[Video ](https://github.com/organicmaps/organicmaps/assets/93644977/f690f019-13cc-4c33-9598-713ef20c1391)

**System information:**
 - Operating system and its version: Android 14 (GrapheneOS)
 - Organic Maps version: 2023.12.25-6-Google (23122506)
 - Device Model: Pixel 4a (5g)

**Additional context**
This is the Organic Maps beta obviously.
Android Auto version 11.0.635014-release (110635014)

### PR DESCRIPTION
**Pull request by AndrewShkrob**
Closes #7034

### CODE REVIEW

**Review by biodranik — APPROVED** [review]
Awesome, thanks!

**Comment by pabloscloud** [comment]
Brilliant

**Comment by pabloscloud** [comment]
Didn't fix it for me at least :/

**Comment by biodranik** [comment]
@pabloscloud can you please describe in details your case in the linked issue?

**Pull request merged**
