### PR TITLE
Add entrance icon

### PR DESCRIPTION
**Pull request by endim8**
Discussed in https://github.com/organicmaps/organicmaps/pull/3717

gdgdg

### CODE REVIEW

**Review by vng — APPROVED** [review]

**Comment by biodranik** [comment]
Isn't it too bright in the dark mode? Maybe try to use the same color which is used for other texts and icons?

**Comment by endim8** [comment]
> Isn't it too bright in the dark mode? Maybe try to use the same color which is used for other texts and icons?
It looked too dark with the same colour as monument:
Screenshot_20221031-100515_Organic Maps (Beta)

Currently, dark mode is a bit mixed, some icons use this dark colour, but most use white (bench, bin, phonebox, lift, postbox, sign etc)

**Comment by vng** [comment]
I like the first screenshot (bright) icon.

**Comment by biodranik** [comment]
I afraid that it can be too colorful when every entrance is mapped in close buildings. If it looks ok, then we can merge as is. Or in any case, we can improve it later.

**Comment by vng** [comment]
@endim8 Please, rebase.

**Comment by endim8** [comment]
> @endim8 Please, rebase.

done 👍

**Pull request merged**
