### PR TITLE
[android-auto] Route planning

### PR DESCRIPTION
**Pull request by AndrewShkrob**
https://github.com/organicmaps/organicmaps/assets/10351358/9aa5bb45-11ef-42af-9f7c-5da36d520441

### CODE REVIEW

**Comment by biodranik** [comment]
How will it work if a user can not or does not want to touch the screen?

**Comment by AndrewShkrob** [comment]
Ignore the misclicks. Input works through mouse scroll. It's not really convenient

https://github.com/organicmaps/organicmaps/assets/10351358/97aa57db-05f5-449f-a9e2-b33e007229ed

**Comment by biodranik** [comment]
It is not clear which result is selected in the list. It means that there is almost no sense to show blue dots on the map now.
On iOS, when you scroll the list, the route to the selected list item starts to build, the Finish Flag icon is displayed on the selected result on the map, and the map is centered so your current location and the selected destination are both visible on the map. And in a few seconds, a full route appears (some visible indicator is needed to build it).

**Comment by AndrewShkrob** [comment]
> It is not clear which result is selected in the list. It means that there is almost no sense to show blue dots on the map now.

That's why I created issue https://github.com/organicmaps/organicmaps/issues/5039

> On iOS, when you scroll the list, the route to the selected list item starts to build, the Finish Flag icon is displayed on the selected result on the map, and the map is centered so your current location and the selected destination are both visible on the map.

Well, that possibly could be implemented for interactive search and bookmark screens. But in a separate PR as this one is only about `Route to` button.

> And in a few seconds, a full route appears (some visible indicator is needed to build it).

This is also a good topic to discuss. Currently, the route is not built automatically and you have to click `Route to` button.
It may be inconvenient for some users.  But for me, it looks better this way. What do you think?

**Comment by biodranik** [comment]
Is it feasible to simply copy the iOS approach for the start, and then iteratively improve it later? Even if numbers will be displayed on the map, it is impossible to understand quickly for the driver which numbers means what, when the car is driving.

Organic Maps was always designed to be as simple as possible. We spent 80% of our time thinking, testing and planning a simpler UX, and only 20% of time implementing it. It would be a pity to break this simplicity rule with Android Auto. Any unnecessary clicks or actions should be avoided. Every additional action that requires driver's attention increases the chance of a road accident. Simplicity and easiness of use should be at the top priority also from the safety perspective.

**Review by rtsisyk — APPROVED** [review]
I tested this branch. It looks in general, but some operations require too many clicks to get things done.

Let's take a look at a typical use case: Search -> Find a place -> Start navigation.

## Yandex

**Step 1:**

изображение

**Step 2:**

изображение

**Step 3:**

изображение

**Done**

## Organic Maps


**Step 1:**

изображение

**Step 2:**

изображение

**Step 3**:

изображение

**Step 4**:

изображение

----------------------

Yandex requires 3 steps, Organic Maps - 4 steps. Ideally, it should be possible to finish this operation in 2 steps.

Please consider adding shortcuts to optimize the user journey in the future patches.

**Comment by AndrewShkrob** [comment]
@biodranik PTAL

I updated the code and now route will be built automatically after the timer. Like here:

**Comment by biodranik** [comment]
Why not building the route immediately, and cancel/rebuild it if user changes something?

**Comment by AndrewShkrob** [comment]
It will require more complex changes (with rethinking of all UX flow) that I don't have time for. I want to focus on the Navigation Screen now and come back to this issue later.

**Review by rtsisyk — APPROVED** [review]

**Comment by rtsisyk** [comment]
Let's address UI/UX improvements in the next iteration, after finishing with [the initial plan](https://github.com/organicmaps/organicmaps/issues/4096).

**Pull request merged**
