### PR TITLE
[tools] Filter out pt-PT and zh translation generated by Google

### PR DESCRIPTION
**Pull request by biodranik**
```
    [tools] Updated translate.py script
    
    - Correct/filter out pt-PT and zh translations
    - Use ar in DeepL
    - Remove es-MX as it is not supported by Google
```

### CODE REVIEW

**Comment by biodranik** [comment]
@dvdmrtnz does it work for you?

**Comment by dvdmrtnz** [comment]
@biodranik It works. I think that `zh` needs to be filtered too. Currently it's generating `zh`, `zh-Hans` and `zh-Hant`, but we only use `zh-Hans` and `zh-Hant`.

**Comment by biodranik** [comment]
@dvdmrtnz thanks! Fixed, also fixed other issues. PTAL

**Comment by dvdmrtnz** [comment]
It's good!

**Review by dvdmrtnz — APPROVED** [review]

**Pull request merged**
