### PR TITLE
Allow antialiazing with ?aa and ?no-aa search commands

### PR DESCRIPTION
**Pull request by biodranik**
It is disabled by default.

### CODE REVIEW

**Comment by vng** [comment]
I have doubts about allowing it even via search.
AA creates additional several frame buffers and makes heavy stuff.

**Review by biodranik — COMMENTED** [review]
@vng this PR doesn't create any additional stuff. It only enables again the option to enable/disable AA via the search box.

**Comment by vng** [comment]
And I wrote above, I have doubts about giving this option even from search.

**Comment by pastk** [comment]
`?aa`/`?no-aa` commands had been working for me for ages (without this PR) both on linux desktop and on my android device (and there is a visual difference indeed). So its not clear to me what does this PR enable?
A different type of AA?

**Comment by biodranik** [comment]
This pr restored AA from settings at the start. OK, let's close it then.

**Pull request closed without merging**
