### PR TITLE
[outdoors] Increase visibilities of bridle/cycle/foot-ways and steps

### PR DESCRIPTION
**Pull request by pastk**
Outdoors:
- makes bridle/cycle/foot-ways same visibility as paths/tracks (z11-), steps z12-
- changes bridleways' style to be in-between cycleways/tracks and paths - uses longer dashes than path, but same color (when we settle on a better more contrast cycleways color maybe we can use it for bridleways too)
- increase label sizes for paths/tracks/steps/bridle/cycle/foot-ways

Bridleway vs path vs track
image

Closes
- #6658

### CODE REVIEW

**Comment by pastk** [comment]
Some increase of map sizes is expected mostly due to footways visibility rise. But we had footways on geom2 (the biggest impact) already before #2209. And now we exclude sidewalks and crosswalks from the rise which comprise 1/3 of all footways.

**Comment by pastk** [comment]
Raised footways don't add much more clutter to the cities as they visually merge with roads.
They're mostly visible in parks.

z11:
z11

Footway-mapped trails are now visible in the forest area amongst other trails.
z13:
z13

z17:
z17

**Comment by biodranik** [comment]
Z13 doesn't look good in smaller parks, they are unreadable.

**Comment by pastk** [comment]
Yes, but we can't fix it easily.
Its a compromise. The outdoors style is not meant for small city parks. But its important to have footways visibility on par with other trails, as its not unusual for an outdoor trail to be mapped as a footway.

See #6658

**Review by vng — APPROVED** [review]

**Pull request merged**
