### PR TITLE
Regenerated strings, removed duplicates

### PR DESCRIPTION
**Pull request by biodranik**

### CODE REVIEW

**Comment by vng** [comment]
Как получилось что "lisbon" вернулся назад? НЕго быть не должно, только lisboa.

**Comment by biodranik** [comment]
@vng удалить вообще строки с lisbon?
```
➜  omim git:(strings-regen) git blame data/strings/types_strings.txt | grep lisbon

bdea05cb155 data/strings/types_strings.txt (Hidde Wieringa     2022-10-15 15:53:15 +0200 17094)   [type.railway.station.subway.lisbon]
d1130b03d9c data/strings/types_strings.txt (Filip Czaplicki    2022-10-07 20:50:58 +0200 17494)   [type.railway.subway_entrance.lisbon]
```

**Comment by vng** [comment]
Да, у нас есть type = lisboa.

**Comment by biodranik** [comment]
@vng PTAL

**Review by matheusgomesms — APPROVED** [review]
I fixed some small mistakes in PT, and since I was editing, I fixed too other strings not related to this PR.

**Review by LaoshuBaby — APPROVED** [review]

**Comment by biodranik** [comment]
@matheusgomesms Thanks! Please next time edit source strings.txt or types_strings.txt files, not generated ones. I'll update it properly now.

**Comment by matheusgomesms** [comment]
> @matheusgomesms Thanks! Please next time edit source strings.txt or types_strings.txt files, not generated ones. I'll update it properly now.

Aaaah I see. Thanks! I'll do another edit here, let's see if I edit them correctly.

**Review by vng — APPROVED** [review]

**Pull request merged**
