### PR TITLE
[3party] Switch to latest upstream protobuf v3.21.9

### PR DESCRIPTION
**Pull request by Ferenc-**
Signed-off-by: Ferenc Géczi <ferenc.gm@gmail.com>

### CODE REVIEW

**Comment by Ferenc-** [comment]
Would be needed for: https://github.com/organicmaps/organicmaps/pull/3822#issuecomment-1304739895

**Comment by biodranik** [comment]
Protobuf already has its own CMakeLists.txt, can it be accurately reused instead of our own "bicycle"?

**Comment by biodranik** [comment]
@Ferenc- is protobuf 4 already present in many Linux distros? Can you please test this PR: https://github.com/organicmaps/organicmaps/pull/5557 ?

**Comment by Ferenc-** [comment]
> @Ferenc- is protobuf 4 already present in many Linux distros? Can you please test this PR: #5557 ?

From the mainstream ones, `Arch` (AUR) and `Alpine` (PmOS) are good to go already.
NixOS might have some catching up to do,
The rest of the Distros don't even attempt to package `organicmaps` just yet, so those users have to rely on using a `flatpak` or building from source anyway.

**Comment by Ferenc-** [comment]
Superseeded by #5557

**Comment by biodranik** [comment]
@Ferenc- what about the development context? If Protobuf 4 is integrated and then switched to be used as an external package on Linux, will developers on the most popular systems be able to build the project locally?

**Comment by Ferenc-** [comment]
> If Protobuf 4 is integrated and then switched to be used as an external package on Linux, will developers on the most popular systems be able to build the project locally?

Well, while many distros like Ubuntu, don't package the required version yet.
I would think, that if somebody is bold enough to use the `WITH_SYSTEM_PROVIDED_3PARTY` switch, then they know how to fill the gap and get the right protobuf version themselves, a few options:

* Building and running in a `flatpak`, might be desireable anyway.
* Use a `distrobox` to get a build environment with packages from another distro, that does ship the right protobuf version, like Arch.
* Use a distro independend package/dependency manager like `brew` or `conan`
* Install protobuf from the github [release](https://github.com/protocolbuffers/protobuf/releases)

**Pull request closed without merging**
