### PR TITLE
Update types_strings.txt

### PR DESCRIPTION
**Pull request by jmarchon1**
Improved wording. My first edit, so feedback is greatly appreciated.

### CODE REVIEW

**Review by biodranik — APPROVED** [review]
Your contribution is great, thanks! Are you familiar with git? Can you amend the commit and add an appropriate [DCO signature](https://github.com/organicmaps/organicmaps/pull/4612/checks) there?

And then regenerate your changes by `tools/unix/generate_localizations.sh` and adding them into a separate commit "[strings] Regenerated]", also with a DCO signoff? (adding `-s` to `git commit` is enough).

**Comment by jmarchon1** [comment]
I am not familiar with git at all, unfortunately. Where do I add the signature?

**Comment by biodranik** [comment]
You need to add the DCO signature to the commit's detailed message when you create a commit. Let's see what we can do here...

**Comment by jmarchon1** [comment]
> You need to add the DCO signature to the commit's detailed message when you create a commit. Let's see what we can do here...

How would I go about doing that _after_ creating the commit, if you don't mind me asking?

**Comment by matkoniecz** [comment]
> How would I go about doing that after creating the commit, if you don't mind me asking?

rebase (impossible in online github.com interface, requires actual git client)

**Review by vng — APPROVED** [review]

**Comment by vng** [comment]
@jmarchon1 Just add a comment here like:
Signed-off-by: <Your Name> <Your email>

**Comment by jmarchon1** [comment]
Signed-off-by: <jmarchon> <jmarchon35@outlook.com>

Like this? I'd prefer not to post my real name.

**Pull request merged**
