### PR TITLE
Update strings.txt added missing finnish translations  Signed-off-by: houtari markku.huotari@hsl.fi

### PR DESCRIPTION
**Pull request by houtari**
added missing finnish translations

Signed-off-by: houtari <markku.huotari@hsl.fi>

### CODE REVIEW

**Comment by biodranik** [comment]
Thanks! Can you please sign your commit with the DCO, as listed here: https://github.com/organicmaps/organicmaps/pull/1571/checks?check_run_id=4257817415 ?
Or you can create a new commit with the signature, I'll squash them.

**Comment by houtari** [comment]
> 
> 
> Thanks! Can you please sign your commit with the DCO, as listed here: https://github.com/organicmaps/organicmaps/pull/1571/checks?check_run_id=4257817415 ? Or you can create a new commit with the signature, I'll squash them.

I'm fairly new to Github. Took a look at the instructions and am not quite sure of what I need to do. I've now added a signature to the pull request. Did I get it right?

**Comment by biodranik** [comment]
Almost ) the commit itself should be edited (or another commit with a signature should be added).

**Comment by houtari** [comment]
I think I'll give up. I just can't understand how github works. Its far too complicated for me. It's easy and quite straightforward to use when you're the only contributor, but this collaboration with pull requests and specially this DCO signing makes it way too difficult for me. I've made my first [commit](https://github.com/osmlab/osm-community-index/pull/388) a year ago but don't remember having to DCO sign anything back then. I've now tried to edit the commit itself but I don't think I managed to do that. I even tried to delete the pull request to be able to create a new one, but simply just couldn't figure out how to do that. I've already spent a number of 4-letter words (in finnish we have more letters :-)  ) with this.

**Pull request closed without merging**
