### PR TITLE
[3party] Fixed expat compile errors for Android

### PR DESCRIPTION
**Pull request by biodranik**
TODO: Detect installed packages for Mac OS.

CC @Ferenc-

### CODE REVIEW

**Review by vng — APPROVED** [review]

**Review by vng — APPROVED** [review]

**Comment by Ferenc-** [comment]
> TODO: Detect installed packages for Mac OS.
> 
> CC @Ferenc-

Do I get it right that there should be test jobs in `android-check.yaml`
as well to compile for android with packaged dependencies?

**Comment by biodranik** [comment]
The bug was in CMakeLists.txt, it did not work on Mac, but for some reason worked on Linux CI checks.

**Comment by biodranik** [comment]
More important is to check MacOS builds too in the same way as we're checking Linux builds. But if building Android there is also possible, then it's even better.

**Comment by Ferenc-** [comment]
This "fix" broke the build with the packaged expat (https://github.com/organicmaps/organicmaps/pull/3951) on Linux.
It was working with [config mode](https://github.com/libexpat/libexpat#b-config-mode), where the package name has to be lowercase `expat`, and this PR changed it to uppercase `EXPAT`.

**Comment by biodranik** [comment]
@Ferenc- Android builds should also work. What do you propose?

**Comment by Ferenc-** [comment]
> @Ferenc- Android builds should also work. What do you propose?

I think PR https://github.com/organicmaps/organicmaps/pull/4213 should cover that scenario as well.

**Pull request merged**
