### PR TITLE
Add TrackerControl for iOS in readme

### LINKED ISSUE #5173: Add new link to Tracker Control
New project was created recently forked from Exodus Privacy platform to analyze permissions and trackers on IOS app

First report is available here:
- https://ios.trackercontrol.org/app/app.organicmaps

I suggest to add link in README.md and website

### PR DESCRIPTION
**Pull request by Altonss**
This fixes #5173

### CODE REVIEW

**Comment by Altonss** [comment]
Wow this DCO is getting a bit annoying over time ^^

**Review by Jean-BaptisteC — APPROVED** [review]
Thanks, can you doing same thing on website repo ?

**Comment by Altonss** [comment]
> Thanks, can you doing same thing on website repo ?

Sure, I just need to find it :)

**Review by biodranik — COMMENTED** [review]
Would it be better to display images in a table?

**Review by rtsisyk — APPROVED** [review]

**Pull request merged**
