### PR TITLE
Serbian translations (strings and categories)

### PR DESCRIPTION
**Pull request by dobridabar**
Scope of this PR:

1. All strings in data/strings/strings.txt (Serbian cyrillic only)
2. Most categories in data/categories.txt (Serbian cyrillic and latin)

All strings in data/strings/strings.txt are translated to Serbian (this covers most of the UI strings). Serbian uses both cyrillic and latin alphabets. Some Android phones offer Serbian (cyrillic) language setting, some offer Serbian (latin) language setting, and some offer both.

I only provided cyrillic strings in strings.txt file. My testing showed that if an Android user selects Serbian (cyrillic) language setting, then those strings will be displayed as-is. If a user selects Serbian (latin) language setting, then Android will automatically convert Serbian cyrillic into latin for all UI labels. Therefore, it seems that it is not necessary to provide Serbian latin translations for Android in strings.txt.

I didn't have a chance to test with iPhone, so I don't know the exact behavior for that platform.

If in the future we decide that we also need Serbian latin translations, they can be generated automatically from cyrillic counterparts.

Most categories in data/categories.txt are translated to Serbian. I used both cyrillic and latin, because categories represent the user input, and people in Serbia use different keyboard settings: some of them use only cyrillic, some of them use only latin, and some use both. Because there is not automatic transcription of cyrillic **input** into latin, we need to state both cyrillic and latin category names.

The remaining translations will be a subject of a future PRs.

### CODE REVIEW

**Comment by pastk** [comment]
Will need to enable Serbian language in categories.txt first like in 35613f8dabd60bf1de836f613133ccc0ba16e804

**Comment by dobridabar** [comment]
@pastk, I added Serbian to [android/app/src/main/res/xml/locales_config.xml](https://github.com/organicmaps/organicmaps/pull/9857/files#diff-88f959835dc599bce30be8e9f59285122810e240a330788b07268e300e5d5bfd) and to [indexer/categories_holder.hpp](https://github.com/organicmaps/organicmaps/pull/9857/commits/ff4ed61b24bb8089357d05bf03ff687247806b1c#diff-3d58789860b74a030a907066f95e9b5da8e211ecef340e59035ca4418ca8f99b), and regenerated.

**Comment by dobridabar** [comment]
It seems that I accidentally change a single Marathi translation in categories.txt. I just did another force push to undo that change.

**Comment by pastk** [comment]
FYI @biodranik

**Review by biodranik — APPROVED** [review]
Thank you very much for your contribution!

I'll check iOS. The next step is to translate types_strings.txt

**Comment by ZeljkoBG** [comment]
@biodranik 
I announced that I was translating **types_strings.txt**  for the Serbian language. Don't let me and someone else translate so that it becomes a wasted job. That I worked for nothing.

**Pull request merged**
