### PR TITLE
Making the whole Wikipedia article clickable

### LINKED ISSUE #4529: Wikipedia "more" button is hard to click on Android
It is very hard to tap the "more..." button for a partially visible Wikipedia article in the Place Page. I often miss it, and the PP closes.

It would be great to make the whole Wikipedia article view clickable.

### PR DESCRIPTION
**Pull request by ANS-UXI**
Fixes #4529 : Now the whole Wikipedia article is clickable.
 Previously:
 
OMprev

Now:
OMnow

### CODE REVIEW

**Review by biodranik — APPROVED** [review]

**Comment by biodranik** [comment]
Please also test if the Place Page can be dragged by selecting the Wiki area without opening Wikipedia details.

**Review by biodranik — CHANGES_REQUESTED** [review]
Please also sign your commit, as described in the failed check.

**Comment by ANS-UXI** [comment]
> Please also test if the Place Page can be dragged by selecting the Wiki area without opening Wikipedia details.

You mean this, right?
Draggable

**Comment by ANS-UXI** [comment]
Sorry made a mistake

**Comment by biodranik** [comment]
@ANS-UXI Please don't close Pull Requests even if you made a mistake. You can always force-push a correct git branch again to refresh the PR and leave its history readable.

**Comment by ANS-UXI** [comment]
> @ANS-UXI Please don't close Pull Requests even if you made a mistake. You can always force-push a correct git branch again to refresh the PR and leave its history readable.

My bad 😣. Thanks, now I know how to do it!

**Pull request closed without merging**
