### PR TITLE
[ios] Blue color for route-to button

### PR DESCRIPTION
**Pull request by biodranik**
image

CC @community-build

### CODE REVIEW

**Comment by vng** [comment]
I understand your motivation, but in this case looks like all other buttons are inactive and only "Route To" is active. Controversial for me.

**Comment by biodranik** [comment]
All other apps simply inverse the background (and make it blue) and foreground color. Do you have any better ideas?

**Comment by vng** [comment]
My point is that all 4 buttons should look the same (doesn't matter will they be blue or inversed). They are all enabled and actionable. Your screenshot looks like 1 is enabled and 3 others are disabled.

**Comment by biodranik** [comment]
@community-build please check Android UI. The main toolbar was removed from there, it is also the goal for iOS.

We need to solve the discoverability issue ONCE. After that, anyone will easily use these convenient buttons to build routes. So let's focus on HOW we can hint to users about building routes ONCE.

**Comment by biodranik** [comment]
@community-build please check Android UI. The main toolbar was removed from there, it is also the goal for iOS.

We need to solve the discoverability issue ONCE. After that, anyone will easily use these convenient buttons to build routes. So let's focus on HOW we can hint to users about building routes ONCE.

**Comment by biodranik** [comment]
@community-build please check Android UI. The main toolbar was removed from there, it is also the goal for iOS.

We need to solve the discoverability issue ONCE. After that, anyone will easily use these convenient buttons to build routes. So let's focus on HOW we can hint to users about building routes ONCE.

**Comment by biodranik** [comment]
@community-build please check Android UI. The main toolbar was removed from there, it is also the goal for iOS.

We need to solve the discoverability issue ONCE. After that, anyone will easily use these convenient buttons to build routes. So let's focus on HOW we can hint to users about building routes ONCE.

**Comment by biodranik** [comment]
Please check Android UI. The main toolbar was removed from there, it is also the goal for iOS.

We need to solve the discoverability issue ONCE. After that, anyone will easily use these convenient buttons to build routes. So let's focus on HOW we can hint to users about building routes ONCE.

**Comment by biodranik** [comment]
@community-build please check Android UI. The main toolbar was removed from there, it is also the goal for iOS.

We need to solve the discoverability issue ONCE. After that, anyone will easily use these convenient buttons to build routes. So let's focus on HOW we can hint to users about building routes ONCE.

**Comment by biodranik** [comment]
@community-build please check Android UI. The main toolbar was removed from there, it is also the goal for iOS.

We need to solve the discoverability issue ONCE. After that, anyone will easily use these convenient buttons to build routes. So let's focus on HOW we can hint to users about building routes ONCE.

**Comment by biodranik** [comment]
Closing it until we refactor the bottom toolbar.

**Pull request closed without merging**
