### PR TITLE
[android] Upgraded to target API 33

### PR DESCRIPTION
**Pull request by biodranik**
@rtsisyk please check if API 32 or API 33 have any specific requirements that we should properly support. And of course, please test it on your devices.

Required for #3537 to customize a language per app.

### CODE REVIEW

**Comment by Jean-BaptisteC** [comment]
@biodranik you need to add this permission [POST_NOTIFICATIONS ](https://developer.android.com/develop/ui/views/notifications/notification-permission)in Android Manifest to target API 33.
Maybe do you want add this new permission in other pull request ?

**Comment by rtsisyk** [comment]
> @biodranik you need to add this permission [POST_NOTIFICATIONS ](https://developer.android.com/develop/ui/views/notifications/notification-permission)in Android Manifest to target API 33. Maybe do you want add this new permission in other pull request ?

I saw that Android 13 displays additional permission screen on our app even without [POST_NOTIFICATIONS ](https://developer.android.com/develop/ui/views/notifications/notification-permission) permission. I will check both combinations on device.

**Comment by Jean-BaptisteC** [comment]
On Android 13, you need to add this permission in manifest file and if you want show notifications, you need to add function to ask permission.
I think if permission are not declared in manifest, Google can reject app on Play Store.

**Comment by biodranik** [comment]
But OM doesn't show any notifications, right? Then we don't need that permission. @Jean-BaptisteC where did you see that Google rejects app without that permission?

**Comment by biodranik** [comment]
Updated docs about the new CMake. We'll need it in the future to generate XCode projects.

**Comment by Jean-BaptisteC** [comment]
> But OM doesn't show any notifications, right? Then we don't need that permission. @Jean-BaptisteC where did you see that Google rejects apps without that permission?

OM use permission when user downloaded new maps #756
If you use permission on Android 13, permission POST_NOTIFICATIONS is present in lists of permissions on app settings.
Google can reject OM, because you use permission without declaration in manifest and this permission is consedered like [dangerous ](https://developer.android.com/reference/android/Manifest.permission#POST_NOTIFICATIONS) and you need consent user to use this. In Android 13, if you don't ask user consent permission is reject by default.

**Comment by biodranik** [comment]
Thanks for the example. You probably meant "OM uses notifications", right? I don't remember that I saw any download notifications. We don't use DownloadManager anymore, because many users had a lot of download issues with it. That doesn't mean that we won't use notifications again.

**Review by rtsisyk — COMMENTED** [review]
Please wait until I fix lint errors before merging this PR. Some parts may stop working because of deprecation.

**Comment by biodranik** [comment]
#3537 can be implemented after merging this.

**Review by rtsisyk — APPROVED** [review]

**Pull request merged**
