### PR TITLE
[style] add Hong Kong metro icon

### LINKED ISSUE #3988: Logo for Hong Kong MTR train stations
Would be great if you can use the MTR logo for its stations.

A svg logo is avialable at https://en.wikipedia.org/wiki/File:HK_MTR_logo.svg

The logo can be used for the stations of the train lines shown in [this map](https://commons.wikimedia.org/wiki/File:Hong_Kong_Railway_Route_Map_en.svg), except:
 * "Light Rail" has its own log. The station and road signs usually use the Light Rail logo.
 * "Airport Express" has its own logo, but it's common to simply use the MTR logo.
 * "Ngong Ping Cable Car" don't use the MTR logo. It's not train/subway anyway.

Some OSM entities that denotes MTR stations, for example:
 * Shek Kip Mei station https://www.openstreetmap.org/way/816466449
 * Sham Shui Po station https://www.openstreetmap.org/way/389315494
 * Cheung Sha Wan station https://www.openstreetmap.org/node/2544686378

### PR DESCRIPTION
**Pull request by ubahnverleih**
I added metro icons for Hong Kong - this fixes #3988

* Icons are manually created by me (in light and dark style)
* I modified the Hong Kong bbox to cover the whole network but don't conflict with Shenzhen. (Only one HK station is not in the bbox as it would overlap several of Shenzhen's stations.)

This is my first PR on the project, and i hope i did everything correctly

### CODE REVIEW

**Review by vng — APPROVED** [review]

**Comment by vng** [comment]
Merge 2 [styles] Regenerated commits into one?

**Review by pastk — APPROVED** [review]
Looks great, thanks! Just merge the regen styles commits.

**Comment by ubahnverleih** [comment]
> Looks great, thanks! Just merge the regen styles commits.

Done

**Comment by pastk** [comment]
Many thanks for your first contribution!! :rocket:

**Pull request merged**
