### PR TITLE
[android][iOS] Reduce build size.

### PR DESCRIPTION
**Pull request by Endem10n**
[android] [iOS]Recompressed png icon atlases in lossless manner. Removed old unused atlas from resources_xxxhdpi_dark. Removed a few unused images from nodpi android resources. Build size will reduce aproximately by 3,5-3,7 Mb for each platform. For recompression used compressor.io, for validation that atlas did not changed - Araxis Merge tool. Checked after changes on different android emulators with different densities from mdpi to xxxhdpi both in normal and night mode. Need help with checks on iOS and other platforms.

### CODE REVIEW

**Comment by biodranik** [comment]
Wait, symbols are regenerated by tools/unix/generate_symbols.sh (see skin generator) every time when we add or change icons. Optimizing their size manually after that is not a flexible approach. Embedding optimizations into the Qt-based skin generator is the best approach, using some (optional) external tool from the bash script is also good.

**Comment by Endem10n** [comment]
Ok, will take a look into current pipeline and try to automate it.

**Comment by Endem10n** [comment]
Closed. This kind of optimization should be injected into current resources pipeline and not done manually

**Comment by biodranik** [comment]
Wait, the cleanup part is ok to merge :)

**Pull request closed without merging**
