### PR TITLE
Set last modified time for imported KML or GPX before saving them

### LINKED ISSUE #7564: [bookmarks] kml's lastModified field should be fully initialized before saving
This bug is related to the https://github.com/organicmaps/organicmaps/issues/3475

### Bug description
 The `lastModified` attribute is missed during the group importing process, leading to unexpected groups sorting.

When the user imports a new file from some other apps and we parse it to kml the `lastModified` is skipped if file's last modified date wasn't set:
```cpp
  if (categoryData.m_lastModified != Timestamp())
  {
    writer << indent << "<mwm:lastModified>" << TimestampToString(categoryData.m_lastModified)
           << "</mwm:lastModified>\n";
  }
```
image

And only after that method `UpdateLastModifiedTime(*collection);` is called at the end of the importing process.
So this metadata will be skipped in kml file but will be valid in the in-memory object.
Example of the newly imported file where we can see the absence of that field:
```xml
  <name>2024-02-18-0129 2024-02-15-0101 Безымянный трек-3-7</name>
  <visibility>1</visibility>
  <ExtendedData xmlns:mwm="https://omaps.app">
    <mwm:name>
      <mwm:lang code="default">2024-02-18-0129 2024-02-15-0101 Безымянный трек-3-7</mwm:lang>
    </mwm:name>
    <mwm:annotation>
    </mwm:annotation>
    <mwm:description>
    </mwm:description>
                                            // < -- should be here
    <mwm:accessRules>Local</mwm:accessRules>
  </ExtendedData>
  <Placemark>
    <name>2024-02-15-0101 Безымянный трек-3</name>
    <Style><LineStyle
      <color>FFC76E00</color>
```
How to reproduce:
- import some categories from the non-OM app
- see it at the top of the bookmarks list (because in-memory lastModified was set properly)
- terminate app
- open app
- category will be at the bottom of the list (because there's no such field in the the kml)

https://github.com/organicmaps/organicmaps/assets/79797627/68670756-0e3a-442d-9a64-f51485506236

### Related conversations about how to fix: 
https://github.com/organicmaps/organicmaps/pull/7533#discussion_r1516862565

### PR DESCRIPTION
**Pull request by biodranik**
Fixes #7564

@cyber-toad The fix was easy, there is no need to use the last modified file time because files are often copied anyway just before importing them, due to system restrictions.

@kirylkaveryn can you please test it and confirm that the fix works?

### CODE REVIEW

**Comment by biodranik** [comment]
> Why do we use this mwm:lastModifiedTime custom metadata instead of relying in mtime on the file?

Because mtime in file is not reliable. When the file is imported via content provider, it is copied locally.

In theory it is possible to query the content provider for the modification time, and also extract mtime on iOS, but in practice it doesn't make much sense, most imported files usually are created/sent to OM just before the import.

Modification time is only important for our default sorting (last modified is at the top).

What are your concerns about the approach?

**Comment by biodranik** [comment]
@rtsisyk @cyber-toad @vng It is actually more reliable to use real file modification date. Added the necessary code to Platform. Please review.

**Comment by kirylkaveryn** [comment]
@biodranik thanks a lot! It works well and new imported categories have the proper lastModified tag. I have checked files in the device's container.
From GuruMaps and Osmand importing works well!

**Review by kirylkaveryn — APPROVED** [review]
@biodranik thanks a lot! It works well and new imported categories have the proper lastModified tag. I have checked files in the device's container.
From GuruMaps and Osmand importing works well!

**Review by vng — APPROVED** [review]

**Pull request merged**
