### PR TITLE
fix: Bad translation for French of "Wind generator" string

### PR DESCRIPTION
**Pull request by tungbq**
Fixes: #5265

### CODE REVIEW

**Comment by biodranik** [comment]
Can you please fix your branch and force-push it again?

**Comment by tungbq** [comment]
Thanks @biodranik . I've created a new one: https://github.com/organicmaps/organicmaps/pull/5267

**Comment by biodranik** [comment]
Please do not spam us by notifications by creating new pull requests and branches. You can reuse the existing PR and existing branch next time.

**Comment by tungbq** [comment]
> Please do not spam us by notifications by creating new pull requests and branches. You can reuse the existing PR and existing branch next time.

Sure! Sorry for this

**Pull request closed without merging**
