### PR TITLE
Add icon for vending=excrement_bags

### PR DESCRIPTION
**Pull request by j13m126**
[source](https://wiki.openstreetmap.org/wiki/File:Excrement_bags-14.svg)
Bildschirmfoto vom 2022-09-09 23-53-48
Bildschirmfoto vom 2022-09-09 23-54-19

### CODE REVIEW

**Review by vng — APPROVED** [review]

**Comment by biodranik** [comment]
The icon looks complex, is it possible to use just a simple bag + shit?

**Comment by biodranik** [comment]
It looks like a fireplace )

Maybe a small dog icon with one rear leg up would be better?

**Review by rtsisyk — CHANGES_REQUESTED** [review]
Please find a better icon.

**Comment by Jean-BaptisteC** [comment]
@dvdmrtnz @RedAuburn did you have a better idea

**Comment by RedAuburn** [comment]
[iD uses this:](https://cdn.jsdelivr.net/gh/rapideditor/temaki/icons/vending_pet_waste.svg)


but it might still be too hard to distinguish when it's small

**Comment by Jean-BaptisteC** [comment]
Maybe a head of dog on excrements bags ?

**Comment by dvdmrtnz** [comment]
The Röntgen icon set has a family of vending icons that could be adapted to organic maps, and could be used to represent this type in particular:

https://github.com/enzet/Roentgen


IMG_2845

**Comment by RedAuburn** [comment]
maybe something like this?:

**Comment by dvdmrtnz** [comment]
Here is an icon proposal. I based it on @RedAuburn's suggestion but simplified the bag and took the poop icon from @j13m126's original proposal. The icon is grid aligned, so it should look okay in the smallest 18x18 size.

**Pull request closed without merging**
