### PR TITLE
[android] Fix Google Location Dialog on the start

### PR DESCRIPTION
**Pull request by rtsisyk**
Fixes the test case (3).

### CODE REVIEW

**Comment by Jean-BaptisteC** [comment]
I'm not sure if you have fixed in the right place. In this version, pop-up is too aggressive (pop-up appears before the map have fully loaded)
In 2023.08.18-8-Google, the pop-up is visible only when the user touches location button.

**Comment by rtsisyk** [comment]
> I'm not sure if you have fixed in the right place. In this version, pop-up is too aggressive (pop-up appears before the map have fully loaded) In 2023.08.18-8-Google, the pop-up is visible only when the user touches location button. You can leave pop-up in start, but I think, wait map fully loaded is better

People complained that the previous 2023.07 version displayed that dialog on the start, while the new version doesn't.

**Review by biodranik — APPROVED** [review]

**Comment by biodranik** [comment]
> People complained that the previous 2023.07 version displayed that dialog on the start, while the new version doesn't.

I wrote about 2023.08 version.

> I'm not sure if you have fixed it in the right place. In this version, the pop-up is too aggressive (pop-up appears before the map has fully loaded)

@rtsisyk the behavior should be the same as it was in the August release.

**Comment by rtsisyk** [comment]
> > People complained that the previous 2023.07 version displayed that dialog on the start, while the new version doesn't.
> 
> I wrote about 2023.08 version.
> 
> > I'm not sure if you have fixed it in the right place. In this version, the pop-up is too aggressive (pop-up appears before the map has fully loaded)
> 
> @rtsisyk the behavior should be the same as it was in the August release.

Yes, it should be the same as in the August.

@Jean-BaptisteC , I plan to rework how Google Location works for the next release.

**Pull request merged**
