### PR TITLE
Compatiblity interface for deprecated APIs.

### PR DESCRIPTION
**Pull request by n1snt**
### What is this?

This is a common interface that would help abstract away the differences between the deprecated and non-deprecated APIs.
(Inspired by the AnkiDroid implementation.)

### What each file does:

- The Compat interface and its implementations are needed in the above code to provide a unified API that can be used across different versions of the Android platform.
- The CompatHelper class is a singleton that has a private constructor and exposes a compat property that returns an instance of the Compat interface. It uses a when expression to decide which implementation of the Compat interface to use based on the Android SDK version of the device.
- The CompatV21 class is an implementation of the Compat interface that supports Android API level 21 and above. This is the base implementation of Compat.
- The CompatV23 class is an implementation of the Compat interface that supports Android API level 23 and above. It uses the non-deprecated hour and minute properties to get and set the hour and minute values of a TimePicker widget.

### Why we need this:

- If we had to implement the same without this compact system we would need to check the `Build.VERSION_CODES` every time we used any of the deprecated APIs which would lead to more maintenance & a lot of repeated code.
- Encapsulation: The implementation details of each Compat version are encapsulated within their respective classes, which means that other parts of the codebase don't need to know or care about the differences in the TimePicker API between different Android versions.

### Other:
I had originally implemented it in Kotlin https://github.com/organicmaps/organicmaps/pull/4801
There is still some work to be done here (mostly comments & documentation for the developer)
Any feedback on this would be really appreciated.

### CODE REVIEW

**Comment by biodranik** [comment]
1. The benefits of this approach are not clear in our specific use cases. Now, instead of a few lines of code, we have interfaces and classes with many lines of code.
2. You are not following our java style. Did you read the java style guide in the repo's docs folder?

**Comment by n1snt** [comment]
I have added a few more deprecation fixes to demonstrate how this works.
The normal way to fix a deprecated API that works on a api level but does not work on another would be to add an if else statement, but that would get really messy if you are trying to clean up deprecated APIs in a codebase of this scale with thousands of lines of code.
You would need to add the following things each time you find a deprecated API in codebase:
1. If else statement to check API level
2. A deprecation supression annotation
3. Target Api annotation

So this interface comes in clutch in this scenario. 
This interface will automatically map api calls based on API level so it will lead to better encapsulation of deprecated APIs & remove all those if else statements & annotations with CompatHelper.getCompat().<API_HERE>

Supporting APIs:
1. If we want to bump the API level support of app and you encounter a deprecation.
We can easily add Compat<API_LEVEL>.java & add it to CompatHelper.java to support the new API.
2. To remove support for older APIs we can simply remove the Compat<API_LEVEL>.java file & remove it from CompatHelper & that's it.

In general it would make maintaining deprecated APIs a lot manageable.

**Comment by n1snt** [comment]
[This](https://github.com/organicmaps/organicmaps/pull/4803/commits/44e0f6338c58444035b25c8718f203bc0660945f) commit demonstrates how I added support for API 33 for this interface.

**Comment by n1snt** [comment]
There are around 100 instances of deprecated APIs in the codebase & if we went the simple route of writing if-else statements, checking the build version... It will take a lot more code & will be a lot messier compared to this imo.

**Review by rtsisyk — CHANGES_REQUESTED** [review]
Please take a look at https://github.com/organicmaps/organicmaps/blob/b4101783c8427714d5ab30faa09682921d79e2bc/android/src/app/organicmaps/util/Utils.java#L810-L841 and https://github.com/organicmaps/organicmaps/pull/4658

**Comment by n1snt** [comment]
I have gone through utils & went through how we handle current deprecated APIs.

- In utils, we still need an if-else for every deprecated api
- As well as suppression & TargetApi annotations.
- Does not encapsulate according to different API versions.

The implementation I am proposing:
- This will no longer require if-else statements for every API
- This will allow us to support newer APIs easily.
- We have over 100 deprecated API calls in the codebase right so it will help unify all of those if-else statements, suppressions, etc.
- It encapsulates deprecated APIs in files according to their API level.
- On top of that, this implementation would work well if we ever move over to kotlin because of [function extensions](https://kotlinlang.org/docs/extensions.html) that means in future if we ever move to kotlin the compat calls would look like they were implemented in the library/API itself.

**Comment by biodranik** [comment]
Does your solution require more lines of code than our existing approach?

**Comment by matkoniecz** [comment]
@n1snt

> Does your solution require more lines of code than our existing approach?

**Comment by n1snt** [comment]
Sorry for the late reply, I was caught up in some tests.
It will reduce the lines of code required to fix the deprecated APIs.
And it will also distribute the lines of code across files (Encapsulate according to different API versions.)

**Review by Jean-BaptisteC — APPROVED** [review]
✅ Pixel 6 - Android 13
✅ Yoga Tab 2 - Android 5

**Comment by biodranik** [comment]
image

We are prioritizing simplicity, fewer lines of code, and focusing only on existing issues, without doing something "in case we need it later, here is it!".

**Comment by rtsisyk** [comment]
t would be better to rely on existing Compat classes provided by JetPack. Methods that are not in JetPack yet can be added to Utils.java. Utils.java has shrinked in the size significatly after upgrading to the latest JetPack and removing all dead code. Let's keep it simple.

**Pull request closed without merging**
