### PR TITLE
Updated Slovak translations

### PR DESCRIPTION
**Pull request by ojesko**
Fixed some Slovak translations and added some missing ones.

### CODE REVIEW

**Review by biodranik — COMMENTED** [review]
Thanks! Can you please use interactive rebase to:
1. Squash two commits modifying strings.txt into one
2. Remove regeneration commits and then either create a new one (without modified es-MX file), or don't regen strings at all (we'll do it later)

**Comment by ojesko** [comment]
Ok. I think I did it. Although not sure if I did it correctly :/
Can you please check it?

**Comment by biodranik** [comment]
Thanks! Almost fine, the strings check script says the sorting order is a bit wrong and should be fixed: https://github.com/organicmaps/organicmaps/actions/runs/8126087803/job/22209382999#step:4:144

**Comment by ojesko** [comment]
It should be fixed now. Sorry for the mess :(

**Review by biodranik — APPROVED** [review]
Žiadny problém, veľmi pekne ďakujem za pomoc s prekladmi!

**Pull request merged**
