### PR TITLE
qt: Add route marking buttons to place pages

### PR DESCRIPTION
**Pull request by Ferenc-**

### CODE REVIEW

**Comment by Ferenc-** [comment]
cc: @tristanvigar

**Comment by Ferenc-** [comment]
cc: @Bugsbane

**Comment by biodranik** [comment]
@Ferenc- thanks! The bottom buttons should be in a separate container that is not related to the left list of labels:
image

**Comment by Ferenc-** [comment]
> @Ferenc- thanks! The bottom buttons should be in a separate container that is not related to the left list of labels

That behaviour is independent from this PR, so I have opened a separate PR for that https://github.com/organicmaps/organicmaps/pull/7940

**Comment by biodranik** [comment]
Bottom buttons in this pr should not increase spacing on the left column.

**Comment by Ferenc-** [comment]
> Bottom buttons in this pr should not increase spacing on the left column.

I believe after the rebase, that is not happening anymore. Please check.

**Review by biodranik — APPROVED** [review]
Cool, thanks!

**Comment by Bugsbane** [comment]
Nice addition to see! I'm curious, does it's width fit a mobile device screen (eg 720px)? I ask as I'm mainly interested in eventually using Organic Maps on mobile Linux devices (eg Pine Phone Pro).

**Comment by biodranik** [comment]
Test and tell us :)

**Comment by Ferenc-** [comment]
> does it's width fit a mobile device screen (eg 720px)

It depends on a few things. I am thinking about a way to keep the size within bounds.

**Comment by pastk** [comment]
@Ferenc- when I close the PP via Esc or a window close button (not the "Close" button inside the PP) it sets a route starting point (as if I've pressed the "Route from" explicitly).

**Comment by biodranik** [comment]
Good catch! @Ferenc- can you please fix that?

**Comment by Ferenc-** [comment]
> Good catch! @Ferenc- can you please fix that?

https://github.com/organicmaps/organicmaps/pull/7956

**Pull request merged**
