### PR TITLE
[qt] Migrated on Qt6.

### PR DESCRIPTION
**Pull request by vng**
Working app based on Qt6 (no back compatibility with Qt5).

Not necessary to merge right now, for the future.

### CODE REVIEW

**Comment by biodranik** [comment]
I'm not sure if every system already has Qt6 packages available. We need to check with our Linux contributors first before merging it.

@pastk ?

**Comment by biodranik** [comment]
You also need to install qt6 in our Linux-check GitHub action. Maybe @pastk can help.

**Comment by vng** [comment]
We need Ubuntu 22. Now we have 20 on GA.

**Comment by pastk** [comment]
> I'm not sure if every system already has Qt6 packages available. We need to check with our Linux contributors first before merging it.

My distro (Ubuntu 18.04) is quite old, there is no qt6 for it.

**Comment by biodranik** [comment]
Paths also should be fixed as in #2565
Don't think that merging it is a good idea, Qt5 is stable, popular and good enough.

**Comment by biodranik** [comment]
@vng блин я случайно ветку удалил. Осталось локально? Пушни пожалуйста, хотя бы без PR.

**Comment by biodranik** [comment]
Фуф, восстановил.

**Comment by rtsisyk** [comment]
homebrew on Mac installs 6.3.0, bot qt5...

**Comment by biodranik** [comment]
> homebrew on Mac installs 6.3.0, bot qt5... 

Bot? `brew install qt@5`

**Comment by vng** [comment]
PTAL
See linux-check.yaml, INSTALL.md

**Comment by biodranik** [comment]
RE: scaled icons for Qt5: https://doc.qt.io/qt-5/highdpi.html

On macOS, high-DPI support is enabled by settings in the Info.plist file; so make sure these settings are present.

<key>NSPrincipalClass</key>
<string>NSApplication</string>
<key>NSHighResolutionCapable</key>
<string>True</string>

**Comment by vng** [comment]
@biodranik Of course this settings are already set since 2015 (check qt/res/Info.plist.in).
Here are 2 screenshots with obvious icons rendering quality:
Qt5:
qt5
Qt6:
qt6

**Comment by pastk** [comment]
> 
> My distro (Ubuntu 18.04) is quite old, there is no qt6 for it.

I found a PPA with QT 6.2 packages for LTS Ubuntu versions as old as 16.04: https://launchpad.net/~savoury1/+archive/ubuntu/qt-6-2
I'll give it a go for Ubuntu 18.04 and report back.

**Comment by bam80** [comment]
@pastk would it be possible for you to try things within next week maybe?
We tried this branch and didn't find notable issues, so we are going to update the documentation and merge this, but after you give us your approval.

**Comment by vng** [comment]
Updated branch.
PTAL and merge?

**Review by biodranik — APPROVED** [review]
LGTM

**Comment by bam80** [comment]
If anyone wanted to test, I've opened PR for adding flathub-beta channel:
https://github.com/flathub/app.organicmaps.desktop/pull/35

**Comment by pastk** [comment]
Looks like rendering of the map in the release desktop app became slower...
A quick search didn't bring anything like "Qt6 is slower than Qt5", so maybe some default settings had changed?

**Comment by bam80** [comment]
What version did you test? Release is not on Qt6 yet, neither flatpak beta

**Comment by biodranik** [comment]
We're working and testing the master branch directly. We noticed that debug version became slower.

@pastk can you please create an issue? It can be a major reason to revert to Qt5 in the worst case and to fix the slow-down root cause in the best case.

**Comment by pastk** [comment]
> We're working and testing the master branch directly. We noticed that debug version became slower.

I've noticed it on a release build.

**Pull request merged**
