### PR TITLE
[borders] fix bad essex/oxford border

### PR DESCRIPTION
**Pull request by RedAuburn**
fixes https://github.com/organicmaps/organicmaps/issues/477
the issue was that the bridge is not in the essex mwm, so not used in routing when only essex is installed

red: new, grey: old
image

### CODE REVIEW

**Comment by RedAuburn** [comment]
i'm not sure how to generate the other style of value, but hopefully it'll work. Edited using Zverik's poly plugin for JOSM

**Comment by vng** [comment]
1. I'd prefer to have simple straight line. Less highways intersections - easier for routing algorithm :)
image

2. Need to find how to regenerate packed_polygons.bin.

**Comment by biodranik** [comment]
@vng is local maps regeneration enough to test routing here?

**Comment by vng** [comment]
Well, everything should be ok, except for the case when a user updates Oxford but keeps Essex old. Honestly, I don't know what do we have for this case.

**Comment by biodranik** [comment]
Updating maps will fix the issue. Automated map updates will also help. So let's not worry about outdated maps.

**Comment by biodranik** [comment]
@RedAuburn please regenerate packed borders with the generator tool after your changes (and use straight lines, less points = faster OM):
```
DEFINE_bool(generate_packed_borders, false, "Generate packed file with country polygons.");
```

**Comment by RedAuburn** [comment]
> (and use straight lines, less points = faster OM):

in that case, we might want to simplify all the borders, currently there are a _lot_ of unnecessary nodes (33,334 just for the Oxford border):

image

**Comment by RedAuburn** [comment]
@biodranik @vng ptal :)

border changed to this and generated packed borders
Screenshot from 2023-11-03 11-21-56

**Comment by vng** [comment]
No need to simplify borders, we do it programmatically. Intersection with roads matters.
Please, rebase on the current master, tests were fixed.

**Review by biodranik — APPROVED** [review]
LGTM

**Pull request merged**
