### PR TITLE
[strings] Improve Czech routing translation, new strings 

### PR DESCRIPTION
**Pull request by kudlav**

### CODE REVIEW

**Comment by matheusgomesms** [comment]
I guess old code was used. PT-BR, ES-MX and TR is now messed up. Could you please revert these changes (on these languages)? Thanks!

**Review by biodranik — CHANGES_REQUESTED** [review]
Please 
1. Remove the regenerate commit
2. Rebase your changes on top of the most recent master branch
3. Regenerate strings again

**Comment by kudlav** [comment]
Sorry, but this branch (kudlav:kudlav-lang-route) is 2 commits ahead of organicmaps:master.

**Comment by biodranik** [comment]
Please revert es-MX and pt-BR English sound strings change back. Looks like there is some strange issue with our strings generation tool, need to investigate why it reverts es-MX and pt-BR to English despite their presence in data/strings/sound.txt

**Review by biodranik — APPROVED** [review]
Thank you! We'll check what is wrong with strings generation.

Looks like Android Github checks are failing due to some networking issues.

**Pull request merged**
