### PR TITLE
WIP Outdoors style

### PR DESCRIPTION
**Pull request by pastk**
A quick take on an outdoors style.

Bigger/thicker and/or visible at lower zoom levels features:
- paths/tracks, cliffs
- contour lines
- railways, powerlines and towers
- water sources, peaks, saddles, passes
- waterfalls, lighthouses, caves
- campsites, huts, shelters, picnic sites
- gates, stiles, fords
- etc.

Its possible to test it by building along with #2798, otherwise a map regeneration is needed to make all the changes take effect.

Needs more improvements and polishing.

Needed-for: #2356

### CODE REVIEW

**Comment by pastk** [comment]
outdoors-1


outdoors-2

**Comment by vng** [comment]
Should we make completely different outdoor style instead of modify the current one?

**Comment by biodranik** [comment]
> Should we make completely different outdoor style instead of modify the current one?

Of course.

**Comment by pastk** [comment]
> Should we make completely different outdoor style instead of modify the current one?

Its just temporary to have an easy way to test it / use it and see the difference to the main style.

We also need to review the way style inheritance work to avoid having isolated copies of all styling rules for each style (as its going to be a maintenance issue).

**Comment by not-available-username** [comment]
Currently `trail_blaze` is displayed as a generic **_i_** and is useless since it's impossible to know what kind of information it is. My personal opinion is that a trail blaze is useless when it's part of a path (you can use the path itself and your position to check if you are following the route), but I think that could be useful to render the trail blazes only when the key `trail_visibility` is `bad` or worse.

IMHO this could be applied also for the standard style.

I can create a smaller icon for trail_blaze, maybe a little rhombus.

File 01-07-22, 13 41 20

**Comment by pastk** [comment]
> Currently `trail_blaze` is displayed as a generic **_i_** and is useless since it's impossible to know what kind of information it is. My personal opinion is that a trail blaze is useless when it's part of a path (you can use the path itself and your position to check if you are following the route), but I think that could be useful to render the trail blazes only when the key `trail_visibility` is `bad` or worse.


Thanks for spotting!
ATM OM differentiates only some values of [`information=*`](https://wiki.openstreetmap.org/wiki/Key:information).
Namely, its `office`, `map`, `board` & `guidepost`.
All other values incl. `trail_blaze`, `route_marker`, `terminal` etc. just fall into a generic `tourism-information` OM type and are displayed by that `i` icon. Which is especially wrong in case of a route markers - as you noted.
So the fix will be to add a separate OM type for `trail_blaze`/`route_marker` and use a separate (small) icon for it.

**Comment by rtsisyk** [comment]
I like the idea of adding this new outdoor style. Do we want to plan existing "Terrain" layer or add a new one?

**Comment by hallahan** [comment]
This is cool!

I would also like to author a map style. It might make sense to modify the "Map layers" panel to be "Map Styles", and then we can add to the list various cohesive map styles. Also, there would be the official styles that ship with the app, but the user could somehow add a url somewhere in the settings?

A given style would involve a set of layers, so the "Outdoors" style would include contour lines, and maybe a "City" style would include the subway data?

**Comment by biodranik** [comment]
@hallahan please check other issues and discussions about styles. The idea is to focus on activities: Hiking, Cycling, Driving, City Tourism, Public Transport.

**Comment by pastk** [comment]
> I would also like to author a map style. It might make sense to modify the "Map layers" panel to be "Map Styles", and then we can add to the list various cohesive map styles. Also, there would be the official styles that ship with the app, but the user could somehow add a url somewhere in the settings?
> 

Yeap we're thinking of making it easier to use custom styles. ATM you can actually have a custom style already, but its not that convenient to switch between it and a shipped style (got to move files for that). One step to make it more easy is #2798 (can use search commands to switch, also allows to raise visibility of features in custom styles).

**Comment by KronosTheLate** [comment]
Screenshot of what i mentioned sbout steep landscape being coloured, with red being the steepest:
Screenshot_20230828-114611

Red steepness and marked hiking trails is what I look for in identifying beautiful yet practical areas to hike.

High density of marked trails also reveals a generally nice area, so I would love to keep those visible at low levels of zoom, when in hiking mode.

**Pull request closed without merging**
