### PR TITLE
[ios] Add PrivacyInfo with missing API declarations

### PR DESCRIPTION
**Pull request by kirylkaveryn**
Closes https://github.com/organicmaps/organicmaps/issues/7754

This PR adds PrivacyInfo file with missing API declarations as described in [Documentation](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api).

### CODE REVIEW

**Review by biodranik — COMMENTED** [review]
Thanks! Should we also craft appropriate string translations? Where/how they will be displayed to users?

**Comment by kirylkaveryn** [comment]
> Thanks! Should we also craft appropriate string translations? Where/how they will be displayed to users?

No! This declarations only for Apple.
And we should only set this new plist and add predefined values into the arrays:
image

**Comment by biodranik** [comment]
This one is needed when we add iCloud support:
```
C617.1
    Declare this reason to access the timestamps, size, or other metadata of files inside the app container, app group container, or the app’s CloudKit container.
```

This one is needed when/if we add "Import bookmarks and tracks" button that will open Files app to select any kml, kmz or gpx. Is it possible @kirylkaveryn ?
```
3B52.1
    Declare this reason to access the timestamps, size, or other metadata of files or directories that the user specifically granted access to, such as using a document picker view controller.
```

**Review by biodranik — APPROVED** [review]
Thanks! After rebasing, you can add the container-related file modification part into the iCloud PR (if it is used there).

**Pull request merged**
