### PR TITLE
Minor clang-tidying

### PR DESCRIPTION
**Pull request by biodranik**

### CODE REVIEW

**Comment by biodranik** [comment]
@rtsisyk @vng PTAL, only minor tidying is left.

**Review by vng — COMMENTED** [review]
Well, I have these changes strange. Yes, it terms of C++ some methods may be const, but not in terms of design logic.

How making functions like Invalidate, SetXXX, AddXXX should help to understand the code better - IDK. I made a quick look and don't agree here, definitely.

**Comment by vng** [comment]
This short example shows how ridiculous these changes are and how we should filter all _tidy_ stuff.
```
class Foo
{
    class Impl
    {
        int m_state;
    public:
        void ChangeState() { ++m_state; }
    };

    Impl * m_impl;

public:
    // Aha, const, oops.
    void ChangeState() const { m_impl->ChangeState(); }
};
```

**Comment by vng** [comment]
All these functions change state. Indirectly, via the pointer, but anyway. 
I do not accept all const changes.

```
void AddTouchEvent(TouchEvent const & event) const;
  void Scale(double factor, m2::PointD const & pxPoint, bool isAnim) const;
  void Move(double factorX, double factorY, bool isAnim) const;
  void Scroll(double distanceX, double distanceY) const;
  void Rotate(double azimuth, bool isAnim) const;
```

**Pull request closed without merging**
