### PR TITLE
Add, fix and improve mandarin translation

### PR DESCRIPTION
**Pull request by MASangys**

### CODE REVIEW

**Review by biodranik — APPROVED** [review]

**Comment by biodranik** [comment]
Thanks! Please sign DCO as described here: https://github.com/organicmaps/organicmaps/pull/910/checks?check_run_id=3139856047

(or simply edit your commit and manually add your signature).

**Comment by MASangys** [comment]
Sorry but I was trying many solutions to figure out how to sign, I didnt learn any coding and was unable do sign even I had downloaded GitHub desktop version. But based on Next, head to your local branch and run: , I cannot find a button to run. I had digged down for hours to sign but unfortunately I still dindt figure out. I do hope that these 3 PR can be completed.

**Comment by biodranik** [comment]
The easiest way is to
```
git commit --amend --signoff
git push -f
```

**Comment by MASangys** [comment]
> The easiest way is to
> 
> ```
> git commit --amend --signoff
> git push -f
> ```

How?

**Review by rtsisyk — APPROVED** [review]

**Review by biodranik — APPROVED** [review]

**Pull request merged**
