### PR TITLE
[android] Improve theming in alertDialog on most recent devices

### PR DESCRIPTION
**Pull request by Jean-BaptisteC**
Tested on Pixel 6 - Android 13, Honor 8 - Android 8
| Before | After |
|---|---|
|||
|||
|||

I have re-used properties used in dialog layout https://github.com/organicmaps/organicmaps/blob/352ac9bda12b4f2bd57c0bba1065bf28a7a2c2d0/android/res/layout/dialog_sorting_types.xml#L7

I have check on Yoga Tab 2 - Android 5, background color is good without corrections

I have just need help to fix color on Title and text :)

### CODE REVIEW

**Comment by Jean-BaptisteC** [comment]
I have try to update different color on alertdialog theme, but text have always wrong color in light or dark mode.
I think dark theme for alert dialog is never used (except for alert dialog with layout).
I have see this solution, to call right theme but, i think is not really a good fix, normally android is able to call right theme
https://github.com/organicmaps/organicmaps/blob/fd7b293faf936e9973f27ef453a9028a2686514b/android/src/app/organicmaps/editor/HoursMinutesPickerFragment.java#L81

An idea ? @arnaudvergnet :)

**Comment by arnaudvergnet** [comment]
I'm not a pro with android themes, but I agree with you that the current approach is not the best. We should not have to manually check if we are in night mode or not.

We should try to make all dialog themes inherit from `MwmTheme.AlertDialog` so we only overwrite the properties we need, and the rest is shared.

To avoid manually defining a day/night variant, we could use attributes instead of colors. For example, instead of `@color/bg_cards`, we could use `@attr/cardBackground`, which is defined in `theme-base.xml` as either `@color/bg_cards` when using the light theme or `@color/bg_cards_night` when night. The attribute automatically changes when the user switches theme so we would not need the solution you linked to choose the right theme.

**Comment by Jean-BaptisteC** [comment]
Tested on Android 8 and Android 13
Thanks :) @arnaudvergnet 

PTAL

**Review by vng — APPROVED** [review]
Is it separate with https://github.com/organicmaps/organicmaps/pull/4665 or should go together?

**Comment by Jean-BaptisteC** [comment]
Separate because here we fix a bug, in other PR, i migrate alert dialogs to prepare migration to Material Theming

**Pull request merged**
