### PR TITLE
[android] Add word-wrapping to text-type editor fields

### LINKED ISSUE #2721: [Editor]: add word wrapping
Some lengthy website addresses etc [aren't word-wrapped](https://user-images.githubusercontent.com/22843816/173226628-063151a3-13da-48ed-a2ed-c2841443c484.png), and it isn't very convenient to edit them.

It would be nice if editor fields would have word wrapping

### PR DESCRIPTION
**Pull request by iuvenis**
Should make it easier to modify long mail or website addresses.

Relevant issue: https://github.com/organicmaps/organicmaps/issues/2721

Resolves #2721

Signed-off-by: David Jung <jungwdk@pm.me>

### CODE REVIEW

**Comment by biodranik** [comment]
Thanks! What does it look like now, especially on smaller screens?

**Comment by iuvenis** [comment]
I tested in on an emulated Pixel 2. Not a particularly small screen, but I think it gets the principle across alright - it makes line breaks preferentially at dots/slashes/dashes/underscores/etc and otherwise at the full width of the input field. Or do you want to see it on a smaller screen still?

Screenshot 2022-06-27 at 00 05 15

**Review by biodranik — COMMENTED** [review]
Thanks, it looks ok.

After checking the current implementation, I see that instead of defining UI elements' attributes in XML, they are duplicated there and manually overridden here, from the code. Do you have any idea, why? Won't the code be cleaner, faster to initialize, and easier to edit/maintain if all (or some) of these UI elements will be initialized in the XML with proper attributes, instead of overriding default ones from the code? What do you think?

**Comment by iuvenis** [comment]
No, you are probably right. That seemed strange to me as well, but then I got a bit timid about starting to refactor stuff right away before getting more familiar with the codebase. I'll check if it's not better to move it into the xml either later today or sometime this week.

**Comment by biodranik** [comment]
Refactoring is the best way to learn and understand the code ;-) It would be great if you can simplify/cleanup it a bit. Or at least find a real reason why the code is organized in the current messy way.

**Comment by iuvenis** [comment]
After a bit of experimentation and reading up on android layout XMLs and their limitations (https://stackoverflow.com/questions/9013298/setting-attribute-of-child-element-of-included-layout) I'm now doubting that it makes sense to move the attributes of those individual input fields from the code to the XML. As I see it we'd have to copy-paste most of the item_editor_input.xml for each input field, setting only the hint, the icon src and the input type differently for each. The attributes aren't really overridden in the code, either - hint and icon src are only specified using tools attributes in the XML, so they would be stripped away in compilation and are only displayed as placeholders in the android studio design view apparently. The input type isn't explicitly specified in the XML. All in all the alternative seems more verbose, less maintainable, and I'm unsure what difference it would make either way performance-wise.

I'm quite open for suggestions. But at this point this particular messiness seems to make sense to me :-)

**Review by biodranik — APPROVED** [review]
Thanks for the research ) Looks like Android guys were too lazy to allow overriding parameters in included layouts. Ok, let's merge it!

**Pull request merged**
