### PR TITLE
[styles] Lower isolines priority

### PR DESCRIPTION
**Pull request by pastk**
Isolines are drawn over 2d buildings (but not 3d), roads, etc. It makes the map look messy and less readable.

Made isolines priority lower than buildings and most other lines
(just removed a wrong z-index value that was overriding a normal one - it was like this from the isolines inception ec88d57c66a1b0ccd4e68032a01346e2e935f378).
This made isolines captions priority lower too (though I didn't notice any actual display difference so far).

isolines_priority

Still, isolines are drawn over tunnels with a negative `layer=` (see motorway tunnel above), because `layer=` code modifies priorities.

And they're visible under transparent 3d buildings still:

3d_buildings

And above water also: #1731

We can get back to these special cases later.

### CODE REVIEW

**Review by biodranik — APPROVED** [review]
@vng WDYT?

**Comment by vng** [comment]
Actually, I don't mind with this change. But we have isolines as completely _separate_ layer. Don't you think that if somebody turns on isolines, the main and primary visible objects should be isolines? Ok, who cares that they draw above buildings?

Moreover, I'd like to see isolines height-text more often in this mode.

**Comment by biodranik** [comment]
Good arguments.

Nobody complained so far, that's true.
And numbers with elevation are extremely useful. The elevation is not obvious when they are hidden.

**Comment by pastk** [comment]
> Actually, I don't mind with this change. But we have isolines as completely _separate_ layer. Don't you think that if somebody turns on isolines, the main and primary visible objects should be isolines?
> 

No. Isolines are meant to **add** altitude/relief information to the map. People use **the map** augmented with isolines, not vice versa. E.g. to examine at which altitude does the track go or a village is - for this you need to see clearly map features first.

> Moreover, I'd like to see isolines height-text more often in this mode.

Outdoors they're visible fine. Just check the screenshots - is it not enough captions? In big cities isolines are of limited use anyway.
But we can raise their priority separately if its really needed.

**Comment by pastk** [comment]
Basically just check any proper topo map and see how isolines are layered...

**Comment by pastk** [comment]
Rebased.

**Comment by biodranik** [comment]
The approach is great, but the altitude text won't be visible in many cases now, right? Do we have a mechanism to find a proper text label placement not covered by some other objects?

**Comment by pastk** [comment]
> The approach is great, but the altitude text won't be visible in many cases now, right? Do we have a mechanism to find a proper text label placement not covered by some other objects?

Why? Labels are very well visible still, check the screenshots. TBH I haven't been able to see any change, maybe in some rare cases... - the captions priority change was very minor..

**Comment by pastk** [comment]
Here are details on relative priorities changes in this PR:
IMO isolines' path texts priorities became insignificantly lower (usually became just below highways), so it doesn't make sense to e.g. add an exception to make them higher back.

```diff
 OVRL/z10	 text	 place-islet                   	 z[14-19]
 OVRL/z10	 text	 place-suburb                  	 z[10-14]
 OVRL/z11	 icon	 amenity-ferry_terminal        	 z[11-19]
 OVRL/z11	 icon	 railway-station-subway-moscow 	 z[11-19]
 OVRL/z11	 icon	 railway-station-subway-spb    	 z[11-19]
 OVRL/z11	 icon	 natural-cave_entrance         	 z[11-19]
 OVRL/z11	 icon	 waterway-waterfall            	 z[11-19]
-OVRL/z11	 ptxt	 isoline-step_1000             	 z[11-19]
-OVRL/z11	 ptxt	 isoline-step_500              	 z[12-19]
 OVRL/z11	 ptxt	 highway-tertiary              	 z[12-19]
 OVRL/z11	 ptxt	 highway-tertiary-bridge       	 z[12-19]
 OVRL/z11	 ptxt	 highway-tertiary-tunnel       	 z[12-19]
 OVRL/z11	 ptxt	 highway-unclassified          	 z[13-19]
 OVRL/z11	 ptxt	 highway-unclassified-area     	 z[13-19]
 OVRL/z11	 ptxt	 highway-unclassified-bridge   	 z[13-19]
 OVRL/z11	 ptxt	 highway-unclassified-tunnel   	 z[13-19]
+OVRL/z11	 ptxt	 isoline-step_1000             	 z[11-19]
+OVRL/z11	 ptxt	 isoline-step_500              	 z[12-19]
 OVRL/z11	 text	 amenity-ferry_terminal        	 z[16-19]
 OVRL/z11	 text	 railway-station-subway-moscow 	 z[12-15]
 OVRL/z11	 text	 railway-station-subway-spb    	 z[12-16]
 OVRL/z11	 text	 natural-cave_entrance         	 z[11-19]
 OVRL/z11	 text	 waterway-waterfall            	 z[11-19]
 OVRL/z11	 text	 place-village                 	 z[11-19]
 OVRL/z11	 text	 natural-wetland               	 z[16-19]
 OVRL/z11	 text	 natural-wetland-bog           	 z[16-19]
 OVRL/z11	 text	 natural-wetland-marsh         	 z[16-19]
 OVRL/z12	 icon	 railway-station               	 z[12-19]
 OVRL/z12	 icon	 railway-station-light_rail    	 z[12-19]
...
 OVRL/z13	 icon	 leisure-swimming_pool-private 	 z[17-19]
 OVRL/z13	 icon	 historic-city_gate            	 z[13-19]
 OVRL/z13	 ptxt	 highway-cycleway              	 z[15-19]
 OVRL/z13	 ptxt	 highway-cycleway-bridge       	 z[15-19]
 OVRL/z13	 ptxt	 highway-cycleway-permissive   	 z[15-19]
 OVRL/z13	 ptxt	 highway-cycleway-tunnel       	 z[15-19]
-OVRL/z13	 ptxt	 isoline-step_100              	 z[15-19]
 OVRL/z13	 icon	 highway-ford                  	 z[16-19]
 OVRL/z13	 ptxt	 highway-ford                  	 z[16-19]
 OVRL/z13	 ptxt	 highway-pedestrian            	 z[14-19]
 OVRL/z13	 ptxt	 highway-pedestrian-area       	 z[14-19]
 OVRL/z13	 ptxt	 highway-pedestrian-bridge     	 z[14-19]
 OVRL/z13	 ptxt	 highway-pedestrian-tunnel     	 z[14-19]
 OVRL/z13	 ptxt	 highway-construction          	 z[15-19]
+OVRL/z13	 ptxt	 isoline-step_100              	 z[15-19]
 OVRL/z13	 text	 natural-strait                	 z[13-19]
 OVRL/z13	 text	 railway-station-subway        	 z[14-19]
 OVRL/z13	 text	 railway-station-subway-ankara 	 z[14-19]
 OVRL/z13	 text	 railway-station-subway-athens 	 z[14-19]
...
 OVRL/z15	 icon	 man_made-water_tap            	 z[15-19]
 OVRL/z15	 icon	 man_made-water_well           	 z[15-19]
 OVRL/z15	 ptxt	 highway-steps                 	 z[16-19]
 OVRL/z15	 ptxt	 highway-steps-bridge          	 z[16-19]
 OVRL/z15	 ptxt	 highway-steps-tunnel          	 z[16-19]
-OVRL/z15	 ptxt	 isoline-step_10               	 z[17-19]
-OVRL/z15	 ptxt	 isoline-step_50               	 z[17-19]
-OVRL/z15	 ptxt	 isoline-zero                  	 z[17-19]
 OVRL/z15	 ptxt	 highway-tertiary_link         	 z[18-19]
 OVRL/z15	 ptxt	 highway-tertiary_link-bridge  	 z[18-19]
 OVRL/z15	 ptxt	 highway-tertiary_link-tunnel  	 z[18-19]
 OVRL/z15	 ptxt	 highway-busway                	 z[16-19]
 OVRL/z15	 ptxt	 highway-busway-bridge         	 z[16-19]
 OVRL/z15	 ptxt	 highway-busway-tunnel         	 z[16-19]
 OVRL/z15	 ptxt	 highway-service               	 z[16-19]
 OVRL/z15	 ptxt	 highway-service-area          	 z[16-19]
 OVRL/z15	 ptxt	 highway-service-bridge        	 z[16-19]
 OVRL/z15	 ptxt	 highway-service-busway        	 z[16-19]
 OVRL/z15	 ptxt	 highway-service-parking_aisle 	 z[16-19]
 OVRL/z15	 ptxt	 highway-service-tunnel        	 z[16-19]
 OVRL/z15	 ptxt	 highway-footway               	 z[15-19]
 OVRL/z15	 ptxt	 highway-footway-bridge        	 z[15-19]
 OVRL/z15	 ptxt	 highway-footway-permissive    	 z[15-19]
 OVRL/z15	 ptxt	 highway-footway-tunnel        	 z[15-19]
 OVRL/z15	 icon	 amenity-parking               	 z[16-19]
 OVRL/z15	 icon	 amenity-parking-fee           	 z[16-19]
 OVRL/z15	 icon	 amenity-parking-multi-storey  	 z[16-19]
 OVRL/z15	 icon	 amenity-parking-no-access     	 z[16-19]
 OVRL/z15	 icon	 amenity-parking-park_and_ride 	 z[16-19]
 OVRL/z15	 icon	 amenity-parking-permissive    	 z[16-19]
 OVRL/z15	 icon	 amenity-parking-private       	 z[16-19]
 OVRL/z15	 icon	 amenity-parking-underground   	 z[16-19]
+OVRL/z15	 ptxt	 isoline-step_10               	 z[17-19]
+OVRL/z15	 ptxt	 isoline-step_50               	 z[17-19]
+OVRL/z15	 ptxt	 isoline-zero                  	 z[17-19]
 OVRL/z15	 icon	 leisure-pitch                 	 z[17-19]
 OVRL/z15	 icon	 amenity-college               	 z[16-19]
 OVRL/z15	 icon	 amenity-kindergarten          	 z[17-19]
 OVRL/z15	 icon	 amenity-school                	 z[17-19]
 OVRL/z15	 text	 amenity-college               	 z[16-19]

...
 GEOM	 line1	 highway-primary-tunnel        	 z[14-19]
 GEOM	 line1	 highway-primary_link          	 z[11-19]
 GEOM	 line1	 highway-primary_link-bridge   	 z[11-13]
 GEOM	 line3	 highway-primary_link-bridge   	 z[14-19]
 GEOM	 line1	 highway-primary_link-tunnel   	 z[11-13]
 GEOM	 line2	 highway-primary_link-tunnel   	 z[14-19]
 GEOM	 line1	 highway-primary_link-tunnel   	 z[14-19]
-GEOM	 line1	 isoline-step_10               	 z[15-19]
-GEOM	 line1	 isoline-step_100              	 z[13-19]
-GEOM	 line1	 isoline-step_1000             	 z[11-19]
-GEOM	 line1	 isoline-step_50               	 z[15-19]
-GEOM	 line1	 isoline-step_500              	 z[11-19]
-GEOM	 line1	 isoline-zero                  	 z[15-19]
 GEOM	 line1	 highway-secondary             	 z[10-19]
 GEOM	 line1	 highway-secondary-bridge      	 z[10-13]
 GEOM	 line3	 highway-secondary-bridge      	 z[14-19]
 GEOM	 line1	 highway-secondary-tunnel      	 z[10-15]
 GEOM	 line2	 highway-secondary-tunnel      	 z[16-19]
 GEOM	 line1	 highway-secondary-tunnel      	 z[16-19]
 GEOM	 line1	 highway-secondary_link        	 z[14-19]
 GEOM	 line3	 highway-secondary_link-bridge 	 z[14-19]
 GEOM	 line1	 highway-secondary_link-tunnel 	 z[14-15]
 GEOM	 line2	 highway-secondary_link-tunnel 	 z[16-19]
 GEOM	 line1	 highway-secondary_link-tunnel 	 z[16-19]
 GEOM	 line1	 highway-residential           	 z[12-19]
 GEOM	 line1	 highway-residential-area      	 z[12-19]
 GEOM	 line1	 highway-residential-bridge    	 z[12-13]
 GEOM	 line3	 highway-residential-bridge    	 z[14-19]
...
 GEOM	 area	 building:part                 	 z[16-19]
 GEOM	 area	 landuse-garages               	 z[14-19]
 GEOM	 line1	 barrier-retaining_wall        	 z[16-19]
 GEOM	 line1	 man_made-embankment           	 z[16-19]
 GEOM	 line1	 natural-cliff                 	 z[14-19]
 GEOM	 line1	 natural-earth_bank            	 z[14-19]
 GEOM	 line1	 boundary-administrative-2     	 z[2-19]
 GEOM	 line1	 boundary-administrative-3     	 z[4]
 GEOM	 line1	 boundary-administrative-4     	 z[5-19]
 GEOM	 line1	 boundary-military             	 z[10-19]
 GEOM	 line1	 man_made-cutline              	 z[14-19]
 GEOM	 line1	 route-ferry                   	 z[10-19]
 GEOM	 line1	 aeroway-runway                	 z[12-19]
 GEOM	 line1	 aeroway-taxiway               	 z[14-19]
 GEOM	 line1	 barrier-ditch                 	 z[17-19]
+GEOM	 line1	 isoline-step_10               	 z[15-19]
+GEOM	 line1	 isoline-step_100              	 z[13-19]
+GEOM	 line1	 isoline-step_1000             	 z[11-19]
+GEOM	 line1	 isoline-step_50               	 z[15-19]
+GEOM	 line1	 isoline-step_500              	 z[11-19]
+GEOM	 line1	 isoline-zero                  	 z[15-19]
 GEOM	 line2	 highway-footway-tunnel        	 z[17-19]
 GEOM	 line2	 highway-path-tunnel           	 z[17-19]
 GEOM	 line2	 highway-steps-tunnel          	 z[17-19]
 GEOM	 line1	 railway-light_rail-bridge     	 z[14-15]
 GEOM	 line2	 railway-light_rail-bridge     	 z[16-19]
 GEOM	 line1	 railway-yard-bridge           	 z[14-15]
 GEOM	 line2	 railway-yard-bridge           	 z[16-19]
 GEOM	 line1	 highway-footway-tunnel        	 z[17-19]
 GEOM	 line1	 highway-path-tunnel           	 z[17-19]
 GEOM	 line1	 highway-steps-tunnel          	 z[17-19]
 GEOM	 line1	 railway-light_rail-bridge     	 z[16-19]
 GEOM	 line1	 railway-yard-bridge           	 z[16-19]
 GEOM	 line1	 natural-strait                	 z[13-19]
 GEOM	 line1	 waterway-canal                	 z[13-19]
 GEOM	 line1	 waterway-river                	 z[10-19]
```

**Review by vng — APPROVED** [review]

**Pull request merged**
