### PR TITLE
[TTS] Regenerated missing es-MX and pt-BR strings

### LINKED ISSUE #3972: Add PT-BR to sound strings
Hi there,

I went to review #3130 but I could not find PT-BR in [organicmaps/data/sound-strings/](https://github.com/organicmaps/organicmaps/tree/master/data/sound-strings). However, the strings do exist in [organicmaps/data/strings/sound.txt](https://github.com/organicmaps/organicmaps/blob/master/data/strings/sound.txt).

I think the problem is related to the strings regenerator.

### PR DESCRIPTION
**Pull request by biodranik**
Fixes #3972

But it should be tested first. I suspect that locales with more than two characters in name/path won't be loaded/detected/used properly.

### CODE REVIEW

**Comment by vng** [comment]
Aggregate this changes https://github.com/organicmaps/organicmaps/pull/3983 after merge?

**Comment by matheusgomesms** [comment]
Sounds good, but please regenerate PT/PT-BR strings, since #3980 updated some of them.

**Review by rtsisyk — APPROVED** [review]

**Comment by matheusgomesms** [comment]
@vng Can you please take a look? #3983 got closed, so perhaps doesn't need to wait for that PR.

**Comment by biodranik** [comment]
Let me fix it.

**Comment by biodranik** [comment]
@Jean-BaptisteC can you please test if these locales work properly? It makes sense to check for differences in es and es-MX, pt and pt-BR versions in https://github.com/organicmaps/organicmaps/blob/master/data/strings/sound.txt and confirm that they work if the appropriate TTS engine is selected.

**Review by matheusgomesms — APPROVED** [review]

**Review by vng — APPROVED** [review]

**Pull request merged**
