### PR TITLE
[styles] add icon for traffic lights in vehicle style

### PR DESCRIPTION
**Pull request by RedAuburn**
image1
MWM with traffic signals generated: https://drive.proton.me/urls/V5PQKS2DMM#iELWaRN9Xtu3

I'd like to make them a bit bigger ideally, but it seems like there's an icon size cap somewhere?

map regen needed

### CODE REVIEW

**Comment by RedAuburn** [comment]
i'd like to make them a bit bigger ideally, but it seems like there's a hardcoded icon size cap somewhere?

**Comment by dvdmrtnz** [comment]
> it seems like there's an icon size cap somewhere?

Icons are limited to 18x18 max. See https://github.com/organicmaps/organicmaps/issues/7195#issuecomment-1913622629

**Comment by RedAuburn** [comment]
i think the failing check isn't related to this PR?

**Comment by vng** [comment]
@RedAuburn On what device did you make these screenshots? What dpi was set?!
Here is xhdpi:

**Comment by vng** [comment]
And something strange happened with styles generator.
@pastk Did you see it? We declare z19- (same as z19, z20) in vehicle style only, but got only z19 in general drules_proto.txt

**Comment by biodranik** [comment]
Would it be possible to display traffic lights and STOP sign icons on top of the built route, like "paid" symbols are displayed now (and like other maps are displaying them)?

выява

выява

выява

**Comment by RedAuburn** [comment]
> @RedAuburn On what device did you make these screenshots? What dpi was set?!

Desktop @ 2256px x 1504px, with QT scaling hardcoded to 1.25 to match 125% desktop scaling (auto scaling is broken, see https://github.com/organicmaps/organicmaps/issues/4836)

**Comment by RedAuburn** [comment]
> Would it be possible to display traffic lights and STOP sign icons on top of the built route, like "paid" symbols are displayed now (and like other maps are displaying them)?

i think this should already work, but a generating a mwm to test & fix if not 👍️

**Comment by RedAuburn** [comment]
can confirm that it renders over the route fine
image

the main issue is still that the icons are quite small (capped to 18x18), but it looks quite complicated to fix

**Comment by pastk** [comment]
> And something strange happened with styles generator. @pastk Did you see it? We declare z19- (same as z19, z20) in vehicle style only, but got only z19 in general drules_proto.txt

Yeap its strange. Might need to debug `tools/python/stylesheet/drules_merge.py`.

**Comment by pastk** [comment]
Personally I'd love to see traffic lights in the main style too (no earlier than z19-). Its useful for pedestrians and cyclists too.

For reference, there are 1.8M `highway=traffic_signals`.

`crossing=traffic_signals` (1.4M) is even more useful for pedestrians, but should have a different icon to be distinguishable.

BTW [fun fact re OM :)](https://wiki.openstreetmap.org/wiki/Tag:crossing%3Dtraffic_signals#Renderers)

**Comment by pastk** [comment]
Also need to test it on cases with many signals mapped close to each other on complex intersections, see https://wiki.openstreetmap.org/wiki/Tag:highway=traffic_signals#Tag_all_incoming_ways

**Comment by biodranik** [comment]
> Personally I'd love to see traffic lights in the main style too

I don't think it's a good idea. Pedestrians should carefully look around, not blindly trust the (possibly outdated or incorrect) community-generated map source. It also pollute the already polluted general style in cities.

**Comment by pastk** [comment]
> Pedestrians should carefully look around, not blindly trust the (possibly outdated or incorrect) community-generated map source. 

No doubt! The point is not about "blind trust", but about discovery. Thanks to traffic lights display a user can e.g. choose a route that will cross a bigger road in a safer place with signals (esp. important for reduced mobility people).

**Comment by euf** [comment]
I'd like to propose two changes: 
1. @dvdmrtnz is it possible to change `skin_generator/generator.cpp` so that maximum size is capped at 24×24 instead of 18×18? Could you try it? I'm not any good with C++.
2. @RedAuburn would you consider these 24×24 icons I sketched as a replacement for your variant? It has the same color choices, but apart from being bigger they are also aligned on a pixel grid to look more crisp and legible.


| clear | night |
|------|------|
| traffic_signals-l-clear | traffic_signals-l-night |  

The point is we already have `speedcam-alert-l` which is 24×24. I believe it's supposed to be rendered big on the map to be clearly seen during navigation, just like suggested `traffic_signals-l`.

**Comment by dvdmrtnz** [comment]
>  1. @dvdmrtnz is it possible to change `skin_generator/generator.cpp` so that maximum size is capped at 24×24 instead of 18×18? Could you try it? I'm not any good with C++.

@euf Yes, maximum size can be increased to 24x24 easily. However we should fix first the current svg files that are bigger than 18x18 so they don't become bigger in the app.

**Comment by RedAuburn** [comment]
thank you @euf ! now using new icons. i need to learn to do this grid alignment thing :)

it's probably best to fix the size issue in another PR? then can update this one & merge

**Comment by RedAuburn** [comment]
> Personally I'd love to see traffic lights in the main style too (no earlier than z19-). Its useful for pedestrians and cyclists too.
> 
> For reference, there are 1.8M `highway=traffic_signals`.
> 
> `crossing=traffic_signals` (1.4M) is even more useful for pedestrians, but should have a different icon to be distinguishable.

i think in the main style, we should only render `crossing=traffic_signals`, and ideally other crossing types too :)

> BTW [fun fact re OM :)](https://wiki.openstreetmap.org/wiki/Tag:crossing%3Dtraffic_signals#Renderers)

that changes in this pr 😅 i'll update the wiki when it's merged

**Comment by euf** [comment]
@dvdmrtnz I checked which of the icons are bigger than 18×18. There are 44 entries by overall size: 


|name|style-clear|style-night|width|height|
|-|-|-|-|-|
|speedcam-alert-l.svg|||24|24|
|subway-adana-m.svg|||22.5|22.5|
|subway-ankara-m.svg|||22.5|22.5|
|subway-marseille-m.svg|||22.5|21.75|
|motorcycle-parking-m.svg|||21.75|21.75|
|subway-cairo-m.svg|||21.75|21.75|
|subway-ekb-m.svg|||21.75|21.75|
|subway-hirosima-m.svg|||21.75|21.75|
|subway-isfahan-m.svg|||21.75|21.75|
|subway-medellin-m.svg|||21.75|21.75|
|subway-panama-m.svg|||21.75|21.75|
|subway-southkorea-m.svg|||21.75|21.75|
|geyser-l.svg|||21|21|
|subway-algeria-m.svg|||21|21|
|subway-stlouis-m.svg|||21|21|
|subway-taoyuan-m.svg|||21|18|
|subway-almaty-m.svg|||21|17.25|
|subway-omsk-m.svg|||21.75|16.5|
|subway-tabriz-m.svg|||21.75|16.5|
|subway-buenosaires-m.svg|||18.75|18.75|
|subway-glasgow-m.svg|||18.75|18.75|
|subway-lausanne-m.svg|||18.75|18.75|
|subway-losangeles-m.svg|||18.75|18.75|
|subway-pittsburgh-m.svg|||18.75|18.75|
|subway-pyongyang-m.svg|||18.75|18.75|
|subway-rennes-m.svg|||18.75|18.75|
|subway-riodejaneiro-m.svg|||18.75|18.75|
|subway-warszawa-m.svg|||18.75|18.75|
|subway-dalian-m.svg|||19|18|
|subway-sapporo-m.svg|||19|18|
|subway-lucknow-m.svg|||21.75|15|
|subway-palma-m.svg|||21.75|14.25|
|subway-istanbul-m.svg|||15.75|19.5|
|subway-brussel-m.svg|||22.5|13.5|
|subway-kharkiv-m.svg|||22.5|13.5|
|subway-osaka-m.svg|||20.25|15|
|subway-sendai-m.svg|||21.75|13.5|
|subway-barcelona-m.svg|||20.25|14.25|
|subway-madrid-m.svg|||20.25|14.25|
|subway-edmonton-m.svg|||23.25|11.25|
|subway-manila-m.svg|||20.25|12|
|subway-kolkata-m.svg|||18.75|12.75|
|subway-baku-m.svg|||21.75|9|
|subway-chongqing-m.svg|||23.25|8.25|

 * not sure if we should fix `subway-` icons or let them be a little bit bigger
 * `motorcycle-parking-m` should be fixed
 * `geyser-l` seems to be bigger on purpose, as well as `speedcam-alert-l`

What do you think?

**Comment by euf** [comment]
In the meantime I've drawn a stop sign icon. It's perfectly aligned on a 24×24 pixel grid to be crisp and readable ✨ 

| original svg | rasterized mdpi |
|----|----|
| stop_sign-l | stop_sign-l-mdpi | 

Feel free to grab this `stop_sign-l.svg` and use it in addition to traffic lights!

**Comment by euf** [comment]
And just to fill the gap here is the yield sign I've drawn. It's also aligned on a 24×24 pixel grid.

| original svg | rasterized mdpi |
|----|----|
| give_way-sign-l | give_way-sign-l-mdpi | 

I hope this `give_way-sign-l.svg` will also prove useful.

**Comment by euf** [comment]
Luckily @dvdmrtnz already made a #7321 PR that addresses this resizing issue ❤️ 

Once it's merged, this traffic lights PR can be rebased and checked for visual appearance. I'm sure it would look great!

**Comment by pastk** [comment]
> what about keeping the 19x19 cap, but providing an override flag in the mapcss? this way, we can ensure the majority of icons are sized correctly, but can have bigger icons if needed.

Perhaps for now the suffix `-s/-m/-l` of the icon file could be used as a "flag", i.e. validate and allow >18x18 sizes for `-l` icons only.

But actually why do we have several manually created sizes?
Is it hard to automatically upsize or downsize an svg icon just before rendering it into png? @dvdmrtnz 
If its reasonably easy to do then indeed we should use a `icon-size` param in styles.

**Comment by biodranik** [comment]
Rebase and fix tests?

**Comment by pastk** [comment]
> > And something strange happened with styles generator. @pastk Did you see it? We declare z19- (same as z19, z20) in vehicle style only, but got only z19 in general drules_proto.txt
> 
> Yeap its strange. Might need to debug `tools/python/stylesheet/drules_merge.py`.

@RedAuburn could you pease take a look at this issue?

**Comment by RedAuburn** [comment]
> > Yeap its strange. Might need to debug `tools/python/stylesheet/drules_merge.py`.
> 
> @RedAuburn could you please take a look at this issue?

will try

**Comment by euf** [comment]
Hi all, any updates on the PR? I'd really love to see these traffic lights, stop signs and yield signs in the Navigation mode 🔥

**Comment by RedAuburn** [comment]
> Hi all, any updates on the PR? I'd really love to see these traffic lights, stop signs and yield signs in the Navigation mode 🔥

i'm gonna be really busy for the next few months unfortunately, feel free to fork this PR! (if not, i'll get around to it eventually)

**Pull request closed without merging**
