### PR TITLE
Fix build modes other than Release and Debug in 3party/osrm

### LINKED ISSUE #2859: [Linux desktop] Failure to compile on 32-bit systems
Due to https://github.com/organicmaps/organicmaps/blob/master/generator/intermediate_data.cpp#L131

Is 32-bit actively unsupported? Wouldn't that lock out a lot of Android phones as well? Or is it somehow trying to compile code which it just shouldn't do?

### PR DESCRIPTION
**Pull request by PureTryOut**
osrm only supported the "Release" and "Debug" build modes but CMake supports
several other options. The lack of support for these options made it so
using those made the `desktop` build target unavailable

Thus if the cmake build mode wasn't set to "Release" or "Debug", `cmake
--target desktop` would not work

Fixes #2859

### CODE REVIEW

**Comment by vng** [comment]
Hm, I don't mind about this change, but our working targets don't depend on osrm (maybe I miss something). So I don't understand what it should fix .. Osrm remains in repo for possible future standalone tool ..

**Comment by PureTryOut** [comment]
I'm not entirely sure why it would matter, but it's a fact that I had no `desktop` target available in make without this change. It's the only thing I could find that would mind a build type other than `Release` and `Debug`. So _something_ is still invoking the CMake files of osrm, somehow.

**Comment by biodranik** [comment]
@PureTryOut can you please share the log of your errors on the master branch without these changes? There should be no OSRM dependency in the main repo. We need to investigate it.

**Comment by PureTryOut** [comment]
Sure, but I'm not sure what error log you'd want. The error is literally cmake (or make, both complain the same) telling me there is no desktop target available (when I call `cmake --target desktop` or `make desktop`). There are no errors other than that

**Comment by biodranik** [comment]
What are your previous commands? What is the exact log?

There is obviously a desktop target, and there is no osrm dependency.

**Comment by biodranik** [comment]
1. This patch is not related to the desktop target of the main repo. Our code does not depend on OSRM. Please get the latest version of organic maps on the master branch and publish all your commands and logs if you still have some errors there. 
2. If you build osrm separately, and want to fix it, then it's better to update the whole osrm module to the latest version.

**Comment by Jean-BaptisteC** [comment]
This PR is really necessary?

**Comment by biodranik** [comment]
No, we don't use OSRM, so it can be closed.

**Pull request closed without merging**
