### PR TITLE
Fix map generator dependencies. Remove missing localads_mwm_to_csv.

### PR DESCRIPTION
**Pull request by rawder**

### CODE REVIEW

**Review by biodranik — APPROVED** [review]
LGTM

**Comment by biodranik** [comment]
@rawder Can you please sign your commit `git commit --amend --signoff` and then `git push -f` ?

**Review by rtsisyk — CHANGES_REQUESTED** [review]
Please sign off, we don't accept anonymous contributions.

**Comment by rawder** [comment]
> Please sign off, we don't accept anonymous contributions.

Sorry, 
done!

**Comment by biodranik** [comment]
@rawder you need to sign all commits, e.g. `git rebase --exec 'git commit --amend --no-edit -n --signoff' -i master`

**Comment by rtsisyk** [comment]
It is still anonymous: `Signed-off-by: rawder <ppp7829@mail.ru>`. @rawder, you already have the real name on GitHub. Please just use `Signed-off-by: Andrew Kovalenko <ppp7829@mail.ru>` instead.  See https://github.com/organicmaps/organicmaps/blob/master/docs/CONTRIBUTING.md#pull-requests for details.

**Pull request merged**
