### PR TITLE
add metal_construction icon

### PR DESCRIPTION
**Pull request by yaslack**

### CODE REVIEW

**Comment by Jean-BaptisteC** [comment]
Thanks
Please follow https://github.com/organicmaps/organicmaps/blob/master/docs/STYLES.md

**Review by biodranik — COMMENTED** [review]
1. Does this icon look good on lower DPI devices? E.g. older Androids 5,6,7?
2. Can you please split your actual changes and icon vs regenerated files into separate commits?

**Comment by yaslack** [comment]
> 1. Does this icon look good on lower DPI devices? E.g. older Androids 5,6,7?
> 2. Can you please split your actual changes and icon vs regenerated files into separate commits?

1. yes if others do since i copy paste a existent one and only change the <path>
2. i will try

**Comment by vng** [comment]
Please, actual changes in the first commit. Regenerated symbols in the second commit.

**Comment by Jean-BaptisteC** [comment]
Please don't close PR and reopened another, if you don't know how rebase PR

**Pull request closed without merging**
