### PR TITLE
[android] Unify accent color across the app

### PR DESCRIPTION
**Pull request by meenbeese**
Closes #4444

### CODE REVIEW

**Comment by meenbeese** [comment]
@Jean-BaptisteC Can you help with screenshots/video as was done in #4444 if you have time?

**Comment by RedAuburn** [comment]
looks nice 👍️
image1

the download maps ui still has blue buttons, and i'd guess that the symbol added in https://github.com/organicmaps/organicmaps/pull/6989 needs it's colour changed too

**Comment by Jean-BaptisteC** [comment]
Nice job, looks good is light and dark mode.
I have one suggestions -> keep blue arrow in location button
And this change need to be tested in Android Auto

**Comment by Jean-BaptisteC** [comment]
Can you rebase your branch?

**Pull request closed without merging**
