### PR TITLE
Fix pier area rendering as lines on lower zoom levels

### PR DESCRIPTION
**Pull request by endim8**
before/after:
signal-2022-11-02-112221

fixes https://github.com/organicmaps/organicmaps/issues/3781

### CODE REVIEW

**Review by vng — COMMENTED** [review]
Well, this is not a good fix for area priority.
Not sure if I can, but I'm gonna make a bit another fix ..

**Comment by vng** [comment]
In short, water has declared z=100, pier has declared z=120. The error occurs in Basemap_label.mapcss, where z=10000 for water. I suspect that it was intented to water caption styles only!

**Comment by vng** [comment]
https://github.com/organicmaps/organicmaps/pull/3803/commits/37761494f35e574e69f171506149b1f92c7664e3

**Comment by endim8** [comment]
> [3776149](https://github.com/organicmaps/organicmaps/commit/37761494f35e574e69f171506149b1f92c7664e3)

thank you :)

**Pull request closed without merging**
