### PR TITLE
[strings] Fix PT strings

### PR DESCRIPTION
**Pull request by matheusgomesms**
Quick fix: PT and PT-BR were mixed here.

### CODE REVIEW

**Comment by vng** [comment]
Please put pt-BR above the pt: to satisfy validation check.

**Comment by matheusgomesms** [comment]
> Please put pt-BR above the pt: to satisfy validation check.

I can easily do that, but is it correct? In the whole app, PT comes before PT-BR, so perhaps the check should be updated?

**Comment by vng** [comment]
Well, this is because of ':' like "pt-BR:one" string is _lexicographically_ less than "pt:one" string.
IMO, better to change here rather than invent some new comparison in a script ..

**Comment by matheusgomesms** [comment]
Done! I'm using web version, so I can't merge my commits nor do regen strings.

**Review by vng — APPROVED** [review]

**Pull request merged**
