### PR TITLE
[android] SpeedLimitView

### PR DESCRIPTION
**Pull request by AndrewShkrob**
Finally! It's an improvement, but there's more to consider.

We need to decide on a location for it. In portrait mode, it looks good. However, in landscape mode, it might overlap with buttons. If we opt to move this sign to the right corner, we'll need to address the issues with lanes beforehand.

https://github.com/organicmaps/organicmaps/assets/10351358/76ac99db-ef52-4483-adbd-fc8e4a421f8f

### CODE REVIEW

**Comment by biodranik** [comment]
Thanks!

1. Is there any reason for not moving the right buttons to the bottom in the landscape mode? @Jean-BaptisteC @arnaudvergnet 
2. Space on the left under the direction sign is also used for the next turn. And it looks unbalanced with the right part of the screen.
3. Lane arrows UI should be rewritten #1404 #1104, then the position of the speed limit indicator may change.
4. Now in portrait on Android, where lanes are already implemented, it can be displayed as in the screenshot above if the lanes widget size will be automatically scaled down to see all lanes.
5. The size of the speed limit indicator can be slightly reduced.
6. Note that many roads don't have any limits, so the speed limit will appear and disappear frequently.
7. A current speed can be displayed under the speed limit (a separate task).

**Comment by AndrewShkrob** [comment]
Moved view to the top right corner in the land mode.
Fixed bug with incorrect rounding.
Need to move right buttons to the bottom (separate PR).

**Comment by Jean-BaptisteC** [comment]
I'm working to update layouts not fit with RTL, it's can be good to remove LTR forced in new layout

**Comment by fitojb** [comment]
Might a MUTCD red `#bd2025` (instead of this pure red) look better in the speed limit widget? I think the current hue might look a little garish in some screens. (I’m not married with the exact color value; someone could adjust it to conform to a palette.)

**Comment by Jean-BaptisteC** [comment]
A proper solution is to reduce size of SpeedLimitView and down a little buttons at the right in landscape.
In the future, it could be good to rethink the navigation screen and reduce the number of items present to have more space to see the road.

**Comment by RageGamerBoi** [comment]
I believe this implementation is currently overly intrusive.
Is it possible to implement this inside of the bar at the bottom of the screen or somewhere similar?

**Comment by CaldeiraG** [comment]
> I believe this implementation is currently overly intrusive. Is it possible to implement this inside of the bar at the bottom of the screen or somewhere similar?

On iOS, the speed limit is part of the speed indicator as 51/50 (also red text if you're exceeding the limit) but I'm not too bothered about this current implementation if it's a bit smaller.

**Comment by RageGamerBoi** [comment]
That implementation seems ideal, as it doesn't invade the ui too much for those that don't need it, and is still perfectly useful for those who do.
There is also no need for localization for places like the US which doesn't use the red circle for speed limit signs.

**Comment by aureliensoria** [comment]
Hello, I'm very interested in this feature. Is there anything we can do to help regarding this pull request ?

**Comment by AndrewShkrob** [comment]
I'm closing this PR as the work continues in https://github.com/organicmaps/organicmaps/pull/9355

**Pull request closed without merging**
