### PR TITLE
Add China_Beijing, China_Tianjin; Modify China_Hebei

### PR DESCRIPTION
**Pull request by LaoshuBaby**
In issue #511 I think the region Hebei is too big and wrong contain 2 province, so this time I separate Beijing and Tianjin to 2 poly files.

### CODE REVIEW

**Comment by biodranik** [comment]
Thanks! Can you please sign the DCO? You can also squash all commits into one.

@vng it should work, right?

**Comment by vng** [comment]
Thanks for this PR! At this moment, country polygons are also implicitly embedded into cross-mwm road graph. We are planning to avoid this ASAP and your PR will help us with initial testing, but unfortunately we can't merge it right now.

**Comment by LaoshuBaby** [comment]
> 
> 
> Thanks for this PR! At this moment, country polygons are also implicitly embedded into cross-mwm road graph. We are planning to avoid this ASAP and your PR will help us with initial testing, but unfortunately we can't merge it right now.

So, what should I do to make this PR merged ?

DCO, and what others I can do?

**Comment by biodranik** [comment]
Please wait, we'll provide instructions on how to fix some polygons (or fix them ourselves). Also, new regions should be added to the regions list. And routing migration code should be fixed. No worries, we'll merge it!

**Comment by LaoshuBaby** [comment]
> 1. new regions should be added to the regions list

> 2. routing migration code

Thank you for your quick reply, If show me with document or instructions I can do this myself

**Pull request closed without merging**
