### PR TITLE
af localization

### PR DESCRIPTION
**Pull request by gjwentink**
I have added Afrikaans translations for the strings.

### CODE REVIEW

**Comment by biodranik** [comment]
Thanks! Did you use Windows text editor? Line endings should be converted to Linux/Unix ones.

**Review by biodranik — APPROVED** [review]
Thanks! I have fixed line endings and other mistakes and updated the PR. Please review if it is ok:
https://github.com/organicmaps/organicmaps/pull/5394/files?diff=unified&w=1

**Comment by gjwentink** [comment]
Hi @biodranik, I used BBedit on Mac. Please excuse if I did something wrong. I am very new to GitHub. Apparently (if I understand the messages correctly) there is at least one string that is appended with 'aaf' when it should be 'af'. Not sure how to correct that, but I'll give it a shot.

**Comment by biodranik** [comment]
@gjwentink thanks! I've fixed it. You can start working on other files (in another pull request) that are mentioned here: https://github.com/organicmaps/organicmaps/blob/master/docs/TRANSLATIONS.md

Please don't forget to save them with the correct Unix line endings.

**Review by biodranik — APPROVED** [review]

**Comment by biodranik** [comment]
Thank you for your contribution! We can enable af language when you finish translations in other files.

**Pull request merged**
