### PR TITLE
Add icons and adjust POIs visibilities

### LINKED ISSUE #5799: Show POI for power lines
Hi,

would it be possible to add an appropriate Poi symbol for power lines? At the moment only the poles are drawn if one is at maximum zoom. Maybe with bigger dots and lines in between? 
An example is this location:
49.821436, 12.201555
Which can also be found here: https://omaps.app/44Gjm2y3pb/Power_Tower

Thanks!

All the best,
Chris

### LINKED ISSUE #6697: Show golf course place pins on outdoor style
When trying the new outdoor map style, I noticed that golf courses in the US look like parks with incomplete information. After noticing several of these I went to edit the map on OSM and noticed they do, indeed, have labeled places associated with them, they're just not shown in the outdoor style. This is important, at least in the US, since when looking for parks and trails, it the map looks really incomplete and I have to cross-reference with Google Maps when looking for places to hike or explore.

See screenshot from Ohio with unlabeled golf course in the center:

IMG_2CF47E473705-1

Related to #5696 but I would argue that this is really only important for the new outdoor style. Though even on the regular map, there's no way to get directions to a golf course since you can't tap on a place that's not visible.

### LINKED ISSUE #6713: Icons improvements needed for the outdoors style
- [ ] the mountain_pass / saddle icon looks too heavy / big compared to mountain peaks
image

- [ ] need small versions of campsite-m, picnic-m, shelter-m, caravan_site-m, bcontrol-m and mountain-pass
- [ ] maybe a new "medium" icon for masts, flagpoles, etc. (now a "dot" is used, which is fine for low zooms, but at higher zooms would be good to have e.g. a dot surrounded by a small circle)
  - related to #5799

Those requests are mostly for the outdoors style, but some of them are needed for the generic one too (e.g. a lighter saddle icon).

### LINKED ISSUE #6953: Increase Toilets and Campsite visibility in outdoors style
> 1. I think that 'Campsite' should be shown more prominently as a lower zoom level, perhaps at the same zoom level as 'Viewpoint' 
> 2. And also, maybe 'Toilet' should be shown at the same zoom level as 'Drinking Water' as that's probably the same level of importance.

### PR DESCRIPTION
**Pull request by pastk**
Summary of changes:
  
  - new ford icon
  - smaller/lighter pass/saddle icons
  - small icon versions where needed
  
main style
  - natural-saddle visibility from z14- to z15- (less important than peaks and passes)
  - natural-rock from 15 to 16
  - barrier-border_control from 15 to 14
  - leisure-golf_course from 17 to 15
  - man_made-survey_point from 16 to 18
  - water sources from 15 to 16
  - amenity-ice_cream caption from 19 to 17
  
  outdoors
  - new power-tower icon
  - new man_made-mast/flagpole icons on z14-
  - natural-saddle from 11 to 13
  - natural-rock from 15 to 14
  - tourism-camp_site/caravan_site from 14 to 13
  - tourism-chalet from 15 to 14
  - barrier-border_control from 14 to 12
  - amenity-bbq from 18 to 16
  - amenity-toilets from 18 to 15
  - tourism-information-board/map/guidepost from 16 to 15
  - tourism-information-office/visitor_center from 15 to 13
  - highway-rest_area from 15 to 14
  - man_made-survey_point from z16 to z14
  
vehicle style
  - added amenity-toilets from 17
  - added shop-convenience from 17
  - barrier-border_control from 15 to 14
  - tourism-artwork from 15 to 18
  

Thanks @patepelo for help with the icons!

- closes #6697
- closes #5799
- closes #6713
- closes #6953
- some points from #6016

### CODE REVIEW

**Comment by pastk** [comment]
Tests are failing because of regenerate symbols commit absence.

**Comment by pastk** [comment]
Fords:
image

Power towers (outdoors only):
image

Mountain pass vs peaks:
image

**Review by vng — COMMENTED** [review]
- Keep some unique notation/agreement for svg dimensions? Looks like they are different (github renders small or large)
- Regenerate symbols?

**Comment by pastk** [comment]
> * Keep some unique notation/agreement for svg dimensions? Looks like they are different (github renders small or large). For example barrier-entrance-s and bcontrol-s.

I've noticed that github renders it different too. Probably depends on which tags exactly are used inside SVGs.

Re actual size - historically we have some standard sizes like 16x16 for small icons, but its mostly used for circled icons.
More free-form and smaller icons like dots, benches, peaks, entrances etc. have their unique sizes that fit the actual drawing exactly.
There are pros and cons to it, need to discuss it, perhaps when we'll refactor icons workflow.

> 
>     * Regenerate symbols?

Please see first sentence in the first post, I don't want to create unnecessary diff noise..

**Comment by pastk** [comment]
> * Keep some unique notation/agreement for svg dimensions? Looks like they are different (github renders small or large). For example barrier-entrance-s and bcontrol-s.

I've noticed that github renders it different too. Probably depends on which tags exactly are used inside SVGs.

Re actual size - historically we have some standard sizes like 16x16 for small icons, but its mostly used for circled icons.
More free-form and smaller icons like dots, benches, peaks, entrances etc. have their unique sizes that fit the actual drawing exactly.
There are pros and cons to it, need to discuss it, perhaps when we'll refactor icons workflow.

> 
>     * Regenerate symbols?

Please see first sentence in the first post, I don't want to create unnecessary diff noise..

**Comment by pastk** [comment]
> I've noticed that github renders it different too. Probably depends on which tags exactly are used inside SVGs.

It's because only `viewBox="0 0 16 16"` was present and there was no `width="16" height="16"`.
Now all icons are rendered small by GH. But looks like it doesn't matter for our icons pipeline (png skins rendering).

**Comment by vng** [comment]
AFAIR, we have tests that rely on existing symbols in skins.

**Comment by pastk** [comment]
> AFAIR, we have tests that rely on existing symbols in skins.

Yes https://github.com/organicmaps/organicmaps/pull/7056#issuecomment-1874389200

**Comment by dvdmrtnz** [comment]
Can the peak triangle icon be made bigger in outdoors style? I feel like they should stand out more

**Comment by dvdmrtnz** [comment]
> Can the peak triangle icon be made bigger in outdoors style? I feel like they should stand out more

Also maybe add text outline to the names. If the text is shown on top a trail it is unreadable. Compare the text visibility of peak and forest here:

**Comment by pastk** [comment]
> Can the peak triangle icon be made bigger in outdoors style? I feel like they should stand out more

Sometimes its too much already (z10)...
image

Overall peaks are much more visible and use bigger icons for longer compared to the main style already.

**Comment by pastk** [comment]
> Also maybe add text outline to the names. If the text is shown on top a trail it is unreadable.

Yes its a good idea. Probably outlines should be added and font sizes adjusted for other outdoor specific POIs as well and e.g. trail labels (e.g. I've added an outline to rivers/streams recently, looks really good now IMO). And place labels (villages, cities...) should be somewhat increased accordingly.
But I'd like to keep the scope of this PR limited.
Feel free to open a new one!

**Review by euf — CHANGES_REQUESTED** [review]
I'm afraid that further work needed for some icons. 

First of all, at least `ford-m.svg`, `mast-m.svg`, `power-tower-m.svg` are too small to be legible at `mdpi` (aka `@1`) screen resolution, especially if you remember the 0.75 downscaling. Even after merging #7118 the 5×5px and 8×8px images are too small for my taste. Ford icon even has an outline which is less than half-pixel width, it should also be fixed.

Secondly, are you sure we should go with this obscure cartographic signs? Fellow tourist may not see these symbols as meaningful icons. Are there any downsides for using more clear images? I've made some quick drafts based on Roentgen designs. Here are they rendered at mdpi compared to proposed icons. What do you think? 

Power tower: power_tower vs. power-tower-m
Flagpole: flagpole vs. mast-m
Mast: power_pole vs. mast-m

**Comment by pastk** [comment]
> First of all, at least `ford-m.svg`, `mast-m.svg`, `power-tower-m.svg` are too small to be legible at `mdpi` (aka `@1`) screen resolution, especially if you remember the 0.75 downscaling. Even after merging #7118 the 5×5px and 8×8px images are too small for my taste. Ford icon even has an outline which is less than half-pixel width, it should also be fixed.
> 

1. Actually this PR makes them bigger than before (all of them were dot.svg which is 5x5 including the outline).
2. These features are not supposed to be too distinct (they're more prominent in the outdoors style).
3. My screenshots in https://github.com/organicmaps/organicmaps/pull/7056#issuecomment-1874969944 are from mdpi screen.

> Secondly, are you sure we should go with this obscure cartographic signs? Fellow tourist may not see these symbols as meaningful icons. Are there any downsides for using more clear images? I've made some quick drafts based on Roentgen designs. Here are they rendered at mdpi compared to proposed icons. What do you think?
> 

I think its better to have an omnidirectional icon for the power tower as its usually connected with lines.

Your flagpole icon looks good, though I'm not sure if its too big size increase.. If someone wants to test?
Your suggested mast looks like a power pole, which it is not. Should be something simpler, probably. Also same size concern here..
For reference: flagpoles are visible from z15, masts from z16 in the main style; and z12/z13 in outdoors. This is very early compared to many other POIs because they could be orientation points, but still, they shouldn't be too promiment at those zooms compared to e.g. mountain peaks. That's the reason I've added the new mast icon to z14-  in outdoors only, lower zooms use a smaller "dot" icon still.

**Comment by vng** [comment]
Skin regeneration commit? Make sure that tests will be ok then.

**Review by vng — APPROVED** [review]

**Comment by vng** [comment]
@euf @dvdmrtnz Looks good?

**Comment by vng** [comment]
@euf Merging because new icons are definitely better than previous dots. Feel free to make new PR for power towers, flags, etc. Honestly, I don't think that we need large/detailed icons for these types.

**Comment by euf** [comment]
@vng Okay, I agree. Initially I was under impression that these icons are supposed to be easily readable, but now I see they are merely replacing dot icon on `z14-` and closer. 

I'd try to correct `ford` icon after #7118 is merged, when it will be appropriate to check many icons at once for their pixel grid alignment.

**Comment by patepelo** [comment]
> Power tower: power_tower vs. power-tower-m
> Flagpole: flagpole vs. mast-m
> Mast: power_pole vs. mast-m

@euf Your proposals are interesting. Maybe we could add a feature where icons change when you zoom max? Like revealing their representation as using your flagpole, mast, etc. when you zoom further. 
Just as a raw idea.

**Pull request merged**
