### PR TITLE
[strings] Improve Dutch (NL) translations

### PR DESCRIPTION
**Pull request by sndrtn**
This makes the Dutch translation more clear, more consistent and more action-focused.

I am a native Dutch speaker and checked the whole strings.txt file. Please review.

### CODE REVIEW

**Comment by sndrtn** [comment]
> Thanks a lot! Did you also check types_strings.txt file?

I did not, but just had a look. Checked up to line 4500 and so far looks good. Thanks for responding.

**Comment by jimcarst** [comment]
Thanks, clear improvements.

I'm not sure about the choice for action-focused verbs. In some places it looks good, in others a bit off (e.g. "Update"). In other apps I see both forms; some use the action-focused form, some use the infinitive. I do like the consistency. Why did you chose this form for verbs?

**Comment by sndrtn** [comment]
> I'm not sure about the choice for action-focused verbs. In some places it looks good, in others a bit off (e.g. "Update"). In other apps I see both forms; some use the action-focused form, some use the infinitive. I do like the consistency. Why did you chose this form for verbs?

For a couple of reasons:
1. In multi word labels you see the most important word (the action) first, so you can be faster. ("Download kaarten" vs "Kaarten downloaden")
2. Most labels describe an action (e.g. on a button) and not a state (e.g. in a progress screen)
3. This matches how Apple does it in iOS and their apps (not sure about Android)
4. As you mentioned, for consistency, the current version has a mix of the two. Although I do agree that in some cases the infinitive can be a better fit.

Does that help? Thanks for checking!

Also, if you have a way to preview a build with these translations I would be happy to test them.

**Comment by biodranik** [comment]
Thanks for the review! Translations can be checked in a beta which we publish later.

**Comment by jimcarst** [comment]
That's clear. Regarding 1, I don't think the action is always the most important word, for example: is "Schakel iCloud-synchronisatie in" really clearer than "iCloud-synchronisatie inschakelen"?

I checked on Android and both forms are used in various apps, with the infinitive being more frequent. I suspect that this is due to (lazy) translation from English, which would in first instance translate into the infinitive, even though it often looks unconcise and clumsy. So I checked the Picnic-app, which is Dutch-developed, and it uses a mix between the two forms.

So I propose we take another look and try to find the form that looks the most natural for each string, instead of striving for 100% consistency. It's an app after all, and not a list of git-commit messages where a naming rule is beneficial.

Nevertheless, in many strings the singular form is an improvement over the infinitive, so good work.

**Comment by biodranik** [comment]
I also think that the contextual improvement approach instead of 100% consistency will improve OM.

**Comment by sndrtn** [comment]
I agree. I think the beta would be useful, so we can judge the updated form in context. Or @jimcarst if you already have a list of suggestions for the infinitive form, I could review it or make a PR for it.

**Pull request merged**
