### PR TITLE
[android] Move the share button in the place page

### LINKED ISSUE #4545: Icons button in toolbar under bottomsheet are cutted
**Describe the issue**
With recently refactoring about place page fragment #4366 
In somes devices with little screen -> Icons in toolbar are cutted

It's better if icons is always display and text is little cutted following app language used

**System information:**
 - Operating system and its version: Android 8.0
 - Organic Maps version: [2023.02.18-4-Web-debug](https://github.com/organicmaps/organicmaps/actions/runs/4211758576)
 - Device Model: Honor 8

### LINKED ISSUE #4983: Moving the share button in the place page
To help fix https://github.com/organicmaps/organicmaps/issues/4545 and reduce the number of buttons under the place page, @biodranik suggested moving the share button inside of the place page.

Here are some first impressions, what do you think? I tried putting the direction arrow under the share button but it did not look good (too much empty space under the title on the left).

|-|-|
|-|-|
| Screenshot_1681548984 | Screenshot_1681549002 |

### PR DESCRIPTION
**Pull request by arnaudvergnet**
Fixes #4983
Fixes #4545

Needs #4808

Moves the share button inside the place page, next to a brand new close button. The PR also makes the bottom buttons background the same color as the place page. It is IMO prettier and more in line with the iOS version.

Screenshot_20230422-184959_Organic Maps (Debug)

### CODE REVIEW

**Comment by arnaudvergnet** [comment]
@Jean-BaptisteC would love your input on this! Is the tap area enough? Is it understandable that you can click on the buttons/direction arrow?

**Comment by Jean-BaptisteC** [comment]
Yes on Pixel 6, it's enough, i have planned to test on small device
Focus on location is broken during routing, is it caused by your new changes on map fragment improvement ?


Click on svg buttons is understandable but i think add background for arrow can help to know, that it's clickable (i have discover this feature very later)

**Comment by arnaudvergnet** [comment]
Thanks for the find! There was indeed an issue with the way we computed the available map viewport. Should be fixed now.

**Comment by biodranik** [comment]
When the device's orientation is unknown: 
image

**Comment by biodranik** [comment]
The blue arrow with the distance to a selected POI doesn't draw properly yet. It's similar to my previous screenshot. Only a part of the letter k and a small part of a number are displayed for some reason.

**Comment by arnaudvergnet** [comment]
@biodranik I can't reproduce your issue, how did you manage to get into that state? DO you have location enabled but direction not available? If so how do you do this?

**Comment by biodranik** [comment]
You can comment the compass callback to reproduce it. Some devices do not have magnetometer.

**Comment by arnaudvergnet** [comment]
Looks good on my end, can you retry the latest version?

Screenshot_1684308605

**Comment by arnaudvergnet** [comment]
@biodranik any news about the compass issue?

**Comment by biodranik** [comment]
@arnaudvergnet the issue is still reproduced on Android 8 (and is not reproduced on Android 9 and 5). Add this patch to reproduce (you may try to use an emulator):

```
diff --git a/android/src/app/organicmaps/location/SensorHelper.java b/android/src/app/organicmaps/location/SensorHelper.java
index ee3f2f17bb..9bc88062aa 100644
--- a/android/src/app/organicmaps/location/SensorHelper.java
+++ b/android/src/app/organicmaps/location/SensorHelper.java
@@ -63,7 +63,7 @@ class SensorHelper implements SensorEventListener
     SensorManager.getOrientation(mRotationMatrix, mRotationValues);
 
     // mRotationValues indexes: 0 - yaw (azimuth), 1 - pitch, 2 - roll.
-    LocationHelper.INSTANCE.notifyCompassUpdated(mRotationValues[0]);
+    //LocationHelper.INSTANCE.notifyCompassUpdated(mRotationValues[0]);
   }
 
   @Override
```

**Comment by biodranik** [comment]
It visually looks like the distance is cut by a rhombus (e.g. the distance text is under a "window" that is like a rhombus and only a part of the text is visible through this "window").

Another bit of information: it doesn't depend on the compass. On the same device with compass enabled it is still cut like this:

image

**Comment by biodranik** [comment]
Correction: just reproduced it on Android 5 too...

**Comment by biodranik** [comment]
Looks like the layout issue was introduced by CardView wrapper over LinearLayout. Why was it used?

**Comment by arnaudvergnet** [comment]
Rebased on master

> Looks like the layout issue was introduced by CardView wrapper over LinearLayout. Why was it used?

I used this to have a simple way to do rounded corners for the button because I could not find an easy way to do that with xml (without defining shapes and all that annoying stuff). But if it behaves differently between android versions then I'll just remove it and forget about rounded corner.

**Comment by arnaudvergnet** [comment]
Removed the rounded corners, can you please confirm it fixes your issue?

I also reverted the bottom buttons color to the grey background. I'll make a separate PR later to change it to white so we can have a better discussion on how to make users understand they can drag the place page to open it.

**Review by biodranik — APPROVED** [review]
LGTM

@vng @rtsisyk PTAL

This change is needed for https://github.com/organicmaps/organicmaps/issues/1452 which introduces one additional "add next stop" button when building a route.

**Review by biodranik — APPROVED** [review]
Let's see how it flies in the beta.

**Pull request merged**
