### PR TITLE
Request for an issue reporting template

### PR DESCRIPTION
**Pull request by Asteliks**
@biodranik based on https://github.com/organicmaps/organicmaps/issues/2459 I've made two templates for now and later on we can expand as needed

### CODE REVIEW

**Comment by biodranik** [comment]
Is it possible to preview it? Can you please activate these changes in your own repository for the demonstration?

**Comment by Asteliks** [comment]
@biodranik Yes, it is possible to preview it. I already have made these visible in my fork. Were you not able to see them?
Just in case you can preview the changes here: https://github.com/Asteliks/organicmaps/issues/new/choose
And the files are here: https://github.com/Asteliks/organicmaps/tree/patch-1/.github/ISSUE_TEMPLATE

**Comment by dbf256** [comment]
As a person, who submitted 14 bugs to OrganicMaps bugtracker I want to ask, do we really need this? These templates are quite large and complex. I usually submit issues in 1-2 sentences and there were no problems with it.
For example, I spend 1-2 mins to raise such issue: https://github.com/organicmaps/organicmaps/issues/1254 in 2 sentences. In new mode it will be required to tick 4 check boxes, 1 combo-box and populate 5 textboxes.

But it is a point of view of the person, who raises issues, if it is helpful for maintainers it is fine.

**Comment by Asteliks** [comment]
I would say that if the maintainer knows what your writing about then I guess it may by ok but on the other hand what these forms give us is:
- making sure we don't get duplicate tickets
- a new person willing to contribute may find it much easer to understand the issue (note that Organic Maps participates in the Google Summer of Code 2022 program)
- a check list for the person submitting the issue allowing them to make sure they don't miss something relevant
- and lets be honest look at the number of open issues we have. The question here is what do we want? Get more vaguely described that may loose their meaning to us over time OR get less issues but their quality will be much higher

**Comment by biodranik** [comment]
It should be simple for everyone: novices and experts.

The goal is to actually fix issues, not focusing on their numbers.

The simpler are templates the better is it for everyone. I'll check your demo later.

**Comment by biodranik** [comment]
Wow, it's too complex, and some fields are not relevant and not needed.
- No checkboxes, simple text is enough
- No code of conduct for issues
- bugs can be for desktop oses too
- no separate input for os version, just mention it as a text
- well, it's not a corporate bug tracker. Everything can be optional. Just write a text with what should be in an issue, don't force separate fields

**Comment by pastk** [comment]
Yeap I agree the proposed templates are way too complex.
Some minimal structure would be good to have, e.g. a reminder to mention is it android or ios or desktop affected.
Maybe it should be more like an optional guidance / reminders instead of mandatory separate fields..?

**Pull request closed without merging**
