### PR TITLE
[android] Migrated MwmJobIntentService.java to MwmWork

### PR DESCRIPTION
**Pull request by sum20156**
Removed all classes using jobintentservice as it is deprecated, workmanager is used in the place.

Android O and above devices, it is not guaranteed that the jobIntentService starts immediately, but start with the delay depending on the device's condition. But, some phone manufacturers are deliberately canceling the job for better battery life . So the job is never called.
Workmanager try to execute the job immediately if it is not possible immediately it schedule it for later, but it assures it will be executed.

Closes [#4531](https://github.com/organicmaps/organicmaps/issues/4531)

### CODE REVIEW

**Comment by biodranik** [comment]
Thanks!

1. Did you test it? Did you successfully upload some of your OSM edits in the background? You can check the existing edits status by typing `?edits` in the search field.
2. Please amend and sign the commit with the DCO, as it listed here: https://github.com/organicmaps/organicmaps/pull/4684/checks?check_run_id=11760103200

**Comment by sum20156** [comment]
Hi @biodranik , I have tested it, it is uploading, if you want i can screen record it and post it.
Regarding DCO, I think I have added my full name as author name thats why it is rejected, I have fixed it now.

**Comment by sum20156** [comment]
@biodranik closing this PR, facing lot of issues while changing commit messages. I have created new PR https://github.com/organicmaps/organicmaps/pull/4691 with DCO check passed.

**Comment by biodranik** [comment]
@sum20156 please DO NOT CLOSE PULL REQUESTS. Learn how to edit your commits with git rebase, and change your commits history in the same PR.

**Comment by sum20156** [comment]
sure @biodranik , will take care it in future.

**Pull request closed without merging**
