### PR TITLE
[cmake][opening_hours] Replace dependency on rsync

### PR DESCRIPTION
**Pull request by Ferenc-**
As suggested by @biodranik [in this comment](https://github.com/flathub/app.organicmaps.desktop/pull/8#discussion_r895190182)

Signed-off-by: Ferenc Géczi <ferenc.gm@gmail.com>

### CODE REVIEW

**Review by biodranik — COMMENTED** [review]
rsync was introduced to avoid unnecessary copying each time. Can you do the same using cp on all archs? Mac OS doesn't have `-u` switch.

**Comment by Ferenc-** [comment]
> rsync was introduced to avoid unnecessary copying each time. Can you do the same using cp on all archs? Mac OS doesn't have `-u` switch.

I assume you meant the `-a`.

So please check the new commit.
On Linux this should work with at least the following:
* [GNU coreutils](https://www.gnu.org/software/coreutils/manual/html_node/cp-invocation.html#cp-invocation)
* [uutils coreutils](https://github.com/uutils/coreutils/blob/main/src/uu/cp/src/cp.rs#L435)
* [busybox](https://linux.die.net/man/1/busybox)
* [toybox](https://github.com/landley/toybox/blob/master/toys/posix/cp.c#L31)

**Comment by biodranik** [comment]
No, -a still makes another copy, while -u and rsunc avoid it. But -u doesn't work on Mac...

**Comment by Ferenc-** [comment]
Then I misunderstood your comment [here](https://github.com/flathub/app.organicmaps.desktop/pull/8#discussion_r895190182) : "rsync -a can be replaced with cp -a".
Anyhow, there is a commit for that scenario as well, please take a look again.

**Review by biodranik — COMMENTED** [review]
I would avoid copy-paste and put only `set(COPY_CMD "cp -u")` under if. Although I'm not sure about word expansion in cmake, will it properly split cp and its argument?

**Comment by Ferenc-** [comment]
> I would avoid copy-paste and put only `set(COPY_CMD "cp -u")` under if. Although I'm not sure about word expansion in cmake, will it properly split cp and its argument?

The latest commit has worked out for me.

**Review by biodranik — APPROVED** [review]

**Pull request merged**
