### PR TITLE
[android] Removed unused resources

### PR DESCRIPTION
**Pull request by biodranik**
As API 21 is our minimum, there is no need to override it anymore

### CODE REVIEW

**Review by rtsisyk — APPROVED** [review]

**Comment by biodranik** [comment]
Два чека не сработали, но два аппрува получено :)

**Comment by rtsisyk** [comment]
Мы надеемся, что ты доведешь до конца.

**Comment by Jean-BaptisteC** [comment]
This PR have sense with this #3476 ?

**Comment by biodranik** [comment]
It makes sense, I have updated the PR. @arnaudvergnet can you please carefully review it?

**Comment by arnaudvergnet** [comment]
Why are the files ic_news, ic_question_mark and ic_report_a_bug listed in GitHub as empty files? This PR should not touch them.

Other than that and the review above, LGTM. Did not have time to test on device but if it compiles and runs it should be ok.

**Comment by rtsisyk** [comment]
Updated.

**Pull request merged**
