### PR TITLE
 Improve icons graphical consistency

### PR DESCRIPTION
**Pull request by dvdmrtnz**
This PR is trying to start the work on improving the consistency of the icons style (https://github.com/organicmaps/organicmaps/issues/3940). I have updated the color of some icons and changed some outline styles to filled. Also I changed the stationery icon; I think this one is more recognizable when the icons are small.

| Before | After |
|-|-|
|  |   |
|  |   |
|  |   |
|  |   |
|  |   |
|  |   |
|  |   |
|  |   |

### CODE REVIEW

**Review by biodranik — APPROVED** [review]

**Comment by dvdmrtnz** [comment]
Some more icon improvements:

| Before | After |
|-|-|
|  |   |
|  |   |
|  |   |
|  |   |
|  |   |
|  |   |

**Comment by biodranik** [comment]
Good! Can taxi icon be improved?

**Review by vng — APPROVED** [review]

**Comment by dvdmrtnz** [comment]
@biodranik I agree that the taxi icon can be improved. I just drew a new taxi icon. I think it looks good. What do you think?

**Comment by biodranik** [comment]
How it will look when it's reduced to 18x18 pixels? What about other [ideas](https://www.google.com/search?q=taxi+icon&client=firefox-b-d&sxsrf=ALiCzsaAxdA2AstLURZ51iXngzSkDwd8_A:1669794275023&source=lnms&tbm=isch&sa=X&ved=2ahUKEwj1-PC0tNX7AhWGDOwKHSOICeUQ_AUoAXoECAIQAw&biw=1453&bih=848&dpr=2)?

**Comment by dvdmrtnz** [comment]
Maybe there is too much detail for such a small icon. 

Here is a better alternative icon focusing on the symbolic "chess pattern" of taxis:

**Comment by biodranik** [comment]
This one is more recognizable! 👍

**Comment by mpawelski** [comment]
Is this "[checkered pattern](https://history.stackexchange.com/questions/4490/when-did-the-taxi-become-associated-with-the-checkered-pattern)" of taxis really that universally recognizable?

In my head I don't have any association between taxi and this pattern. Actually, current taxi icon in OM is one of least recognizable to me. I remember I had to click it couple of times to check that it is taxi icon before I _learned_ that this is the "taxi icon".

Also it might be just me but... I just showed my girlfriend the current taxi icon on OM and asked her to guess what it represents. Her guesses were: "some racetrack", "kart racing". When I told her it's taxi she exclaimed: "no way! who thought of that!"  🤣
I encourage you guys to do similar UX tests 😉 When you think about it actually makes sense that she associated this icon [with racing](https://www.google.com/search?q=racing+flag&sxsrf=ALiCzsbz7S8NJcoUyCqFhK5vY4WAlL9s7A:1670086057738&source=lnms&tbm=isch&sa=X&ved=2ahUKEwik2dyx8937AhWQ6CoKHVSCALoQ_AUoAXoECAEQAw&biw=1920&bih=927&dpr=1).

I really suggest trying to find a better icon. For example some car shape with long top sign, maybe even "TAXI" text (but I think we want to avoid texts in icons), something more than just this checkered pattern.

**Comment by biodranik** [comment]
Ok, let's combine the best from both approaches, and draw the bigger contour of that lamp with a pattern on the top of the taxi car.

**Comment by not-available-username** [comment]
I improved consistency for those icons

- historic-ship: removed background historic-ship-m
- military: added background military-m
- stadium: fixed opacity (the current one is not white) stadium-m
- viewpoint: added background viewpoint-m
- parking-disabled: added background parking-disabled-m

**Comment by not-available-username** [comment]
My two proposals for the taxi icon:

taxi_1-m
taxi_2-m

**Comment by mpawelski** [comment]
> * military: added background military-m
> 
> * viewpoint: added background viewpoint-m

Actually, I recently removed background from military and stadium (#4012) because I thought the map looks better without it and the current recommendation for when we should use the background is: ["circles are used only for businesses"](https://github.com/organicmaps/organicmaps/issues/4002#issue-1469718272).

But I just discovered this [wiki](https://github.com/organicmaps/organicmaps/wiki/Icons) and the parent issue (#3940) and indeed now military and sightseeing icons are inconsistent in "Tourism" and "Others" category. But I think we should try to remove backgrounds from other icons in these groups too.

On the other hand, some of the icons can be considered "business" too. For example laundry, layer, mail in Others group. Some touristic places can also be considered business (like cinema), other places like sightseeing spots are mostly free for anybody, without any business involved. So I'm not sure there always will be a clear line for the icon to be considered "business" and have background icon or not.
 

> * parking-disabled: added background parking-disabled-m

This is definitely an improvement in consistency with current icons.
Just for reference, there is an issue (#3863) and PR (#3896) where we consider removing background for parking icons.

> My two proposals for the taxi icon:
> 
> taxi_1-m taxi_2-m

For me it's better that just a checkered pattern, but I think the top taxi sign is not that visible. I like the one drawn before by @dvdmrtnz much more:


> @biodranik I agree that the taxi icon can be improved. I just drew a new taxi icon. I think it looks good. What do you think?
> 
>

**Comment by not-available-username** [comment]
> Actually, I recently removed background from military and stadium (#4012) because I thought the map looks better without it and the current recommendation for when we should use the background is: ["circles are used only for businesses"](https://github.com/organicmaps/organicmaps/issues/4002#issue-1469718272).
>
> But I just discovered this [wiki](https://github.com/organicmaps/organicmaps/wiki/Icons) and the parent issue (#3940) and indeed now military and sightseeing icons are inconsistent in "Tourism" and "Others" category. But I think we should try to remove backgrounds from other icons in these groups too.
>
> On the other hand, some of the icons can be considered "business" too. For example laundry, layer, mail in Others group. Some touristic places can also be considered business (like cinema), other places like sightseeing spots are mostly free for anybody, without any business involved. So I'm not sure there always will be a clear line for the icon to be considered "business" and have background icon or not.

I've modified the icons based on the ones in wiki you linked, unless there isn't a clear wiki with guidelines I can't sarch for recomendation in the issue threads. Just tell me how I have to modify them and I will do it 👍

 > This is definitely an improvement in consistency with current icons. Just for reference, there is an issue (#3863) and PR (#3896) where we consider removing background for parking icons.

Yep, it could help removing the background, but all the icons made by multiple shapes will be much less readable in my opinion. And there are many issues related to the drawing of POIs and zoom level, but I can't do nothing more than reporting it since I don't have the skills to code.

> For me it's better that just a checkered pattern, but I think the top taxi sign is not that visible. I like the one drawn before by @dvdmrtnz much more:

I can enlarge the taxi sign at the top if this icon is chosen. IMHO the https://github.com/organicmaps/organicmaps/pull/3979#issuecomment-1331028309 shuld not have the checker pattern since is very small and I prefer a frontal view, like trains, metro, ship...

**Comment by mpawelski** [comment]
> I've modified the icons based on the ones in wiki you linked, unless there isn't a clear wiki with guidelines I can't sarch for recomendation in the issue threads. 

I wanted to point out that I removed background from some icons [yesterday](https://github.com/organicmaps/organicmaps/pull/4012), and you brought it back. I just don't want you to waste time on something that might be not used.

The problem is that (to my knowledge) there is no clear guideline documented somewhere on wiki or in [docs](https://github.com/organicmaps/organicmaps/tree/master/docs) which describes which icons should have background and which not. The #3940 issue also didn't stated clearly for which icons from [wiki](https://github.com/organicmaps/organicmaps/wiki/Icons) we should remove (or add) circle background. The recommendation about removing background icons from non business icons is something I just noticed in couple of issues and PRs here on GitHub (last time in [this](https://github.com/organicmaps/organicmaps/issues/4002#issue-1469718272) issue)

> Just tell me how I have to modify them and I will do it 👍

I'm not a core team member. I just wanted to discuss about possible improvements to icons. The final say on which icon to choose and what are the guidelines for icons is probably for the core team members. Like @biodranik for example.

Maybe @biodranik you can take a look at icons in [wiki](https://github.com/organicmaps/organicmaps/wiki/Icons) and mark which ones you want circle background to be removed?

>Yep, it could help removing the background, but all the icons made by multiple shapes will be much less readable in my opinion. And there are many issues related to the drawing of POIs and zoom level, but I can't do nothing more than reporting it since I don't have the skills to code.

Thanks for contribution anyway! We also need non-code contributions like yours :)
I just wanted to point out there is some work on parking icons already, nothing more.

> > For me it's better that just a checkered pattern, but I think the top taxi sign is not that visible. I like the one drawn before by @dvdmrtnz much more:
> 
> I can enlarge the taxi sign at the top if this icon is chosen. IMHO the [#3979 (comment)](https://github.com/organicmaps/organicmaps/pull/3979#issuecomment-1331028309) shuld not have the checker pattern since is very small and I prefer a frontal view, like trains, metro, ship...

Sure, people have different style preferences. I guess the final say on this is on @biodranik anyway :)

**Comment by biodranik** [comment]
Wow, thank you both for the constructive dialog. The wiki page is very helpful!

The brown color is used in many countries for touristic/historical places, so it may make sense to leave it as is (and likely revert back the viewpoint icon) until we find some better idea.

All other icons should be made consistent too.

A business is usually a place where you expect some humans (or robots!) helping you to get some service or goods, likely under some cover or inside a building. If we keep touristic icons rounded, then they won't contradict it...

I agree that it's sometimes hard to distinguish between a business or not a business. But the main goal of icons is to be visually detectable by users. If they clearly understand what's there, then the problem is solved. If it is more or less consistent, it is a nice bonus.

What do you think? What are your ideas about a better visual grouping/changing background or colors? How do other maps apps do that? Who is the best/most readable in your opinion?

**Comment by not-available-username** [comment]
Thank you @mpawelski for your thoughts and clarifications, I agree with what you wrote!

@biodranik imho using circle to distinguish business and not isn't strictly needed since, as you wrote, you can identify them by the icon.
Altough some icons are not understandable, given the small size and the lack of an universal visual language that fits for every cuture or nation. 

Maybe circle can be used for everything that is not natural (peak, saddle, cave, waterfall...) infrastructure (mast, barrier, gate, lighthouse...) or street furniture (bench, table, guidepost, bin, fire hydrant...)

**Comment by dvdmrtnz** [comment]
I think the classification that @not-available-username is making is very similar to what @biodranik was going for. I think the general idea is:

Circles: shops, food & drinks, places of worship, museums, theaters, zoos, accomodations, offices and other businesses or similar places where you get some service or goods, likely under some cover or inside a building.

No circles: natural (peak, saddle, cave, waterfall...) infrastructure (mast, barrier, gate, lighthouse...) street furniture (bench, table, guidepost, bin, fire hydrant...), minor things (elevator, vending machine, gate...), sport pitches, tourism POIs that are not a building themselves (viewpoint, wayside cross, monument, plaques...), outdoors POIs (dog park, picnic site, playgrounds)

**Comment by endim8** [comment]
i never got around to it, but it'd be good to add all this to https://github.com/organicmaps/organicmaps/issues/2205 :)

**Pull request merged**
