### PR TITLE
[outdoors] Increase isolines density on z11 and z13

### PR DESCRIPTION
**Pull request by pastk**
Outdoors:
- increase isoline 100 visibility to z11
- increase isoline 50 visibility to z13

This change doesn't increase geometry size.

### CODE REVIEW

**Comment by pastk** [comment]
z11

z13

**Review by biodranik — APPROVED** [review]
Does it slow down the rendering on the device?

**Comment by pastk** [comment]
> Does it slow down the rendering on the device?

I doubt the difference is measurable.
Its more important to make the map more informative and higher isolines density helps with it. Otherwise a user will have to zoom in to see more detailed terrain and it'll have a much bigger performance/battery impact.

**Comment by pastk** [comment]
Related to #6157

**Review by vng — APPROVED** [review]

**Comment by vng** [comment]
We have some jitter with isolines (captions), but it should be solved in drape.

**Comment by pastk** [comment]
Also this change doesn't increase amount of captions, so it doesn't cause more jitter.

**Pull request merged**
