### PR TITLE
[drape] Do not break iOS position arrow behaviour.

### PR DESCRIPTION
**Pull request by vng**

### CODE REVIEW

**Review by biodranik — APPROVED** [review]
This is a hotfix/temporary workaround. @rtsisyk @arnaudvergnet can we do it better?

To remind you, before the blue arrow position and the height of the bottom bar in the nav mode were hard-coded. It worked until we decided to increase the font size in the bottom bar.
That previous hotfix broke it on iOS and didn't solve the problem if users change font settings on their devices to a large one.

Now thinking about the best solution, I have this idea: do not draw the bottom bar _over_ the map, but draw it _under_ the map. E.g., instead of this:

```
=========
|       |
|       |
|  map  |
|       |
|       |
|       |
|       |
|-------|
|bar    |
|-------|
=========
```
draw this:
```
=========
|       |
|       |
|  map  |
|       |
|       |
|       |
=========
---------
|bar    |
---------
```

It will not only resolve the offset issue (now it can be safely hard-coded again), but also increases the rendering speed, and saves more battery.

For the landscape, another approach should be used with a custom layout. I see two possible options:

1. As we discussed previously, something similar to the CarPlay approach, where the top and bottom bars are on the left, while the whole right half of the screen is used for the map, and the blue arrow is centered there.
  PROS: important vertical space is not occupied by bars.
  CONS: less map is visible on the right side from the current position.
2. Bottom bar can be removed, and its info/buttons can be drawn on the left and right corners. PROS: current position is centered. CONS: less vertical space, ineffective use of the top bar (very long street names are very rare).

**Comment by arnaudvergnet** [comment]
Isn't changing the map viewport size a heavy task? I fear it would slow down the switch to/from navigation on older devices.

**Comment by vng** [comment]
Well, no need to resize actual map view, it can be slow, yes. Just give me correct bottom bar sizes (or bar's upper edge pixel coordinates) and I will do the rest work. Now we have _hardcoded_ pixel bar sizes. And it works bad if we change system font's height.

**Comment by biodranik** [comment]
Why it can be slow? The whole activity is relaunched when you start navigation (and return back to the main map). Initializing the map layout with a bit smaller rectangle should not be an issue at all. Or am I missing something?

**Comment by vng** [comment]
The difference in OGL (Vulkan) surface recreation when Bar and Map view in mutual resize policy.

**Comment by biodranik** [comment]
Isn't it done anyway when Nav mode is started? We enable perspective, and do some other changes too. There is no really important reason to render the map on the _always_ invisible area under the top and bottom bars.

**Comment by vng** [comment]
I think it shouldn't. At least we have _visible rect_ attribute in drape (besides pixel rect), introduced when folks made CarPlay (I suppose?).

**Comment by biodranik** [comment]
There is a related bug in CarPlay: #804 The map is rendered _under_ the left bar, and everything on the map is centered incorrectly because of that.

**Comment by vng** [comment]
Yes, not all controls are properly tuned with _visible_ rect or its not properly set, but anyway.
Also, bottom bar is floating if I'm not mistaken, at least in iOS, so _visible_ rect is a good concept here, IMO.

**Comment by biodranik** [comment]
Do we really need these bottom bars _floating_? What are the benefits? Now I see that the bottom part is always covered by the bar in navigation mode.

**Comment by biodranik** [comment]
What are the real blockers to changing the map view size? Is the same surface reused without recreation/resizing in both landscape/portrait modes? Is it or to use a bit different map view sizes for landscape/portrait? Will it cause significant visible delays when users rotate the device? What are other issues?

Let's summarize here all the important points, and create a separate issue for the proper navigation layout.

**Pull request merged**
