### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by kaoneko**
The referenced star icon is now a bookmark icon.

### CODE REVIEW

**Comment by kaoneko** [comment]
I hope I'm doing this right, I've never done anything like this before...

**Comment by biodranik** [comment]
Almost :)
Please find and edit the text in data/strings/strings.txt
Commit your changes and sign the commit
Then run ./tools/unix/generate_localizations.sh
Commit your changes and sign the commit

Push the changes and make a pull request.

OR we may help if you're not familiar with git :)

**Comment by kaoneko** [comment]
Thanks, I think I figured most of it out!

Running ./tools/unix/generate_localizations.sh fails with
`./tools/unix/generate_localizations.sh: line 25: ./tools/unix/../../tools/twine/twine: No such file or directory`

The twine directory is actually empty, no executable named twine there... I'll look into it next time I have some time, and maybe you can give me a hint :)

**Comment by biodranik** [comment]
You forgot to check out submodules:
git submodule update --init --recursive

**Comment by kaoneko** [comment]
Alright, I give up! I checked out the submodules, then I had to install Ruby, then Ruby threw a LoadError... Actually it was my intention to save you guys some time by fixing the string myself instead of filing a bug report. It was not my intention to get a full development environment up and running 😅 I have no prior experience with git or Ruby, just thought I could change a word right here on GitHub but it turned out to be a little more complex than that.

But hey, I was pleasantly surprised to find out you're one of the founders of MAPS.ME! I had been wondering who the people behind this fork are. I think it's a good thing Organic Maps exist as an open source and privacy friendly alternative to the new MAPS.ME. Thanks!

I guess I'll stick to contributing to OpenStreetMap and filing bug reports only for now then 😄

Should I file a bug report or can you take it from here?

**Comment by vng** [comment]
Hm, but to add bookmarks is a star icon (on the bottom menu), no?

**Comment by kaoneko** [comment]
I think it might have been in MAPS.ME, but in Organic Maps it's a bookmark with either a + (add bookmark) or an x (remove bookmark), see https://organicmaps.app/docs/screenshots/2.jpg

Not to be confused with the Bookmarks menu which is actually represented with a star icon on the bottom menu when no place is selected.

**Comment by biodranik** [comment]
Thanks for the try! We need to update and patch the Twine tool to avoid these nasty errors.
@rtsisyk Btw, I think the iOS icon is better for bookmarks than the Android one. Maybe we should use it in Android too?

**Comment by biodranik** [comment]
The proper fix for this issue will be to replace the icon back :) Thanks for raising this issue!
See #695

**Pull request closed without merging**
