### PR TITLE
[android] Show the user a prompt to keep the app's data on uninstall

### LINKED ISSUE #1075: [android] Allow user to keep application data on removal
Android 10+ prompt to keep app data on removal. Organic Maps should enable this feature.

https://developer.android.com/reference/android/R.attr#hasFragileUserData

### PR DESCRIPTION
**Pull request by rtsisyk**
Closes #1075

###

### CODE REVIEW

**Comment by pastk** [comment]
What will happen to this data if the user won't reinstall the app? Will he be able to delete it somehow?

**Comment by rtsisyk** [comment]
@pastk, the app is not fully removed from Application Manager:
Screenshot_20220207-112005_Settings

**Comment by rtsisyk** [comment]
I tested this feature thoroughly. It looks like that this option is not compatible with automatic backups. Yes, Android preserves all app files both in `/data/data/app.organicmaps` and `/sdcard/Android/data/app.organicmaps` on uninstall. However, on the next install "AutoBackup" feature overwrites content of both folders and removes all saved data. 🤦 Disabling `android:allowBackup` fixes `android:hasFragileUserData`. I don't think that we want to enable this feature in favor of removal of automatic backups...

**Comment by pastk** [comment]
Also its not clear what use cases this feature will solve...
Temporary uninstall the app to reinstall it shortly after? To downgrade perhaps?
Looks like it won't be possible to e.g. uninstall Google version to later re-install an F-Droid one https://gist.github.com/agnostic-apollo/58def38fdb1c90563454974108ae52df
And given that OM has a lot of BIG files then the danger of users cluttering their devices is quite real...

**Comment by rtsisyk** [comment]
OK, this feature is broken. I am closing this PR and related ticket.

**Pull request closed without merging**
