### PR TITLE
[android] Fixed GPS location overrided by the networking provider

### LINKED ISSUE #6270: Speedometer flickering due to trying all GPS providers
**Describe the issue**
Commit 1ad8df19651dd41e21a46377f1ac5d676df69f9d introduced a regression in which (only on FDroid builds, Google unaffected) speedometer in navigation mode flickers. Up: Google Play version, down: FDroid version

**Steps to reproduce**
1. Run navigation mode
2. Speed will subtly flicker, especially so at sub 10 km/h.

**Expected behavior**
As of before said commit, speed is stable.

https://github.com/organicmaps/organicmaps/assets/1409116/863702ed-92c1-4b14-b889-430212af3016

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**System information:**
 - Operating system and its version: Android 13
 - Organic Maps version: [you can find it by tapping the button with the green OrganicMaps logo, bottom left of the main screen on Android, or the `?` button on iOS]
 - Device Model: [Samsung Galaxy S23

**Additional context**
This commit also breaks mock location aka fake GPS on real devices. It will jump back and forth between real and mocked location.

### PR DESCRIPTION
**Pull request by biodranik**
May fix #6270

### CODE REVIEW

**Comment by vng** [comment]
IDK, how to check the quality of this heuristic over the previous one?

**Comment by pm4rcin** [comment]
@biodranik I have tried it but it's still the same. Anyone knows how OSMAnd handles it? It might be worth to check and compare to OM implementation.

**Comment by pm4rcin** [comment]
Any chance of fixing it? It makes the app completely unusable for navigation in any profile since a few months.

**Comment by Jean-BaptisteC** [comment]
Can you rebase your branch?

**Comment by biodranik** [comment]
@Jean-BaptisteC do you reproduce the issue to test if it was fixed?

**Comment by Jean-BaptisteC** [comment]
Not, I'm not able to reproduce. But I can check this fix doesn't broke another thing :)

**Review by Jean-BaptisteC — APPROVED** [review]
See no difference on my Pixel 6 with Google Play Services location and with only GPS

**Comment by penn5** [comment]
I've tested the FDroidBeta CI build from this PR and it doesn't appear to help.

https://github.com/user-attachments/assets/9b899290-594d-434a-857f-77efa494fb5f

Tested on Fairphone 5, Android 14, no GSF/GMS.

**Comment by penn5** [comment]
Logs from CI build:
[logs patch.zip](https://github.com/user-attachments/files/16739778/logs.patch.zip)

**Comment by biodranik** [comment]
The proper solution is to stop using the network provider when the GPS provider sends valid locations. It will also save more battery. 

@rtsisyk had ideas on how to implement it properly.

**Pull request closed without merging**
