### PR TITLE
[cmake] Fix failing tests on the latest Mac OS X / clang

### PR DESCRIPTION
**Pull request by biodranik**

### CODE REVIEW

**Review by vng — COMMENTED** [review]
I don't like different compiler options for different _projects_
Especially when we have static linkage and our _projects_ division is "so-so" :)

**Comment by biodranik** [comment]
What are the risks of having custom flags in geometry project for Mac OS builds? It is a temporary solution to make the master green.

These fixes show that the issue is caused by associativity operations, and by rounding issues with intermediate results. It should be feasible to dig deeper into failing tests and fix them later. And at least understand the scope of the problem, whether is it test-only issue, generator issue, or client issue.

Another possibly better workaround could be in finding the function of failing code, and disabling optimization only there with pragmas.

I don't think that pessimizing all math calculations speed without confirmed facts is a good idea.

**Comment by strump** [comment]
@vng as far as I understand, tests were green previously (before llvm update?) Failing tests mean that behaviour changed (maybe new bugs appeared). To have old behaviour we need green tests back.

**Comment by vng** [comment]
I understand that. My point is to disable failing tests ```#ifdef DEBUG <failing tests> #endif```
But not to set different compiler options for different projects.

**Comment by biodranik** [comment]
@vng PTAL

**Review by vng — COMMENTED** [review]
- I'd prefer to keep it in DEBUG
- how ```__apple_build_version__``` define works say on Linux?
- I see no reason to undef each sentence, just enable/disable the whole test, less code bloat
- Also check search_integration_test

**Comment by biodranik** [comment]
> * I'd prefer to keep it in DEBUG

Good point. Fixed.

> * how `__apple_build_version__` define works say on Linux?

It's true when its not defined. Meaning: the ifdefed line is executed on Linux, exactly what we want. Added a comment.

> * I see no reason to undef each sentence, just enable/disable the whole test, less code bloat

1. It is important to still run other tests.
2. Ifdefing specific lines greatly helps anyone who decides to investigate and fix these TODOs later. It hints about the root cause of the issue. I don't see any harm to ifdef specific tests with clear comments.

> * Also check search_integration_test

Do you think that it's also related to the enabled clang optimization? Let's debug it separately.

**Pull request merged**
