### PR TITLE
Add a z20 scale

### LINKED ISSUE #4156: Allow zooming even further on the map
At the moment it is not easy to see all icons or add a new place precisely when there are many icons on the map. Allowing zooming further may help in some cases.

A better option for showing hidden icons is their grouping (discussed in #1109)

### PR DESCRIPTION
**Pull request by pastk**
Closes #4156 

Changing the consts and kothic's max scale and re-generating styles seems to work :)
(depends on https://github.com/organicmaps/kothic/pull/25)

Need to fix some styles that were declared as `z19` max instead of `z19-`.

And test in various modes (vehicle style!) on misc devices (I tried on desktop only so far).

image

### CODE REVIEW

**Comment by RedAuburn** [comment]
When navigating from search results or back to your current location, the map zooms to z20, which might be too close. Staying at z19 might be better

**Comment by biodranik** [comment]
Let's document anyway all related issues and steps to reproduce them.

**Comment by pastk** [comment]
Fixed the ruler not showing scales less than 10m. Thanks to @RedAuburn for the hint!

**Comment by pastk** [comment]
It would be great if someone could test on iPhone too..

And did anyone tried it in the navigation perspective mode?

**Review by vng — COMMENTED** [review]
Did you check last geometry simplification epsilon (calculated from zoom) in generator?

**Comment by pastk** [comment]
It would be great if someone could test on iPhone too..

And did anyone tried it in the navigation perspective mode?

> Did you check last geometry simplification epsilon (calculated from zoom) in generator?

It shouldn't be affected as geom3 is generated for GetUpperScale() which is 17 always.
Each MWM header contains a list of zoom ranges also, but it ends at z17 too.

But I'll generate a test map for sure, thanks for reminding!

**Comment by pastk** [comment]
I've generated a small map, didn't notice any issues.

I think this change is good to go through a beta.

**Comment by vng** [comment]
Not this PR, but probably we should review:
- simplification epsilon. 18, 19, 20 scales were introduced after we fixed 17 as the last zoom level for geometry.
- tiling zooms (I suspect now it is stopped at 17).

**Review by vng — APPROVED** [review]

**Comment by pastk** [comment]
Rebased. Merge? @vng

**Pull request merged**
