### PR TITLE
Tune down prominence of highway-footway-bicycle

### PR DESCRIPTION
**Pull request by pastk**
Following https://github.com/organicmaps/organicmaps/pull/7925

Apparently treating `highway=footway bicycle=yes` as a shared path produces random short "cycling" stretches in some countries, which doesn't look good or make sense:
image

In case we'd want to release a beta based on #8009 we can tune them down like this:
image

I.e. don't merge this PR but include into the beta.

### CODE REVIEW

**Comment by map-per** [comment]
I wouldn't change shared foot- and cycleways, they are not too prominent. The dedicated and segregated cycleways are the ones that are too prominent at lower zoom levels at the moment.

**Comment by biodranik** [comment]
Please don't pollute the main style with unnecessary information.

telegram-cloud-photo-size-2-5292075556592016768-y
telegram-cloud-photo-size-2-5292075556592016767-y
telegram-cloud-photo-size-2-5292075556592016766-y
telegram-cloud-photo-size-2-5292075556592016765-y

**Comment by pastk** [comment]
> Please don't pollute the main style with unnecessary information.
> 
> telegram-cloud-photo-size-2-5292075556592016766-y 

It'd be more helpful if you'd post before/after screenshots and tell more specifically what you see as unnecessary information.
E.g. the same place in the current release (mdpi screen):
image

Many "new" shared ways in the bottom around the park are e.g. `footway bicycle=yes` and they should be removed indeed as we discussed already.
Otherwise there are some e.g. `bicycle=designated foot=designated highway=path segregated=yes/no` that were brown dashed and now are converted into a white dash with a cycle line which is right, no?
`

**Comment by pastk** [comment]
or the same on a vs=3 device

**Comment by biodranik** [comment]
Your screenshots are cleaner, there are no blue solid and dashed lines.

**Comment by pastk** [comment]
Closed in favor of https://github.com/organicmaps/organicmaps/pull/8045

**Pull request closed without merging**
