### PR TITLE
[drape] Fixed inertial kinetic scroll.

### PR DESCRIPTION
**Pull request by vng**
Closes https://github.com/organicmaps/organicmaps/issues/2652

Please, test on your Android devices.

### CODE REVIEW

**Comment by biodranik** [comment]
Cool! Let's call our guru @Jean-BaptisteC to help!

**Review by biodranik — APPROVED** [review]

**Comment by biodranik** [comment]
On Android the animation is not as smooth as on iOS.

**Comment by vng** [comment]
Thos PR fixes situation when inertial scroll os not started. That was often in Android. Smooth or "jerky" depends on device speed, right? Or what do you mean?

**Comment by RicoElectrico** [comment]
Kinetic scroll is much improved on:
Galaxy S23 (Android 13)
Xperia E5 (Android 6)

Really makes a lot of difference, thanks Viktor :sparkles:

**Comment by biodranik** [comment]
> Or what do you mean?

Quickly drag and remove the finger on iOS and on Android. On Android it's not smooth. Although it's better than before, we can improve it later separately (just create an issue for it or update the existing one).

**Pull request merged**
