### PR TITLE
[styles] Water icon visibility fixes

### LINKED ISSUE #2683: Water icons hard to see
Issue created for https://github.com/organicmaps/organicmaps/pull/2203#issuecomment-1147356877

potential issues:
- waterfalls
- fountains
- drinking water points

### PR DESCRIPTION
**Pull request by endim8**
Checked `waterfall`, `fountain` & `drinking_water` icons for visibility on different surfaces and in dark mode. In the end just scaling them a bit and tweaking the levels was enough to fix the visibility issues.

waterfall
fountain
(benches recently added with OM editor so not in debug map)
drinking

fixes #2683 & #2645

### CODE REVIEW

**Comment by vng** [comment]
Screenshots to understand how big water icons now on z18-?

**Review by vng — APPROVED** [review]
Waterfall, fountain are ok.
What do colleagues think about big water drop?

**Comment by pastk** [comment]
> Waterfall, fountain are ok. What do colleagues think about big water drop?

Maybe make it bigger on z19 only just like fountains?

A big water icon will be great for a hiking style, but e.g. for an urban traveller its of much lower importance.

**Comment by endim8** [comment]
> Maybe make it bigger on z19 only just like fountains?

Agreed, at z19 it looks better. i'll fix it when i get back  👍

**Comment by endim8** [comment]
changed the bigger water drop to z19 👍

**Review by pastk — APPROVED** [review]

**Pull request merged**
