### PR TITLE
WIP: [styles] Add more visible cycleway and bicycle=yes outdoor styling

### PR DESCRIPTION
**Pull request by zyphlar**
A major feature of outdoor activity involves cycleways and bike paths; this is a first draft at improving visibility of those on the outdoor map.

One thing I need to improve is visibility of bike lanes on orange-colored streets, and style conflicts with dashed footpaths (they become 0.3 opacity cycleways unlike the nice dashed overlay on streets)

### CODE REVIEW

**Comment by pastk** [comment]
Its supposed to fix
- https://github.com/organicmaps/organicmaps/issues/5289

**Comment by zyphlar** [comment]
@pastk no specific issue fix intended, just generally necessary to improve bicycle route visibility at some point somehow and it seemed like an easy way to start that process. I'd like to figure out how to include regional route relations in the rendering and maybe use `cycleway=lane` etc instead of `hwtag=yesbicycle`

**Comment by vng** [comment]
Yes, want screenshots here :)

**Comment by pastk** [comment]
> I'd like to figure out how to include regional route relations in the rendering and maybe use `cycleway=lane` etc instead of `hwtag=yesbicycle`

re routes support please check general thoughts here first
- https://github.com/organicmaps/organicmaps/issues/2185#issuecomment-1614907113

And here is some sample code (needs a cleanup and rebase) for hiking routes:
- https://github.com/organicmaps/organicmaps/pull/6790

**Comment by zyphlar** [comment]
@vng @pastk sorry for the delay, here were screenshots from chat

cycling3
cycling2
cycling1

**Pull request closed without merging**
