### PR TITLE
[ios] replace circle checkbox image (radioBtnOff/On) with rounded rect

### PR DESCRIPTION
**Pull request by kirylkaveryn**
Closes https://github.com/organicmaps/organicmaps/issues/8389

@euf thanks a lot for the new icon!
~~Nit: the image you provide looks great but has a little bit thicker insets and because of that it looks smaller in comparison with the old circle. - _fixed_~~

Before/After:
image image

### CODE REVIEW

**Comment by euf** [comment]
Hmmm, I'll update the icons then. Actually I was hoping they'll be visually the same size due to squares looking "heavier" than circles. Turns out the round shapes had virtually no insets

**Review by biodranik — COMMENTED** [review]
Agree, a bit bigger checkboxes would look better.

**Comment by euf** [comment]
Could you please try these SVGs instead?

check-empty
check-fill

**Comment by kirylkaveryn** [comment]
> Could you please try these SVGs instead?
> 
> check-empty check-fill

Thanks! I've updated the PR description screenshots.
@biodranik can you please take a look?

**Review by biodranik — APPROVED** [review]
Thanks, LGTM!

**Pull request merged**
