### PR TITLE
[strings] Greek Translations

### PR DESCRIPTION
**Pull request by billpcs**
I have just fixed many of the Greek translations that needed rewording (they were probably automatically generated) and also added some that were missing.

### CODE REVIEW

**Comment by meenbeese** [comment]
@biodranik Ready to merge. I can't regenerate strings due to a script error.

**Review by biodranik — APPROVED** [review]
Wow, thanks for your contribution, that's a lot of work!

**Comment by biodranik** [comment]
@billpcs validator [complains](https://github.com/organicmaps/organicmaps/actions/runs/8544998243/job/23413859075?pr=7800#step:4:108) about strings order (and for some whitespace symbols?), can you please fix it?

выява

**Comment by billpcs** [comment]
> Wow, thanks for your contribution, that's a lot of work!

I was two evenings of work. The least I could do for such an amazing app. Thank you!

**Pull request merged**
