### PR TITLE
[drape] Render semi-transparent areas after opaque areas and lines 

### PR DESCRIPTION
**Pull request by pastk**
Fixes a case with lines not rendered under a semi-transparent bridge.
- https://github.com/organicmaps/organicmaps/issues/5339#issuecomment-1691866730

transparent-areas

However it causes artifacts at line joins
image

Basically its the same situation as before.
Before: under bridge lines' pixels were not rendered because (semi-transparent) bridge pixels were rendered already and they have higher z-value.
After: bridge's pixels are not rendered because (fully transparent) above bridge line joins triangles were rendered already and they have higher z-value.

Hence above-the-bridge lines should be rendered after bridge area :)

### CODE REVIEW

**Comment by pastk** [comment]
Also making 2D buildings semi-transparent leads to a bug similar to https://github.com/organicmaps/organicmaps/issues/5339#issue-1757346054

image

Here it seems to be 3(!) different shades even.
And compared to https://github.com/organicmaps/organicmaps/issues/5339#issue-1757346054 here there is no explicit background area..

**Comment by pastk** [comment]
I think I found a good solution ☺️ (unless some new artifacts/bugs are found)

- render line joins/caps (but not line themselves) always after transparent areas

It solves the "holes in the bridge" issue seen on a screenshot above.

A minor disadvantage is it makes line joins/caps invisible if they happen to be under a transparent area e.g. a bridge.
But this is a rare case (have to find curved thick lines under the bridge) and a small sacrifice in visual quality (usually barely noticeable) is fine.

If you have a good eye you can see small "cracks" in the angles of the curved orange under-bridge line:

image

@biodranik @vng please take a look, I think it'd be good to include it in beta for a more thorough testing.

**Comment by pastk** [comment]
A semi-transparent bridge without "line joins holes"

image

**Comment by biodranik** [comment]
The different color for the bridge area over the water doesn't look good on the last screenshot. Is there any way to make it the same color as the background color while keeping it transparent/see what's underneath? And maybe ideas on how to highlight the bridge in this situation? E.g. draw some distinct border on its edge? Or doesn't draw the bridge at all, only draw roads and paths (because who cares? Google and Apple don't bother, Apple even doesn't draw footpaths).

**Comment by pastk** [comment]
> The different color for the bridge area over the water doesn't look good on the last screenshot. Is there any way to make it the same color as the background color while keeping it transparent/see what's underneath? 

Find such a color which will produce a background color when blended with water color? 🤪

> And maybe ideas on how to highlight the bridge in this situation? E.g. draw some distinct border on its edge? Or doesn't draw the bridge at all, only draw roads and paths (because who cares? Google and Apple don't bother, Apple even doesn't draw footpaths).

Please create a separate issue for that, this PR doesn't change it, water is seen through the bridges in master.

**Comment by pastk** [comment]
it can't build harfbuzz lib, it doesn't seem related to the PR

**Comment by biodranik** [comment]
This is the real iOS build error:
```
/Users/runner/work/organicmaps/organicmaps/shaders/metal_program_pool.mm:104:1: error: no matching constructor for initialization of 'gpu::metal::(anonymous namespace)::ProgramInfo'
}};
^
/Users/runner/work/organicmaps/organicmaps/shaders/metal_program_pool.mm:18:8: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 0 were provided
struct ProgramInfo
       ^
/Users/runner/work/organicmaps/organicmaps/shaders/metal_program_pool.mm:18:8: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 0 were provided
/Users/runner/work/organicmaps/organicmaps/shaders/metal_program_pool.mm:27:3: note: candidate constructor not viable: requires 3 arguments, but 0 were provided
  ProgramInfo(std::string && vertexShaderName, std::string && fragmentShaderName,
  ^
/Users/runner/work/organicmaps/organicmaps/shaders/metal_program_pool.mm:104:1: note: in implicit initialization of array element 54 with omitted initializer
}};
^
1 error generated.
```

The likely culprit is this commit which added two new shaders: https://github.com/organicmaps/organicmaps/commit/49b943bd066f1536eb75d394a2a2b47922f4d1ea

@AndrewShkrob can you please take a look?

**Comment by AndrewShkrob** [comment]
> This is the real iOS build error:
> 
> ```
> 
> /Users/runner/work/organicmaps/organicmaps/shaders/metal_program_pool.mm:104:1: error: no matching constructor for initialization of 'gpu::metal::(anonymous namespace)::ProgramInfo'
> 
> }};
> 
> ^
> 
> /Users/runner/work/organicmaps/organicmaps/shaders/metal_program_pool.mm:18:8: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 0 were provided
> 
> struct ProgramInfo
> 
>        ^
> 
> /Users/runner/work/organicmaps/organicmaps/shaders/metal_program_pool.mm:18:8: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 0 were provided
> 
> /Users/runner/work/organicmaps/organicmaps/shaders/metal_program_pool.mm:27:3: note: candidate constructor not viable: requires 3 arguments, but 0 were provided
> 
>   ProgramInfo(std::string && vertexShaderName, std::string && fragmentShaderName,
> 
>   ^
> 
> /Users/runner/work/organicmaps/organicmaps/shaders/metal_program_pool.mm:104:1: note: in implicit initialization of array element 54 with omitted initializer
> 
> }};
> 
> ^
> 
> 1 error generated.
> 
> ```
> 
> 
> 
> The likely culprit is this commit which added two new shaders: https://github.com/organicmaps/organicmaps/commit/49b943bd066f1536eb75d394a2a2b47922f4d1ea
> 
> 
> 
> @AndrewShkrob can you please take a look?

My commit has nothing to do with this build error.

**Comment by biodranik** [comment]
Thanks, Andrew. @pastk you forgot to add a new shader and reorder another shader in metal_program_pool.mm

**Comment by pastk** [comment]
@biodranik fixed, thanks!

Could you please test if it works as intended on iOS, please?

**Comment by biodranik** [comment]
@kirylkaveryn maybe you can help with a smoke-test?

**Comment by pastk** [comment]
> @pastk you forgot to add a new shader and reorder another shader in metal_program_pool.mm

I've addded a comment into the programs list

**Comment by biodranik** [comment]
Metal shader validator aborts on iOS:
```
-[MTLDebugRenderCommandEncoder validateCommonDrawErrors:instanceCount:baseInstance:maxVertexID:]:5708: failed assertion `Draw Errors Validation
missing vertexDescriptor buffer binding at index 1.
'
```
Here:
```
    [encoder drawPrimitives:GetPrimitiveType(m_mesh->m_drawPrimitive) vertexStart:0
                vertexCount:verticesCount];

```

**Comment by pastk** [comment]
> Metal shader validator aborts on iOS:

Does it happen on this PR only?

Its strange as I didn't change the shaders but just reused/moved them. Maybe some other files need to be changed for metal? @vng

**Comment by biodranik** [comment]
@pastk looks like the issue comes from the master branch, when API validation checkmark is enabled. It would be great to bisect when it was introduced...

выява

**Comment by kirylkaveryn** [comment]
> @kirylkaveryn maybe you can help with a smoke-test?

I haven't had any crashes or any triggered asserts. Tested on simulator and device.

**Comment by pastk** [comment]
It went through the beta well. Merge?
@biodranik @vng

**Pull request merged**
