### PR TITLE
Improve icons graphical consistency + artwork icons

### PR DESCRIPTION
**Pull request by dvdmrtnz**
* From https://github.com/organicmaps/organicmaps/issues/3940:

* Change amenity=hunting_stand icon

* Change amenity=sanitary_dumping_station icon

* Change aeroway=heliport, aeroway=helipad icon

* Remove circle from man_made=windmill icon

* Remove circle from man_made=light_house icon

* Remove circle from amenity=bbq icon

* Change tourism=theme_park circle color to brown

* From https://github.com/organicmaps/organicmaps/issues/4858:

* Change tourism=artwork + artwork_type=statue icon
* Change tourism=artwork icon

### CODE REVIEW

**Review by vng — APPROVED** [review]
Good as always :)

**Comment by biodranik** [comment]
Cool! Maybe we can try to make the lighthouse icon more distinguishable (larger?) later.

Can you please rebase/regenerate?

**Review by biodranik — APPROVED** [review]
Thank you!

**Comment by patepelo** [comment]
Very good change. Thank you :)

**Comment by DavidMacalister** [comment]
Very nice change!

**Pull request merged**
