### PR TITLE
Allow comments in mapcss-mapping.csv

### PR DESCRIPTION
**Pull request by pastk**
Needs https://github.com/organicmaps/kothic/pull/13 merged first.

### CODE REVIEW

**Review by biodranik — APPROVED** [review]
Please double-check that submodule's hash is equal to the merged kothik's one.

**Comment by vng** [comment]
Actually, the initial idea here was to have line numbers equal to values :)
I don't mind if it helps to maintain this file.

**Comment by biodranik** [comment]
Hm, does it break the initial idea now, or was it broken for a long time?

**Comment by pastk** [comment]
> Actually, the initial idea here was to have line numbers equal to values :) I don't mind if it helps to maintain this file.

So does it break anything?
Otherwise I think its important to have comments in this file..

**Pull request merged**
