### PR TITLE
[strings] Serbian description added

### PR DESCRIPTION
**Pull request by dobridabar**
Added Serbian description file, authored by ZeljkoBG, with minor corrections from my side.

CC: @ZeljkoBG @zyphlar

### CODE REVIEW

**Comment by zyphlar** [comment]
@dobridabar @ZeljkoBG thanks! No need to include me, I was only involved because Zeljko started by commenting on my TTS task. I have no authority on translations or Serbian in general, I'll just work with people when they need special grammar considerations for making phrases like "in 500 meters, take exit 5 onto Highway 5 for Oslo towards Downtown"

**Comment by dobridabar** [comment]
@zyphlar, saw this too late, already added you to another PR. :)

Anyway, thanks a bunch for your help so far, your guidance and support was appreciated.

**Review by pastk — APPROVED** [review]
It'd be great to also translate the `short-description.txt` and `title.txt` etc.

**Comment by ZeljkoBG** [comment]
> It'd be great to also translate the `short-description.txt` and `title.txt` etc.
What is that? Where are those files?
There are none here - https://github.com/organicmaps/organicmaps/blob/master/docs/TRANSLATIONS.md

**Comment by pastk** [comment]
> What is that? Where are those files? 

In the same place as the main description:
https://github.com/organicmaps/organicmaps/tree/master/android/app/src/fdroid/play/listings/sr

and for the Apple AppStore:

https://github.com/organicmaps/organicmaps/tree/master/iphone/metadata

**Comment by pastk** [comment]
@ZeljkoBG check how other langs are translated e.g. https://github.com/organicmaps/organicmaps/tree/master/android/app/src/fdroid/play/listings/ru-RU

**Pull request merged**
