### PR TITLE
add a white outline for place-square text

### PR DESCRIPTION
**Pull request by hb0nd**
fixes https://github.com/orgs/organicmaps/discussions/6321

before/after
image1-6

### CODE REVIEW

**Comment by patepelo** [comment]
This looks much better, thank you :)

**Review by biodranik — APPROVED** [review]
@pastk

**Review by pastk — APPROVED** [review]

**Comment by biodranik** [comment]
@jumelles it should be fixed after finishing #4281

**Comment by RedAuburn** [comment]
rebased

**Comment by RedAuburn** [comment]
@pastk looks like a test isn't passing due to #6246 

```
Running visibility_test.cpp::VisibleScales_Highway
(-1, -1) highway|traffic_signals|
FAILED
indexer_tests/visibility_test.cpp:72 TEST(m_res.second == scales::GetUpperStyleScale()) 19 20 (17, 19)
Test took 0 ms
```

**Comment by pastk** [comment]
Did you do `git submodule update` before regenerating drules? I don't see a z20 in there.

**Comment by pastk** [comment]
Please rebase (with an updated kothic submodule).

So what happened is #6339 was accidentally merged with a downgraded to pre-z20 kothic and consequently drules w/o z20.
#6359 has fixed it in master now.

**Comment by RedAuburn** [comment]
ahh, sorry about that 😅 rebased

**Review by pastk — APPROVED** [review]
All scales are in place now, LGTM!

@vng merge?

**Pull request merged**
