### PR TITLE
[styles] improve metro station rendering

### PR DESCRIPTION
**Pull request by RedAuburn**
Reduced the size of `railway=subway_entrance` to differentiate it from the main station POI & standardised rendering of all metros

before / after (Moscow)
Screenshot 2022-10-23 at 23 19 41

before/after (Kiev)
Screenshot 2022-10-23 at 22 15 57

before/after (London)
Screenshot 2022-10-23 at 21 53 33

### CODE REVIEW

**Comment by biodranik** [comment]
It is not enough to visually differentiate the entrance. Are there any other ideas on how to do it? Other icons? Additional icons or text?

**Comment by endim8** [comment]
> It is not enough to visually differentiate the entrance. Are there any other ideas on how to do it? Other icons? Additional icons or text?

just noticed that there's already an icon for subway entrance.

it's not really good enough IMO, the best icon would be the metro logo in an arrow or something, but not really sure.

also, i've made and included an icon for a normal entrance now:

**Comment by matheusgomesms** [comment]
In my opinion (of a regular OM user) having the same icon for the station and entrances (even though the size is different) makes it hard to know exactly the metro entrance. I would still prefer the old icon (or some improvement on it, as I agree it is not the best icon).

The regular entrance icon looks great to me, though!

**Comment by biodranik** [comment]
@endim8 The proposed icon looks like a door entrance to the building and may be confusing. Something like stairs going down to the underground could be better. Considering that the station icon is big enough and visible somewhere nearby, then entrances may not need the same underground symbol on them.

How is it done in Apple and Google maps?

**Comment by matheusgomesms** [comment]
> The proposed icon looks like a door entrance to the building and may be confusing. Something like stairs going down to the underground could be better. Considering that the station icon is big enough and visible somewhere nearby, then entrances may not need the same underground symbol on them.

I believe @endim8 is referring to two different entrances. The door entrance is for the regular entrance (updating the small square used now on OM), and the metro entrance is using the metro symbol.

**Comment by biodranik** [comment]
1. Ok, I see. Doesn't a building entrance also mean an exit from the building? Are there more intuitive icons than this one?
2. Regarding metro entrances, the previous icon was better than the current ones, it clearly said about the entrance. But it can be improved! What about the same arrow without a circle? Filled or non-filled? Can you please try it?

**Comment by endim8** [comment]
Another entrance icon version:


Screenshot 2022-10-24 at 21 54 51

and with single arrow:


Screenshot 2022-10-24 at 21 59 18

i think i like this second one most

**Comment by biodranik** [comment]
Thanks!
1. Can you please also try the maki entrance icon? https://github.com/mapbox/maki/blob/main/icons/entrance-alt1.svg
2. Regarding stations, all options are not great... Maybe if we could combine the metro logo with an arrow (or draw two icons), or somehow style the logo in a different way, it could be better. Are there any other ideas on how to differentiate entrances from stations? Maybe also use a different text style/position? I'm afraid that if only one icon is visible on the screen, it's hard to easily decide if it's a station or entrance only by its size.

**Comment by matheusgomesms** [comment]
_Google Maps version:_
IMG_4485


_Apple Maps Version:_
IMG_4486

**Comment by endim8** [comment]
The Maki icon:
Screenshot 2022-10-24 at 22 20 01

it's quite faint, but that might actually be a good thing because the thicker icon made it look a bit cluttered

**Comment by biodranik** [comment]
Maki looks good, agree. Let's brainstorm the subway entrance )

**Comment by endim8** [comment]
[Qwant Maps](https://www.qwant.com/maps/) uses a stairs/escalator icon:


maybe one like magic earth?:

signal-2022-10-24-224833_002

**Comment by biodranik** [comment]
A better idea could be a pole with a symbol at the top. But it is not feasible to redraw each custom metro icon for that. Maybe simulate it with a T letter and icon on top of it? :)

**Comment by vng** [comment]
Take into account that subway entrances may be far away from _main_ metro sign (Moscow, Istanbul). I afraid that there will be not obvious what is this entrance for, if it is drawn by some generic icon.

I don't see a problem drawing entrances with metro icons. And it was made specially to hide _main_ metro icon and show entrances on high zoom levels, which are usually not so dense ..

**Comment by biodranik** [comment]
> And it was made specially to hide main metro icon and show entrances on high zoom levels, which are usually not so dense ..

It is good logic. But according to it, we should make subway entrances _larger_, and the underground station itself _smaller_, or even not visible at all on detailed zooms.

**Comment by vng** [comment]
It works exactly like you said now. Entrances become -m instead of -s, middle icon disappears.

**Comment by vng** [comment]
Oh, it works like this in Moscow (maybe some other cities) only. In other cities middle icon doesn't disappear.

**Comment by endim8** [comment]
I think keeping the main station icon is important, as its place page has the wikipedia description, contact info etc.

How about emphasising the main station POI with a background like this?:
Screenshot 2022-10-25 at 09 45 20
this is my favourite solution so far i think

**Comment by vng** [comment]
Also removing middle icon is ok for the very well mapped cities. Unfortunately, I can't say that all cities have mapped entrances.

**Comment by biodranik** [comment]
Let's try to remove the white text contour for entrance texts.
Another idea to try is to draw text labels for (underground) stations above the icon, at least on these detailed zoom levels.

**Comment by endim8** [comment]
also need to fix https://github.com/organicmaps/organicmaps/issues/1778 in this PR

**Comment by endim8** [comment]
> Let's try to remove the white text contour for entrance texts
i'll try this

What do you think about the translucent white background for the main icon?

**Comment by biodranik** [comment]
> What do you think about the translucent white background for the main icon?

It may not look good for other metro icons, because they all are very different.

**Comment by endim8** [comment]
>It may not look good for other metro icons, because they all are very different. 

fair point 👍

how's this? With smaller entrance icon, without white text and bigger main icon:

**Comment by biodranik** [comment]
1. Font color for entrances will probably look better if it will be more grayish, like other POIs.
2. Thinking again about the background. What if we actually try a blue square box either for stations or for entrances? It is clearly associated with transport (as for a bus stop nearby). It may look strange, of course, for some other icon colors/symbols, but in theory, if it will look good, it could be possible to rewrite all metro icons as white on blue for example.

**Comment by endim8** [comment]
Bing Maps:
Screenshot 2022-11-16 at 11 21 21

Google Maps:
Screenshot 2022-11-16 at 11 21 44

Apple Maps:


looks like just the icon might be the way to go, i'll try different styles for it though

**Comment by matheusgomesms** [comment]
> Bing Maps:

Please see [my message above](https://github.com/organicmaps/organicmaps/pull/3717#issuecomment-1289621129). On the mobile apps, the entrances are shown, with different icons.

**Comment by biodranik** [comment]
@pastk @vng does this PR or its ideas still make sense?

**Comment by pastk** [comment]
I think the current approach is alright (the main icon disappearing at higher zooms and giving way to entrance icons).
Probably the biggest drawback is that the main icons are holding wiki links etc. But it could be solved by duplicating this info into the entrance POIs.

**Comment by RedAuburn** [comment]
closing because it'd be easier to completely redo than rebase. the discussion is useful but the PR itself is not.

**Pull request closed without merging**
