### PR TITLE
Natural scrub rendering improvements

### PR DESCRIPTION
**Pull request by mpawelski**
Follow up on https://github.com/organicmaps/organicmaps/pull/3548#issuecomment-1296886672 to make scrub and shrubbery render on grass areas.

This PR changes insludes:
- Render `natural=scrub` with the same color as `forest`/`park`/`garden`.
- Make the z-index for `natural=scrub` bigger then `landuse=grass` to render scrubs that are mapped on grass areas.

before 1:
image
after 2:
image

before2:
image
after2:
image

Looks like and improvement for me. Map is more detailed, but the new rendered green areas are not too distracting.

### CODE REVIEW

**Review by biodranik — APPROVED** [review]
Thanks! I also like it )

**Review by vng — APPROVED** [review]

**Comment by vng** [comment]
Please, call ./tools/unix/generate_drules.sh script when you changed styles only (not icons).
Avoids unneeded symbols.png changes.

**Comment by rtsisyk** [comment]
Why were symbols updated?

**Comment by mpawelski** [comment]
> Please, call ./tools/unix/generate_drules.sh script when you changed styles only (not icons). Avoids unneeded symbols.png changes.

got it, I changed and rebased.

> Why were symbols updated?

I ran ./tools/unix/generate_styles.sh and it regenerated symbols. Or I just compiled whole project desktop app and it generated different symbols file (with different order of icon in generated file).

I fixed it. This PR contains only drules changes now.

**Comment by vng** [comment]
Looks like you should fetch and rebase once again :)

**Comment by mpawelski** [comment]
@vng done :)

**Comment by mpawelski** [comment]
no, wait, I rebased on wrong master 😅

**Comment by mpawelski** [comment]
now it's done ;)

**Review by biodranik — APPROVED** [review]

**Review by biodranik — APPROVED** [review]
Thanks!

**Comment by pastk** [comment]
Before this PR scrubs were rendered from z12-, now they're visible later starting at z14-
Is it by intention?

**Comment by pastk** [comment]
Related: https://github.com/organicmaps/organicmaps/pull/4758

**Comment by mpawelski** [comment]
> Before this PR scrubs were rendered from z12-, now they're visible later starting at z14-
> Is it by intention?

You mean why I deleted [this](https://github.com/organicmaps/organicmaps/pull/3786/commits/9d95eaccab6f4591bf71a4e6f9e36b819354e458#diff-b239d7ebf27bf7add6f6928016d3d19185f5d8638b8c5831bb5f6c8b07046252L311) line? 

I can't remember now. But it's probably a mistake, I guess I just went too far in making sure scrubs are rendered as forest/park/garden and deleted this line by accident. It should probably stay there because on such low zoom having just a `green0` color is [fine](https://github.com/organicmaps/organicmaps/pull/4758#issuecomment-1465170825).

**Comment by biodranik** [comment]
@mpawelski can you please return it back then and test what it looks like? 🙏

**Comment by mpawelski** [comment]
I've found some scrub without other green area outside to test: [52.57049,16.63636](https://www.openstreetmap.org/way/243299569). And yes, the scrub are not visible on z12 and z13:
current master:
14z
image
13z
image
12z
image

But bringing back [the line](https://github.com/organicmaps/organicmaps/pull/3786/commits/9d95eaccab6f4591bf71a4e6f9e36b819354e458#diff-b239d7ebf27bf7add6f6928016d3d19185f5d8638b8c5831bb5f6c8b07046252L311) doesn't change anything. I guess I need to rebuild the map. I didn't do it before.  I just tried to build the generator tool with `tools/unix/build_omim.sh -r generator_tool`, but I didn't found any `../omim-build-release/generator_tool` executable to run. Do you know what I'm doing wrong @biodranik ?

**Comment by pastk** [comment]
> But bringing back [the line](https://github.com/organicmaps/organicmaps/pull/3786/commits/9d95eaccab6f4591bf71a4e6f9e36b819354e458#diff-b239d7ebf27bf7add6f6928016d3d19185f5d8638b8c5831bb5f6c8b07046252L311) doesn't change anything. I guess I need to rebuild the map. I didn't do it before. I just tried to build the generator tool with `tools/unix/build_omim.sh -r generator_tool`, but I didn't found any `../omim-build-release/generator_tool` executable to run. Do you know what I'm doing wrong @biodranik ?

That's right, you have to re-gen the map, which might be not easy to setup: https://github.com/organicmaps/organicmaps/blob/master/tools/python/maps_generator/README.md

Or temporary apply the patch from https://github.com/organicmaps/organicmaps/pull/2798 to make it work for design purposes w/o maps re-gen.
(@biodranik this is exactly the case when having the patch in master would save contributors' time).

**Comment by biodranik** [comment]
@pastk I understand, it is always a tough decision, what to choose: to make the life of several contributors easier or to slow down hundreds of thousands of users in production.

As the patch can be easily applied by an interested developer, there is no urgent need to slow down the production experience yet.

**Comment by pastk** [comment]
> @pastk I understand, it is always a tough decision, what to choose: to make the life of several contributors easier or to slow down hundreds of thousands of users in production.
> 

It would be true and I wouldn't be pushing this patch if it was slowing things down for other users indeed. But its not.
(Sorry, but despite a lot of discussion, you didn't present any actual proof of performance degradation for other users... If you'd examine the code carefully you'd see degradation is not possible because the patch does nothing unless its activated by a search command.)

> As the patch can be easily applied by an interested developer, there is no urgent need to slow down the production experience yet.

Unfortunately applying the patch takes ~10-15 extra minutes too which is also a lot just to make a few screenshots...
And there is a power user custom style use case as well which is not solvable by applying a patch.

**Pull request merged**
