### PR TITLE
Update types_strings.txt

### PR DESCRIPTION
**Pull request by Mannivu**
Fix Italian translation of "guest house" (we have many, but the most widespread is guest house)

### CODE REVIEW

**Review by biodranik — APPROVED** [review]
Thanks! CC @organicmaps/translations-it

**Comment by fitojb** [comment]
Not a fan of further spreading anglicismi TBH

**Comment by biodranik** [comment]
What does the official dictionary say? And what is widely used by people?

**Comment by Mannivu** [comment]
I've made a short research and maybe a more correct translation would be "Affittacamere" (I've checked the most known hotel booking websites). I'll change the file.

**Review by biodranik — COMMENTED** [review]
What is in data/categories.txt? Is new translation there? Please make sure that other possible synonyms that users can type, are also present there (including Guest House).

**Comment by Mannivu** [comment]
> What is in data/categories.txt? Is new translation there? Please make sure that other possible synonyms that users can type, are also present there (including Guest House).

Updated that too (I didn't know about that file).

**Review by biodranik — APPROVED** [review]
Grazie!

**Pull request merged**
