### PR TITLE
[Android] Issue #1825 - Place page schedule rework

### PR DESCRIPTION
**Pull request by strump**
Fixing issue #1825 
Now week schedule is chronological. But depending on device settings either Monday is the first day of week or Sunday is.

| Before | After (Monday first) | After (Sunday first) |
| :-: | :-: | :-: |
| Samsha-before | Samsha-after-monday | Samsha-after-sunday |
| Kyiv-before | Kyiv-after-monday | Kyiv-after-sunday |

Changes:

1. Moved files from
    `android/src/com` -> `android/src/main/com`
    `android/src/fdroid` -> `android/src/main/frdoid`
    `android/src/google` -> `android/src/main/google`
2. Created unit-tests in `android/src/test` with single test class `PlaceOpeningHoursAdapterTest`

## Questions
Maybe it makes sense to run unittests at github checks?

### CODE REVIEW

**Comment by biodranik** [comment]
Why did you move/rename files?

**Comment by biodranik** [comment]
> I understand that moving of big amount of files makes harder to track git history. I had to do it to create `android/src/test` subfolder with tests.

Why do you need this rename for tests to work? Why they can't work without renaming? It probably doesn't worth it…

**Comment by biodranik** [comment]
If it is really no way to avoid this renaming, I would prefer to do it in a separate commit, and also rename all classes/packages from com.mapswithme.maps to app.organicmaps, and replace all MWM prefixes with OM.

**Comment by strump** [comment]
I was looking where to put unit tests. If I put to 'src':

* `android/src/core`
* `android/src/fdroid`
* `android/src/google`
* `android/src/test` <-- Looks wrong

It looks wrong to have tests on the same level as code. Those tests will get to APK. So I created `android/src/main` folder.

To avoid renaming I can put unittests to `android/srcTests` folder. How do you think?

**Comment by biodranik** [comment]
android/tests is even better :)

**Pull request closed without merging**
