### PR TITLE
Reduce outdoor POIs visibilities in the main style

### PR DESCRIPTION
**Pull request by pastk**
[Overview of changes](https://github.com/organicmaps/organicmaps/pull/7407/files#diff-749a1aa8c1be0b0df3e95763fee2ab6cd1ef3048fbc43efcb900faf9be9d29ab)

<strike>The only exception - I've raised `tourism-caravan_site` from z16- to z15- as its needed for RV trip planning.</strike>
(upd: will be included into another PR)

Also made font sizes and captions' appearances more consistent.

### CODE REVIEW

**Review by biodranik — COMMENTED** [review]
It's better to beta-test these changes. Not everyone may get used to the outdoors style yet.

**Review by euf — APPROVED** [review]
I checked several types of POIs, and their discoverability still looks good to me after the priorities decrease.

**Comment by pastk** [comment]
Update:
- reduced visibilities of power towers and forests icons
- removed the `tourism-caravan_site` vis raise (will be included into another PR)

So now this PR could be added to a beta w/o map regeneration.

z12

**Comment by pastk** [comment]
The tests that fail here do pass on my local machine...

Looks like geometry tests are failing because of some platform-specific precision issue?

**Review by vng — COMMENTED** [review]
- Agree with volcano, forest, etc ..
- Why removed shelter, picnic on z16? z16 is already very detailed zoom IMO.

**Comment by euf** [comment]
> Shelters are often polluting cities when its `public_transport=platform` `shelter=yes` 

Would it make sense to move this combination into a separate type, so they have `shelter=yes` priority for outdoors style, but it's ignored for generic style? Or maybe draw a separate icon for sheltered platfroms? 

I'm not sure how the logic for displaying primary / optional tags works, I only heard that improvements were planned for the toilets / drinking_water subtags

**Comment by biodranik** [comment]
Showing shelters instead of bus stops is a very annoying bug, critical for the UX in cities. @vng is there a better solution (e.g. using main types), instead of _kostyling_ it?

**Comment by vng** [comment]
- This is not about _main_ type, usually there is only one shelter type there.
- Also this is closely connected with PTv1, PTv2. Trying to put _stop_ type can lead to stops icons overflowing. Especially when there are PT nodes, platform ways or relations mapped defining one logical stop.

Please, link the issue with shelter-stops here, and put the most _annoying_ examples into the issue. Let's discuss and find a solution there.

**Comment by pastk** [comment]
> > Shelters are often polluting cities when its `public_transport=platform` `shelter=yes`
> 
> Would it make sense to move this combination into a separate type, so they have `shelter=yes` priority for outdoors style, but it's ignored for generic style? Or maybe draw a separate icon for sheltered platfroms?
> 

- https://github.com/organicmaps/organicmaps/issues/2319

**Comment by pastk** [comment]
> > ```
> > * Why removed shelter, picnic on z16? z16 is already very detailed zoom IMO.
> > ```
> 
> Shelters are often polluting cities when its `public_transport=platform shelter=yes`.

Regardless of it - isn't z16 is too visible for shelters in the main style?
E.g. we have schools, kindergartens, dentists, playgrounds and plethora of other amenities/shops/crafts at z17.

**Comment by pastk** [comment]
master (https://www.openstreetmap.org/node/9481196117):
Screenshot_1710072714

**Pull request merged**
