### PR TITLE
[styles] Secondary roads, farmlands

### PR DESCRIPTION
**Pull request by Sparker95**
Hello,
There are two styles-related changes in this pull request:

**Secondary roads**
I've changed color of secondary roads so that they are distinguishable from minor roads. The new color is derived from orange color of primary roads, but it is more subtle. I've changed it in clear and night styles.
clear secondary road diff
night secondary road diff

**Farmlands**
Where I live there are many fields marked as 'farmlands' and when whole screen is occupied by them, the yellow color looks very bright on my phone. So I tweaked the farmland color to be softer. I've done it only for clear style.
farmland diff

### CODE REVIEW

**Comment by Sparker95** [comment]
DCO complains about this:

> Commit sha: [071998e](https://github.com/organicmaps/organicmaps/pull/7048/commits/071998ef5288a82debde2f181f47cfbdf84b1495), Author: Saveliy Tronza, Committer: Saveliy Tronza; Expected "Saveliy Tronza [sparker_95@mail.ru](mailto:sparker_95@mail.ru)", but got "Saveliy Tronza [saveliytronza@gmail.com](mailto:saveliytronza@gmail.com)".
> Commit sha: [5c8c2b3](https://github.com/organicmaps/organicmaps/pull/7048/commits/5c8c2b30464404c3d4eeb4502db718140b9941c4), Author: Saveliy Tronza, Committer: Saveliy Tronza; Expected "Saveliy Tronza [sparker_95@mail.ru](mailto:sparker_95@mail.ru)", but got "Saveliy Tronza [saveliytronza@gmail.com](mailto:saveliytronza@gmail.com)".

But I switched my GitHub primary email to gmail.com mentioned in the log today. I think we can just ignore it.

**Review by RedAuburn — APPROVED** [review]
looks great!

**Comment by pastk** [comment]
> **Farmlands**
> Where I live there are many fields marked as 'farmlands' and when whole screen is occupied by them, the yellow color looks very bright on my phone. So I tweaked the farmland color to be softer. I've done it only for clear style.

For the history/context:
farmlands were made more saturated in https://github.com/organicmaps/organicmaps/pull/2134 to make white roads and footways more contrast against them;
but maybe after #6590 we can increase lines contrast independently;
I agree that a paler color is better aesthetically (maybe its better to revert to the original color changed in #2134).

**Comment by pastk** [comment]
Do the new secondary color look contrast enough against parkings (probably it is) and beach areas (its much more bright yellow)?

**Comment by vng** [comment]
I like distinguishable secondary road color.

**Comment by pastk** [comment]
I like a lot the extra "structure" secondaries now give to urban areas and how more important/through roads are highlighted in the countryside too!

However it seems that now secondaries are too bright / saturated compared to primaries even. I think they should be a tad more pale.

**Comment by Misalf-git** [comment]
Looks promising!
Only judging by the screenshots, it also seems to be tricky regarding wood (or other greenery) where the light orange doesn't really stand out.
Maybe darker colors for the greens?

**Comment by pastk** [comment]
I tried to make it a bit paler ("old" is the current PR, "current" is my adjustment `#ffbf52`)
image

Some screenshots with `#ffbf52`.

z10

its true its not the best against the green, but IMO its OK
(and adjusting the greens is a complex story, I'd avoid it :))
z11

z13

z17

**Comment by Misalf-git** [comment]
What about a thin outline?

As on intersections:


I don't know if that's an artifact only visible at those intersections, but this "effect" (as a white outline) might help to see secondary roads on some backgrounds.

**Comment by RedAuburn** [comment]
> I don't know if that's an artifact only visible at those intersections, but this "effect" (as a white outline) might help to see secondary roads on some backgrounds.

afaik this artifact is caused by the old fake aliasing (removed in https://github.com/organicmaps/organicmaps/pull/6590).
some sort of outline might be good though

**Comment by pastk** [comment]
On overview zooms road lines are very thin already (~1px, depending on screen dpi), so adding an outline will make them thicker.
Also it can impact performance when rendering big cities as every road will have to be rendered by two lines instead of 1.

It'd make more sense to use outlines on more detailed zooms, but there the roads are thick enough already to be easily distinguishable from the background.
(might make sense still e.g. for outdoors where more contrast is desired)

**Comment by biodranik** [comment]
1. Aren't secondary roads already visually distinguished by their width? I don't like the rainbow palette in some places with many secondary roads. The map looks way cleaner with a white color.
2. It's better do not mix different changes in one PR and split independent logical changes into different PRs that can be reviewed/merged separately.

**Comment by vng** [comment]
@pastk Every _after_ screen looks better than _before_, thanks. The big difference and value will be in "American" cities. Could you please make same gifs for NY or Buenos Aires?

For me, the value is to understand where a quiet residential area and where is a major city road (secondary).

**Comment by Sparker95** [comment]
Hi, sorry for not replying for a while, and thanks for taking a look.

> Do the new secondary color look contrast enough against parkings (probably it is) and beach areas (its much more bright yellow)?

I couldn't find an actual parking spot or beach with secondary road going right over it, or close to it. But I tried to draw some lines over beach and parking site and it seems fine. I used #ffbf52 color, the one you propose @pastk . I think it looks fine on my screen.
image

> It's better do not mix different changes in one PR and split independent logical changes into different PRs that can be reviewed/merged separately.

Hello, yes I agree, I hoped to discuss if briefly here and then I would either remove farmland color from PR or move it to a different PR.

**Comment by pastk** [comment]
> 1. Aren't secondary roads already visually distinguished by their width? I don't like the rainbow palette in some places with many secondary roads. The map looks way cleaner with a white color.
> 

Not really.. On overview zooms all roads are too thin to see the difference.

And even on detailed zooms the difference is too subtle to grasp without using a ruler :)
E.g. in my last z17 screenshot there are tertiary and residential roads connected to the secondary, but they're not really distinguishable by their width.
At z17 secondaries are 6.6 wide, while tertiaries and residential share a 5.5 width.

I think after this PR we can re-visit the widths to make tertiaries stand out from residentials width-wise (important in e.g. villages as now its often imossible to say which street is the "main"/through road).

**Comment by pastk** [comment]
BTW note that this PR doesn't color secondaries in the vehicle/navigation style.

Which is discussable.
On one hand - why a driver would care on which road type they're driving? Might make sense to distinguish only motorroads, as they should have physical directions separation, no cyclists/pedestrians and no crosses/lights (atm motorways, trunks and primaries are highlighted).
On the other hand when one is following a route but wants to deviate from it (e.g. due to congestion), then its useful to know which road is major. And overall highlighting major roads gives more "structure" to the journey like "OK, we've passed this big avenue, a little more to arrive".

**Comment by pastk** [comment]
Buenos Aires

ldpi_z10

Interestingly, on z13-14 width difference between secondaries and lower roads looks most prominent (but somewhat less on high dpi devices, than on this screenshot). E.g. on z14 the difference is 3 vs 1.8.
ldpi_z14

**Comment by biodranik** [comment]
> Not really.. On overview zooms all roads are too thin to see the difference.

> I think after this PR we can re-visit the widths to make tertiaries stand out from residentials width-wise

Let's do it before this PR. The most obvious way for any person to understand the road priority is by using its width: the wider the noisier/the more important the road.

Using colors is NOT obvious and requires some learning/getting used to it.

See how widths are used in the right way in other maps compared to OM:

Google Maps | Apple Maps | OM
--|--|--
telegram-cloud-photo-size-2-5247084288107731760-y|telegram-cloud-photo-size-2-5247084288107731992-y|telegram-cloud-photo-size-2-5247084288107731761-y

**Comment by biodranik** [comment]
1. As you can see from the screenshots above, the issue is not with secondary roads that are clearly visible in OM. The issue is with tertiary roads that are also noisy.
2. All-orange roads on screenshots in BA look less readable and more noisy.

**Comment by pastk** [comment]
> > I think after this PR we can re-visit the widths to make tertiaries stand out from residentials width-wise
> 
> Let's do it before this PR. The most obvious way for any person to understand the road priority is by using its width: the wider the noisier/the more important the road.

Now we have secondaries, tertiaries, unclassifieds and residentials sharing almost the same width (depending on zoom level).

If we'll make secondaries' and tertiaries' widths different enough on all zooms, then we have an issue with tertiaries and residentials still.
And we can't make residentials much thinner as they'll look like service roads then.

We just can't have enough easily distinguishable width classes to cover all road types we want (especially in lower zooms and/or on lower dpi devices), hence the color comes to help.

**Comment by biodranik** [comment]
Coloring only minor roads on detailed zooms won't hurt as much as all-orange cities on observe zoom levels.

Note that major maps do not use bright orange-like colors. Apple highlights secondaries with a different color, but it's not a bright one. Google was using all-whites before its recent changes, exactly like OM.

Using widths where possible makes the map readable and cleaner.

**Comment by pastk** [comment]
> Coloring only minor roads on detailed zooms won't hurt as much as all-orange cities on observe zoom levels.

Do you mean this idea https://github.com/organicmaps/organicmaps/issues/6128#issuecomment-1734242019 ?
The downside there as that the color for the same road type will be different on various zoom levels and it might cause confusion...

Or do you mean coloring **minor** roads not major ones? It'll be not in line with the current approach of highlighting *major* roads so will be even more confusing IMO. I think its better to stick to "shades of orange" approach that try to introduce another "minor" color (e.g. grey-ish will be tricky as our background is grey..).

> 
> Note that major maps do not use bright orange-like colors. Apple highlights secondaries with a different color, but it's not a bright one. Google was using all-whites before its recent changes, exactly like OM.

Sorry I don't get the point, MM/OM used orange historically and it worked really well. And the new shade is paler / less prominent than the currently used ones.

> 
> Using widths where possible makes the map readable and cleaner.

True. I hope it'll be possible to better distinguish tertiaries/unclassifieds vs residentials vs service by width. But no more grades than that, hence need a color for secondaries.

**Comment by pastk** [comment]
> Hello, yes I agree, I hoped to discuss if briefly here and then I would either remove farmland color from PR or move it to a different PR.

Could you please amend the color to `#ffbf52` and rebase?
And just make a separate commit for the farmlands change I think.

**Review by euf — APPROVED** [review]
Okay, there are two big topics: overall legibility and exact color choices. 

For the map feel, so called "rainbow look" is not bad per se. Organic Maps already uses more colors (and offers more contrast) than Google or Apple. I believe this was a deliberate design choice made a decades ago, and users are okay with it. Introducing a new color for secondary roads doesn't necessarily make things worse. One could argue that it's even an improvement: bridging the gap between super-orange primary roads and all-white other roads may decrease mental load for reading the map. 

As others noted, the current thickness of white secondary roads is not sufficient for visually accenting them as a distinctive part of the road graph. Introducing an orange-ish color between primary orange and white is a good alternative. 

Comparing suggested `#ffbf52` against `#ffffff` shows significantly worse contrast on `@forest` `#AABF65` background (and other shades of `@green`). On every other background it performs as well as the original pure white. 

image

Overall, I believe increasing road graph legibility on low and medium zooms is worth the effort. Secondary roads do not collide with greenery too often, so this compromise looks promising. It still leaves enough room for the further improvements:
- tweaking the road thickness
- adding road casings for better contrast (that's what Apple and Google do)
- working on shades of greenery 
- adjusting the overall palette (now we are locked in the "let's find an unused color with enough contrast" paradigm, which is bad)  

I'll say go for it, and wait for users feedback. This PR is not a revolution or a redesign, it's just a marginal improvement and a compromise, and it's okay.

**Comment by pastk** [comment]
@euf thanks for the analysis and visualizing in the table form!
What is `DNP`? Some contrast metric?

**Comment by pastk** [comment]
BTW currently trunks and primaries use several orange shades across various zoom levels.
E.g. the darkest / the most contrast `@primary_orange` on low zooms, then lighter `@primary_orange_medium` and then the lightest / the most pale `@primary_orange_light` on detailed zooms.

So we can try use this approach for secondaries on overview zooms as well, i.e. where they're the thinnest and the contrast is not enough use a darker / more contrast shade to make them more visible against greenery.

**Comment by pastk** [comment]
> BTW currently trunks and primaries use several orange shades across various zoom levels. E.g. the darkest / the most contrast `@primary_orange` on low zooms, then lighter `@primary_orange_medium` and then the lightest / the most pale `@primary_orange_light` on detailed zooms.
> 
> So we can try use this approach for secondaries on overview zooms as well, i.e. where they're the thinnest and the contrast is not enough use a darker / more contrast shade to make them more visible against greenery.

- I've implemented it in #7117

**Comment by pastk** [comment]
This PR is superceded by #7117

**Comment by euf** [comment]
@pastk Yes, DNP is a shorthand for "Does Not Pass", meaning that contrast ratio is too low for WCAG guidelines. Since we are not doing text accessibility, it's okay. I was looking only at exact contrast values. This screenshot was made with this tool (and some extra tweaks): 

https://contrast-grid.eightshapes.com/?version=1.1.0&background-colors=E3E1D2%2C%20%40background%0D%0AEEE5B2%2C%20%40desert%0D%0AAABF65%2C%20%40forest%0D%0AE4E2EB%2C%20%40industrial%0D%0AEBE4A5%2C%20%40farmland%20(current)%0D%0AE4DEAD%2C%20%40farmland%20(suggested)%0D%0A&foreground-colors=%23FF7326%2C%20%40trunk_orange_medium%0D%0A%23FFFFFF%2C%20%40secondary%20(current)%0D%0A%23FFB226%2C%20%40secondary%20(suggested)%0D%0A&es-color-form__tile-size=compact&es-color-form__show-contrast=aaa&es-color-form__show-contrast=aa&es-color-form__show-contrast=aa18&es-color-form__show-contrast=dnp

**Comment by Sparker95** [comment]
Awesome, thanks for taking a look. Sorry that I wasn't able to keep up with discussion here.
I think it's safe to close this PR to keep PR list more clear.

**Pull request closed without merging**
