### PR TITLE
[styles] redo entrances

### PR DESCRIPTION
**Pull request by endim8**
see latest comment for screenshots: https://github.com/organicmaps/organicmaps/pull/4295#issuecomment-1405886248
(needs map regeneration for entrance-main type)
fixes https://github.com/organicmaps/organicmaps/issues/3890

### CODE REVIEW

**Comment by pastk** [comment]
Maybe demote secondary entrances to z19 while keeping main ones at z18-?
Also makes sense to add a separate "Main Entrance" translation?

**Comment by biodranik** [comment]
No bold, please. Imagine buildings with only one main entrance, then we'll see a lot of boldy entrances.

**Comment by pastk** [comment]
> No bold, please. Imagine buildings with only one main entrance, then we'll see a lot of boldy entrances.

And an alternative to this could be making secondary entrances e.g. half-transparent?

**Comment by endim8** [comment]
z18 / z19
Screenshot 2023-01-18 at 15 15 49

with opacity, higher zoom level for entrance=yes

the lower rendering is good, but once on z19 it's still difficult to differentiate

**Comment by pastk** [comment]
Yeap a different icon would work better, e.g. a bigger looking double-door/arch icon for main entrance. The current icon is good for secondary I think as it resembles emergency exit signs which are not used often :)

**Comment by endim8** [comment]
How are these? I like the first one, the second is more similar to the icon you suggested
Screenshot 2023-01-22 at 21 41 52

**Comment by endim8** [comment]
failing check seems unrelated to this pr:

```
Running osm_type_test.cpp::TestWithClassificator_OsmType_Address
FAILED
generator_tests/osm_type_test.cpp:221 TEST(params.IsTypeExist(GetType({"building", "address"}))) 
Test took 207 ms
```

**Review by Grreby — APPROVED** [review]

**Review by Kazing — APPROVED** [review]

**Review by matheusgomesms — APPROVED** [review]

**Review by j13m126 — APPROVED** [review]

**Review by dvdmrtnz — APPROVED** [review]

**Review by j13m126 — APPROVED** [review]

**Review by LaoshuBaby — APPROVED** [review]

**Review by jimcarst — APPROVED** [review]

**Comment by pastk** [comment]
The new icon looks good in big size, however when its actual size on the map then I personally had hard time to "read" it...
Maybe there are similar alternatives better suited for small sizes?

**Comment by dvdmrtnz** [comment]
A different approach would be using some really simple symbols for entrances like OSM Carto uses: A filled square for main entrances and a non-filled square for the rest:

map

https://www.openstreetmap.org/#map=19/51.47680/0.00046

**Comment by endim8** [comment]
i'll try using squares and post screenshots 👍 although they might be _too_ simple

**Comment by endim8** [comment]
> The new icon looks good in big size, however when its actual size on the map then I personally had hard time to "read" it... Maybe there are similar alternatives better suited for small sizes?

i agree, readability at small sizes is pretty hard :(

Maybe something like this?
Screenshot 2023-01-25 at 18 54 45

**Comment by pastk** [comment]
> > The new icon looks good in big size, however when its actual size on the map then I personally had hard time to "read" it... Maybe there are similar alternatives better suited for small sizes?
> 
> i agree, readability at small sizes is pretty hard :(
> 
> Maybe something like this? Screenshot 2023-01-25 at 18 54 45

Worth trying!

Filled/empty squares might work but will require users to learn first (and rememeber!) that it depicts an entrance actually.

**Comment by lunarna-gh** [comment]
The entrance icons used to be simple circles and they got replaced with door icons at one point to make them easier to understand, but it also made the map look much more cluttered in door-dense places (like apartment blocks).
 The suggestion of squares (or maybe just bringing back the circles but with filled and unfilled variants) makes more sense to me, since multiple door icons would worsen this effect.

**Review by lunarna-gh — APPROVED** [review]

**Comment by biodranik** [comment]
Let's try small vertical filled/unfilled rectangles (like squares on Carto, but more similar to doors). Cluttering is a bigger problem. Users always can select an object on the map and _read_ what it means. And learn it immediately.

**Review by MetehanOzyurek — APPROVED** [review]

**Review by d4f5409d — APPROVED** [review]
Good. (hu_HU)

**Comment by d4f5409d** [comment]
> Let's try small vertical filled/unfilled rectangles (like squares on Carto, but more similar to doors). Cluttering is a bigger problem. Users always can select an object on the map and _read_ what it means. And learn it immediately.

Do you have the svg of the current entrance door icon? I could make a modificstion to make it differ from others.

**Comment by endim8** [comment]
> Do you have the svg, and could you send or link it then, of the current entrance door icon? I could make a modification to make it differ from others.

[the current entrance icon ](https://github.com/organicmaps/organicmaps/blob/master/data/styles/clear/style-clear/symbols/entrance-s.svg)

[the main_entrance from this pr](https://github.com/organicmaps/organicmaps/blob/1f7df28208d8dfc6210dc4a198cc73cae5f4b30f/data/styles/clear/style-clear/symbols/main_entrance-s.svg)

I think the carto rectangle method is probably what we'll end up using though, am working on updating this PR with them atm

**Comment by endim8** [comment]
Screenshot 2023-01-26 at 18 02 56
Screenshot 2023-01-26 at 17 53 30


using rectangles! imo this looks the best so far

**Comment by d4f5409d** [comment]
entrance
We could use this icon for either main entrances or other entrances! It fits the current state I think.

**Comment by d4f5409d** [comment]
> Screenshot 2023-01-26 at 18 02 56
> 
> Screenshot 2023-01-26 at 17 53 30
> 
> using rectangles! imo this looks the best so far

It looks like an icon is missing. I'm sure users will think it's a bug that the icon appears like that. I would rather not use that.

**Comment by d4f5409d** [comment]
Alright I made some icons, so we can choose from. I made the current entrance icon a little smaller and imo it should be used for all the entrances. The main entrances should use the circular ones. Or other way round. Tell me your thoughts!

**SVGs:**
entrance2
entranceside
entrancesideround
s.githubusercontent.com/76624594/214928526-23c369d9-eb37-402d-a9ff-dcfbfd685959.png)

**Comment by biodranik** [comment]
It's obvious to improve the vertical rectangle by adding a small door handle :) E.g. small white horizontal line (or dot) for the main entrance on the left, and small line of the door's color for the secondary entrance.

**Comment by biodranik** [comment]
Icons with an arrow are not ideal: every building entrance is also an exit.

**Comment by d4f5409d** [comment]
> It's obvious to improve the vertical rectangle by adding a small door handle :) E.g. small white horizontal line (or dot) for the main entrance on the left, and small line of the door's color for the secondary entrance.

That's right! Agreed on this one!

**Comment by d4f5409d** [comment]
> Icons with an arrow are not ideal: every building entrance is also an exit.

Great argument! This is why FOSS projects often thrive! Discussion!

**Comment by endim8** [comment]
Adding a door handle looks good! I like it

**Comment by endim8** [comment]
Screenshot 2023-01-27 at 01 13 42

yes, staircase, shop, exit, secondary can be covered by generic `entrance` type
main can be `main-entrance`
home, garage, service, emergency can be covered by`minor-entrance`

need to add minor-entrance type

**Comment by biodranik** [comment]
1. Can you please rebase?
2. Can handles be a bit smaller?
3. Are they drawn from z18? Doesn't it pollute the dense map? Can we draw entrances only on z19?

**Comment by endim8** [comment]
> 1. Can you please rebase?

done
>     2. Can handles be a bit smaller?


done, this is probably the smallest they can be while still being legible
>     3. Are they drawn from z18? Doesn't it pollute the dense map? Can we draw entrances only on z19?

only main entrances are drawn on z18, it shouldn't pollute provided entrances are tagged correctly, but we can revisit it if it does :)

**Comment by biodranik** [comment]
> done, this is probably the smallest they can be while still being legible

Looks good to me! @vng PTAL

**Review by biodranik — APPROVED** [review]

**Comment by vng** [comment]
Hm, do you really like black door (is it entrance=main)? In fact black rectangle ... looks unreadable for me

**Comment by biodranik** [comment]
1. Unfilled door looks great! Thanks!
2. Now all doors are rendered unfilled, even the main ones.
3. We need to differentiate translations for entrances. What about "Main Entrance" and "Entrance" (here we need to add a comment that it's a secondary entrance for translators)?
4. What about the following idea for the main door? Make it also unfilled, but consisting of 2 doors: e.g. two vertical rectangles in a square/rectangle (so the width is only slightly bigger than the current single door's width), with door handles at the center (from the left and from the right of the central vertical line)? E.g. to draw a _closed_ two-parts door, compared to previously discussed icons.

**Comment by endim8** [comment]
>     2. Now all doors are rendered unfilled, even the main ones. 
>     3. We need to differentiate translations for entrances. What about "Main Entrance" and "Entrance" (here we need to add a comment that it's a secondary entrance for translators)?

These are already implemented, but require a map regeneration :)
added comments about primary and secondary strings.

>     4. Should entrance=yes be drawn as a main door, or as the secondary one?

entrance=yes is a generic type, but also used for secondary entrances. it's best to only render main entrances when explicitly tagged as =main

>     5. What about the following idea for the main door? 

this looks alright, possibly less readable, but it's still good:
(PR now using this icon)
Screenshot 2023-02-06 at 15 05 22

**Comment by endim8** [comment]
in-app screenshots of further apart handles:
signal-2023-02-06-161454_002

**Comment by endim8** [comment]
(PR now using the further apart door handles)

**Comment by endim8** [comment]
fails look unrelated? seems like the http://azure.archive.ubuntu.com went down for a sec or something

**Comment by biodranik** [comment]
Cool, now it looks great! @vng WDYT?

**Comment by vng** [comment]
LGTM. If ok in night mode.

**Comment by endim8** [comment]
Night mode:
Screenshot_20230207-093934_Organic Maps

**Review by biodranik — APPROVED** [review]
LGTM!

**Pull request merged**
