### PR TITLE
[styles] Tune cycleways

### PR DESCRIPTION
**Pull request by pastk**
Compared to beta #8018 it makes dedicated/segregated cycleways a little more transparent at z13-14 while shared paths a little bit more visible.

Closes #8018

### CODE REVIEW

**Comment by biodranik** [comment]
Any screenshots in good quality? )

**Comment by pastk** [comment]
Comparison with the last beta:
cycleways-barcelona-z13-beta

Comparison with the last release:
cycleways-barcelona-z13-rel

**Comment by pastk** [comment]
cycleways-luxembourg-z16-beta

**Comment by biodranik** [comment]
Cycling lines are still too prominent for the general style, which looks dirtier now.

**Comment by pastk** [comment]
> Cycling lines are still too prominent for the general style, which looks dirtier now. Cyclists are only a subgroup of all our users. We don't highlight paths on the main style, why highlighting cycling paths then?

These PRs are not intended to "highlight" cycleways anymore than they were already. They change the color and patterns, but strive to keep the cycling / non-cycling balance as is.

If your intention is to change the status quo balance then please create a new issue for that. These set of interdependent PRs is complex enough already.

> Let's make them more prominent in the outdoors style, and grayish in the main style, to avoid distracting most users from the map.

I don't think the Outdoors style is suitable for urban cycling, e.g.
Screenshot_20240502-134528_sm

**Comment by pastk** [comment]
I've reduced cycleways opacity on overview zooms a little more:

compared to the previous beta
cycleways-barcelona-z13-beta-new

compared to the last release
cycleways-barcelona-z13-rel-new

**Comment by pastk** [comment]
@biodranik @vng PTAL!

**Review by vng — APPROVED** [review]

**Pull request merged**
