### PR TITLE
Permission screen for android auto.

### PR DESCRIPTION
**Pull request by n1snt**

### CODE REVIEW

**Comment by AndrewShkrob** [comment]
I believe this is a bad architectural design.

Please, check this PR: https://github.com/organicmaps/organicmaps/pull/4602

We're trying to remove the UI from `LocationHelper` and you're bringing it back.
Why do you make two separate modules `car` and `location` being strongly connected?
Can you omit this and push a new screen to the screen manager directly in the `car` module without bringing out the implementation details of one module to another?
(Actually, the answer is "Yes". You just need to figure out how to do this 😄)

I also don't understand the part in `NavigationSession.onStart`. I assume it's only for testing purposes.
You just need to check if we have the required permissions during `NavigationSession.onCreateScreen` call. If no - show the "Permission Request" screen (like [here](https://github.com/android/car-samples/blob/main/car_app_library/navigation/common/src/main/java/androidx/car/app/sample/navigation/common/car/RequestPermissionScreen.java), for example). Not the "Error" screen.

**Comment by n1snt** [comment]
I am really sorry for the confusion I created this PR to display how we can display errors when the location is denied or disabled in my Proposal.
I know injecting carContext & surface renderer is a bad architectural design.
There is still much work to do here, including creating a new screen & all the other tasks you mentioned.

**Comment by n1snt** [comment]
If we add the check in `NavigationSession.onCreateScreen` & user disables/denies the permission after that wouldn't it still show the navigationScreen?
Please correct me if I am wrong but wouldn't it be better if we implement a listener in `BaseLocationProvider` and use that in `LocationHelper`? (Just like `onLocationUpdated` & `onCompassUpdated`)

**Comment by n1snt** [comment]
We can use LocationUtils to display an error in OnCreateScreen Something like this:
(Using error screen for demonstration)
image

But if we disable the location after the screen is created then it won't show the error.

**Comment by n1snt** [comment]
I have tried reimplemented it by using callback have a look at it again.

**Comment by n1snt** [comment]
### Permission Disabled screen:
image

### Permission Denied screen:
image

_**Note:** This is placeholder text. Would change it soon :) Would love some ideas on what text to put in the screens above._

There is still a lot of work to do here.
I guess some more informative text and something like a phone notification to ask the user to grant/enable permission?

**Comment by rtsisyk** [comment]
Folks, what is the current status here?

**Comment by Jean-BaptisteC** [comment]
Can be closed, permissions screen has already been implemented.

**Pull request closed without merging**
