### PR TITLE
Added Lithuanian strings to strings.txt

### PR DESCRIPTION
**Pull request by ErnestasKaralius**

### CODE REVIEW

**Comment by biodranik** [comment]
I have manually cleaned up the strings. Please review if there is anything missing or wrong.

@vng can you please double-check that all special strings with %@ %d %s etc are correct?

**Comment by biodranik** [comment]
@ErnestasKaralius please note that we are sorting strings by alphabet, with `en` language being the first one. You can translate other strings files, but please take the latest version of them from our master branch (you may sync your fork with Organic Maps, or delete the fork and create it again if you are not familiar how to sync it).

**Comment by vng** [comment]
LGTM. Why do we have %@ and %s at the same time? What is the difference?

**Comment by biodranik** [comment]
> LGTM. Why do we have %@ and %s at the same time? What is the difference?

That's a complex story, will describe it in another PR.

**Review by biodranik — APPROVED** [review]

**Comment by biodranik** [comment]
@ErnestasKaralius Thank you! Please check other files that should be translated. After it's done, we can enable the translation.

**Pull request merged**
