### PR TITLE
Add Water, RV Facilities and Recyling search categories

### PR DESCRIPTION
**Pull request by pastk**
Closes: #1921, #1621

I didn't add iOS icons yet - please help if you know an easy way to convert from android vector drawables to iOS png resources.

### CODE REVIEW

**Comment by pastk** [comment]
Screenshot_1643285951

Screenshot_1643286019

**Comment by pastk** [comment]
Unfortunately "Recycling" search category doesn't show suggestions like "recycling of ..." (see https://github.com/organicmaps/organicmaps/pull/1922#issuecomment-1019915943).

That's because the search automatically adds a trailing space, so it becomes "Recycling " and hence doesn't match the terms defined in categories.txt (even though they contain the space, e.g. "recycling of batteries").

**Comment by not-available-username** [comment]
> > I didn't add iOS icons yet - please help if you know an easy way to convert from android vector drawables to iOS png resources.
> 
> @not-available-username maybe you can help with the icons here, please, if you have the experience?

what icons do you need?

**Comment by pastk** [comment]
> > > I didn't add iOS icons yet - please help if you know an easy way to convert from android vector drawables to iOS png resources.
> > 
> > 
> > @not-available-username maybe you can help with the icons here, please, if you have the experience?
> 
> what icons do you need?

The icons are created already, check commits in this PR, e.g. an icon for recycling category [android/res/drawable/ic_category_recycling.xml](https://github.com/organicmaps/organicmaps/pull/1954/files#diff-40f9721b0ed2b5e883d87a757852165d4713039d259bbc3605296cab6bafb5d8).

Now we need to somehow convert them into iOS format like in https://github.com/organicmaps/organicmaps/tree/master/iphone/Maps/Images.xcassets/Search/Categories/ic_entertainment_light.imageset

I've tried a few android vector drawable to svg/png converters, but all of them failed to convert the icons properly (they don't support the outer filled circle of the icon).

**Comment by not-available-username** [comment]
> > > > I didn't add iOS icons yet - please help if you know an easy way to convert from android vector drawables to iOS png resources.
> > > 
> > > 
> > > @not-available-username maybe you can help with the icons here, please, if you have the experience?
> > 
> > 
> > what icons do you need?
> 
> The icons are created already, check commits in this PR, e.g. an icon for recycling category [android/res/drawable/ic_category_recycling.xml](https://github.com/organicmaps/organicmaps/pull/1954/files#diff-40f9721b0ed2b5e883d87a757852165d4713039d259bbc3605296cab6bafb5d8).
> 
> Now we need to somehow convert them into iOS format like in https://github.com/organicmaps/organicmaps/tree/master/iphone/Maps/Images.xcassets/Search/Categories/ic_entertainment_light.imageset
> 
> I've tried a few android vector drawable to svg/png converters, but all of them failed to convert the icons properly (they don't support the outer filled circle of the icon).

Since I'm not very familiar with github and software dev in general, I ask if you can post here a wetrasfer link with all the svg that needs to be converted into png. Or the icons are in another format and need to be converted in svg first?

**Comment by pastk** [comment]
Yeap they're not svg, but an android-specific "vector drawable" format and I was unable to convert them to svg so far...

**Comment by biodranik** [comment]
> Yeap they're not svg, but an android-specific "vector drawable" format and I was unable to convert them to svg so far...

You may try https://shapeshifter.design/

**Comment by biodranik** [comment]
> That's because the search automatically adds a trailing space, so it becomes "Recycling " and hence doesn't match the terms defined in categories.txt (even though they contain the space, e.g. "recycling of batteries").

@vng I think suggestions with spaces should be displayed in this case.

**Comment by vng** [comment]
Well, we append space specially to avoid prefix match from categories list. Also, we specially advise suggestions only for prefix match. I think we can make an exception for "Recycling".

**Comment by biodranik** [comment]
There are some other categories terms with spaces. Will they work?

**Comment by pastk** [comment]
> > Yeap they're not svg, but an android-specific "vector drawable" format and I was unable to convert them to svg so far...
> 
> You may try https://shapeshifter.design/

Nope, doesn't work. All of the converters I tried don't support `<shape>` element.
I'll have to re-do the icons for iOS in inkscape I guess.

**Comment by pastk** [comment]
> Well, we append space specially to avoid prefix match from categories list. Also, we specially advise suggestions only for prefix match. I think we can make an exception for "Recycling".

Hmm, I thought a space was added for user convenience to be able to add/type something to the search string faster.

Do you recall any cases when avoiding prefix match was necessary?
I just went over most of our search categories and deleted the trailing space - no change in search output at all, except "Shopping" where a "shopping mall" suggestion popped up (which is fine and legit to my mind).

TBH I see no point of "muffling" search suggestions this way.

I suggest let's keep the trailing space (for user's convenience), but strip the search term internally before looking for matches.
What do you think?
Could you point me to the code where it could be changed?

**Comment by pastk** [comment]
I've also updated the Pharmacy search icon, it matches the ones used in iOS and on the map now
Screenshot_1643362202

**Comment by not-available-username** [comment]
> > > Yeap they're not svg, but an android-specific "vector drawable" format and I was unable to convert them to svg so far...
> > 
> > 
> > You may try https://shapeshifter.design/
> 
> Nope, doesn't work. All of the converters I tried don't support `<shape>` element. I'll have to re-do the icons for iOS in inkscape I guess.

Sorry but I can't help, I'm not familiar with xml vector drawables

**Comment by pastk** [comment]
For the record:
there was code in `skin_generator_tool` to convert source svg search icons into png of different sizes (as required by iOS).
We might consider restoring it if we need it later.
Ref commits: a2b5bb80468f80100caa80ee54c56669c8cddda3 and b10124479aa9bd0051444794ab0888b8daea8177

**Comment by pastk** [comment]
> I've also updated the Pharmacy search icon, it matches the ones used in iOS and on the map now Screenshot_1643362202

@biodranik if the icons look good enough then I'll make iOS versions for them, I understand I need to put them into `iphone/Maps/Images.xcassets/Search/Categories/` and `iphone/Maps/Images.xcassets/Spotlight/`

**Comment by biodranik** [comment]
Svg to png is easy, xml to svg is more complicated. 

On iOS you may need to also add these icons into the project file by analogy with others.

**Comment by pastk** [comment]
PTAL

**Review by biodranik — APPROVED** [review]

**Comment by vng** [comment]
А расскажите мне почему search-icons/svg стали obsolete?

**Pull request merged**
