### PR TITLE
[strings] Italian translations and Dutch translation improvements from #3635

### PR DESCRIPTION
**Pull request by hiddewie**
PR with content of https://github.com/organicmaps/organicmaps/issues/3635

Fixes https://github.com/organicmaps/organicmaps/issues/3635

@501Ghost

### CODE REVIEW

**Review by vng — APPROVED** [review]
Please, rebase on latest master.

**Comment by hiddewie** [comment]
@vng  Thanks for the review, rebase is done.

**Review by rtsisyk — APPROVED** [review]

**Comment by vng** [comment]
Something went wrong here. You did an additional useless "Merge commit". And conflict is still present.
Please, make a valid rebase here.

**Comment by hiddewie** [comment]
Ah I see something got merged before rebasing. There is a single signed commit now, and the conflict is gone. Hopefully this is OK.

**Pull request merged**
