### PR TITLE
[android] Fix NPE in MwmActivity.showStartPointNotice()

### LINKED ISSUE #6628: [android] NullPointerException at app.organicmaps.MwmActivity.showStartPointNotice
Xiaomi pine (Redmi 7A)
Android 10 (SDK 29)
Version: 23111718 (2023.11.17-18-Google)

```
Exception java.lang.NullPointerException:
  at java.util.Objects.requireNonNull (Objects.java:203)
  at app.organicmaps.MwmActivity.showStartPointNotice (MwmActivity.java:1680)
  at app.organicmaps.MwmActivity.onRoutingStart (MwmActivity.java:2055)
  at app.organicmaps.routing.RoutingBottomMenuController.lambda$setStartButton$0 (RoutingBottomMenuController.java:288)
  at android.view.View.performClick (View.java:7184)
  at android.view.View.performClickInternal (View.java:7161)
  at android.view.View.access$3500 (View.java:818)
  at android.view.View$PerformClick.run (View.java:27677)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:223)
  at android.app.ActivityThread.main (ActivityThread.java:7562)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:539)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:950)
```

UI inconsistency bug uncovered by 921cb80a20c963f6d46490e6ad3012014488fd4c.
The route button was displayed without the start point selected.

https://github.com/organicmaps/organicmaps/blob/add2242230fae973d7d12e95e55edd98d256fdbf/android/app/src/main/java/app/organicmaps/MwmActivity.java#L1670-L1677

https://github.com/organicmaps/organicmaps/blob/add2242230fae973d7d12e95e55edd98d256fdbf/android/app/src/main/java/app/organicmaps/MwmActivity.java#L1341-L1379

Need to find a way how to reproduce this issue.

### PR DESCRIPTION
**Pull request by rtsisyk**
Reproduces when the back and start buttons are pressed at the same time.

Fixes #6628

### CODE REVIEW

**Comment by Jean-BaptisteC** [comment]
It's harder to generate a crash, but I can with new stacktrace :)

```
FATAL EXCEPTION: main
Process: app.organicmaps.debug, PID: 11988
android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{e1e8fec u0 app.organicmaps.debug/app.organicmaps.routing.NavigationService}
at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2109)
at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2080)
at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2374)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.app.ActivityThread.main(ActivityThread.java:8194)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by biodranik** [comment]
@Jean-BaptisteC what did you do?

**Comment by Jean-BaptisteC** [comment]
Same thing press back button and start button in same time.

**Review by vng — APPROVED** [review]

**Review by biodranik — CHANGES_REQUESTED** [review]
@vng @rtsisyk if I got @Jean-BaptisteC correctly, the crash is still reproducible, it should be fixed first.

**Review by Jean-BaptisteC — APPROVED** [review]
✅ Pixel 6 - Android 14

**Pull request merged**
