### PR TITLE
[android] Disclaimer fix

### PR DESCRIPTION
**Pull request by AndrewShkrob**
Fixes bug in https://github.com/organicmaps/organicmaps/pull/4987

### CODE REVIEW

**Comment by biodranik** [comment]
In the merged PR there was a `fromApi` flag which is not used now. Should it also be fixed? Routes built from https://omaps.app/api should work for a hot and for a cold start of OM.

**Review by Jean-BaptisteC — APPROVED** [review]
✅ Pixel 6 - Android 13

Thanks :)

**Comment by biodranik** [comment]
@Jean-BaptisteC does it work also for API calls?

**Comment by Jean-BaptisteC** [comment]
Works properly with API call, i have try with this link https://omaps.app/route?v=1&sll=1.337412,103.696997&saddr=Start%20Point&dll=1.343107,103.732609&daddr=EndPoint&type=transit

**Review by biodranik — APPROVED** [review]
Thanks!

**Review by vng — APPROVED** [review]

**Pull request merged**
