### PR TITLE
[strings] Improved parking translations

### PR DESCRIPTION
**Pull request by dvdmrtnz**
Improved parking translations

### CODE REVIEW

**Review by starsep — APPROVED** [review]

**Review by LaoshuBaby — APPROVED** [review]

**Review by MetehanOzyurek — APPROVED** [review]

**Review by arnaudvergnet — APPROVED** [review]

**Review by csidirop — APPROVED** [review]
Greek looks correct to me

**Review by matheusgomesms — APPROVED** [review]
I've corrected some Portuguese (PT and PT-BR) directly on the files. Now seems good to me.

**Comment by dvdmrtnz** [comment]
> I've corrected some Portuguese (PT and PT-BR) directly on the files. Now seems good to me.

I've squashed your commits into mine for cleaner history

**Review by jimcarst — APPROVED** [review]

**Review by biodranik — COMMENTED** [review]
Please squash commits and it's good to merge.

**Comment by dvdmrtnz** [comment]
Squashed

**Review by biodranik — APPROVED** [review]
That was fast! Thanks to everyone for your contributions!

**Pull request merged**
