### PR TITLE
Show disabled parking space

### PR DESCRIPTION
**Pull request by dvdmrtnz**
This PR adds an icon for the disabled parking spaces. There's nearly 100k places tagged with [parking_space=disabled](https://taginfo.openstreetmap.org/tags/parking_space=disabled) in OSM. 

Source for the icon is [Material Icons](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Aaccessible%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048).

### CODE REVIEW

**Comment by endim8** [comment]
How does it look here? 
https://www.openstreetmap.org/?mlat=51.48873&mlon=0.01606#map=18/51.48873/0.01606
`amenity=parking_space`+`parking_space=disabled` is meant to be used for singular parking spaces, so it might result in a mess of icons similar to when individual parking spaces had icons (see https://github.com/organicmaps/organicmaps/issues/684).
(i would test it myself, but it takes a while to generate a map file)

**Comment by dvdmrtnz** [comment]
> How does it look here? https://www.openstreetmap.org/?mlat=51.48873&mlon=0.01606#map=18/51.48873/0.01606 `amenity=parking_space`+`parking_space=disabled` is meant to be used for singular parking spaces, so it might result in a mess of icons similar to when individual parking spaces had icons (see #684).

This is how it looks there:

**Comment by dvdmrtnz** [comment]
We could also make them less prominent by changing background to white:



Or not showing any background at all:

**Comment by biodranik** [comment]
I like the variant without a background! Does it also work well in the night mode?

**Comment by dvdmrtnz** [comment]
Here it is in dark mode:

**Review by biodranik — APPROVED** [review]
@vng ?

**Review by vng — APPROVED** [review]

**Pull request merged**
