### PR TITLE
[styles] rendering for waterway=fish_pass

### PR DESCRIPTION
**Pull request by map-per**
Added support for waterway=fish_pass. Rendering is the same as for ditch and drain.

#### Open Questions:
- should name be used as well?
- should rendering be like ditch and drain or rather like stream?
- (vehicle style not implemented yet)

Thanks for the review!

#### Example rendering:
(before and after, https://www.openstreetmap.org/way/102490507)
Screenshot_20230514_160736
Screenshot_20230514_191842

### CODE REVIEW

**Comment by map-per** [comment]
Took a look at a waterway=drain on my phone (whith a higher resolution) and discovered that a dashed pattern is used... 
A dashed pattern doesn't really make sense so I'd use the same rendering as for stream.

**Comment by map-per** [comment]
Ok, changed the rendering to match stream and canal. Added a label for the name and excluded waterways in tunnels. Added a type translation to `types_strings.txt` and a search term to `categories.txt`. 
No changes to the vehicle style, fish_passes are not needed there (just like stream and canal).

Screenshot_20230516_232301
(Tunnels not shown https://www.openstreetmap.org/way/377038998)

Screenshot_20230516_230439
(name is shown https://www.openstreetmap.org/way/322673529)

**Comment by vng** [comment]
Good, thanks! Some comments:
- we have a rule in mapcss_mapping: lower number -> more frequent type. Please, move fish_pass somewhere around 500.
- categories.txt are used for "commonly" used search terms. Draines, ditches and fish passes are not of them. Please, remove it.
- make separate commites: ```[styles] Regenerated``` and ```[strings] Regenerated```
- do rebase on latest master

**Review by vng — APPROVED** [review]

**Comment by map-per** [comment]
I hadn't finished the styles and string regeneration. Added both in #5215.
Doing the rebase took a bit longer as git didn't quite do what I wanted. And generating new Map data for final testing took 5 hours as well.

**Pull request merged**
