### PR TITLE
[strings] Fixed PT translation

### PR DESCRIPTION
**Pull request by matheusgomesms**
Fixed arts center and lottery tickets strings in PT and PT-BR.

Signed-off-by: Matheus Gomes <86851490+matheusgomesms@users.noreply.github.com>

### CODE REVIEW

**Comment by matheusgomesms** [comment]
I am the only member in those groups, but thanks anyway! :P

Ah, I don't know how to regenerate the strings, so any maintainer could please do that?

**Review by biodranik — APPROVED** [review]
Thanks! You can use `tools/unix/generate_localizations.sh` to update translations. Changing categories doesn't require regen.

**Comment by matheusgomesms** [comment]
@biodranik This still doesn't show updated in the latest version. Is there anything else to be done in order to show in OM?

**Comment by biodranik** [comment]
@matheusgomesms categories.txt are for search queries, values there should match values in translation files. What exactly are you checking and what is not working?

**Comment by matheusgomesms** [comment]
Ah, I see, I didn't update the translation in types_strings.txt. Doing that in a PR now, thanks @biodranik!

**Pull request merged**
