### PR TITLE
Serbian strings corrections

### PR DESCRIPTION
**Pull request by dobridabar**
Intensively tested Serbian translation of OM in the past couple of days, and fixed all errors that I was able to found.

### CODE REVIEW

**Comment by dobridabar** [comment]
CC: @ZeljkoBG, @zyphlar

**Review by zyphlar — APPROVED** [review]

**Comment by ZeljkoBG** [comment]
@dobridabar you and I missed it. I think so
Станица за пуњење...  - there are several places
to
Станица за напајање

**Comment by pastk** [comment]
@dobridabar is it good to be merged or you'll add some changes according to @ZeljkoBG 's comment above?

**Comment by ZeljkoBG** [comment]
> @dobridabar is it good to be merged or you'll add some changes according to @ZeljkoBG 's comment above?

I just changed. Can you check if I did it right? That is, do you see changes?

**Comment by zyphlar** [comment]
> I just changed. Can you check if I did it right? That is, do you see changes? 

@ZeljkoBG if you click the Edit button and make changes, they are stored on a branch in your copy of organicmaps, like this:
https://github.com/ZeljkoBG/organicmaps/commit/f0018286fe33e50e707dec5db3e658652d0ccfc2

We won't automatically see it especially if you didn't make the initial pull request and aren't updating the same branch name (in this case pull-13). So if you make edits you need to pay attention to where they are saved and visible and tell us.

It might help if you look at GitHub how-to guides for making pull requests. Otherwise, just make comments and mention @dobridabar with incorrect and correct versions of strings so he can make changes. Uploading complete changed files is hard because five seconds later someone else could change that file too (like they did with Finnish earlier) and then it's a mess.

**Comment by ZeljkoBG** [comment]
> > I just changed. Can you check if I did it right? That is, do you see changes?
> 
> @ZeljkoBG if you click the Edit button and make changes, they are stored on a branch in your copy of organicmaps, like this: [ZeljkoBG@f001828](https://github.com/ZeljkoBG/organicmaps/commit/f0018286fe33e50e707dec5db3e658652d0ccfc2)
> 
> We won't automatically see it especially if you didn't make the initial pull request and aren't updating the same branch name (in this case pull-13). So if you make edits you need to pay attention to where they are saved and visible and tell us.
> 
> It might help if you look at GitHub how-to guides for making pull requests. Otherwise, just make comments and mention @dobridabar with incorrect and correct versions of strings so he can make changes. Uploading complete changed files is hard because five seconds later someone else could change that file too (like they did with Finnish earlier) and then it's a mess.

Good thing I didn't break anything. I wonder what the devil made me change, when I don't know.

It's no use reading the instructions, it's not for me. From now on I will write every irregularity in my topic and ask you to do it for me.

**Comment by dobridabar** [comment]
> @dobridabar you and I missed it. I think so Станица за пуњење... - there are several places (бисикла, Станица за пуњење ЕВ (електрична возила),... to Станица за напајање

1. "Станица за напајање" is "Power station"
2. "Станица за пуњење" is "Charging station"

So I thinkg that 1. is correct translation.


> If I'm right "Подзид" the western-Serbian dialect. The Croats call it that. I think it was right "Подзида". That's what Google says. Or at least "Потпорни зид"

Ok, I changed it to "Потпорни зид", because I cannot find any references to word "подзида".

If there are no more comments, @pastk, feel free to merge.

**Comment by ZeljkoBG** [comment]
> > @dobridabar you and I missed it. I think so Станица за пуњење... - there are several places (бисикла, Станица за пуњење ЕВ (електрична возила),... to Станица за напајање
> 
> 1. "Станица за напајање" is "Power station"
> 2. "Станица за пуњење" is "Charging station"
> 
> So I thinkg that 1. is correct translation.
> 
> > If I'm right "Подзид" the western-Serbian dialect. The Croats call it that. I think it was right "Подзида". That's what Google says. Or at least "Потпорни зид"
> 
> Ok, I changed it to "Потпорни зид", because I cannot find any references to word "подзида".
> 
> If there are no more comments, @pastk, feel free to merge.

@dobridabar thanks


"references to word "подзида"" - https://www.google.com/search?q=Podzida&sca_esv=9029f727d4831701&sxsrf=ADLYWII4WGVUOkqPGKOSv5-2wtSXYtyjzA%3A1735032628710&ei=NH9qZ4iCK8r-7_UPsfiLgAM&ved=0ahUKEwiI7IecjMCKAxVK_7sIHTH8AjAQ4dUDCBA&uact=5&oq=Podzida&gs_lp=Egxnd3Mtd2l6LXNlcnAiB1BvZHppZGEyBhAAGAcYHjIFEAAYgAQyBRAAGIAEMgYQABgHGB4yBRAAGIAEMgYQABgHGB4yBhAAGAcYHjIFEAAYgAQyBRAAGIAEMgcQABiABBgKSJUxUMULWMULcAF4AJABAJgBXaABXaoBATG4AQPIAQD4AQGYAgKgAmrCAg0QABiABBiwAxhDGIoFwgIJEAAYsAMYBxgewgIKEAAYgAQYsAMYCsICCxAAGLADGAcYChgewgIHEAAYsAMYHpgDAIgGAZAGCpIHATKgB_4E&sclient=gws-wiz-serp
and
https://www.kontekst.io/srpski/podzida

**Pull request merged**
