### PR TITLE
[styles] Fix svg code of subway-lyon

### PR DESCRIPTION
**Pull request by dvdmrtnz**
`subway-lyon-m.svg` and `subway-lyon-s.svg`were missing the `xmlns` tag in the svg. This prevented the thumbnail from appearing in Finder in macOS and also prevented the wiki from showing the icon correctly.

### CODE REVIEW

**Review by biodranik — APPROVED** [review]
Thanks!

**Review by vng — COMMENTED** [review]
Please, check style-night symbols also.

Then I'll merge and regenerate the palette.

**Comment by dvdmrtnz** [comment]
> Please, check style-night symbols also.
> 
> Then I'll merge and regenerate the palette.

Fixed style-night

**Comment by RedAuburn** [comment]
> Then I'll merge and regenerate the palette.

There's no need to regenerate symbols, the actual svg hasn't changed & will generate identically :)

**Pull request merged**
