### PR TITLE
[android] Fix "If you select a node that has outdoor seating and then select something else it will incorrectly say it also has outdoor seating"

### LINKED ISSUE #9100: If you select a node that has outdoor seating and then select something else it will incorrectly say it also has outdoor seating
⚠ Have you searched for similar, already existing issues?
Yes, i found #9049 which also is about outdoor seating but it involves the editor and this bug is about displaying the property.

**Describe the issue**
If you click a node that has `outdoor_seating=yes` and then click a second node that doesn't have it and expand it then it looks like the second object has outdoor seating even though it doesn't.

**Steps to reproduce**
1. Find a node that has `outdoor_seating=yes` like [this ice cream shop](https://www.openstreetmap.org/node/1778361759) and another nearby poi that doesn't have it like [this clothes shop](https://www.openstreetmap.org/node/4850279044).
1. Scroll to them on the map
1. Make sure nothing is selected
1. Click the first node for the ice cream shop with outdoor seating but don't "expand it".
1. Click the second node for the clothes shop and expand it to view more info, check if it has outdoor seating.
1. Close the node.
1. Click the clothes shop again and expand it to check if it's different in any way.

**Expected behaviour**
You would expect the clothes shop info to be displayed and it is but it also shows "outdoors seating" which is incorrect, it's like it inherits the property of the last thing selected.

**Screenshots**

<details>
<summary>Click here to see the screenshots</summary>

lx5jeBiWST

</details>

**System information:**
 - Operating system and its version: Android 14 (API 34)
 - Organic Maps version: 2024.08.17-4-Google
 - Device Model: OnePlus8T (KB2003)

**Additional context**
None.

### PR DESCRIPTION
**Pull request by Arthur-GYT**
All is in the title ^^.

Close #9100

https://github.com/user-attachments/assets/bb28efbf-dff9-4972-95b0-d572ec67cb88

### CODE REVIEW

**Review by biodranik — APPROVED** [review]
Thanks!

**Comment by Aerondyyyy** [comment]
Thanks for the quick response! 👍 

I looked at the video and the steps taken won't produce the bug for me right now on current version. Maybe these changes fixed the bug video doesn't show it.

What the video shows:
1. Click the ice cream shop
1. Expand the ice cream shop by dragging it up
1. Minimize or close the ice cream shop
1. Click the clothes store
1. Expand the clothes store by drag it up

Result on 2024.08.17-4-Google:
No outdoor seating for the clothes store.

How you reproduce the bug:
1. Click the ice cream shop **but don't drag it up**
1. Click the clothes store
1. Expand the clothes store by dragging it up

Result on 2024.08.17-4-Google:
Outdoor seating for the clothes store.

Again, maybe this change fixed it but the video doesn't show it, I just think it's worth double checking that the three steps won't produce it.

**Comment by Arthur-GYT** [comment]
@Aerondyyyy When I try to reproduce, I have this

https://github.com/user-attachments/assets/86562197-44e2-4a38-8fd0-436f98a09ecf

**Comment by Aerondyyyy** [comment]
Perfect, thanks for double checking! 👍

**Pull request merged**
