### PR TITLE
Display major roads earlier on z6 (world overview map)

### PR DESCRIPTION
**Pull request by pastk**
In less populous areas its hard to get a road network overview for longer trips.
Sometimes its even impossible to see connections to the nearest displayed/labeled city.
(especially common in areas further from the equator, see https://github.com/organicmaps/organicmaps/issues/5427)

Screenshot_20240610-142020

Making major roads (motorway, trunk) display one zoom level earlier helps a lot:
Screenshot_20240610-142035

Screenshot_20240610-142317

On z6 I've made them much more subtle than on z7. This way they're traceable / useful in "empty" areas still and at the same time they don't stand out too much in dense areas:
Screenshot_20240610-142439

E.g. compare to z7 where roads are much more prominent:
Screenshot_20240610-142534

The size of the World map doesn't increase (+5Kb only) as no additional geometry bucket is introduced.

To test it locally:
- switch to PR's branch
- build generator_tool `tools/unix/build_omim.sh -r generator_tool`
- run `../omim-build-release/generator_tool --generate_index=true --data_path=data/ --output="World"` to update map's visibility index

Related to:
- #3460
- #5363

### CODE REVIEW

**Comment by biodranik** [comment]
The benefit of empty map areas is clear. But the polluted map in dense areas looks less readable (region names/cities are more important here than roads).

So again we're blocked from doing it perfectly by the absent option to use different styling in dense/non-dense areas.

**Comment by pastk** [comment]
> But the polluted map in dense areas looks less readable (region names/cities are more important here than roads).

IMHO added roads are subtle enough to not affect legibility of captions in a significant way.
Moreover such dense regions (as China above) are quite rare. E.g. in the most of Western Europe added z6 roads look helpful and not cluttered.

@organicmaps/styles WDYT?

Its better to test on a real device (make sure you test the main style, not the outdoors). Road lines in screenshots above may look thick when viewed via a desktop screen (which is usually lower dpi than vs=3 screenshots above).

**Review by euf — APPROVED** [review]
This looks like an improvement to me 👍 

Dynamic styling, as @biodranik said, would be even better someday, but for now it's already better

**Review by vng — APPROVED** [review]
- I like roads on z6
- drules_proto_design.bin - ??

Please, make a correct "Regenerated" commit.

**Comment by pastk** [comment]
> Please, make a correct "Regenerated" commit.

Fixed!

**Pull request merged**
