### PR TITLE
Add ferry routes to the World map 

### PR DESCRIPTION
**Pull request by pastk**
Test small World generation:
(note there is a small line in the lake also)
world_ferries

The search index didn't grow.

### CODE REVIEW

**Comment by pastk** [comment]
@vng why ferry routes are not in
https://github.com/organicmaps/organicmaps/blob/c8986f395bbd4169749b9082af38f57276ac044f/generator/world_roads_builder/world_roads_builder_tool/world_roads_builder_tool.cpp#L51-L53
?

I understand its used to signal about missing mwms for routing?

**Review by vng — APPROVED** [review]

**Review by biodranik — APPROVED** [review]
Maybe too small lines (too short ones, with a small rect) should be removed.

@vng won't it break the routing algo? Does it need an additional ferry filtering for features from the world map?

**Comment by biodranik** [comment]
A separate issue/important thing: can we draw a ferry route name or reference (whatever is useful in the OSM)? What are other maps drawing on such routes?

**Comment by pastk** [comment]
> Maybe too small lines (too short ones, with a small rect) should be removed.
> 

There is a filter for world map that discards too small lines (maybe too many of them even :)).

**Comment by pastk** [comment]
> A separate issue/important thing: can we draw a ferry route name or reference (whatever is useful in the OSM)? What are other maps drawing on such routes?

Looks like only the name is relevant. Its being displayed in country maps.

**Comment by pastk** [comment]
Looks good overall!
Adds ~300Kb.

z9
image

In some places could be dense.
z7
image

In some cases not so useful. Perhaps the min length threshold should be more strict for ferries compared to highways. And somehow synchronized with water area threshold.
z9
image

Connecting the broken rivers! :)
image

**Comment by biodranik** [comment]
How to fix broken rivers?

**Comment by pastk** [comment]
> How to fix broken rivers?

The easy way is just to change the area threshold to include smaller water polygons.

A proper way... Maybe devise a list of important rivers first or invent some metric like length and/or area surface..

**Comment by pastk** [comment]
Or maybe integrate https://www.naturalearthdata.com/downloads/10m-physical-vectors/10m-rivers-lake-centerlines/

**Comment by biodranik** [comment]
No external data should be necessary, please avoid such solutions. There is already everything complete in OSM. We can likely merge and simplify _in beautiful way_ all lakes and rivers, to make them look better than now. Can you please create an issue to track it, with screenshots from here?

**Pull request merged**
