### PR TITLE
Render shared paths with an underline, change cycleways color

### LINKED ISSUE #5289: Cycleways have poor visibility if they go through a forest because of the color. (color blind?)
**Describe the issue**
I'm a bit colorblind so it might be a colorblind only thing but if you look at any `highway=cycleway` on the map that goes through a `landuse=forest` then it's really hard to make out, i can sorta see it but it doesn't stand out for sure. It might be perfectly fine for people with normal color vision but I would guess that it's at least less visible than an `highway=path` because that's a white dotted thicker line, even `highway=footway` is thicker and dotted and the color is less of an issue (at least for me)

Using night mode it's less of an issue but still the line is very thin.

The color or the lack of contrast it has is the main problem for me, it's way to similar to the green background

I'm really curious if everyone agrees that cycleways are at least a bit harder to make out in a forest than most other types highways. Post your thoughts below.

**Steps to reproduce**
1. Make sure you got the night mode disabled
2. Go to any cycleway that goes through a forest like this one for example: https://omaps.app/w4nByZrznI/Forest
3. Look at the cycleway and see if it's hard to see compared to a lets say a path or a footpath going through a forest (there is one to the west in the example link.

**Expected behavior**
The cycleway should be stand out no matter the background and maybe even should have a thicker line. The contrast is just the exact same which you can see if you look at the app using the grayscale filter on your phone, the cycleway just becomes invisible.

**Screenshots**

Full sized screenshot: https://github.com/organicmaps/organicmaps/assets/73029732/4dd0d8fd-657f-43f1-ad71-2fc75c070e71

**System information:**
 - Operating system and its version: Android 13
 - Organic Maps version: 2023.06.04-13-Google (but it's been like this for a while)
 - Device Model: OnePlus 8T (KB2003)

**Additional context**
If you're designing anything you can try to test it using the grayscale setting [on your PC](https://support.microsoft.com/en-us/windows/use-color-filters-in-windows-43893e44-b8b3-2e27-1a29-b0c15ef0e5ce) or [your phone](https://support.google.com/accessibility/android/answer/11183305?hl=en#zippy=%2Cuse-color-correction) and if you can still use the app in some way then it should be fine. I'm not saying it has be absolutely usable in every way without color but it should at at least be somewhat usable.
Example: Even if you can't tell different ways apart in grayscale you should **at least see that there are ways there**, the rest you can find out by holding your finger on the way.

### PR DESCRIPTION
**Pull request by pastk**
Shared paths: add a cycling underline.

- made shared paths's dashes more sparse so that cycle underline is more visible
- change cycle lines color to blue
- use a tad darker blue color for outdoors style
- tuned cycle lines widths

Depends on #7878
- closes https://github.com/organicmaps/organicmaps/issues/5289
- closes https://github.com/organicmaps/organicmaps/pull/7255

### CODE REVIEW

**Comment by pastk** [comment]
shared and dedicated
image

z13 dedicated
image

z17 shared unpaved
image

Note that we might have a distinct color for paved vs unpaved dedicated cycleways too - similar to footways vs paths.

**Comment by pastk** [comment]
The new color is much more contrast against all backgrounds compared to the current violet. And hopefully is distinct enough from the rivers :)
Dark green could be another option.

([table source](https://contrast-grid.eightshapes.com/?version=1.1.0&background-colors=E3E1D2%2C%20%40background%0D%0AEDE8D6%2C%20%40pedestrian_area%0D%0ACFD5A8%2C%20%40green0%0D%0AAABF65%2C%20%40forest%0D%0AE4DEAD%2C%20%40farmland%0D%0A8BD3E0%2C%20%40water%0D%0A36B0BF%2C%20%40river%0D%0A&foreground-colors=%23FF87AD%2C%20%40cycleway%20current%0D%0A%23534DEB%2C%20proposed%0D%0A%235654FF%2C%20proposed%20by%20will%0D%0A%23548004%2C%20dark%20green%0D%0A&es-color-form__tile-size=compact&es-color-form__show-contrast=aaa&es-color-form__show-contrast=aa&es-color-form__show-contrast=aa18&es-color-form__show-contrast=dnp))
image

**Comment by pastk** [comment]
- made shared paths's dashes more sparse so that cycle underline is more visible
- tuned cycle lines widths
- use a tad darker color for outdoors

**Comment by pastk** [comment]
shared-urban-z13

shared-urban-z16

shared-od-z12

**Review by vng — APPROVED** [review]

**Comment by pastk** [comment]
Another comparison with the previous color:
cycleways-zurich-z13

**Comment by map-per** [comment]
Tested the PR with the new map data from #8009: Sometimes the blue line is drawn on top of the white line (e.g. https://www.openstreetmap.org/way/1158116910). Looks like it has something to do with `segregated`.

**Comment by pastk** [comment]
> Tested the PR with the new map data from #8009: Sometimes the blue line is drawn on top of the white line (e.g. https://www.openstreetmap.org/way/1158116910). Looks like it has something to do with `segregated`.

Yeap its as intended:
- dedicated cycleways are solid blue lines
- segregated cycleways + footways are solid blue lines over white dashes
- non-segregated (shared) cycleways + footways are blue lines under white dashes

It'd be better to render "segregated cycleways + footways" somehow different, e.g. a solid blue line along white dashes, but we don't have this capability ATM, see #7952

**Comment by biodranik** [comment]
It's too colorful for the main style, let's move these changes to the outdoor style.

**Comment by map-per** [comment]
Distinguishing paths for cyclists and not for cyclists in the main style is good. Especially for cycling in cities, as the the outdoor style is not designed for dense areas.

But especially at zoom 13 dedicated cycleways and segregated cycleways + footways do are very prominent.

I would either
 - drop the distinction of `segregated` (this info is not really important for cycling) and always draw the blue line below the white line. This way the paths won't be that prominent.
 
or

 - fine tune the the prominence on lower zoom levels e.g. with higher opacity

**Comment by biodranik** [comment]
Please don't turn the clean main style into a second outdoor style but for cyclists.

**Comment by map-per** [comment]
I didn't fully figure out what you changed for cycleways, but it looks good now. The blue lines are not too prominent any more. 👍 

| A few days ago | now|
|--------|--------|
| signal-2024-04-30-102450_002| signal-2024-04-30-102450_003|

**Comment by pastk** [comment]
@map-per your "now" screenshot looks strange - the most of cycleways are just gone there :/ I guess it has a different map data version, e.g. from a previous release as most of those cycleways seem to be `highway=path segregated=yes` and were not displayed at low zooms

In the current beta it should be like (z14):
image

Likely we'll reduce cycleways opacity a little on z13-14 before the release.

**Comment by pastk** [comment]
z14 from the last release for comparison
(paths are not displayed on z13)

**Comment by pastk** [comment]
Stats:
- ~100k of `highway=path segregated=yes` are converted into cycleways and hence will be visible from z13
- ~1M (out of 1.7M!) of non-segregated `highway=cycleway foot=yes/designated` are converted into "shared" `footway-bicycle` and hence will disappear on z13-14

So overall number of cycleways visible on z13-14 will significantly reduce, but in some regions like Munchen it could look vice versa.

**Comment by biodranik** [comment]
Display them prominently in Outdoors, and leave not prominent at all in the main style?

**Comment by map-per** [comment]
> your "now" screenshot looks strange - the most of cycleways are just gone there :/ I guess it has a different map data version, e.g. from a previous release as most of those cycleways seem to be highway=path segregated=yes and were not displayed at low zooms

Oh, yes, that was the old map data from March. I overlooked that the new map data isn't merged into master yet.

**Comment by elbotho** [comment]
@pastk thank you so much for adding this!
I was wishing for this feature since I first opened the app 💚

**Pull request merged**
