### PR TITLE
Added link to the code of conduct in README.MD

### PR DESCRIPTION
**Pull request by ramanjitsingh-hub**
#4609 I hereby certify that I am the author of the commit and that I have the right to submit it under the open source license indicated in the file; or, if not an author, I represent that my employer or client has authorized me to contribute it under the same license.

### CODE REVIEW

**Comment by ramanjitsingh-hub** [comment]
I have closed the previous pull request as I was unable to sign the commits with DCO and in a result many redundant commits were committed in that

**Comment by biodranik** [comment]
Please DO NOT CLOSE PULL REQUESTS. Learn how to edit and amend your commits with `git commit --amend` and `git rebase -i master`, and update your pull request with `git push -f`

**Comment by matkoniecz** [comment]
likely intended to fix #4597

**Comment by ramanjitsingh-hub** [comment]
Will take care of it from next time 😊

**Review by biodranik — APPROVED** [review]
Thanks! You don't need to declare anything in the PR description, just add a DCO signature into the commit's message :)

**Pull request merged**
