### PR TITLE
[styles] Make isolines more dense

### PR DESCRIPTION
**Pull request by pastk**
As we're going to store more data in map files to increase isolines visibility for the outdoors style anyway,
why not use it to improve isolines display in the main style too?
	
This focuses not on raising overall visibility (i.e. isolines are appearing on z11 still), but on adding more lines density on existing zooms to make relief easier to read:
	
`isoline_step100` will appear on z12 now (was z13):
isolines_density_z12

And their captions on z14 (was z15):
isolines_density_z14

`isoline_step50` (used in 1/3 of mwms) will appear on z14 (was z15):
isolines_density_z14_step50

### CODE REVIEW

**Comment by biodranik** [comment]
What about the size of the data?

**Comment by pastk** [comment]
> What about the size of the data?

Its the same isolines data which is needed for the outdoors style, so size increase is same, see https://github.com/organicmaps/organicmaps/pull/4399
(actually a tad less, because here we don't increase visibility of `step_500` and `step_1000` isolines to z10)

**Review by biodranik — CHANGES_REQUESTED** [review]
@vng can we test it to see how big will be the size after the upcoming data update?

I don't think it's a good idea to merge it before other outdoor-related changes.

**Comment by pastk** [comment]
Rebased.

**Comment by pastk** [comment]
https://github.com/organicmaps/organicmaps/pull/5540 seems to help with isolines sizes greatly by discarding very similar geometries from geom2.
It makes raising isolines densities very "cheap" size-wise - e.g. on Macedonia its just 2% increase instead of 8.5%

**Comment by biodranik** [comment]
There are many map regions where isolines are disabled because of their large size. It would be great to focus on space savings only and enable isolines in such regions.
Increasing density won't help much, a refactoring is requires for the elevation.

**Comment by RedAuburn** [comment]
I would like to add that space isn't that precious on modern (and even most older) devices, and the current density of isolines is almost useless. A 20% increase in a 100MB MWM would IMO be fine if it makes isolines more useful

**Comment by biodranik** [comment]
Only some users are using isolines. The space could be ignored if downloading isolines would be separated from maps, so only those who really need it would download it. 

It should be refactored anyway.

**Comment by pastk** [comment]
> There are many map regions where isolines are disabled because of their large size. It would be great to focus on space savings only and enable isolines in such regions. 

Do you have an example of such a region?

The most of size increase of this PR comes from `isoline_step50` being added to geom2. Only 30% of mwms use this isoline step. And I think that the regions that has no isolines will not use this step anyway, as it looks like even including `step500` is too much for them.

So I think this PR won't make it any harder to enable isolines in regions that doesn't have it atm.

**Comment by vng** [comment]
Alaska, Chile_South, Kazakhstan_South, a lot ..
Check data/conf/isolines/countries-to-generate.json

Actually, I can run a tool to generate _normal_ (or high) isolines for all countries and may check what kind of files we will get.

**Comment by biodranik** [comment]
@vng it would be great to check the size without more dense isolines first, to have a clear base point.

**Comment by pastk** [comment]
> Alaska, Chile_South, Kazakhstan_South, a lot .. Check data/conf/isolines/countries-to-generate.json
> 

Yeap they don't even have a profile set.. Do you know how `countries-to-generate.json` was generated? A script or something.. I couldn't find such code.

**Comment by pastk** [comment]
> Actually, I can run a tool to generate _normal_ (or high) isolines for all countries and may check what kind of files we will get.

If the size was the reason to omit isolines for those countries then it would make more sense to generate a `poor` profile isolines for them first?

#5540 should nearly halve the size of `poor` isolines (as they're pre-simplified to z14 (=geom2), so naturally geom2 and geom3 are duplicate in this case). So chances are high we'll be able to add basic isolines to those regions.

**Review by vng — APPROVED** [review]

**Pull request merged**
