### PR TITLE
[tools] Use formal translations instead of informal for DeepL languages

### PR DESCRIPTION
**Pull request by biodranik**
Most of our translations are formal, let's keep it in sync.

### CODE REVIEW

**Comment by matheusgomesms** [comment]
Just a small comment: PT-BR got waaaay formal, language not used in any app (including OM). For PT is nice, they prefer more formal (3rd person, like _Sie_ in DE).

**Comment by biodranik** [comment]
@matheusgomesms  Changing pt-BR to informal would benefit BR users, right? We can do it. Translation script can be explicitly patched to get informal translations for specific languages.

**Comment by matheusgomesms** [comment]
> @matheusgomesms Changing pt-BR to informal would benefit BR users, right? We can do it. Translation script can be explicitly patched to get informal translations for specific languages.

That would be great, using the previous behavior (prefer_less) for PT-BR. For PT, the new formal way I believe it's better (but have to test more).

**Comment by matheusgomesms** [comment]
Let's see how it goes with PT in the next strings regen. I suppose PT-BR will remain the same due to last commit.

**Pull request merged**
