### PR TITLE
don't upload external_uri tag

### PR DESCRIPTION
**Pull request by RedAuburn**
hopefully fixes https://github.com/organicmaps/organicmaps/issues/6571 (testing now)

### CODE REVIEW

**Comment by RedAuburn** [comment]
nope, didn't work: https://www.openstreetmap.org/changeset/144059466

**Comment by RedAuburn** [comment]
closing as idk

**Comment by biodranik** [comment]
@vng

**Comment by biodranik** [comment]
@RedAuburn we'll fix it.

**Pull request closed without merging**
