### PR TITLE
[android] Fix navigation with NOT_FOLLOW_NO_POSITION

### LINKED ISSUE #5024: [android] Annoying "Navigation is available only from your current location" when location is disabled
**Steps to reproduce**
1. Disable Wi-Fi, disable Cellular Data, enable Location;
2. Get under a roof and away from the open sky and any windows;
3. Restart device, start the app, and wait 30 seconds until
  "Continue detecting your current location?" appears;
4. Tap "No"
5. Now start navigation...
6. "Navigation is available only from your current location" will appeal

Really simple use-case:

1. Go to elevator to the underground parking (=> location lost)
2. Accidentally press "No" button in "Continue detecting your current location?" dialog (=> mode=NOT_FOLLOW_NO_POSITION)
3. Start navigation in your car
4. Get misleading "Navigation is available only from your current location"  message

### PR DESCRIPTION
**Pull request by rtsisyk**
Remove annoying "Navigation is available only from your current location" and just start navigation by using the best available information.

Fixes #5024

### CODE REVIEW

**Review by biodranik — COMMENTED** [review]
@rtsisyk what happens if the current location is unknown?

**Comment by Jean-BaptisteC** [comment]
I'm not sure is a good idea, OM is not adapted in this case, check this screenshot, information about distance are missing because OM use localisation to determine distance

**Comment by rtsisyk** [comment]
> I'm not sure is a good idea, OM is not adapted in this case, check this screenshot, information about distance are missing because OM use localisation to determine distance 

> use localisation 

What do you mean by that? How to reproduce this issue?

**Comment by rtsisyk** [comment]
Unfortunately, this approach is not going to work until C++ routing core supports routes with "NULL" = "MY CURRENT POSITION". I want to start with the unknown location and set it when as GPS is received. Implementing this approach on the client side in Android will require significant overengineering and replication of the routing state machine in Java code.

**Pull request closed without merging**
