### PR TITLE
[categories] alt names for "recycling centre"

### PR DESCRIPTION
**Pull request by RedAuburn**
adds "Tip" and "Dump" to categories.txt, as these are common terms for a recycling centre

### CODE REVIEW

**Review by biodranik — APPROVED** [review]
Thanks!

**Comment by vng** [comment]
"tip"?
Adding "slang" or very "local" nouns can confuse other users because we have kinda greedy matching now, and the user will be confused with the results if "tip" will be a prefix for some name.

Please, don't add "specific" synonyms at least now while search algo is far from the ideal ..

**Comment by RedAuburn** [comment]
> "tip"?
> Adding "slang" or very "local" nouns can confuse other users because we have kinda greedy matching now, and the user will be confused with the results if "tip" will be a prefix for some name.
> 
> Please, don't add "specific" synonyms at least now while search algo is far from the ideal ..

'tip' is a very common way to refer to any disposal site, either a landfill or recycling centre. But i'm happy to remove it if you think it'll be an issue :)

**Comment by vng** [comment]
Let's see how it goes.

**Comment by biodranik** [comment]
Can we move it into GB-only hint?

**Pull request merged**
