### PR TITLE
Bookmark icons fix

### PR DESCRIPTION
**Pull request by strump**
Added `bookmark-judaism-m.svg`. Fixed `bookmark-islam-m.svg`.

TODO: Renamed `islam` to `muslim` because we already have `muslim-s.svg`, `muslim-m.svg` files.

### CODE REVIEW

**Review by pastk — APPROVED** [review]

**Comment by vng** [comment]
Why have the blue icons become smaller?
Did you use the master sking_generator tool?

Lets wait for @dvdmrtnz

**Comment by strump** [comment]
@vng  I used outdated `sking_generator`. Deleted `out` dir and renederated resources.

**Review by vng — APPROVED** [review]

**Comment by dvdmrtnz** [comment]
@strump Thanks!

**Comment by dvdmrtnz** [comment]
> TODO: Renamed `islam` to `muslim` because we already have `muslim-s.svg`, `muslim-m.svg` files.

That's true. But that's not the only one. There's multiple icons that have different names for POIs vs bookmarks. They should be reviewed and names should be unified.

**Pull request merged**
