### PR TITLE
[android] Don't request POST_NOTIFICATIONS on the start

### PR DESCRIPTION
**Pull request by rtsisyk**

### CODE REVIEW

**Comment by rtsisyk** [comment]
This is needed before releasing the next version.

**Review by Jean-BaptisteC — APPROVED** [review]
✅ Pixel 6 - Android 13

**Review by biodranik — COMMENTED** [review]
When notifications will be requested instead?

**Comment by rtsisyk** [comment]
> When notifications will be requested instead?

When the user explicitly clicks "Download" on the map.

**Comment by rtsisyk** [comment]
This patch fixes the annoying permission request for notifications on the first start. All other improvements like additional informational screens should be implemented separately.

**Pull request merged**
