### PR TITLE
Updated categories (2nd version)

### PR DESCRIPTION
**Pull request by FinixFighter**
Signed-off-by: Luca Finizio <luca.finizio.mgbx@hotmail.it>

### CODE REVIEW

**Comment by FinixFighter** [comment]
See discussion here: https://github.com/organicmaps/organicmaps/pull/531

**Comment by biodranik** [comment]
Thanks! Only DCO is missing :) You may sign the commit either by `git commit --amend --signoff` or manually add the following line in the commit description:
`Signed-off-by: Your Name <your@email.com>`

**Review by rtsisyk — APPROVED** [review]

**Comment by FinixFighter** [comment]
> Thanks! Only DCO is missing :) You may sign the commit either by `git commit --amend --signoff` or manually add the following line in the commit description:
> `Signed-off-by: Your Name <your@email.com>`

It's already commented with the sign. Isn't it right?
Screenshot at 2021-06-12 09-18-13

**Comment by biodranik** [comment]
You're right, it's a bug in the plugin. @rtsisyk can you please check and fix it? https://github.com/organicmaps/organicmaps/runs/2800290888

**Pull request merged**
