### PR TITLE
[styles] Add Metal Construction icons

### PR DESCRIPTION
**Pull request by yaslack**

### CODE REVIEW

**Comment by biodranik** [comment]
1. How do these icons look on the map?
2. Is it easily recognizable? It is more about the "I" letter.
3. Please don't forget to sign your commits with [DCO](https://github.com/organicmaps/organicmaps/pull/4785/checks?check_run_id=11999917766)

**Comment by biodranik** [comment]
4. Please do not close and recreate Pull Requests. Learn how to do `git rebase` and `git commit --amend`, and force-push your changes into the previous PR.

**Comment by yaslack** [comment]
> 2\. about the "I" lett

1. They are like the other i recreate multiple time the logo so it does not appear small,
2. Yes i mean you guys can just see the files changed and look for yourselves
3. Don't really know how to i will check for this
4. I edit it this is now the one with all generated and this one is with only the files changed like you guys tell me to do i suppose

**Review by biodranik — APPROVED** [review]
Thank you, I've checked how it looks on the map (good enough!), so let's merge it. Can you run tools/unix/generate_styles.sh and commit all changes into a separate, DCO-signed commit with a "[styles] Regenerated" title? If no, then we can help to update styles.

**Comment by yaslack** [comment]
> Thank you, I've checked how it looks on the map (good enough!), so let's merge it. Can you run tools/unix/generate_styles.sh and commit all changes into a separate, DCO-signed commit with a "[styles] Regenerated" title? If no, then we can help to update styles.

Ok nice, I can make it

**Pull request closed without merging**
