### PR TITLE
Color secondaries, darker farmlands, highlight tertiaries and other highways adjustments

### LINKED ISSUE #6128: Distinguish primary, secondary, tertiary roads by colors
At the moment many roads in OM have the same white color. It was done like in Google Maps, to match the expectations of the general public and to avoid map cluttering.

Maybe we can try to introduce some _slight_ visual differences without much cluttering for the general style? Maybe at least for primary/secondary roads?

As we plan to introduce different map styles for specific activities #1577 we can properly distinguish road types by colors to make it easier for some specific planning.

We have also discussed that there are two main high-level use cases of OM that may also have different styles/coloring:
1. Route planning mode.
2. Active "in-field" navigation mode.

For cars actually, we can already do it in the vehicle style (although it's not used _yet_ for planning the route, only when car navigation is active).

@pastk WDYT?

### LINKED ISSUE #6694: Better Distinction Between Different Road Types
When cycling, I generally don't want to be on A-Roads (trunk/primary) or B-Roads (secondary) if possible, as they're too busy and the traffic is often fast moving.  Instead, I want to always stick to small low-traffic roads (tertiary/unclassified) if I reasonably can – even if it takes longer.

Therefore, I plan routes in advance using the Bikerouter website, set to the "_Roadbike (minimized traffic, alternative)_" profile, which tries to use very-low-traffic roads wherever possible.  I then export this route as a GPX file and import it into Organic Maps for offline navigation – which works great.

The problem comes when there's a problem along the route and I need to use the built-in navigation.  Organic Maps routing will generally choose more quicker routes, therefore I need to override (manually add points) to make it route along tertiary and unclassified roads where I can.  The issue is, it's difficult to distinguish between different road types in Organic Maps because secondary, tertiary and unclassified roads are all coloured white and all look the same on a small phone screen.  However, there's a big difference cycling-wise between an unclassified road and a secondary road – unclassified roads are great, secondary roads are not.

It would be helpful if there was a clearer distinction between different road types.  Secondary roads especially should not be white, as it's important to easily see which ones they are – meaning they can then be more easily avoided when cycling.  Perhaps a colour-coding scheme something along the lines of darker colours the more major the road classification is, shifting to lighter colours the more minor the road classification is.  I.E.

| Road Type  | Colour |
| ------------- | ------------- |
| Trunk  | Orange (dark)  |
| Primary  | Orange (medium)  |
| Secondary  | Orange (light)  |
| Tertiary  | Yellow  |
| Unclassified  | White  |

I also use [cycle.travel](https://cycle.travel/map) quite often and find it really easy to distinguish between different road types when I'm using their maps. 

**Screenshot A – showing how different road types are displayed in OpenStreetMap style maps (zoomed out):**

[Link 1 to Bikerouter map](https://bikerouter.de/#map=13/50.8524/-4.4520/standard&lonlats=-4.485044,50.883177;-4.484756,50.827339&pois=-4.475109,50.883326,A-Road%20(highway%3Dtrunk)%20%5Bred%5D;-4.408333,50.868291,Minor%20Road%20(highway%3Dunclassified)%20%5Bthin%20white%5D;-4.384266,50.844278,Minor%20Road%20(highway%3Dtertiary)%20%5Bthick%20white%5D;-4.464947,50.829426,B-Road%20(highway%3Dsecondary)%20%5Byellow%5D;-4.400574,50.817779,A-Road%20(highway%3Dprimary)%20%5BOrange%5D&profile=fastbike-verylowtraffic)

Screenshot A

**Screenshot B – showing how different road types are displayed in OpenStreetMap style maps (closer view):**

[Link 2 to Bikerouter map](https://bikerouter.de/#map=15/50.8344/-4.4917/standard&pois=-4.510961,50.839882,A-Road%20(highway%3Dtrunk)%20%5Bred%5D;-4.488035,50.829046,Minor%20Road%20(highway%3Dunclassified)%20%5Bthin%20white%5D;-4.490902,50.837579,Minor%20Road%20(highway%3Dtertiary)%20%5Bthick%20white%5D;-4.465024,50.829372,B-Road%20(highway%3Dsecondary)%20%5Byellow%5D;-4.510978,50.827469,A-Road%20(highway%3Dprimary)%20%5Borange%5D&profile=fastbike-verylowtraffic)

Screenshot B

**Screenshot C - showing how different road types are displayed in Organic Maps:** [GPS location 50.8344, -4.4917]

_Top image:_ This is how they are currently displayed, where it's difficult to distinguish between different road types because secondary, tertiary and unclassified roads are all coloured white and all look the same on a small phone screen.

_Bottom image:_ The same image, but with different colours added.  This is a mock-up to demonstrate how it makes it easier for a user to easily distinguish between road types when they're colour-coded and can plan their route to avoid busy roads more easily.

Screenshot C

### PR DESCRIPTION
**Pull request by pastk**
- color secondaries (two shades for different zooms) and darker farmlands (based on #7048)
- highlight tertiaries/unclassified compared to residentials
- fixed bug with missing secondary z13 and tertiary z14 links
- better looking *_links joins (move all *_links under regular highways)
- tune widths

z15p

note how main through roads are highlighted
z13_2

z12p

- closes #6128 
- closes #6694

### CODE REVIEW

**Comment by pastk** [comment]
*_links are now rendered under adjoining highways (same behavior as on osm.org):

links_B

links_A

**Review by euf — APPROVED** [review]
Great job! Tuned widths look much better now. And thanks for fixing links 🔥

**Review by euf — APPROVED** [review]

**Comment by dvdmrtnz** [comment]
I like the new colors 👍

**Review by dvdmrtnz — APPROVED** [review]

**Review by biodranik — CHANGES_REQUESTED** [review]
1. Why different fixes are mixed in this PR?
2. Now it is hard to distinguish where highways are in cities.
3. Wide white roads are already clearly distinguishable as secondary ones, without recoloring them into the orange color. E.g. recoloring doesn't bring many benefits, but brings more issues.
4. The real issue that should be addressed is that tertiary and other minor roads are indistinguishable.

The map has obviously became worse, compare it with Google which uses widths instead of colors and Apple which also doesn't look great because does not use widths:

OM | Google | Apple
--|--|--
выява|выява|выява




A better solution could be to slightly increase width of secondaries without changing their color, and increase width of tertiaries.

**Comment by euf** [comment]
@biodranik 

> The map has obviously became worse 

Could you please tell what makes you fell that way? Is it a contrast thing, like it's harder to distinguish light orange roads from surrounding background and buildings? Is it overall impression of being too colorful compared to Apple and Google? 

Is it possible that your impression is based on a desktop screen experience, which is not quite relevant for mobiles? I ran this build on a Simulator for the same Manhattan area, and personally I find these results really great: 

| z11 | z12 | z13 | z14 | z15 |
|---|---|---|---|----|
| Simulator Screenshot - iPhone 15 - 2024-01-09 at 21 29 39 | Simulator Screenshot - iPhone 15 - 2024-01-09 at 21 29 45 | Simulator Screenshot - iPhone 15 - 2024-01-09 at 21 29 54 | Simulator Screenshot - iPhone 15 - 2024-01-09 at 21 30 02 | Simulator Screenshot - iPhone 15 - 2024-01-09 at 21 30 13 | 

> compare it with Google which uses widths instead of colors and Apple which also doesn't look great because does not use widths

Apple and Google opted for gray roads and highways, and Organic Maps keeps more cartographic look, like Yandex. Instead of relying on road widths, they also have rich color scheme. You can see they also use amber for "trunks", light orange for "primary", yellow for "secondary", white for "tetriary" and lower. Not better or worse, just different visual paradigm. 

Screenshot 2024-01-09 at 21 33 58

**Comment by vng** [comment]
@biodranik 
Google Maps uses outlines, not only with. It looks good in its gray theme. We have the orange theme and there is no other option for now.
The map has obviously become better and more informative. Make phone (not desktop) screenshots before and after.

@euf I like your screens.

**Review by vng — APPROVED** [review]
I'd like to move forward with this concept.

**Comment by pastk** [comment]
*_links are now rendered under adjoining highways (same behavior as on osm.org):

links_B

links_A

>     3. Wide white roads are already clearly distinguishable as secondary ones, without recoloring them into the orange color. E.g. recoloring doesn't bring many benefits, but brings more issues.

In my z12 screenshot above almost all secondaries have two carriageways, that's why they look so wide when zoomed out.
Single line secondaries in master are highighted similarly to how tertiaries highlighted against residentials in my PR, i.e.  distinguishable yet subtle still.

> 
>     4. The real issue that should be addressed is that tertiary and other minor roads are indistinguishable.
> 
> A better solution could be to slightly increase width of secondaries without changing their color, and increase width of tertiaries.

I've answered it already in https://github.com/organicmaps/organicmaps/pull/7048#issuecomment-1880011615.

Even making tertiaries look good against residentials on all zooms was not easy and time-consuming task. I've spent more than a day on it.
If anyone wants to try a different approach - feel free to experiment!

**Comment by biodranik** [comment]
Am I correctly understanding that using widths requires more time to implement, that is why a simpler recoloring approach is used?

Why changing widths is more challenging?

**Comment by pastk** [comment]
> Am I correctly understanding that using widths requires more time to implement, that is why a simpler recoloring approach is used?

No. If you make secondaries wider then they'll be wider than primaries (now they're same width) and trunks even.
And on lower zooms the width difference should be **significant** to make lines distinguishable.
E.g. in this PR on z13 tertiaries are `1.8` while residentials are `1`. I guess will have to make the secondaries width ~3 then. Consider that residentials in this PR use slightly greyish color compared to the full white tertiaries. Without any color difference will have to make width difference bigger even.

For reference motorways are 2.8 at z13. Primaries in the vehicle style are 3. So the roads will get as thick as in the vehicle style.

BTW in your Gmaps screenshot I see only two 2 distinguishable road widths in the center of the island. Supposed to be 3 (secondary, tertiary, residential). In OM often you won't be able to see the difference between tertiary and residential on z15 either, because many streets are surrounded by sidewalks which make them all look same width (maybe it'll improve in NY after #6789).

**Comment by biodranik** [comment]
> No. If you make secondaries wider then they'll be wider than primaries (now they're same width) and trunks even.

What stops us from increasing primaries/trunks width too?

> Supposed to be 3 (secondary, tertiary, residential)

Distinguishing tertiary and residential is not important/not needed for the general style at non-detailed zooms. We can do some experiments with detailed zooms and see if there is any value.

**Comment by pastk** [comment]
> What stops us from increasing primaries/trunks width too?

It'll be much more accent on the roads like in the vehicle style, which I think is not needed for the main style.
Also distinguishing by width works bad in dense places especially when there are sidewalks around or street names obscure the underlying road line. Color works much better in those cases.

I like the current color solution and think its superior.

> 
> Distinguishing tertiary and residential is not important/not needed for the general style at non-detailed zooms. We can do some experiments with detailed zooms and see if there is any value.

Its important, see a z13 screenshot in the first post.

**Comment by pastk** [comment]
A follow-up
- https://github.com/organicmaps/organicmaps/issues/7139

**Comment by pastk** [comment]
> > It'll be much more accent on the roads like in the vehicle style, which I think is not needed for the main style.
> > Also distinguishing by width works bad in dense places especially when there are sidewalks around or street names obscure the underlying road line. Color works much better in those cases.
> 
> Have you already compared it? Are there any screenshots to see and align with your conclusions?
> 

I did small tests only and based on them and my prior styling experience I've outlined my conclusions above.
I'm not motivated to spend more time to work on a solution I consider inferior, sorry.

**Pull request merged**
