### PR TITLE
Explicitly link to zlib in vendored copy of minizip

### PR DESCRIPTION
**Pull request by Osyotr**

### CODE REVIEW

**Review by vng — COMMENTED** [review]
What does it suppose to fix if our platform compile Actions are fine?

**Comment by biodranik** [comment]
@vng windows, we need to add an action for it too btw (maybe a manual one, until all build issues are fixed).

**Review by biodranik — APPROVED** [review]
Thanks!

**Comment by Osyotr** [comment]
> What does it suppose to fix if our platform compile Actions are fine?

The only reason why it works is that `zlib.h` is in default include path in all platforms you test for.

> we need to add an action for it too btw (**maybe a manual one**, until all build issues are fixed).

My WIP action: https://github.com/Osyotr/organicmaps/blob/wip-windows/.github/workflows/windows-check.yaml
Run results: https://github.com/Osyotr/organicmaps/actions/runs/8901513896/job/24445522531?pr=1
(Note that 30 min configure is because static qt is being built from source and resulting archive is >500mb in size so it can't be cached by vcpkg. Can probably cache the whole `vcpkg_installed/` folder instead. Dynamic Qt does not have this problem.)

**Comment by biodranik** [comment]
Cool, let's add this action with a manual run now into the master. Qt6 is available via both vcpkg and chocolatey, so it shouldn't be a problem, right?

**Pull request merged**
