### PR TITLE
Minor update of liboauthcpp and a few warning fixes

### PR DESCRIPTION
**Pull request by biodranik**
Thanks to @Osyotr for the MSVC build log:
https://github.com/organicmaps/organicmaps/files/14728637/organicmaps-win-build-log.txt

### CODE REVIEW

**Comment by biodranik** [comment]
Hmm, looks like liboauthcpp is not needed/used anymore when oauth2 is merged, right @strump ?

**Comment by Osyotr** [comment]
Base64/SHA1 stuff is used in other places.

**Comment by biodranik** [comment]
> Base64/SHA1 stuff is used in other places.

I see, in coding. Is it the best possible implementation that we can use? The author didn't update the library for 6 years. Are there other better/faster alternatives? @Osyotr

**Comment by strump** [comment]
@biodranik oauth2 doesn't use `liboauthcpp`. Maybe we can replace it with SHA1 lib

**Comment by Osyotr** [comment]
> Are there other better/faster alternatives?

IMHO it's not worth adding an external dependency over these two algorithms.
It's possible to rip out code from https://github.com/weidai11/cryptopp (BSL-1.0).

**Comment by vng** [comment]
We no longer have liboauthcpp.

**Pull request closed without merging**
