### PR TITLE
[styles] Added sac_scale for path difficulty

### LINKED ISSUE #6593: Add sac_scale
All hiking paths look the same now, despite difference in difficulty. Also when tapping it says "path" or the name. So one cannot know what to expect.

Would be great if one taps the path that it would give its difficulty. The sac_scale is great for this. Another option would be to make a sort of warning sign for the last two steps of the scale when tapping the path.
A next step would be to also visualize them differently

As an example have look at this: 49.219973, 20.025669 . Looks like a normal hiking path in OM. In reality this is a rather hard path with very steep sections (chains as well). In OSM this is marked as sac_scale=demanding_alpine_hiking, which is the second most difficult. I think it is useful and important to reflect this in OM.

I searched for a similar issue, but couldn't find it. Sorry if it is a duplicate

### PR DESCRIPTION
**Pull request by map-per**
closes #6593 

Added `sac_scale` for the difficulty of hiking paths to the **outdoor style**.

The `sac_scale` is displayed using different path colours. From yellow, orange and red for ordinary hiking trails to blue and purple for especially difficult routes.

| sac_scale | colour |
|--------|--------|
| hiking (T1) | yellow |
| mountain_hiking (T2) | orange |
| demanding_mountain_hiking (T3) | red |
| alpine_hiking (T4) & demanding_alpine_hiking (T5) | blue |
| difficult_alpine_hiking (T6) | purple | 

Using colour for `sac_scale` makes distinguishing different difficulty levels easy. Moreover the dash pattern is still "free" and can be used to e.g. encode `trail_visibility`.

|  |  |
|--------|--------|
| Screenshot_20240404_141534_Debug Organic Maps | Screenshot_20240404_141603_Debug Organic Maps |
| Screenshot_20240404_144609_Debug Organic Maps | Screenshot_20240404_141729_Debug Organic Maps | 

(https://www.openstreetmap.org/#map=15/47.5262/12.9643)
(https://www.openstreetmap.org/#map=15/47.5271/11.1449)

#### TODO:

- [x] Light style
- [ ] Dark style
- [ ] Handle highway=footway + sac_scale
- [ ] Improve visibility of yellow paths

### CODE REVIEW

**Comment by biodranik** [comment]
1. What happens when we add support for hiking route relation? Won't it mess things up?
2. Would it be better to render difficulty explicitly in the text/path name instead?

**Comment by map-per** [comment]
> 1. What happens when we add support for hiking route relation? Won't it mess things up?

I would render hiking route relations semitransparent below the paths, similar to how [CycleOSM](https://www.openstreetmap.org/#map=19/48.15261/11.59216&layers=Y) does it with cycle routes. OpenAndroMap also does it this way on lower zoom levels (see https://github.com/organicmaps/organicmaps/issues/6593#issuecomment-2037362124)

> 2. Would it be better to render difficulty explicitly in the text/path name instead?

The downside of this approach is that you can easily miss difficult sections if they are very short. (even a short difficult section can block your way)

**Comment by biodranik** [comment]
Colorful tracks do look too colorful/distracting, and still not clear to read without decoding what colors mean. And in different countries different colors may mean different difficulty levels. 

Are there better solutions?

**Comment by map-per** [comment]
For hiking the `sac_scale` is one of the most important infos about a trail, so I think it is ok that this info stands out.

**Comment by biodranik** [comment]
Enabling colors only in Outdoors style may be less risky, if we proceed in this way.

**Comment by map-per** [comment]
Oh, the this is a misunderstanding. The `sac_scale` is for the Outdoor style only.

**Comment by patepelo** [comment]
> 1. What happens when we add support for hiking route relation? Won't it mess things up?
> 
>     2. Would it be better to render difficulty explicitly in the text/path name instead?

I had imagined we would have gone this path. Difficulty in text label and colors for hiking relations. 


This is Komoot's approach for example:

image

**Comment by alensiljak** [comment]
> Would it be better to render difficulty explicitly in the text/path name instead?

As I'm a visual type, I find colours giving me much more information instantaneously, as opposed to text. Using the OpenAndroMaps just for a short time, to look at some areas I've hiked around, makes it immediately obvious which are the dangerous paths and which are easy. I vote for the colour as the differentiator. Although, previously I thought little text tags were a good idea. See https://github.com/organicmaps/organicmaps/issues/6593#issuecomment-2039409905 for comparison.

> I would render hiking route relations semitransparent below the paths

I think this is very convenient and practical. See the link above for comparison. I like how OsmAnd does this.

I may be biased but I actually like the Austrian grading system colours (although I don't think I've ever seen these colours somewhere outside) - blue, red, black. It is probably because I was used to the ski slope grading system, which is green, blue, black. Red normally means danger, so it makes sense to add it before black (black means no coming back).
In that regard, I would prefer if the colours were adjusted. But I understand that might be quite different in different areas. However, let's see what colouring systems are in place, then?

One observation in this scheme here - why are T4 + T5 left together? In the Austrian system, all above T4 (which is fairly complicated for most people) are considered black. Even T3 get difficult but still manageable. But I would not want to be responsible for someone on T4. T5 and T6 are probably for climbing (with ropes) only, not sure.
In that sense, having T4+ as black would be ok provided the details are available when tapping on the section, or something like that. Or, at least combining T5 and T6 under one colour, because that would be outside of the reach of most people and probably never displayed in most countries.

I'm not sure a T1 even requires any specific colouring. Just having a hiking route colours below should be enough, I think.
So, essentially, at the moment I really like the colouring at https://github.com/organicmaps/organicmaps/issues/6593#issuecomment-2037141108, but perhaps even without having a specific colour for T1 as that adds no value. 
The default brown, used in that case, is very close to black when outside. This would have to be tested in practice.

**Comment by alensiljak** [comment]
> I had imagined we would have gone this path. Difficulty in text label and colors for hiking relations.

I used to think that, as well. But, what @map-per is trying to say (and now me too, after I've ran into the following situation two weeks ago), is that a 30-50m T3 section can screw up your day because the rest of your 20km route is T2.
Even though you still have to zoom in, sections like this are much easier spotted when painted differently and have icons for stairs and other helpers on the way, which may be too much for most "regular" people.

**Comment by pastk** [comment]
I've added the most of my thoughts into the original issue https://github.com/organicmaps/organicmaps/issues/6593#issuecomment-2041513047
(as I think its better suited for discussions)
Please check there!

**Comment by pastk** [comment]
Please note that there is an idea to use dark blue color for cycleways...
- https://github.com/organicmaps/organicmaps/pull/7255
- #5289

**Comment by pastk** [comment]
Overall usage of bright colors makes it harder to overlay marked colored routes.

It could be done openandromap / mapy.cz way by drawing another colored "route" line beside the trail line. IMO it makes the doubled lines very thick and confusing what is what (which shows the route color and which shows the difficulty color).

Another way is to highlight by a semi-transparent colored overlay/underlay similar to OsmAnd. I don't like OsmAnd's implementation either because the overlays are very thick and the underlying "difficulty" colors and lines are not very visible anyway.
I guess it could be improved if highlights are underlayed and more narrow and bright, but the "core" line is contrast still because e.g. its limited to dark contrast shades of brown-grey-black and also uses patterns to distinguish grades.

**Comment by biodranik** [comment]
Maybe the thinner the line = the more dangerous is the hike? Using difficulty numbers, or danger symbols is also an option.

**Comment by pastk** [comment]
> Maybe the thinner the line = the more dangerous is the hike?

Actually its the dangerous sections when map readability is very important esp. in adverse conditions (very bright sun, blizzard, ...), so the lines should be prominent.
But not screaming prominent so that they don't attract attention of newbies unnecessarily :)

**Comment by pastk** [comment]
An example of 4 grades:

1. "Just hiking": ungraded or T1-T2. Brown dashed.
2. "Be prepared": T3 or poor visibility. Black short-dashed.
3. "Experts only": T4-T6 or very bad visibility. Dotted black.

So where is the 4th grade? :)

0. Footways. Paved and/or very smooth. White dashed.
(means we should convert current `highway=footway` with not good surface into the "hiking grade" #1796)

**Comment by pastk** [comment]
> An example of 4 grades:

Its already much more sophisticated than New Zealand topo maps:

image

Where actually the middle option is super rare, so basically there are only two visual grades on the map! :)
image

And actually it seems that Mapy.cz is using only two visual difficulty grades too
image

**Comment by pastk** [comment]
SAC also visually separates its 6 categories in just 3 colors (https://www.sac-cas.ch/fileadmin/Ausbildung_und_Wissen/Tourenplanung/Alpinmerkbl%C3%A4tter/20230601_SAC-Wanderskala_D.pdf):
image

A map sample from the SAC portal:
image

**Comment by pastk** [comment]
> 
>     1. "Just hiking": ungraded or T1-T2. Brown dashed.
> 
>     2. "Be prepared": T3 or poor visibility. Black short-dashed.
> 
>     3. "Experts only": T4-T6 or very bad visibility. Dotted black.
> 

It might be nice to have a following color scheme:
1. dark green (easy)
2. brown (med)
3. black (expert)

There is logic in it and still it'll be compatible with highlighting of marked routes.
But it'll be a big visual change for the most of the paths from the current brown to dark green.
And need to check for possible conflicts with hedge lines and `natural=tree_row` (we don't render the latter as of now).

**Comment by biodranik** [comment]
Maybe starting with easy select-and-highlight-track-on-a-single-tap and showing its details in the Place Page would be more useful and less risky?

**Comment by alensiljak** [comment]
>     1. dark green (easy)
>     2. brown (med)
>     3. black (expert)

Why not leave brown as-is, and just add (2) red and (3) black?

**Comment by pastk** [comment]
> 
> Why not leave brown as-is, and just add (2) red and (3) black?

Its an option also, my only concern with the **bright** red is that it'll conflict with later highlighting of routes and that it'll draw too much attention - we want hard sections to be easily distinguishable but not attracting attention unnecessarily.
If its a dark and less saturated variety of red (or any other color actually) then it might work well.

**Pull request closed without merging**
