### PR TITLE
[android] Improve about layout land on device with low dpi

### PR DESCRIPTION
**Pull request by Jean-BaptisteC**
This PR confirms that changes need to be tested on real devices :)
Tested on
- Honor 8 - Android 8 (5.2 inch)
- Pixel 6 - Android 14 (6.45 inch)
- Samsung Galaxy Tab S6 Lite - Android 13 (10.4 inch)

Low DPI
|Before|After|
|-|-|
|||

|Phone|Tablet|
|-|-|
||

### CODE REVIEW

**Review by rtsisyk — APPROVED** [review]

**Review by biodranik — APPROVED** [review]
Merci !

**Comment by biodranik** [comment]
@Jean-BaptisteC Is it hard to move the FAQ button in the landscape in the same row where Donate and Report a Bug buttons are? Or at least move the FAQ button up?

**Comment by Jean-BaptisteC** [comment]
I think three button on the same line is too much, especially on devices with low DPI
Yes, moving FAQ button is better and maybe removing support_us textview because we have already a big button to donate!

**Comment by biodranik** [comment]
Support us and donate are different. No need to remove. But FAQ should be at the top of the list.

**Pull request merged**
