### PR TITLE
Removed charXX_t pointers DebugPrint.

### PR DESCRIPTION
**Pull request by vng**

### CODE REVIEW

**Review by Ferenc- — APPROVED** [review]
Looks OK to me.

**Review by biodranik — COMMENTED** [review]
I agree on assert changes (printing pointers doesn't make sense there, right?)

But I don't think that printing unicode string literals should be disabled. It is very convenient to debug unicode characters natively. Would it be better to print charXX_t by leveraging our utf8 conversion code?
- U"string" for `char32_t *` and `char32_t const *`
- U'c' for `char32_t`
- u"string" for `char16_t *` and `char16_t const *`
- u'c' for `char16_t`

WDYT?

**Comment by vng** [comment]
I don't understand "leveraging our utf8 conversion code".
We store strings as UTF8 buffer.
We work with strings as UniString.

Both of them are printable.

**Comment by biodranik** [comment]
Meaning to DebugPrint these charXX_t strings and characters using utf8cpp. UniString is a buffer_vector, so it's a different case.

For example, now our tests are converting utf8 literals to UniString. We can directly use char32_t const * literals without conversion in such cases. Some hard-coded search tokens may also use char32_t to avoid dynamic conversion with utf8cpp. These examples may require printing these literals with ASSERT/TEST macros.

**Comment by biodranik** [comment]
But now you can't write `ASSERT_EQ(U"ЯЙЦУ", uniString, ());` and should insert `MakeUniString()` call.

**Comment by vng** [comment]
Yes, because I can write ```ASSERT_EQ("ЯЙЦУ", uniString, ());```

**Review by biodranik — APPROVED** [review]
We can always enable printing later if necessary. LGTM

**Pull request merged**
