### PR TITLE
[editor] Removed comment inside comments in editor.config xml.

### PR DESCRIPTION
**Pull request by vng**
I have an assert on the desktop, because looks like a comment inside a comment is a bad-formed xml.

### CODE REVIEW

**Comment by biodranik** [comment]
@kirylkaveryn tests were failing in CI, I didn't see it: https://github.com/organicmaps/organicmaps/actions/runs/6735268208/job/18308044125

It's better to always run all tests locally when you are modifying some C++ core part. @vng what is the best way to run all local tests for contributors?

**Review by biodranik — APPROVED** [review]
Thanks!

**Comment by vng** [comment]
Honestly saying, I usually run only selected tests, where I modify at the moment, like
```./base_tests --filter="SimpleTokenizer"```

Just check that Git Actions run correctly. We have false fails of MacOS tests sometimes.

**Comment by kirylkaveryn** [comment]
@biodranik my fault 😭
It there are some docs how to run tests locally?

**Comment by AndrewShkrob** [comment]
@kirylkaveryn 
Check here: https://github.com/organicmaps/organicmaps/blob/master/docs/INSTALL.md#testing

**Pull request merged**
