### PR TITLE
[styles] Increased visibility and priority for alpine_hut

### PR DESCRIPTION
**Pull request by map-per**
closes #6055 

`tourism=alpine_hut` is now visible from z13 and the priority is similar to museum, monument and city_gate.

Bildschirmfoto vom 2023-09-23 21-51-40
Bildschirmfoto vom 2023-09-23 21-58-10
https://www.openstreetmap.org/node/9917583628

### CODE REVIEW

**Comment by vng** [comment]
Make sense considering that alpine huts are usually in mountains (not very dense areas).
@pastk WDYT?

**Comment by biodranik** [comment]
@map-per is there an easy way to estimate if there will be a lot of alpine huts in some more dense regions? If their priority is lower than other features, then it's okay.

**Comment by map-per** [comment]
By their OSM definitio `alpine_huts` are "remote" (https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dalpine_hut) and a check with Overpass shows that this is also the mapping practice. So `alpine_huts` don't clutter dense regions.
(But, as always, there are odds that look like mapping errors as well (like https://www.openstreetmap.org/node/7233820685))

**Comment by biodranik** [comment]
From a fairness point of view, those who own alpine huts, or those who wrongly mark their guest houses as alpine huts will get an advantage in OM over other hotel and guest house owners.

**Comment by map-per** [comment]
OSM Carto displays `alpine_hut` very prominent as well, so I wouldn't worry too much about vandalism. In general people just don't know enough about how OSM works to properly do "visibility increase" vandalism and about half of the people I've seen adding their own business don't add any feature tag at all, so their place stays invisible.

**Comment by map-per** [comment]
And about the fairness: I don't know, I'd rather focuse on the map user experience

**Review by biodranik — COMMENTED** [review]
Ok, let's proceed with it. LGTM. In New Zealand, it's very important for their Great Hikes.

@pastk Can you please review the PR?

**Review by pastk — APPROVED** [review]
Alpine huts are supposed to be high in the mountains above the tree line, so map cluttering is very unlikely.

**Comment by map-per** [comment]
Rebased

**Comment by map-per** [comment]
Rebased

**Comment by pastk** [comment]
@vng let's merge?

**Pull request merged**
