### PR TITLE
[android] Don't change the viewport when PlacePage is opened

### LINKED ISSUE #4794: The position arrow is wrongly placed at the top in the landscape mode
**Describe the issue**
Hello, when I use the application in landscape mode, the cursor is placed at the top of the screen. It is therefore impossible to see the route to be taken.
Is it possible to place it at the bottom of the screen?

**Steps to reproduce**
1 Put the application in landscape mode
2 Indicate a direction
3 Start route guidance

**Expected behavior**
Have visibility of the route to be taken

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**System information:**
 - Operating system and its version: Android 11,
 - Organic Maps version: 2023.03.05-Google
 - Device Model: Samsung A40
Screenshot_20230316-074933_Organic Maps

**Additional context**
Please add any other context and important details/notes/comments about the problem here.

### PR DESCRIPTION
**Pull request by rtsisyk**
This code doesn't bring any real value, but definetly creates troubles.

Closes #4794

### CODE REVIEW

**Comment by vng** [comment]
Controversial. Real value:
- Open PP
- Press "Position center" mode. The position should be at the viewport's center without PP.

The mentioned issue is already fixed https://github.com/organicmaps/organicmaps/issues/4794 Or do we still have reproducible bug?

**Review by Jean-BaptisteC — APPROVED** [review]
✅ Pixel 6 - Android 13

**Comment by rtsisyk** [comment]
> Controversial. Real value:
> 
>  * Open PP
> 
>  * Press "Position center" mode. The position should be at the viewport's center without PP.
> 

I don't think this is a real problem.

> The mentioned issue is already fixed #4794 Or do we still have reproducible bug?

It reproduces on Huawei P30 always every time I start navigation.

**Comment by biodranik** [comment]
Do not center the arrow breaks the UX. Please see my comment here: https://github.com/organicmaps/organicmaps/issues/4794#issuecomment-1519859697

**Comment by vng** [comment]
@rtsisyk You are the only person with Huawei who can reproduce the problem :)
Could you please check latest master on your device?

**Comment by Jean-BaptisteC** [comment]
@rtsisyk up

**Comment by rtsisyk** [comment]
This PR is not actual anymore. It works somehow and I don't see any issues.

**Pull request closed without merging**
