### PR TITLE
Improve desktop place page dialog

### PR DESCRIPTION
**Pull request by dmfrodrigues**
This PR improves the place page in the desktop version. These improvements are largely based on the mobile UI.

The majority of the less-useful information in the place page was moved to a dialog that can be opened by clicking "Advanced".

The only detail not explicitly shown in the screenshots is that the "Wiki Description" button was moved next to the short description, to the new button "More...".

### Before

image

### After

| Debug mode | Release mode |
|-|-|
| image | image |
| image | image |

### CODE REVIEW

**Comment by biodranik** [comment]
Thanks! 

1. As we use the desktop version for development, can you please add a preference for "Developer mode" which is on by default for Debug builds, and off by default for Release builds, and it always shows the detailed "advanced" dialog if enabled? Then "Advanced" button is not needed in the non-developer mode. The rationale is to save our time by not doing an additional click to see what's in the map data.
2. The Close button is convenient, dialog can be closed by the Enter or the Space too, not only by ESC.
3. lat, lon can be changed to Coordinates
4. Is there a way to format types into a readable string on the desktop for non-dev mode?
5. The metadata title shouldn't be displayed if there is no metadata. Are all metadata fields scanned/displayed now?

**Comment by dmfrodrigues** [comment]
@biodranik 

1. In this case, the debug version would always show the metadata. And in the release version, should the advanced stuff stay in a separate dialog, or would it be better if there was not even an "Advanced" button at all?
2. Done
3. Done
4. I don't understand what you mean. Could you please clarify, or give an example?
5. Yes, in the "Advanced" part, all metadata is displayed, as before. I did not remove anything, I only added stuff.

**Comment by biodranik** [comment]
No Advanced button/view is needed if dev mode is not enabled. Only the Edit Place button.

Check how types are formatted/displayed on mobiles for a non-dev mode: tourism-museum should be replaced by a translation like "Museum". Maybe it is not feasible yet in the core yet, then it can be done separately later.

I've observed "Metadata" header with empty rows for features without any metadata.

**Comment by dmfrodrigues** [comment]
- Advanced button: done (please check new printscreens).
- Showing user-friendly descriptions instead of types is not yet done in core. I'd prefer to do that in a different MR. @RedAuburn 
- Done

@biodranik could you take another look into this?

**Comment by biodranik** [comment]
@dmfrodrigues did you forget to push your changes?

**Comment by dmfrodrigues** [comment]
Indeed I forgot to push some stuff,  sorry :sweat_smile: 

Now everything should be pushed @biodranik

**Comment by biodranik** [comment]
Thanks!

1. Only a few Wikipedia articles have working links in the Release mode.
2. The Close button should be focused by default, not the More... wiki button.
3. There is a bug in debug version, metadata in advanced section is not always displayed.
4. There is no need to duplicate equal fields in "normal" and "advanced" mode. Let's display only "User-friendly" or only "Dev-friendly" mode, so a preference is needed to switch modes.
6. It would be nit to strip http(s):// prefixes from _displayed_ urls.

FYI, there will be many other buttons on the Place Page.

**Comment by Ferenc-** [comment]
@dmfrodrigues do you need help with this PR? Apparently other PRs are also blocked b this.

**Comment by Ferenc-** [comment]
Thanks again @dmfrodrigues for starting this PR.

**Pull request closed without merging**
