### PR TITLE
Hebrew translations of type_strings.txt (not by me)

### PR DESCRIPTION
**Pull request by NeatNit**
I told @MbTy1 about Organic Maps and about the recent call to action at #8854, and he actually decided to get to work on it! He has a bit of trouble dealing with git and GitHub which is why I'm making the PR for him.

I did not go through all the changes, but I did check a few random translations and they are great.

### CODE REVIEW

**Comment by NeatNit** [comment]
To be totally honest, that DCO error is not familiar to me either. I did notice that it said not to do this if I am not the sole author of this, which I am not, so if I need to take any action here I'll need some guidance.

**Comment by NeatNit** [comment]
Oh, I should also say, there are more translations coming so if you want you could hold off and merge it all at once.

**Comment by biodranik** [comment]
DCO needs the same author name/email in the commit message as the author set in ~/.gitconfig (or .git/config) and on GitHub account.

Thanks for the improvements! There were many HE translations missing.

**Comment by NeatNit** [comment]
> Thanks for the improvements! There were many HE translations missing.

I am well aware... It was a daunting task that I was procrastinating since I first discovered that strings.txt wasn't the only file that needed translation.

> DCO needs the same author name/email in the commit message as the author set in ~/.gitconfig (or .git/config) and on GitHub account.

Well, considering it was all authored by @MbTy1, and I'm merely the one putting it together for the PR, what would be the correct way to fix this?

I feel like I'm being needlessly stubborn and obsessive about this when it probably doesn't matter that much. It only goes in the git history. So if you want me to just "lie" to git and say I authored it, I'll do it.

Is there a way to do it from GitHub instead of cloning the full repo to my PC?

**Review by biodranik — APPROVED** [review]
No worries, thanks! I'll squash commits.

If working from a command line, `git commit -a -s` automates the signature.

**Comment by MbTy1** [comment]
Thanks everyone!
I usually like to work offline for my own reasons. I will edit the file and send.
Thanks again, Moshe

**Pull request merged**
