### PR TITLE
[android] Remove `outdoor_seating` support

### PR DESCRIPTION
**Pull request by Arthur-GYT**
All is in the title.

Related to #9049

### CODE REVIEW

**Comment by biodranik** [comment]
@map-per please review. What about iOS? Should it be disabled there too if we proceed with the undo instead of a fix?

**Review by map-per — APPROVED** [review]
Works as intended, the outdoor_seating UI is hidden and edits work on the OSM dev API

**Comment by map-per** [comment]
> What about iOS?

iOS isn't implemented (#9117) and no wrong tags are uploaded to OSM, so iOS is fine.

**Comment by biodranik** [comment]
@Arthur-GYT @map-per what are the next steps with the best possible/correct fix? Can it be done in the upcoming weekend, so we can quickly test it and release a hotfix at the beginning of next week?

**Comment by Arthur-GYT** [comment]
> Can we revert the original PR instead?

image

**Comment by biodranik** [comment]
@rtsisyk @Arthur-GYT Am I correct, that reverting the original PR is complicated, because it is already integrated with iOS?

**Comment by Arthur-GYT** [comment]
Partially yes

**Comment by Marc-marc-marc** [comment]
Does this PR completely remove the tag everywhere, or does it revert out the regression that added this tag to lots of objects for no reason?

**Pull request merged**
