### PR TITLE
[strings] Added norwegian (nb) translations to sound.txt

### PR DESCRIPTION
**Pull request by FTno**
Signed-off-by: FTno <16176811+FTno@users.noreply.github.com>

### CODE REVIEW

**Review by vng — APPROVED** [review]

**Comment by biodranik** [comment]
@FTno can you please sign the commit or this PR by adding a line like this?
`Signed-off-by: Your Name <your@email>`

**Comment by FTno** [comment]
Sorry but I don't like to make my email address publicly visible

**Comment by biodranik** [comment]
@FTno you can use your github email alias instead.

**Review by rtsisyk — APPROVED** [review]

**Review by rtsisyk — CHANGES_REQUESTED** [review]
Sorry, we need your real name or something that can be used to identify you as a real person in `Signed-off-by. Please add your name and/or share any link to your public profiles.

**Comment by FTno** [comment]
I prefer to contribute anonymously only.

**Pull request closed without merging**
