### PR TITLE
[styles] Add border to disabled parking space icon

### PR DESCRIPTION
**Pull request by dvdmrtnz**
* This PR adds a thin white outline border to the disabled parking space icon. This will make the icon match the rest of the new parking icons and also improve visibility. Closes https://github.com/organicmaps/organicmaps/issues/5342

| Day | Night | 
|-|-|
|  |  |

### CODE REVIEW

**Comment by vng** [comment]
AFAIR, @RedAuburn @pastk you recently removed an outline from the disabled parking place, no?

**Comment by RedAuburn** [comment]
> AFAIR, @RedAuburn @pastk you recently removed an outline from the disabled parking place, no?

no, adding an outline was requested but I forgot to include it in my PR :)

**Review by RedAuburn — APPROVED** [review]
looks good, thanks!

**Review by biodranik — APPROVED** [review]
Thank you!

**Pull request merged**
