### PR TITLE
[styles] render prison areas

### PR DESCRIPTION
**Pull request by RedAuburn**
clear/vehicle
image1-9

fixes https://github.com/organicmaps/organicmaps/issues/4204

### CODE REVIEW

**Comment by vng** [comment]
Hm, good question ..
What types does the app show (after generation) when clicking the right button on this area?

**Comment by vng** [comment]
BTW, why [this building](https://www.openstreetmap.org/relation/1416194) have layer=-1 ?

**Comment by RedAuburn** [comment]
> What types does the app show (after generation) when clicking the right button on this area?

only amenity-prison, but military doesn't show anything else either 🤔
image1-6


> BTW, why [this building](https://www.openstreetmap.org/relation/1416194) have layer=-1 ?

looks like it was added by mistake, fixed :)

**Comment by dvdmrtnz** [comment]
@RedAuburn I checked out your branch, regenerated styles and rebuilt the map and it seems to be working fine here:

https://www.openstreetmap.org/way/183236506#map=17/42.82723/-1.67803

**Comment by dvdmrtnz** [comment]
I regenerated London map too and it looks fine there too:

IMG_3308

**Comment by RedAuburn** [comment]
> @RedAuburn I checked out your branch, regenerated styles and rebuilt the map and it seems to be working fine here:
> 
> https://www.openstreetmap.org/way/183236506#map=17/42.82723/-1.67803
> 
> 

huhh 🤔 thank you for trying it! maybe i forgot to rebuild the desktop app or something. i'll give it another go

**Comment by RedAuburn** [comment]
@pastk PTAL :)

**Comment by vng** [comment]
Prisons are usually not so big like military. Probably z12 is early, no?

**Comment by RedAuburn** [comment]
> Prisons are usually not so big like military. Probably z12 is early, no?

They are definitely big in the UK at least, but I think it'll be OK because smaller areas will be filtered out when they are too small. This is also why I kept the icon at a higher zoom.

maybe you're thinking of police stations/jails, which are smaller?

**Review by pastk — APPROVED** [review]

**Comment by pastk** [comment]
If you want to experiment :)
- atm some hatching fills are not very visible at overview zooms (nature reserves especially, military areas are OK-ish)
- at the same time at detailed zooms like z17+ it makes the map look less clear hence harder to see details like small paths, streams...
- so an idea is to make the fills more pronounced/opaque at overview zooms and very light (like they're now) or completely disappearing at detailed zooms (when we're quite certain the viewport is "inside" a reserve already)
- again, its more about nature reserves than "forbidden" areas which should be well visible at any zoom

**Pull request merged**
