### PR TITLE
few fixes for ptbr

### PR DESCRIPTION
**Pull request by inkh0rn**

### CODE REVIEW

**Comment by inkh0rn** [comment]
Hello OrganicMaps, 
I’ve made few changes for local translation, it looks like you need to adjust few things to be able to merge it, I don’t know how to do it, so if you can fix it and merge it, that’d be great, I did my best, hopefully it’s good. Thanks for working on OrganicMaps.

**Comment by dbf256** [comment]
@inkh0rn build check fails because yo have not marked commit as signed-off. If you have console git installed just go to checkout repo and execute these commands, after replace of my@email.com with your actual email 

```
git commit --amend -m "few fixes for ptbr Signed-off-by: inkh0rn <my@email.com>"
git push --force origin master
```

**Comment by inkh0rn** [comment]
Hello again OrganicMaps, 

> If you have console git installed

I’m not much of a coder and use github mainly for contributing with translations and bug fixes, I do everything through GH UI, and don’t have console installed, my GH email is <[103287762+inkh0rn@users.noreply.github.com](mailto:103287762+inkh0rn@users.noreply.github.com)>, you can merge it locally if that's ok with you. And I will also attached file I worked with in message attachement, just in case you want to use it in different way...

[ptbr_strings](https://github.com/organicmaps/organicmaps/files/8614317/ptbr_strings.zip)

**Comment by vng** [comment]
@inkh0rn Well, we can't manage this PR like this. You deleted original file and added the new one (completely reformatted?).
So we have 100K lines added and unable to realize the actual changes. Could you please send us your strings.txt with translations (info@organicmaps.app), I will create the PR myself and you just will add Sign-off comment.

**Comment by vng** [comment]
Could you please attach strings.txt file with your changes.
ptbr_strings.zip has a strange large html inside.

**Comment by vng** [comment]
@inkh0rn
Could you please send us your changes via E-Mail?
ptbr_strings.zip has a strange large html inside. We are working with strings.txt

**Comment by biodranik** [comment]
@inkh0rn you somehow did it in a very wrong way. Please download this text file, edit it in your text editor, and send us back: https://github.com/inkh0rn/organicmaps/blob/eaa0037b4ed2a0c7258bfc473ee41a61bc6bd557/data/strings/strings.txt?raw=true

**Comment by inkh0rn** [comment]
Yes it was kinda mess, but when you try to retrieve [[strings file](https://github.com/organicmaps/organicmaps/blob/master/data/strings/strings.txt)] as advised in [translations instructions](https://github.com/organicmaps/organicmaps/blob/master/docs/TRANSLATIONS.md) 
usings `wget https://github.com/organicmaps/organicmaps/blob/master/data/strings/strings.txt` 
that’s exactly what’s get pulled, 6mb files, don't know why? (maybe you can figure this out)
If you can, please add those strings below manually, few corrections and few new ones.

Thanks for replaying

**Comment by inkh0rn** [comment]
`<td id="LC105" class="blob-code blob-code-inner js-file-line">    pt-BR = Cancelar download</td>`

`<td id="LC218" class="blob-code blob-code-inner js-file-line">    pt-BR = O download falhou, toque para tentar de novo.</td>`

`<td id="LC663" class="blob-code blob-code-inner js-file-line">    pt-BR = Atualmente todos os serviços de localização para este dispositivo ou aplicativo estão desativados. Por favor ative-os em configurações.</td>`

`<td id="LC1035" class="blob-code blob-code-inner js-file-line">    pt-BR = Por favor desconecte o cabo USB ou insira um cartão de memória para usar o Organic Maps</td>`

`<td id="LC1296" class="blob-code blob-code-inner js-file-line">    pt-BR = Pausar</td>`

`<td id="LC1598" class="blob-code blob-code-inner js-file-line">    pt-BR = Meus locais</td>`

`<td id="LC2399" class="blob-code blob-code-inner js-file-line">    pt-BR = Vida noturna</td>`

`<td id="LC2830" class="blob-code blob-code-inner js-file-line">    pt-BR = Anotações</td>`

`<td id="LC2890" class="blob-code blob-code-inner js-file-line">    pt-BR = Olá!\n\nEm anexo estão incluídos meus favoritos do aplicativo Organic Maps. Se tiver instalado o Organic Maps, pode abri-los agora. Caso não tenha, baixe o app para seu dispositivo iOS ou Android via o link https://omaps.app/get?kmz\n\nDisfrute viajar com o Organic Maps!</td>`
        
`<td id="LC3111" class="blob-code blob-code-inner js-file-line">    pt-BR = Lamentamos, as configurações do armazenamento do mapa estão desativadas.</td>`
        </tr>

`<td id="LC3186" class="blob-code blob-code-inner js-file-line">    pt-BR = Veja onde estou agora. Abra o link: %1$@ ou %2$@ Não tem mapas offline instalados? Baixe aqui: https://omaps.app/get</td>`

`<td id="LC3260" class="blob-code blob-code-inner js-file-line">    pt-BR = Veja no mapa a minha localização atual no Organic Maps!</td>`
        </tr>

`<td id="LC4566" class="blob-code blob-code-inner js-file-line">    pt-BR = Permite salvar o caminho percorrido durante um determinado período de tempo e vê-lo no mapa. Note: esta opção usa mais bateria. O caminho será automaticamente apagado do mapa após um tempo.</td>`

`<td id="LC5621" class="blob-code blob-code-inner js-file-line">    pt-BR = Para apagar o mapa, por favor, pare a navegação.</td>`
        </tr>

`<td id="LC5997" class="blob-code blob-code-inner js-file-line">    pt-BR =  Para criar uma rota é necessário baixar e atualizar todos os mapas desde sua localização até seu destino.</td>`
        </tr>

`<td id="LC6580" class="blob-code blob-code-inner js-file-line">    es = Azul claro</td>`
        </tr>

`<td id="LC8009" class="blob-code blob-code-inner js-file-line">    pt-BR = Selecionar mapa</td>`

`<td id="LC8407" class="blob-code blob-code-inner js-file-line">    pt-BR = Histórico de busca</td>`

`<td id="LC8822" class="blob-code blob-code-inner js-file-line">    pt-BR = Apagar horário</td>`

`<td id="LC9003" class="blob-code blob-code-inner js-file-line">    pt-BR = Horário de funcionamento</td>`

`<td id="LC9039" class="blob-code blob-code-inner js-file-line">    pt-BR = Modo avançado</td>`
          
`<td id="LC9075" class="blob-code blob-code-inner js-file-line">    pt-BR = Modo simples</td>`
          
`<td id="LC9255" class="blob-code blob-code-inner js-file-line">    pt-BR = Você modificou o mapa-múndi. Não esconda isto! Diga aos seus amigos e edite junto com eles.</td>`

`<td id="LC9942" class="blob-code blob-code-inner js-file-line">    pt-BR = Abra conta no OSM</td>`

`<td id="LC10720" class="blob-code blob-code-inner js-file-line">    pt-BR = Selecione a culinária</td>`

`<td id="LC10877" class="blob-code blob-code-inner js-file-line">    pt-BR = Todas as edições no mapa serão eliminadas juntamente com o mapa.</td>`

`<td id="LC11633" class="blob-code blob-code-inner js-file-line">    pt-BR = Adicione novos lugares ao mapa e edite os já existentes diretamente no aplicativo.</td>`

`<td id="LC12176" class="blob-code blob-code-inner js-file-line">    pt-BR = Envie uma observação para os editores do OSM</td>`

`<td id="LC13725" class="blob-code blob-code-inner js-file-line">    pt-BR = Digite um número do telefone correto</td>`

`<td id="LC13761" class="blob-code blob-code-inner js-file-line">    pt-BR = Digite um endereço do site válido</td>`

`<td id="LC13797" class="blob-code blob-code-inner js-file-line">    pt-BR = Digite um endereço de email válido</td>`

`<td id="LC14267" class="blob-code blob-code-inner js-file-line">    pt-BR = Organic Maps é um aplicativo gratuito e rápido de mapas offline, sem anúncios e rastreamento. Os mapas são baseados em dados do OpenStreetMap.org, onde você mesmo pode corrigir os erros no mapa e adicionar característica novas. Organic Maps é um projeto de software livre, criado por entusiastas em seu tempo livre. Seu feedback e apoio são bem-vindos!</td>`

`<td id="LC14378" class="blob-code blob-code-inner js-file-line">    pt-BR = Recusar</td>`

`<td id="LC14849" class="blob-code blob-code-inner js-file-line">    pt-BR = Para mostrar os dados de tráfego, o aplicativo deve ser atualizado.</td>`

`<td id="LC15070" class="blob-code blob-code-inner js-file-line">    pt-BR = Usamos o TTS (texto-para-voz) do sistema para instruções de voz. Muitos dispositivos do Android implementam o TTS do Google, você pode baixá-lo ou atualizá-lo no Google Play (https://play.google.com/store/apps/details?id=com.google.android.tts)</td>`

`<td id="LC15070" class="blob-code blob-code-inner js-file-line">    pt-BR = Utilizamos o sistema TTS (texto-para-voz) para instruções de voz. Muitos dispositivos do Android usam o Google TTS, você pode baixá-lo ou atualizá-lo no Google Play (https://play.google.com/store/apps/details?id=com.google.android.tts)</td>`

`<td id="LC15333" class="blob-code blob-code-inner js-file-line">    pt-BR = Adicione um ponto final da viagem para planejar uma rota</td>`

`<td id="LC15407" class="blob-code blob-code-inner js-file-line">    pt-BR = Gerenciar a rota</td>`

`<td id="LC17280" class="blob-code blob-code-inner js-file-line">    pt-BR = Podemos usar seus dados para melhorar a experiência do Organic Maps. As mudanças terão efeitos após reiniciar o app.</td>`

`<td id="LC17660" class="blob-code blob-code-inner js-file-line">    pt-BR = Ocorreu um erro</td>`

`<td id="LC18018" class="blob-code blob-code-inner js-file-line">    pt-BR = Ocorreu um erro enquanto carregava as etiquetas, por favor, tente novamente</td>`

`<td id="LC18360" class="blob-code blob-code-inner js-file-line">    pt-BR = Modo de economia da bateria</td>`

`<td id="LC18512" class="blob-code blob-code-inner js-file-line">    pt-BR = Máxima economia da bateria</td>`

`<td id="LC18550" class="blob-code blob-code-inner js-file-line">    pt-BR = A opção ativa o logging para realizar diagnósticos. Pode ser útil para nossa equipe de suporte que estão solucionando problemas com o aplicativo. Ative esta opção apenas ao ser solicitado pelo suporte do Organic Maps.</td>`

`<td id="LC18892" class="blob-code blob-code-inner js-file-line">    pt-BR = Infelizmente, não conseguimos encontrar uma rota, provavelmente por causa das opções escolhidas. Por favor, altere as configurações e tente novamente</td>`

`<td id="LC20214" class="blob-code blob-code-inner js-file-line">    pt-BR = Alertas de velocidade</td>`

`<td id="LC21080" class="blob-code blob-code-inner js-file-line">    pt-BR = Natação</td>`

`<td id="LC21564" class="blob-code blob-code-inner js-file-line">    pt-BR = A navegação por metrô ainda não está disponível nesta região</td>`

----------------

**And here are the part with new strings, not translated yet for ptbr:**

`<td id="LC22315" class="blob-code blob-code-inner js-file-line">    en = Unable to create folder and move files on internal device´s memory or sdcard</td>`

ptbr = Não foi possível criar a pasta e mover os arquivos à memória interna ou sdcard do dispositivo

`<td id="LC22346" class="blob-code blob-code-inner js-file-line">    en = Disconnect USB cable</td>`
ptbr = Desconecte o cabo USB

`<td id="LC22439" class="blob-code blob-code-inner js-file-line">    en = Show on the lock screen</td>`

ptbr = Mostrar quando a tela de bloqueio está ativa

`<td id="LC22453" class="blob-code blob-code-inner js-file-line">    en = When enabled, you don´t need to unlock your device every time while the app is running.</td>`

ptbr = Quando ativado, você não precisará debloquear seu dispositivo toda vez que o aplicativo estiver funcionando

`<td id="LC22639" class="blob-code blob-code-inner js-file-line">    en = Delete Track</td>`

ptbr = Apagar a rota

`<td id="LC22656" class="blob-code blob-code-inner js-file-line">    en = Track Name</td>`

ptbr = Nome da rota

`<td id="LC22672" class="blob-code blob-code-inner js-file-line">    en = Move</td>`
ptbr = Mover

**Comment by biodranik** [comment]
The proper link is this one ("Raw" button on your link): https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/strings/strings.txt

**Pull request closed without merging**
