### PR TITLE
[styles] lighting icon for future use

### PR DESCRIPTION
**Pull request by RedAuburn**
Modified icon from https://commons.wikimedia.org/wiki/File:Simpleicons_Interface_lightbulb-with-a-bolt.svg (Creative Commons Attribution 3.0 Unported)

image

### CODE REVIEW

**Review by patepelo — APPROVED** [review]

**Comment by RedAuburn** [comment]
merge? @biodranik

**Comment by pastk** [comment]
Why do we need an unused icon in the repo?

**Comment by RedAuburn** [comment]
> Why do we need an unused icon in the repo?

so it's there if someone wants it in future :)

**Comment by pastk** [comment]
We can keep it here in a draft PR and use when/if its needed.

Otherwise it risks sitting in the repo and not getting used for years :) Its better to keep the repo clutter-free.

**Comment by RedAuburn** [comment]
fair enough 👍️

**Pull request closed without merging**
