### PR TITLE
[android] Updated Turkish Screenshots and Full Description

### PR DESCRIPTION
**Pull request by MetehanOzyurek**
* New screenshots in Airplane mode
* Added Turkish screenshots for Android tablets
* All in PNG format
* New screenshots don't include navigation bar
* New directory for tablet screenshots
* Contains new features like ascent and descent at altitude
* Screenshots for new UI (bottom bar)
* Added more screenshots
* Fixed minor typo in play store /f-droid full description

### CODE REVIEW

**Review by biodranik — COMMENTED** [review]
Thanks! It is possible to have up to 8 screenshots btw.

You can also provide screenshots for other devices (tablets), if you have a tablet or can run OM in Emulator. Folder names for tablets are described here:
https://f-droid.org/docs/All_About_Descriptions_Graphics_and_Screenshots/#triple-t-structure

**Comment by csidirop** [comment]
General question: are language specific screenshots wanted?

**Comment by MetehanOzyurek** [comment]
> Thanks! It is possible to have up to 8 screenshots btw.
> 
> You can also provide screenshots for other devices (tablets), if you have a tablet or can run OM in Emulator. Folder names for tablets are described here:
> https://f-droid.org/docs/All_About_Descriptions_Graphics_and_Screenshots/#triple-t-structure

Yes I have, so I'm adding:)

**Comment by biodranik** [comment]
> General question: are language-specific screenshots wanted?

YES! Good screenshots highlighting some unique or interesting local features that are not present in Google or Apple maps help users to decide to try Organic Maps :)

**Comment by MetehanOzyurek** [comment]
@biodranik added tablet screenshots

**Review by biodranik — CHANGES_REQUESTED** [review]
1. Please put all portrait smartphone (up to 8) into `phone-screenshots` folder. For tablet, you need to put them (up to 8 screenshots) into `tablet-screenshots` folder.
2. Please also consider using png images if possible, they do not lose their quality unlike jpg
3. Please enable Airplane/Flight mode for all screenshots, so it will be clear that Organic Maps works fully in offline mode.

**Comment by MetehanOzyurek** [comment]
> 1. Please put all portrait smartphone (up to 8) into `phone-screenshots` folder. For tablet, you need to put them (up to 8 screenshots) into `tablet-screenshots` folder.
> 2. Please also consider using png images if possible, they do not lose their quality unlike jpg
> 3. Please enable Airplane/Flight mode for all screenshots, so it will be clear that Organic Maps works fully in offline mode. 

@biodranik Is it enough that offline screenshots are only for the phone?  It's hard to take and send screenshot from tablet.

**Comment by MetehanOzyurek** [comment]
done👌

**Review by rtsisyk — CHANGES_REQUESTED** [review]
Screenshots are too big to fit into the main repo. There is another repo that contains all screenshots. Let me check permissions and open it first.

**Comment by rtsisyk** [comment]
> Screenshots are too big to fit into the main repo. There is another repo that contains all screenshots. Let me check permissions and open it first.

@MetehanOzyurek, screenshots are great! Thanks a lot!

I've pushed updated full description into master and uploaded screenshots to Google Play. The problem is that screenshots are too large to push into the main repo. I will explore alternative options and come up with some solution later. Google Play will be updated soon in any case. Sorry for the delay.

**Comment by MetehanOzyurek** [comment]
@rtsisyk Can you also replace the screenshots at organicmaps.app/tr with these?

**Comment by Jean-BaptisteC** [comment]
You can create PR here https://github.com/organicmaps/organicmaps.github.io to publish screenshots on website

**Comment by rtsisyk** [comment]
New screenshots are coming to the next release. Please stay tuned. A PR is coming soon.

**Pull request closed without merging**
