### PR TITLE
[bookmarks] Script to convert Google Maps Places to KML

### PR DESCRIPTION
**Pull request by fabwu**
This script converts a CSV file exported from Google Takeout to a KML file. A user can import this KML file to Organic Maps to transfer saved places in Google Maps to Organic Maps bookmarks. The script requires an API key because it needs to look up the coordinates from the Google Places API.

See https://github.com/orgs/organicmaps/discussions/928

### CODE REVIEW

**Comment by fabwu** [comment]
Here's a screen recording of the workflow:

https://github.com/user-attachments/assets/21f17b3d-6f0d-47be-a904-e2f3eb772ede

**Comment by fabwu** [comment]
I've recently moved my saved places (>1000) from Google Maps to Organic Maps and could only find [this script](https://github.com/d1820/GoogleMapExport2KML) for the conversion to KML. The script is written in .NET and I couldn't get it working on my Mac so I created this little python script to make the transition from Google Maps smoother.

It would be great if Organic Maps could support a transition path from Google Maps to motivate more users to switch. Here's a little roadmap with additional features for this script:

- [ ] Add FAQ entry on organicmaps.app
- [ ] Support GeoJson (Starred Places are exported as GeoJson)
- [ ] Concurrent requests to Places API to speed up conversion of many bookmarks

**Comment by strump** [comment]
@fabwu thanks for the script. Could you please update it to get parameters from command line?

The script should be invokable like this:

```shell
python google_maps_bookmarks.py --api_key=XXXYYYXXX --input=bookmarks.csv --output=bookmarks.kml
```

You can use [argparse](https://docs.python.org/3/library/argparse.html) from standard Python library.

**Comment by biodranik** [comment]
Am I correctly understanding that exported CSV require the API to convert coordinates, while exported GeoJSON already has necessary coordinates?

**Comment by strump** [comment]
@biodranik CSV file contains only URLs in format: `https://www.google.com/maps/place/Dearborn+Station/data=!4m2!3m1!1s0x880e2c976c23a915:0x8adc64871d741682` which requires API key to export. While GeoJson is more human readable.

I found that in Google Maps you can save bookmark either into "Favorites" list or in "Starred places" list



And "Favorites" are exported to CSV while "Starred places" to GeoJSON.

**Comment by fabwu** [comment]
> @fabwu thanks for the script. Could you please update it to get parameters from command line?
> 
> The script should be invokable like this:
> 
> ```shell
> python google_maps_bookmarks.py --api_key=XXXYYYXXX --input=bookmarks.csv --output=bookmarks.kml
> ```
> 
> You can use [argparse](https://docs.python.org/3/library/argparse.html) from standard Python library.

I think it’s easier for the user to have the interactive input or why do you want args?

**Comment by soshial** [comment]
AFAIR, only Starred places are exported in Google Takeout. All others are not importable.

**Comment by fabwu** [comment]
> AFAIR, only Starred places are exported in Google Takeout. All others are not importable.

You can export all lists from Google Takeout.

For starred places you select _Maps (My Places_) and they are exported in a GeoJson file. For all other lists you can select _Saved_ and they are exported in a CSV file.

This script supports only CSV files but it should be easy to add support for GeoJson.

**Comment by soshial** [comment]
What about `Labelled places.json` that contains all labels. Does this script processes those as well, @fabwu ? AFAIU, this is not the same as notes of starred places.

**Comment by fabwu** [comment]
> What about `Labelled places.json` that contains all labels? Does this script processes those as well, @fabwu ? AFAIU, this is not the same as notes of starred places.

Nope, not at the moment but I can add support for that later.

@rtsisyk Is there anything that prevents this from getting merged?

**Comment by fabwu** [comment]
@biodranik Any change we get this merged?

**Comment by biodranik** [comment]
I'm trying to understand the difference between this approach and another one:
1. Export geojson with Google Takeout
2. Convert geojson to kml (without any google API key!)

What are the pros here? I see that API key is required. that's a stopper for most of the people.

**Comment by fabwu** [comment]
> I'm trying to understand the difference between this approach and another one:
> 
>     1. Export geojson with Google Takeout
> 
>     2. Convert geojson to kml (without any google API key!)
> 
> 
> What are the pros here? I see that API key is required. that's a stopper for most of the people.

Google Takeout exports the bookmarks in several formats:

image

The _Starred places_ list is exported to GeoJSON and doesn't require an API key. This script doesn't support GeoJSON yet. 

All the other lists are exported as a CSV. As you can see in the example below, all we have is a title and an URL:
```csv
Titel,Notiz,URL,Kommentar
Toluca de Lerdo,,https://www.google.com/maps/place/Toluca+de+Lerdo/data=!4m2!3m1!1s0x85cd89892a50ebb9:0xad3f4ad5550208c4,
```
The script calls the Google Places API to decode this URL and get the coordinates back. That's the reason for the API key. 

I can add GeoJSON support and ask for the API key only if the script encounters a URL. @biodranik What do you think?

**Review by biodranik — APPROVED** [review]
For some reason, I see different files after exporting Maps and Maps (your places):
выява

Also, I didn't see an option to choose a CSV, everything was in .geojson.

More importantly, I see that many `.geojson` encoded places do not have coordinates and use a link to google maps with a cid ID. So looks like the API key will be needed anyway.

Ok, let's move on and improve it later.

**Comment by biodranik** [comment]
Or... can we extract coordinates from the url without an API key?

```
    {
      "geometry": {
        "coordinates": [
          0,
          0
        ],
        "type": "Point"
      },
      "properties": {
        "date": "2018-06-13T23:05:33Z",
        "google_maps_url": "http://maps.google.com/?q=1459+Jefferson+St,+San+Francisco,+CA+94123&ftid=0x8085812819e9ca1f:0x4f76c50c8bf93800",
        "Comment": "No location information is available for this saved place"
      },
      "type": "Feature"
    },

```

**Comment by zyphlar** [comment]
@biodranik afaik querying Google will be required to get coordinates unless we're very lucky and we know exactly where 1459 Jefferson St is (ignoring of course that where the user wants that marker, where Google has/had it, may not be where OSM has it. Sometimes people will bookmark specific entrances or features etc and be upset if it moves.)

Really unfortunate that Google bookmarks URLs ("places") instead of coordinates

**Comment by fabwu** [comment]
> For some reason, I see different files after exporting Maps and Maps (your places):

@biodranik You must select _Saved_ to get the CSVs:

image

Sorry it's in German but I heard you're learning ;)

> Or... can we extract coordinates from the url without an API key?

I agree with @zyphlar. Also the urls in the CSV don't have a address included. It's just the ftid.

**Pull request merged**
