### PR TITLE
[doc] try to document tools/python/stylesheet/cat_stat.py

### PR DESCRIPTION
**Pull request by matkoniecz**
added based on my understanding, code reading and testing - still, may be wrong

### CODE REVIEW

**Comment by matkoniecz** [comment]
https://github.com/organicmaps/organicmaps/issues/3917 will be my next step, I guess

**Review by biodranik — APPROVED** [review]

**Comment by biodranik** [comment]
Let's polish this script too:
- Make sure that it runs on python3
- Document how to set it up and use: now I see this error
```
✗ tools/python/stylesheet/cat_stat.py     
Traceback (most recent call last):
  File "/Users/alex/Developer/omim/omim/tools/python/stylesheet/cat_stat.py", line 3, in <module>
    import drules_struct_pb2
  File "/Users/alex/Developer/omim/omim/tools/python/stylesheet/drules_struct_pb2.py", line 6, in <module>
    from google.protobuf.internal import enum_type_wrapper
ModuleNotFoundError: No module named 'google'
```

**Comment by matkoniecz** [comment]
I am pretty sure that it run on p3 and I run it in this way.

I will try to test it in clean VM to check what is going on here, I guess.

**Comment by matkoniecz** [comment]
Extracted to https://github.com/organicmaps/organicmaps/issues/5060 - I thought that there is such existing dependency file but seems to be missing, likely I had dependencies already installed by accident

**Pull request merged**
