### PR TITLE
[android] Added a privacy preference as per the issue #6186

### PR DESCRIPTION
**Pull request by sandy99405**
Created a privacy preference under general settings which should be enabled by default to hide the search history as per the issue #6186.

### CODE REVIEW

**Comment by pastk** [comment]
What's your plan with this PR?
Its not functional at the moment, I see just a layout stub added for the setting.
Are you going to add the actual keep/discard search history functionality in later commits?

**Comment by sandy99405** [comment]
@pastk yes I am working on it right now

**Comment by biodranik** [comment]
Having this option in the context (in the search history dialog) would be clearer to users. Otherwise, they may not get the meaning of the option immediately.

**Comment by pastk** [comment]
> @pastk yes I am working on it right now

Great, many thanks!

Maybe mark the PR as a draft then (until its ready to be reviewed and merged) - to make its status more clear and to prevent accidental merges of WIP code.

**Comment by sandy99405** [comment]
@pastk can i remove the previous clear search history button ? because after adding the privacy switch in the settings don't need it right?

**Comment by sandy99405** [comment]
and one more clarification..... should the search data be stored even if the switch is on and show the history when the switch is off ? or erase all the search data completely and start storing new searches when the privacy switch is off

**Comment by sandy99405** [comment]
@pastk and @biodranik please clarify so that i can work on it as quickly as possible

**Comment by biodranik** [comment]
Check the related issue.

**Comment by sandy99405** [comment]
@biodranik so is it ok if I remove the functionality of TYPE_CLEAR in CreatViewHolder in SearchHistoryAdapter and add a new flag which tells that the switch is on or off ?

**Comment by sandy99405** [comment]
> @biodranik so is it ok if I remove the functionality of TYPE_CLEAR in CreatViewHolder in SearchHistoryAdapter and add a new flag which tells that the switch is on or off through the getItemViewType?

**Comment by biodranik** [comment]
1. Please rebase your branch to fix conflicts.
2. Please provide screenshots or screen recordings of what have you changed.

**Comment by biodranik** [comment]
Please note that we don't use merge, only rebase.

**Comment by sandy99405** [comment]
Screenshots of the changed code:

### PrivacyTabAdapter.java
https://github.com/sandy99405/ChangedCodePics/blob/main/PrivacyTabAdapter/Screenshot%20(396).png
https://github.com/sandy99405/ChangedCodePics/blob/main/PrivacyTabAdapter/Screenshot%20(397).png
https://github.com/sandy99405/ChangedCodePics/blob/main/PrivacyTabAdapter/Screenshot%20(398).png
https://github.com/sandy99405/ChangedCodePics/blob/main/PrivacyTabAdapter/Screenshot%20(399).png
https://github.com/sandy99405/ChangedCodePics/blob/main/PrivacyTabAdapter/Screenshot%20(400).png
https://github.com/sandy99405/ChangedCodePics/blob/main/PrivacyTabAdapter/Screenshot%20(401).png

### SearchFragment.java
https://github.com/sandy99405/ChangedCodePics/blob/main/SearchFragments/Screenshot%20(394).png
https://github.com/sandy99405/ChangedCodePics/blob/main/SearchFragments/Screenshot%20(395).png

### SettingsPrefsFragment.java
https://github.com/sandy99405/ChangedCodePics/tree/main/SettingsPrefsFragment
https://github.com/sandy99405/ChangedCodePics/blob/main/SettingsPrefsFragment/Screenshot%20(392).png
https://github.com/sandy99405/ChangedCodePics/blob/main/SettingsPrefsFragment/Screenshot%20(393).png

### config.java
https://github.com/sandy99405/ChangedCodePics/blob/main/config/Screenshot%20(386).png
https://github.com/sandy99405/ChangedCodePics/blob/main/config/Screenshot%20(387).png

### prefs_main.xml
https://github.com/sandy99405/ChangedCodePics/blob/main/prefs_main/Screenshot%20(390).png

### strings.xml
https://github.com/sandy99405/ChangedCodePics/blob/main/strings/Screenshot%20(389).png

### donottranslate.xml
https://github.com/sandy99405/ChangedCodePics/blob/main/donottranslate/Screenshot%20(388).png

**Comment by sandy99405** [comment]
@biodranik so what do we don now ?

**Comment by Jean-BaptisteC** [comment]
Not screenshots of changes in code, screenshots from settings in Organic Maps with your changes

**Comment by sandy99405** [comment]
> Not screenshots of changes in code, screenshots from settings in Organic Maps with your changes

@Jean-BaptisteC  How can I implement that ? it's not possible right

**Comment by Jean-BaptisteC** [comment]
Build app, run and take screenshots of your changes in app

**Comment by sandy99405** [comment]
> Build app, run and take screenshots of your changes in app

ok done👍

**Comment by sandy99405** [comment]
> Build app, run and take screenshots of your changes in app
@Jean-BaptisteC 
@biodranik 
Where can i find the BuildConfig file ? It is used in every file but I cannot find the BuildConfig file

**Comment by Jean-BaptisteC** [comment]
To build app, follow instructions available [here](https://github.com/organicmaps/organicmaps/blob/master/docs/INSTALL.md) 

Errors when I try to compile app:
```
/home/runner/work/organicmaps/organicmaps/android/app/src/main/java/app/organicmaps/settings/SettingsPrefsFragment.java:817: error: cannot find symbol
    private SearchHistoryAdapter searchHistoryAdapter = new SearchHistoryAdapter(controller,showMyPosition);
            ^
  symbol:   class SearchHistoryAdapter
  location: class SettingsPrefsFragment
/home/runner/work/organicmaps/organicmaps/android/app/src/main/java/app/organicmaps/settings/SettingsPrefsFragment.java:819: error: cannot find symbol
    private SearchFragment searchFragment = new SearchFragment();
            ^
  symbol:   class SearchFragment
  location: class SettingsPrefsFragment
/home/runner/work/organicmaps/organicmaps/android/app/src/main/java/app/organicmaps/util/Config.java: error: cannot find symbol
     public static void setSuperPrivacyToSharedPrefs(@NonNull SettingsPrefsFragment context) {
                                                              ^
  symbol:   class SettingsPrefsFragment
  location: class Config
```

**Comment by sandy99405** [comment]
@Jean-BaptisteC 

Ive been getting the CMakelists.txt error : 

I need to change few files and directories


C/C++: CMake Error at 3party/CMakeLists.txt:17 (add_subdirectory):
C/C++:   add_subdirectory given source "expat/expat" which is not an existing
C/C++:   directory.
C/C++: CMake Error at 3party/jansson/jansson/expat/expat/CMakeLists.txt:17 (add_subdirectory):
C/C++:   add_subdirectory given source "expat" which is not an existing directory.
C/C++: CMake Error at 3party/jansson/jansson/expat/expat/CMakeLists.txt:25 (add_subdirectory):
C/C++:   add_subdirectory given source "jansson/jansson/" which is not an existing
C/C++:   directory.
C/C++: CMake Error at 3party/jansson/jansson/expat/expat/CMakeLists.txt:26 (target_include_directories):
C/C++:   Cannot specify include directories for target "jansson" which is not built
C/C++:   by this project.


Can you please help me with this ?

**Comment by Jean-BaptisteC** [comment]
Did you have follow instructions here https://github.com/organicmaps/organicmaps/blob/master/docs/INSTALL.md
I think, you don't have submodules on your computer

**Comment by sandy99405** [comment]
@Jean-BaptisteC 

I have done everything until installing NDK 

how can get the submodules in my PC ?

**Comment by sandy99405** [comment]
@Jean-BaptisteC  are you saying that jansson is a submodule and i have to add it in my local organicmaps repository ?

**Comment by sandy99405** [comment]
@Jean-BaptisteC    @biodranik 

D:/git/organicmaps/3party/boost/libs/utility/include/boost/utility.hpp:15:10: fatal error: 'boost/utility/base_from_member.hpp' file not found
#include <boost/utility/base_from_member.hpp>


can you help me set the path of the directories in cmakelists.txt files as per my PC's folder path.
This way the error will be solved I guess.

**Comment by Jean-BaptisteC** [comment]
Check this part of install documentation to get submodules.
https://github.com/organicmaps/organicmaps/blob/master/docs/INSTALL.md#getting-sources

**Comment by sandy99405** [comment]
@Jean-BaptisteC @biodranik   I have intsalled all the submodules recursively but yet it is showing the error : 

D:/git/organicmaps/3party/boost/libs/utility/include/boost/utility.hpp:15:10: fatal error: 'boost/utility/base_from_member.hpp' file not found
#include <boost/utility/base_from_member.hpp>

it's(Android studio) unable to find the files in the organicmaps/3party/boost directory 

Note :  I'm opening the android folder in the Android studio.

**Comment by sandy99405** [comment]
No I didn't enable it

**Comment by Jean-BaptisteC** [comment]
Like mentionned in install documentation, you need to enable symlinks in git

**Comment by sandy99405** [comment]
ok I will do it. Thank you for the help 👍

**Pull request closed without merging**
