### PR TITLE
[styles] add drules for Metro area icons

### PR DESCRIPTION
**Pull request by RedAuburn**
~~Fixes https://github.com/organicmaps/organicmaps/issues/4120~~

edit:
the [station](https://www.openstreetmap.org/way/65203864) is `railway-station-subway` not `railway-station-subway-lille`. It seems that the MatchCity() function doesn't work for areas

### CODE REVIEW

**Comment by vng** [comment]
Thanks for the example! I doubt that it will fix the problem, but I'll check generator.

**Comment by endim8** [comment]
> Thanks for the example! I doubt that it will fix the problem, but I'll check generator.

Thank you <3 I've been trying to implement it but without much luck, it _may_ be something to do with way types not being assigned `m_lat` & `m_lon` In osm2type.cpp, but that's as far as I got

**Comment by biodranik** [comment]
@vng is it still actual?

**Comment by vng** [comment]
No, issue #4120 is actual.

**Pull request closed without merging**
