### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [OrganicMaps/Apple AppStore Metadata](https://hosted.weblate.org/projects/organicmaps/apple-appstore-metadata/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by MetehanOzyurek — COMMENTED** [review]
I'll edit translation today
I found some minor mistakes

**Comment by biodranik** [comment]
@MetehanOzyurek did you fix it on Weblate? Won't it override these commits?
@rtsisyk can you please merge these updated changes now, before they are overridden by Weblate?

**Comment by biodranik** [comment]
@rtsisyk please check before merge if support url is a proper symlink.

**Comment by MetehanOzyurek** [comment]
> @MetehanOzyurek did you fix it on Weblate? Won't it override these commits? @rtsisyk can you please merge these updated changes now, before they are overridden by Weblate?

@biodranik no, fixed on GitHub (web)
I've already added 3 commits
https://github.com/organicmaps/organicmaps/pull/3810/commits/7bdd285535c033a586b8ce1c4eed0e242930f257
https://github.com/organicmaps/organicmaps/pull/3810/commits/f3acbc725c46b6a023a3394937735aac0faa1b19

But this commit isn't looks correct:
https://github.com/organicmaps/organicmaps/pull/3810/commits/232bc3f47b7cabd631dea34cce21dbd72a7c984a

**Comment by MetehanOzyurek** [comment]
LOL, it took back my edits🤦‍♂️

**Comment by MetehanOzyurek** [comment]
> LOL, it took back my edits🤦‍♂️

@biodranik can you redo my edits? Or is it possible?

**Comment by biodranik** [comment]
@MetehanOzyurek yes, I'll take a look later.

**Comment by biodranik** [comment]
@MetehanOzyurek I have integrated your changes. Let's merge this PR if it's OK until it is not overridden again by Weblate.

**Review by MetehanOzyurek — APPROVED** [review]

**Comment by MetehanOzyurek** [comment]
> @MetehanOzyurek I have integrated your changes. Let's merge this PR if it's OK until it is not overridden again by Weblate.

OK you can merge with my changes

**Review by biodranik — APPROVED** [review]

**Pull request merged**
