### PR TITLE
[strings] Add "avoid" keyword for routing options

### PR DESCRIPTION
**Pull request by dvdmrtnz**
I've finished the work started in https://github.com/organicmaps/organicmaps/issues/5796

Closes #5796

| iOS | Android |
|-|-|
|  |  |

* Closes https://github.com/organicmaps/organicmaps/pull/5796
* Closes https://github.com/organicmaps/organicmaps/issues/5779

### CODE REVIEW

**Comment by dvdmrtnz** [comment]
@sciunto, @map-per, @matheusgomesms, @pastk, @biodranik, Can you recheck translations?

**Review by pastk — APPROVED** [review]
Thanks for finishing it!

**Comment by Jean-BaptisteC** [comment]
CI Android fail because you have removed strings used on Android Auto here -> https://github.com/organicmaps/organicmaps/blob/e07eaca2dbe9056b3d6434fa9ce6d3c7a8772bd5/android/app/src/main/java/app/organicmaps/car/screens/settings/DrivingOptionsScreen.java#L97

@AndrewShkrob Title is necessary on builder?

**Comment by dvdmrtnz** [comment]
> CI Android fail because you have removed strings used on Android Auto here ->
> 
> https://github.com/organicmaps/organicmaps/blob/e07eaca2dbe9056b3d6434fa9ce6d3c7a8772bd5/android/app/src/main/java/app/organicmaps/car/screens/settings/DrivingOptionsScreen.java#L97
> 
> Replace this string by driving_options_title string

Thanks! Done

**Review by Jean-BaptisteC — APPROVED** [review]
✅ Pixel 6 - Android 14 + AA Emulator

**Review by biodranik — APPROVED** [review]
Thank you! @AndrewShkrob @Jean-BaptisteC does it look good on AA? Also, please check if the longest string from some language properly fits on the screen in AA and on normal devices.

**Comment by RicoElectrico** [comment]
Isn't there basically an identical label when you tap a red :exclamation: pin on a route?

**Comment by biodranik** [comment]
@RicoElectrico which one? Can you please send a screenshot from the recent master with this change?

**Comment by RicoElectrico** [comment]
I am talking about `avoid_unpaved_roads_placepage` and so on. We could unify them.

image

**Review by map-per — COMMENTED** [review]
German translations look good 👍

**Comment by AndrewShkrob** [comment]
> Thank you! @AndrewShkrob @Jean-BaptisteC does it look good on AA? Also, please check if the longest string from some language properly fits on the screen in AA and on normal devices.

It looks good, in my opinion.

Screenshot 2023-10-07 at 14 11 17
Screenshot 2023-10-07 at 14 12 33

**Comment by biodranik** [comment]
@AndrewShkrob strings in AA are truncated. Is there a way to increase the dialog size or reduce the font size to fit strings properly? If there is no such way, we need to rewrite strings, at least for AA, taking into account the max possible length. Can you please create an issue for that?

**Comment by dvdmrtnz** [comment]
> I am talking about `avoid_unpaved_roads_placepage` and so on. We could unify them.
> 
> image

Nice catch! Will make a PR

**Comment by sciunto** [comment]
Perfect! thank you!

**Review by d4f5409d — APPROVED** [review]
Approved hu translation

**Pull request merged**
