### PR TITLE
Patch for issue #4333

### PR DESCRIPTION
**Pull request by Shura0**

### CODE REVIEW

**Comment by vng** [comment]
Better work with "git rebase" flow (not merge), and leave only one commit here.
Otherwise we have strange last 3 commits now ..

**Comment by Shura0** [comment]
is it possible to make it in github ui?

**Comment by biodranik** [comment]
@Shura0 it is easy to do from the command line. There are many tutorials on how to rebase properly. It saves a lot of time for you and us to review the code.

**Comment by Shura0** [comment]
it is not easy to configure fucking github auth. I'll better send you a patch

**Comment by Shura0** [comment]
[voice_fix.zip](https://github.com/organicmaps/organicmaps/files/10527798/voice_fix.zip)
patch

**Pull request closed without merging**
