### PR TITLE
[styles] Add gate icon

### PR DESCRIPTION
**Pull request by endim8**
Uses carto icon, modified to have border
Also renamed airport gate icon to avoid confusion

before/after
Screenshot from 2023-04-22 20-02-53

### CODE REVIEW

**Review by vng — APPROVED** [review]

**Comment by biodranik** [comment]
It doesn't look like a gate. Are there other, easier to recognize icons?

**Comment by matheusgomesms** [comment]
IMO, the problem with using other icons (than the simple one used by Carto and proposed here) is that on OSM you can specifiy the type of gate. Therefore, using another more recognizable icon can actually conflict with the gate type on [OSM tags](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dgate).

**Comment by endim8** [comment]
> It doesn't look like a gate. Are there other, easier to recognize icons?

On most maps, there are no gate symbols. Some maps use a single line, which is even more confusing. 
IMO the symbol is pretty easy to infer as representing a gate due to context clues, and the simplicity of the symbol prevents visual noise.
Using a realistic icon would probably be too small/thin to recognise. As Matheus said, using the carto icons is an easy solution as there are many gate types :)

**Comment by biodranik** [comment]
Agree, it's better than a dot.

**Pull request merged**
