### PR TITLE
Add area color to `leisure=sports_centre` and remove from `sport=*`

### PR DESCRIPTION
**Pull request by dvdmrtnz**
This PR adds a lighter shade of color to `leisure=sports_centre` and removes the area color from `sport=*`. Pitches and sports centers themselves should have the area shading, not the sports denomination.

* Fixes https://github.com/organicmaps/organicmaps/issues/9164
* Fixes https://github.com/organicmaps/organicmaps/issues/4086
* Fixes https://github.com/organicmaps/organicmaps/issues/4967

Before/after:

### CODE REVIEW

**Comment by biodranik** [comment]
LGTM, @pastk @vng PTAL

**Review by vng — APPROVED** [review]

**Review by map-per — COMMENTED** [review]
- leisure=stadium has the same problem as sports_centre, so it would make sense to also use the lighter color there as well

- maybe name the colour 'sports_grounds' instead of 'sport0'

**Comment by dvdmrtnz** [comment]
> * leisure=stadium has the same problem as sports_centre, so it would make sense to also use the lighter color there as well
> * maybe name the colour 'sports_grounds' instead of 'sport0'

Is there a case where a pitch is inside a stadium inside a sports centre? We may need three colors instead of two? 🤔

**Comment by map-per** [comment]
Damn, this exists: https://www.openstreetmap.org/way/576045130, https://www.openstreetmap.org/way/1177107913, https://www.openstreetmap.org/way/318702399

**Comment by dvdmrtnz** [comment]
I've tweaked the stadium color to be a slightly different shade too

**Comment by vng** [comment]
@pastk

**Comment by vng** [comment]
Please, rebase.

**Comment by dvdmrtnz** [comment]
Rebased

**Pull request merged**
