### PR TITLE
Fix french translations

### PR DESCRIPTION
**Pull request by Jean-BaptisteC**
This PR fixes comments in #6296 and regenerates translations

### CODE REVIEW

**Review by biodranik — APPROVED** [review]
Thanks! How did it happen that a broken strings.txt was merged? Did the strings check failed in the PR before the merge? Did reviewers miss it?

**Comment by Jean-BaptisteC** [comment]
That's weird, in the other PR, 0 checks have started.

**Comment by biodranik** [comment]
In which one? PRs from from first-time contributors need manual approval first.

**Comment by Jean-BaptisteC** [comment]
In #6296
I see workflow only for cleanup caches

**Pull request merged**
