### PR TITLE
[ios] fix: Text trimming on the Menu screen on small screen #7605

### LINKED ISSUE #7605: [ios] Text trimming on the Menu screen on small screen
Text in the Menu screen cells can be trimmed on the small screen.

Simulator iPhone SE 1st gen iOS 15:
image

This issue happens because of the Menu cell layout issue: it contains an image pinned to the trailing but this image is usually invincible except in some situations. But in both cases, it takes some place and decrease Label's width which cause the trimming. 

image

### How to fix:
The trailing Image should have zero width when it is hidden, and standard width when it's visible.

image

### PR DESCRIPTION
**Pull request by v-lozko**
Update the xib and swift files related to BottomMenuItemCell to address the issue seen in fixed #7605 issue.

Screenshot 2024-03-25 at 12 20 53 PM

Tested on Simulator iPhone SE 1st gen iOS 15

### CODE REVIEW

**Comment by Jean-BaptisteC** [comment]
@v-lozko can you check case mentionned here -> #6213

**Comment by v-lozko** [comment]
Here it is simulated on an iphone 15
Screenshot 2024-03-25 at 4 01 44 PM

**Review by biodranik — APPROVED** [review]
Thanks for the elegant fix!

Can you please also check if German language fits?

**Comment by v-lozko** [comment]
Here it is in German
Screenshot 2024-03-25 at 7 43 24 PM

**Comment by biodranik** [comment]
@v-lozko thanks, it's better to fix different issues in different pull-requests (using different git branches)

**Comment by v-lozko** [comment]
Yeah, messed up by not creating a new branch for the other issue. Its been corrected now though

**Comment by v-lozko** [comment]
yes, here is a screenshot from iphone 15 simulator. 
Screenshot 2024-03-26 at 12 39 09 PM

**Review by kirylkaveryn — APPROVED** [review]

**Comment by v-lozko** [comment]
it seems like the PR failed due to a check. Did i mess something up with the commit?

**Comment by biodranik** [comment]
`Signed-off-by: Valery Lozko <valerylozko@gmail.com>`

Is this email registered with the GitHub? For some reason, DCO check fails with it.

**Comment by v-lozko** [comment]
It is, it's tied to this github account.

**Comment by biodranik** [comment]
Check if the same email/user name is set in your ~/.gitconfig
And amend the commit with `git commit --amend --author="John Doe <john@doe.org>"`

**Comment by v-lozko** [comment]
Sorry about that, it looks like i had my name as 'Val' in git config. I amended the commit but am unable to push it as I didn't make a commit on a branch. Sorry, i'm a bit new to this all. Would it be easier to close this PR and i create a new one with the commit on a branch?

**Comment by biodranik** [comment]
if you already amended commit on your local branch `master`, make a `git push -f`

In the future, after merging this commit, it's better to create a separate branch for each pull request, and keep local master branch always synchronized with the main repo master.

**Comment by v-lozko** [comment]
yeah, its a lesson learned, thank you.

**Comment by Jean-BaptisteC** [comment]
@biodranik @rtsisyk ready to merge

**Comment by v-lozko** [comment]
Hello, I inadvertently closed this PR as I originally didn't have this change on a branch. I created a new PR here for closing this:

https://github.com/organicmaps/organicmaps/pull/7898

**Pull request closed without merging**
