### PR TITLE
[strings] Updated Norwegian translations

### PR DESCRIPTION
**Pull request by tkbremnes**
Tried running the `git submodule update --init --recursive`, but it failed.

Do you prefer these as a single commit, or as these three separate ones? I can easily squash them.

### CODE REVIEW

**Review by biodranik — APPROVED** [review]
Thanks! You may squash them and create a separate commit after regenerating strings with tools/unix/generate_localizations.sh

What was your error with submodules?

**Comment by tkbremnes** [comment]
Ah, hehe, I was a bit imprecise here. I tried running `tools/unix/generate_localizations.sh`, but after installing all dependencies I could not get past the submodule issue I mentioned – without spending time debugging more, which I don't have at the moment. I do intend to try to fix it, but that won't be until _maybe_ tonight, maybe this weekend.

**Comment by tkbremnes** [comment]
Trying to re-run the script I now see that I might have made an error. Fixing.

**Comment by tkbremnes** [comment]
Squashed, fixed and added regenerated commit.

**Review by biodranik — CHANGES_REQUESTED** [review]
Thanks! Can you please extract the xml file change from the first commit and move it into the second commit (or remove it and regenerated commit completely, then run the script, and `git commit -a -s -m '[strings] Regenerated'`)? The first commit should have only txt files changed.

**Comment by tkbremnes** [comment]
updated :)

**Pull request merged**
