### PR TITLE
[android] Note to OSM editors is made visible and scrollable when keyboard is open.

### LINKED ISSUE #3323: [android] Note to OSM editors is not visible and not scrollable when keyboard is open
image

image

### PR DESCRIPTION
**Pull request by pratyaksh1610**
fixes #3323 
Note to OSM editors is made visible and scrollable when keyboard is open.

https://user-images.githubusercontent.com/76740999/188175008-91a067e1-b3bb-4d6c-9f9c-b1fd6a4cffec.mp4

### CODE REVIEW

**Review by biodranik — APPROVED** [review]
Wow, that was fast. Thanks!

**Comment by biodranik** [comment]
@pratyaksh1610 can you please take a look at https://github.com/organicmaps/organicmaps/pull/3395 ? Your change introduced some padding, is there a way to remove it?

**Comment by pratyaksh1610** [comment]
@biodranik  Actually `android:fitsSystemWindows="true"` automatically adds padding , and it ovverides any other padding even if we define it to `0`.

**Comment by biodranik** [comment]
@pratyaksh1610  Are there any different/better ways to fix both issues?

**Comment by pratyaksh1610** [comment]
> @pratyaksh1610 Are there any different/better ways to fix both issues?

As of now , I did'nt found any , but I am still exploring for a better approach.

**Pull request merged**
