### PR TITLE
[base] Treat fast_double_parser as a system header

### PR DESCRIPTION
**Pull request by Ferenc-**
* For compiler diagnostics
* For dependency management

Signed-off-by: Ferenc Géczi <ferenc.gm@gmail.com>

### CODE REVIEW

**Review by biodranik — APPROVED** [review]
It's ok. But a better solution is to use an even faster double parser instead of this one. I think it should be mentioned in some issue.

**Comment by Ferenc-** [comment]
> It's ok. But a better solution is to use an even faster double parser instead of this one. I think it should be mentioned in some issue.

Judging by the `Locale-independent code is also faster.` statement [here](https://github.com/organicmaps/organicmaps/issues/1659) you might have meant https://github.com/google/double-conversion?  
I could work on it at a later point, once the 3parties are in a bit less chaotic.

My idea is that it would be nice if we could at least optionally manage the C and C++ 3parties with `conan`,
and see what the community thinks of it. That could give us cmake and xcode support,
and in theory that could make a protobuf update (at least on the 3party depertment) a trivial task, instead of the current situation where one has to deal with a lot of hardcoded dependency.

**Comment by biodranik** [comment]
1. Yes, it would be interesting to compare benchmarks for locale-independent double parsers.
2. Regarding Conan, does it allow customizing all necessary optimization settings for XCode, at least those we're using now in XCode projects? It is critically important for mobile apps.
3. Will we get a lot of benefits from using Conan compared to a simple increase of 3p submodule version during the 3p upgrade?
4. What is wrong with protobuf, and how Conan may help with it?

**Review by biodranik — COMMENTED** [review]
Let's also update the fast double parser submodule.

**Comment by Ferenc-** [comment]
>Yes, it would be interesting to compare benchmarks for locale-independent double parsers.

Do we have specific benchmarks that are more relevant to the project than others?

>does it allow customizing all necessary optimization settings for XCode

It allows a whole lot of customization, but first there should be a draft prepared to see if really everything is covered.

>What is wrong with protobuf, and how Conan may help with it?  

Nothing wrong with protobuf, the way it is managed in this repo that is the problematic part.

> Let's also update the fast double parser submodule.

That is done. Anything else needed here?

**Review by biodranik — APPROVED** [review]

**Comment by biodranik** [comment]
The main strtod usage now is when parsing numbers from OSM XML and KML.

**Pull request merged**
