### PR TITLE
[core] Remove compilation warnings due to missing switch options

### PR DESCRIPTION
**Pull request by gpesquero**

### CODE REVIEW

**Comment by biodranik** [comment]
AFAIR @vng left these warnings deliberately, right?

**Comment by vng** [comment]
Well, yes, I'm still unsure here:
- I don't like this warning
- I don't like supressing it with _default_
- I don't know how to fix it better now. Probably, we will process Village + Poi in a different way in future ..

**Comment by gpesquero** [comment]
@vng: As you don't like to remove the warning with a _default_ option, I've added to the switch statement all the non-handled types and a _"TODO: These types could be processed in a different way in the future..."_ comment. 

In any case, I can live happily with these compilation warnings... If you feel that it's Ok the code as it is, I could cancel this PR.

**Review by biodranik — APPROVED** [review]
I'm ok with that approach, the warning is annoying. Now we'll see it again after introducing a new type, that is helpful.

@vng PTAL

**Review by biodranik — APPROVED** [review]
Thanks!

**Pull request merged**
