### PR TITLE
[ios] Add social media and email links in Place Page

### PR DESCRIPTION
**Pull request by dvdmrtnz**
This PR adds Facebook, Instagram, Twitter and VK social media links to the Place Page in iOS. Also it adds a compose email link to email.

Closes https://github.com/organicmaps/organicmaps/issues/2762, closes https://github.com/organicmaps/organicmaps/issues/1016, closes https://github.com/organicmaps/organicmaps/issues/600

Related to https://github.com/organicmaps/organicmaps/pull/1196

### CODE REVIEW

**Comment by strump** [comment]
On Android we add `@` symbol in front of social login name. E.g `@laliga` for Facebook, twitter, Instagram, etc.

**Comment by dvdmrtnz** [comment]
> On Android we add `@` symbol in front of social login name. E.g `@laliga` for Facebook, twitter, Instagram, etc.

Thanks! Done!

**Comment by TheAdventurer64** [comment]
If I remember correctly, the Android version of the app had editor support for social media. Could that be implemented here?

**Review by vng — APPROVED** [review]

**Comment by Robot8A** [comment]
Hi, I suggest a QoL improvement to this:
To open each social media link in its own app (if the user has it installed) instead of in the built-in browser.
E.g. open the Instagram handle with an intent to Instagram app

**Comment by Robot8A** [comment]
Yes, I am on iOS

**Pull request merged**
