### PR TITLE
[android] Place page performance improvements

### PR DESCRIPTION
**Pull request by arnaudvergnet**
This PR adds various improvements to the handling of the place page.

- Removes the `onLayoutChange` listener. All its logic has been moved outside to improve performance. For some reason this callback was called several times per seconds even when the place page was not shown, calling some unnecessary logic.
- Cleans up the code to remove warnings.
- Removes the custom peek height animation in favor of the native one.

As you can see in the following video, not much changed. The animation is slightly different but more consistent with the opening/closing ones. There is a visual artifact when you expand the bottom sheet then select a new map object, but it was already present before.

https://user-images.githubusercontent.com/80701113/194037067-dbafd45e-279a-4607-a782-0eafde48d2bb.mp4

### CODE REVIEW

**Comment by biodranik** [comment]
What were the reasons for calling the callback so often? Maybe they were legitimate ones? Did you check git blame on why that callback was added?

**Comment by GreenAloe** [comment]
@arnaudvergnet You can check blame here https://github.com/organicmaps/organicmaps/blame/master/android/src/com/mapswithme/maps/widget/placepage/RichPlacePageController.java#L320

**Comment by arnaudvergnet** [comment]
Oh thanks for the link I didn't know GitHub had this feature!

Seems to me that this function was used to detect when the content inside the bottom sheet changed to adapt the peek height, maybe because there was some online feature that could update the content of the sheet after being opened.

But now the content does not change once opened so there is no need to wait for this callback. We simply need to update the peek height when calling the open/restore functions and the viewport will automatically move when the sheet finishes sliding.

**Review by vng — APPROVED** [review]

**Review by biodranik — CHANGES_REQUESTED** [review]
> But now the content does not change once opened so there is no need to wait for this callback.

@arnaudvergnet there is one case out of my mind which can update the content: a bookmark with an HTML description that contains links to images, that can be loaded and displayed with a delay. Can you please test this case?

**Comment by arnaudvergnet** [comment]
Forgot about this feature! I updated the pr to add a simple callback to update the peek height when the place page content changes. It now works better:

https://user-images.githubusercontent.com/80701113/194378485-4b44377f-197f-44fb-a31a-d32b7086a247.mp4

I think it is safer to use this approach rather than to rely on the layout change listener. This way we can control which changes should affect the peek height.

**Comment by TheAdventurer64** [comment]
I got a question: Would it be possible to make the bottom panel (where the route buttons are) "pop" up?

**Comment by biodranik** [comment]
1. @arnaudvergnet please insert this HTML code into the description: ``
2. Then close Place Page or even better restart the app.
3. Open the place page for this bookmark and test how the image is loaded, and how the place page behaves. Does it behave in the same way as before this PR?

People usually import KML with many images and expect to see them loaded when they select a bookmark.

**Comment by arnaudvergnet** [comment]
@biodranik Seems to me it has the same behavior as before the PR:

https://user-images.githubusercontent.com/80701113/194425444-e72cf4cf-799d-439c-90f6-7e5f33639196.mp4

> I got a question: Would it be possible to make the bottom panel (where the route buttons are) "pop" up?

@TheAdventurer64 do you want the 4 buttons at the bottom of the place page to have an animation?

**Comment by biodranik** [comment]
1. Please, don't animate the bottom buttons (or did you mean something else?). The workflow should be instant.
2. @arnaudvergnet the behavior is not correct in the PR and partially in the master branch:
   1. After adding HTML tag and saving it, PP should not jump up but stay at the same height.
   2. After opening PP with an image, it also should not jump if the image is loaded and stay at the same height.

**Comment by arnaudvergnet** [comment]
From what I could see, the behavior in the PR is the same as the one in master.

After adding the tag the PP jumps because it is in state expanded. As the new content takes the whole screen, the PP will respect that.

The PP itself does not jump when the image is loaded, only its content.

As those behavior are already present in master, I don't think this PR should try to chance those, it is not a bug introduced.

About the buttons, I agree to not animate so users do not need to wait for the animation to finish to interact with them.

**Review by biodranik — APPROVED** [review]
Ok, I double-checked, and the PP jump does not reproduce. Thanks for the improvement!

**Pull request merged**
