### PR TITLE
Clean up flatpak metadata

### LINKED ISSUE #4588: <em> tag not rendered in flatpak description
**Describe the issue**
`<em>` tag is not rendered in flatpak description. See: https://github.com/flathub/app.organicmaps.desktop/blob/8e2b573a713abc96413f9f2710b6e41369ac6fd3/app.organicmaps.desktop.yml and the result here https://flathub.org/apps/details/app.organicmaps.desktop or in Gnome Software for example.

**Expected behavior**
A description which renders well :)

**System information:**
 - Organic Maps version: 2023.02.13-11

### PR DESCRIPTION
**Pull request by Altonss**
- Remove em tags
- Fix lists

This fixes #4588

Signed-off-by: @Altonss

### CODE REVIEW

**Review by biodranik — APPROVED** [review]
Thanks! Can you please sign the commit with the DCO? (see failed check)

**Comment by Altonss** [comment]
> Thanks! Can you please sign the commit with the DCO? (see failed check)

I was searching for a way to do it through the github web UI, but I guess its not possible? For small contributions like this it would be easier :)

**Comment by biodranik** [comment]
If you can't amend the commit locally, then add the DCO signature to this Pull Request please, we'll fix/squash it.

**Comment by rtsisyk** [comment]
```
git commit --amend -s
git push origin -f
```

**Comment by Jean-BaptisteC** [comment]
Please add valid DCO in PR

**Comment by Altonss** [comment]
> ```
> git commit --amend -s
> git push origin -f
> ```

It's very strange, I did this from the github codespaces, but somehow it closed the PR without letting me reopen it :thinking:

**Comment by biodranik** [comment]
You pushed the wrong history/version. Please take the latest master branch, add your changes on top of it, and push it again.

**Comment by Ferenc-** [comment]
The original issue has been resolved by flathub:
https://github.com/organicmaps/organicmaps/issues/4588#issuecomment-1578412267

**Pull request closed without merging**
