### PR TITLE
Update strings.txt

### PR DESCRIPTION
**Pull request by danieldegroot2**
Added, changed Dutch, French and German translations.

Signed-off-by: Daniël de Groot <danieldegroot18@gmail.com>

### CODE REVIEW

**Review by rtsisyk — APPROVED** [review]
Thanks for the contribution! Could you please sign-off the commit?
https://github.com/organicmaps/organicmaps/blob/master/docs/CONTRIBUTING.md#legal-requirements

**Review by biodranik — APPROVED** [review]
Thanks!
@rtsisyk please regenerate strings for the app update

**Comment by danieldegroot2** [comment]
Edited above message. Is this okay?

**Comment by biodranik** [comment]
You should edit the commit's message, not the PR text.

A script tools/unix/generate_localizations.sh updates strings. Please commit it separately (and also sign).

**Comment by danieldegroot2** [comment]
Sorry, I have no idea how to run the script.

**Comment by biodranik** [comment]
That's ok, we can run it. But you need to sign the commit. You can do `git commit --amend --signoff --no-edit` and then `git push -f`

**Comment by danieldegroot2** [comment]
> That's ok, we can run it. But you need to sign the commit. You can do `git commit --amend --signoff --no-edit` and then `git push -f`

Where do I do this?

**Comment by biodranik** [comment]
Did you edit the file from the browser? Then we'll help.

**Comment by danieldegroot2** [comment]
> Did you edit the file from the browser? Then we'll help.

Yes, I'm editing in the browser.

**Pull request merged**
