### PR TITLE
[strings] Update Ukrainian locale

### PR DESCRIPTION
**Pull request by edbond88**
I added some updates to Ukrainian locale. But can't run this script `./tools/unix/generate_localizations.sh`

I followed this steps:
1. Run `git submodule update --init --recursive`
2. Run `brew install ruby`
3. Run `./tools/unix/generate_localizations.sh`
4. Get error:
```
+ case $OSTYPE in
+ '[' -x /usr/local/opt/ruby/bin/ruby ']'
+ PATH=/usr/local/opt/ruby/bin:/Users/edbond/.nvm/versions/node/v14.16.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
++ dirname ./tools/unix/generate_localizations.sh
+ OMIM_PATH=./tools/unix/../..
+ TWINE=./tools/unix/../../tools/twine/twine
+ STRINGS_PATH=./tools/unix/../../data/strings
++ mktemp
+ MERGED_FILE=/var/folders/mp/_qdv23fx6tlgdjkx69nk94l40000gn/T/tmp.wOzPX7dx
+ cat ./tools/unix/../../data/strings/strings.txt ./tools/unix/../../data/strings/partners_strings.txt ./tools/unix/../../data/strings/types_strings.txt ./tools/unix/../../data/strings/brands_strings.txt
+ ./tools/unix/../../tools/twine/twine generate-all-localization-files --include translated --format android /var/folders/mp/_qdv23fx6tlgdjkx69nk94l40000gn/T/tmp.wOzPX7dx ./tools/unix/../../android/res/
<internal:/usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- safe_yaml/load (LoadError)
	from <internal:/usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/edbond/Projects/organicmaps/tools/twine/lib/twine/plugin.rb:2:in `<top (required)>'
	from <internal:/usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/edbond/Projects/organicmaps/tools/twine/lib/twine.rb:25:in `<module:Twine>'
	from /Users/edbond/Projects/organicmaps/tools/twine/lib/twine.rb:1:in `<top (required)>'
	from <internal:/usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from ./tools/unix/../../tools/twine/bin/twine:2:in `<main>'
```

**OS:** macOS BigSur 11.4
**Ruby:** ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]

### CODE REVIEW

**Comment by biodranik** [comment]
That's a weird bug with the ruby module. Try to google the error, there are some workarounds (fix permissions for example).

But we can also help to regenerate strings after the review. Please note that there are also three more files: 

https://github.com/organicmaps/organicmaps/blob/master/iphone/plist.txt
https://github.com/organicmaps/organicmaps/blob/master/data/categories_cuisines.txt
and
https://github.com/organicmaps/organicmaps/blob/master/data/categories.txt

The last one is very important. The first word is visible to users and is also used in the search. All other words are "search synonyms", which work if a user types them in the search. A number before a word means "show the whole word as a hint after typing this number of first word's characters"

**Review by biodranik — APPROVED** [review]

**Comment by greshilov** [comment]
> 	from <internal:/usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
> 	from /Users/edbond/Projects/organicmaps/tools/twine/lib/twine/plugin.rb:2:in `<top (required)>'
> 	from <internal:/usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
> 	from <internal:/usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
> 	from /Users/edbond/Projects/organicmaps/tools/twine/lib/twine.rb:25:in `<module:Twine>'
> 	from /Users/edbond/Projects/organicmaps/tools/twine/lib/twine.rb:1:in `<top (required)>'
> 	from <internal:/usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
> 	from <internal:/usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
> 	from ./tools/unix/../../tools/twine/bin/twine:2:in `<main>'
> ```
> 
> **OS:** macOS BigSur 11.4
> **Ruby:** ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]

It's probably because of missing `twine` dependencies. Please, try to install them manually:
```
gem install safe_yaml rubyzip
```

**Comment by biodranik** [comment]
@edbond88 we fixed the regeneration script, but please don't run it yet. Let's merge all changes first.
Can you please amend and sign your commit?
```
git commit --amend --signoff
git push -f
```

**Review by rtsisyk — APPROVED** [review]
Thanks for the contribution. 

Please sign-off:

git commit --amend --signoff
git push -f

**Pull request merged**
