### PR TITLE
Remove priority exceptions

### PR DESCRIPTION
**Pull request by pastk**
Following #4506 here is a second bunch of priority fixes
(there are some minor non-priority fixes alongside too).

Done in same style - with additional temporary priority overview files which help to visualize ordering changes.

Its easier to review commit by commit.

1. Removed exception (added in https://github.com/organicmaps/organicmaps/pull/1512):
```
/*
  Set default text priority for all POIs greater than building text priority (15201) to avoid name and symbol overlap.
  This is the only valid variant to change text priority without overriding background filling priority.
  ToDo: I'd prefer something like area[amenity] { z-name-index: 500; };
  -x-me-min-text-priority and -x-me-text-priority are hacks.
*/
-area[amenity],
-area[man_made],
-{-x-me-min-text-priority: 15300;}
```
Because in reality it affects very few POIs in a very minor way and all of them in higher zoom buckets than buildings (z14) anyway, so this hack is not serving stated purpose anyway... See the diff for details, please.

2. Removed captions from `[amenity=university][!name]` (as there is nothing to display!).

3. `aeroway-gate` priority at z17 was lower than z18-19, made them equal and high in z17 bucket.

4. `aerialway-cable_car/drag_lift/etc`:
- dashed line priority was a tad different between z12-14 and z15-19, fixed
- removed icons as those types are line-only
- changed captions to path texts - now aerialways display their name

aerialways_path_texts

5. Crafts priorities were set for z18-19 only, this made them default to lowest on z17.

6. On z18-19 specific `[tourism=information]` priorities were overriden by generic (and higher) `[tourism]` ones.

`tourism-artwork-architecture/sculpture/etc` also had slightly inconsistent priorities, e.g. on lower zooms (~15-17) they were lower than cafes and bars, on higher zooms (~16-19) they were higher than `tourism-gallery` and `historic-memorial` (reason unknown https://github.com/mapsme/omim/commit/893a8be1a8f182b1d95f89962d59159b2ac2f846). I made them sit between cafes and galleries for all zooms (like its done in vehicle style).

7. For `historic-memorial-plaque/stolperstain/cross` priority was a little different for higher (17-19) and lower (15-17) zooms.
But on lower zooms (15-17) they were invisible anyway ("zero-icon" used), but selectable by a tap still (and in vehicle style they were invisible but tappable on all zooms)! Those fixes were added in https://github.com/organicmaps/organicmaps/pull/3572. I've removed the higher zooms icon completely, so now they're truly drawable on higher zooms only (and this has lowered their priority naturally).

8. Made `leisure-golf_course/playground` area fill priorities consistent across zooms.

9. Made `man_made-pier/breakwater`area fill priorities consistent across zooms.

10. Made `sport-*`priorities consistent across zooms.

11. `shop-car_repair-tyres` priority was slightly different at different zoom levels.

12. `highway-world_level/world_towns_level` priorities were slightly different before z7 and after. What are those highways? Even removing them from drules completely doesn't change anything in rendering.

### CODE REVIEW

**Comment by vng** [comment]
Hm, I will take a deep look later, but please check this: https://github.com/organicmaps/organicmaps/issues/654
I also don't like priority hacks, but this cases should be ok with your refactoring.

**Comment by biodranik** [comment]
> but please check this: https://github.com/organicmaps/organicmaps/issues/654

Texts should never be drawn on top of icons, right? So their placement should always be somewhere near the icon.

**Comment by pastk** [comment]
> > but please check this: #654
> 
> Texts should never be drawn on top of icons, right? So their placement should always be somewhere near the icon.

And its not something dependent on priorities, so I don't see how it is related to this PR really. It was something wrong with the displacement logic, I guess.

**Comment by vng** [comment]
-x-me-min-text-priority and -x-me-text-priority hacks
Just check that features from the issue are looks good with your PR

**Comment by pastk** [comment]
> Hm, I will take a deep look later, but please check this: #654

Thanks, now I see what you mean.
There is no icons and captions overlapping with my change - I checked all the cases from #654.
So the overlapping behavior was changed/fixed elsewhere since your original priorities fix.

But still removing your fix makes the caption to use building's style, not amenity's (there is some difference in font size and color), which is wrong. So I will hold back removing this fix for now, but ideally we should fix the root case instead of working around it via priorities IMO. I created #4590 to discuss it separately.

**Comment by pastk** [comment]
> Hm, I will take a deep look later, but please check this: #654 I also don't like priority hacks, but this cases should be ok with your refactoring.

Have you had a chance to look into other fixes here?

**Comment by pastk** [comment]
> > Hm, I will take a deep look later, but please check this: #654
> 
> Thanks, now I see what you mean. There is no icons and captions overlapping with my change - I checked all the cases from #654. So the overlapping behavior was changed/fixed elsewhere since your original priorities fix.

Overlapping was more properly fixed in https://github.com/organicmaps/organicmaps/pull/2583/commits/b97ae6d789bd6d0d23288ccb605241a8f61d406a (#2573)

**Comment by pastk** [comment]
Done as part of #4645

**Pull request closed without merging**
