### PR TITLE
[strings] fixed en translation for trunk roads

### PR DESCRIPTION
**Pull request by Timmy-Tesseract**
Signed-off-by: Timeo Gut <timeo.gut@gmail.com>

### CODE REVIEW

**Review by biodranik — APPROVED** [review]

**Comment by pastk** [comment]
@Timmy-Tesseract @biodranik 

What was wrong with the previous "National Highway" translation?
"Trunk Road" doesn't seem to be used in common everyday language in any country, see https://wiki.openstreetmap.org/wiki/Tag:highway%3Dtrunk#International_equivalence
Its more like OSM-specific internal term similar to e.g. `highway=unclassified` and doesn't make much sense when translated literally.

"National Highway" and related names (national primary roads, national roads, national routes...) seem to be used much more often.
See #1767 for the whole `highway=*` classification.

**Comment by pastk** [comment]
Linking #3785

**Comment by Timmy-Tesseract** [comment]
> What was wrong with the previous "National Highway" translation?

- many countries don't use this term at all
- in countries where some trunk roads are national highways there are also trunk roads that are not national highways
- in countries where some national highways are trunks there are also national highways that are primary/secondary/tertiary

Translation as "National Highway" might be appropriate where all countries using particular language have identical definition. Ideal solution would be to allow for country-specific translations for every language, but this might be too complex.

As long as this is not possible generic terms should be used (especially for widespread languages like english) to avoid incorrect labels in large parts of the world.

> Its more like OSM-specific internal term similar to e.g. `highway=unclassified` and doesn't make much sense when translated literally.

I agree with this. The reason why I used OSM-specifc term is to fit in with existing english translations of primary/secondary/tertiary road. Looking at other translations currently only en, nl and pt are using OSM vocabulary. For all other languages non-OSM-specific terms are used. 

To conform with this I think it would make sense to change english translations to "Main Road" for trunk/primary and simply "Road" for secondary/tertiary.

**Comment by biodranik** [comment]
Let's focus on the best solution. IMO users need to know the road type/significance, and hiding several types under the same name is not good. 

How can we apply different translations for roads in different countries? Dis someone already do that, so we can reuse proper terms and translations?

Can these names be reverse-engineered from some apps?

**Comment by Timmy-Tesseract** [comment]
> How can we apply different translations for roads in different countries? Did someone already do that, so we can reuse proper terms and translations?

It seems unlikely that such a database already exists. 

> users need to know the road type/significance, and hiding several types under the same name is not good.

OSM classifications simply don't match up with everyday language usage mainly for two reasons:
- They are much more refined than everyday language vocabulary
- They are assigned independently from official road classifications

Even if country-specific translations would be implemented, it is still inevitable that many OSM classifications will share identical labels.

To confirm this we can look at some languages that don't have the problem of widespread usage like english.
Indonesia (id): residential/unclassified/tertiary/secondary/primary/trunk are all translated as "Jalan"
German (de): unclassified/tertiary/secondary are all translated as "Strasse"

The issue of mismatch with official classifications could be resolved to some extent by analysing secondary tags like ref and designation. But this would require a non-trivial effort on a per country basis. Some examples:
Indonesia (id): Any road that has numerical ref tag within range of 1-99 could be labelled as "Jalan Nasional"
Philippines (en-PH): Any road that has numerical ref tag within range of 1-999 could be labelled as "National Road". Additional labels for "National Road", "Provincial Road", "City Road", "Municipal Road" and "Barangay Road" could be deduced from designation tag.

Such added nuance would certrainly be nice to have, but it seems that very large efforts would be required to achieve only minor benefits for map-users.

**Comment by Timmy-Tesseract** [comment]
Looking a bit further into the feasibility of country-specific translations there seem to be even more complications.

Highway=trunk is probably the best example for this due to a very distinct divide in how this classifications is defined globally. While some countries use trunk for expressways or express-way like roads with strict physical criteria and access restrictions, the rest of the world uses trunk for roads that are indistinguishable from primaries/secondaries except for their high importance. 

This means that any non-generic translation in any language will result in incorrect labels in approximately half of the world. 

A person with device language set to German or Portuguese driving around the the Philippines will be very confused if OM tells them that they are currently on a "Schnellstrasse"/"Via rápida" while they're actually driving on a 2-lane undivided country road. 

Someone with device settings in Spanish or Indonesian on the other hand will not be confused because those translations use the generic terms "Calle"/"Jalan".

Based on this it seems highly preferable to keep translations for the basic highway types intentionally generic. 

More nuanced translations could then be added through secondary tags that have more or less standardized definitions globally (e.g. motorroad=yes, expressway=yes). 

Most languages are already using this scheme of generic translations. The only outliers seem to be Chinese, English, French, German, Marathi and Portuguese.

**Comment by pastk** [comment]
> 
> I agree with this. The reason why I used OSM-specifc term is to fit in with existing english translations of primary/secondary/tertiary road. Looking at other translations currently only en, nl and pt are using OSM vocabulary. For all other languages non-OSM-specific terms are used.
> 
> To conform with this I think it would make sense to change english translations to "Main Road" for trunk/primary and simply "Road" for secondary/tertiary.

So to make it better we need to find a suitable generic term which
- won't match exact definitions used in many countries to avoid confusion/mismatch with the terms used locally
- will hint relative significance of the road still, compared to other road types, i.e. higher significance than "primary road"

For me (not a native english speaker) `Trunk Road` doesn't satisfy the 2nd criteria as I can't really tell if its more significant than a primary or not. Maybe for native speakers this connotation is more obvious though?
`National` provides a very good hint that its of a national significance and so more important than `primary` but non-national.
To avoid confusion to `National Highway` term we can use something less frequently used e.g. `National-level Road`, `Major Country-level Highway` etc.

**Comment by biodranik** [comment]
1. Each country has its own road types/priorities, correctly named in the local language(s).
2. Users in their home countries should see road types that are familiar to them. Using some unclear generic terms here doesn't help users to understand the road type.
3. Users visiting other countries should not see their local country road names, but how these roads are named in those other countries. That will help to navigate easier.

There is a [list of OSM tags by country](https://wiki.openstreetmap.org/wiki/Tagging). The only question is how to properly support it.

Moreover, that country-based "mapping" can be also useful for the routing algorithm. @vng what do you think?

**Comment by biodranik** [comment]
@vng am I right that highway=trunk or highway=secondary means the same from the routing perspective independent of the country? Or its meaning can be different in different countries?

**Comment by vng** [comment]
No, all OSM roads are different. Check routing/car_model_coefs.hpp

**Comment by pastk** [comment]
> No, all OSM roads are different. Check routing/car_model_coefs.hpp

AFAIR we have per-mwm average driving speeds adjustments? Do they differ for various highway types too?

**Pull request merged**
