### PR TITLE
Updated the docs link

### PR DESCRIPTION
**Pull request by TauqeerAhmad5201**
Refer to #4721

### CODE REVIEW

**Review by n1snt — COMMENTED** [review]
I can only see 2 of the 5 broken links fixed.
You need to fix the broken links in TRANSLATIONS.md & OBJC_STYLE.md as well.

**Comment by TauqeerAhmad5201** [comment]
Sure, let me complete it.

**Comment by Jean-BaptisteC** [comment]
I think you can simplify release management by keep one link to explain metadata and screenshots use same workflow for IOS

**Comment by rtsisyk** [comment]
up

**Comment by TauqeerAhmad5201** [comment]
Hi @rtsisyk , I'm working on it on a brief. Can you please provide me some more references?

**Pull request closed without merging**
