### PR TITLE
[strings] Fixed Deutsch Avoid unpaved road option translation

### PR DESCRIPTION
**Pull request by biodranik**

### CODE REVIEW

**Comment by j13m126** [comment]
Please make it singular: "Unbefestigte Straße"

**Comment by biodranik** [comment]
> Please make it singular: "Unbefestigte Straße"

Why singular? In "Avoid" route options all translations are plural. E.g. "Avoid unpaved roads", not "Avoid unpaved road".

**Comment by j13m126** [comment]
I'm sorry. You're right of course. I didn't look at the file, I thought this change would be in 'type_strings.txt'.

**Review by vng — APPROVED** [review]

**Review by JohannesDeml — APPROVED** [review]
Looks good!

**Pull request merged**
