### PR TITLE
[styles] Reduce Barcelona subway visibility from z12 to z13

### PR DESCRIPTION
**Pull request by pastk**
On z12 subways are too dense, map becomes cluttered.
On z13 it looks OK.

barcelona-subway

### CODE REVIEW

**Review by vng — APPROVED** [review]

**Comment by biodranik** [comment]
What are other useful features that are now became visible on z12 instead of stations? Did map become more readable?

**Comment by pastk** [comment]
Yes, less cluttered now, more historic features, regular train stations and captions.

2023-03-11-131820_1366x768_scrot

**Comment by biodranik** [comment]
I would expect to see district names on that zoom.

**Comment by patepelo** [comment]
> I would expect to see district names on that zoom.

Yes, this is something happening in Barcelona that is going to be fixed soon in the OSM data.

**Pull request merged**
