### PR TITLE
[Kotlin] Compatiblity interface for deprecated APIs.

### PR DESCRIPTION
**Pull request by n1snt**
### What is this?

This is a common interface that would help abstract away the differences between the deprecated and non-deprecated APIs.
(Inspired by the AnkiDroid implementation.)

### What each file does:

- The Compat interface and its implementations are needed in the above code to provide a unified API that can be used across different versions of the Android platform.
- The CompatHelper class is a singleton that has a private constructor and exposes a compat property that returns an instance of the Compat interface. It uses a when expression to decide which implementation of the Compat interface to use based on the Android SDK version of the device.
- The CompatV21 class is an implementation of the Compat interface that supports Android API level 21 and above. This is the base implementation of Compat.
- The CompatV23 class is an implementation of the Compat interface that supports Android API level 23 and above. It uses the non-deprecated hour and minute properties to get and set the hour and minute values of a TimePicker widget.

### Why we need this:

- If we had to implement the same without this compact system we would need to check the `Build.VERSION_CODES` every time we used any of the deprecated APIs which would lead to more maintenance & a lot of repeated code.
- Encapsulation: The implementation details of each Compat version are encapsulated within their respective classes, which means that other parts of the codebase don't need to know or care about the differences in the TimePicker API between different Android versions.

### Why this was implemented in kotlin:
<strike>
Even though this project is not being migrated to kotlin I personally think that any new code (if possible) should be written in kotlin as it has a lot of benefits over Java such as Conciseness (Readability), Null Safety (Most important if I had to say) & Interoperability with Java code which makes it plug & play.
</strike>
Read the discussion. (Turns out Java is faster)

### Other:
There is still some work to be done here (mostly comments & documentation for the developer)
Any feedback on this would be really appreciated.

### CODE REVIEW

**Comment by Jean-BaptisteC** [comment]
Please check this https://github.com/organicmaps/organicmaps/discussions/2212

**Comment by Jean-BaptisteC** [comment]
I think, fix deprecated is really good things
But use Kotlin for somes classes is too early, we have others issues more priority
Maybe create another PR to fix deprecated API and keep this PR for Kotlin :)

**Comment by n1snt** [comment]
@Jean-BaptisteC I understand your concern about prioritizing other issues
keeping the existing PR for Kotlin conversion is a valid approach. This way, you can prioritize the more urgent issues while still making progress on the Kotlin conversion.
I have created a separate PR to address the deprecated APIs

**Comment by biodranik** [comment]
Enabling Android Auto support will require us to drop api 21 and 22. And these changes will not be necessary. 

It would be great to sync on issues and priorities before implementing them to avoid unnecessary work ;-)

**Comment by n1snt** [comment]
I do know about that.
This interface can be extended beyond API 21 & 23, it will help fix all the deprecation issues with minimal code changes.
That depreciation fix is just to demonstrate how it 
I will add some documentation & another example to demonstrate how this implementation will work.

**Review by biodranik — COMMENTED** [review]
What are the benefits of bringing Kotlin as a dependency here? It can be also done in Java, if really necessary.

We prefer simple, fast, and easy-to-read code without overengineering and unnecessary "modern patterns".

**Comment by n1snt** [comment]
I went with Kotlin due to Conciseness (Readability), Null Safety (Most important if I had to say) & Interoperability with Java code which makes it plug & play.
I actually do have a version of it implemented in java https://github.com/organicmaps/organicmaps/pull/4803

**Review by rtsisyk — CHANGES_REQUESTED** [review]
We don't have Kotlin in the code base and probably don't want to. Please explain why do you want to introduce Kotlin when the entire code base is Java? What is the purpose?

**Comment by rtsisyk** [comment]
Thanks for your efforts. Let's use existing Compat classes provided by JetPack. For anything else please feel free to add new methonds to Utils class.

**Pull request closed without merging**
