### PR TITLE
[strings] add all missing Hindi strings in editor and some error messages

### PR DESCRIPTION
**Pull request by j13m126**
Please add the regenerate commit, I encountered some errors. Thanks!

### CODE REVIEW

**Review by biodranik — APPROVED** [review]
Thank you!

**Comment by biodranik** [comment]
@j13m126 @ArushiGarg09 @unsuman can you please check if Hindi translations on these screenshots are ok?

telegram-cloud-photo-size-2-5199956904753879621-y

CC @yanatalia

**Comment by unsuman** [comment]
> @j13m126 @ArushiGarg09 @unsuman can you please check if Hindi translations on these screenshots are ok?
> 
> 
> 
> telegram-cloud-photo-size-2-5199956904753879621-y
> 
> 
> 
> CC @yanatalia 

Hi @biodranik , hope you doing well! This translations looks good to me👍

**Comment by ArushiGarg09** [comment]
> @j13m126 @ArushiGarg09 @unsuman can you please check if Hindi translations on these screenshots are ok?
> 
> telegram-cloud-photo-size-2-5199956904753879621-y
> 
> CC @yanatalia

Hi @biodranik , The translations look good to me. Have a nice day!

**Pull request merged**
