### PR TITLE
Improve house numbers display in navigation mode

### PR DESCRIPTION
**Pull request by pastk**
See #2030 

ATM I'm being conservative here - just made house numbers font sizes a lil' smaller.

z17 before:
Screenshot_1644234529
z17 after:
Screenshot_1644235192

z18 before:
Screenshot_1644234534
z18 after:
Screenshot_1644235197

### CODE REVIEW

**Comment by pastk** [comment]
I think we can move house numbers to z18- if this zoom level corresponds to speeds around 20-30kph in the auto-zoom mode.
The idea is that house numbers become visible when vehicle is slowing down - perhaps approaching a target address, so house numbers are important to have.

**Comment by pastk** [comment]
ATM house numbers (z17) appear at ~40kph:
https://user-images.githubusercontent.com/18434508/152865638-ee94a8c2-db7f-4015-ab3b-ee47f79152ad.mp4
So it looks like we have some room to reduce it.

When changed to z18 house numbers appear at ~25kph:
https://user-images.githubusercontent.com/18434508/152865794-b4ae3373-edc8-441a-b129-bdc2c8f07476.mp4
So I think we're safe to move to z18.

**Comment by vng** [comment]
40 km/h (z17) is better for buildings, imho

**Comment by pastk** [comment]
> 40 km/h (z17) is better for buildings, imho

z17 looks OK on video and screenshots above because its large buildings there, so not so many of them in the viewport.

But for situations with many small buildings (like on screenshots in #2030 and #1935) viewport will be overwhelmed with plethora of housenumbers.

**Comment by pastk** [comment]
Just to illustrate my point better:
z17 without the patch
Screenshot_1644314349
A smaller font would've improved the situation but not much.

z18 with the patch:
Screenshot_1644315285
Better, but still too many lables imho.

**Pull request merged**
