### PR TITLE
Improve dark style visibility

### PR DESCRIPTION
**Pull request by dvdmrtnz**
In this PR:

* Simplify color names and remove unused colors
* Make buildings a bit lighter in dark style
* Make some labels lighter for improved visibility in dark style

Before/after:

### CODE REVIEW

**Review by vng — APPROVED** [review]
I like screenshots.

@pastk Do you like trunk0, trunk1, ... building0, building1, ... notation?

**Review by pastk — APPROVED** [review]
I like the screenshots too, but let's here from actual night drivers!

**Comment by pastk** [comment]
> 
> @pastk Do you like trunk0, trunk1, ... building0, building1, ... notation?

On one hand its in line with the
```
@green0: #CFD5A8;
@green1: #C6CF93;
@green2: #BCC87E;
@green3: #B3C471;
@green4: #AEC26B;
@green5: #B0C270;
@forest: #AABF65;
@green6: #888C38;
```
(where its apparently not easy to put that many grades in words)
but for the roads its maximum 3 grades (light / med / dark) and it improves at-a-glance understanding of the color role a lot.

So my preference is to continue use a more descriptive wording approach for roads and buildings colors.
But maybe we need better wording, because the meaning of light/dark is reversed in the dark/night mode.
Maybe "strong/med/mild"? Please help with better synonyms 🙏

**Comment by patepelo** [comment]
From the screenshots I can say it looks much better IMO. I almost don't use dark mode because of the lack of readability. This is the way to go!

**Comment by biodranik** [comment]
It would be great to check it in the car at night first before the merge. The master now doesn't highlight houses, and that looks convenient, less distracting. Only numbers are visible.

**Comment by biodranik** [comment]
I've tested it in the car. IMO it looks too bright and distracts the driver. In the master branch houses are almost invisible, only their numbers are conveniently seen if necessary.

But this patch does not change the vehicle style, right?

**Comment by euf** [comment]
@dvdmrtnz Great job, contrast improvements are always welcome, especially for the text labels! 

@biodranik Speaking of design direction, what do you think of Waze night scheme for driving? They use brighter colors than we do, but personally I find it easier on the eyes. Maybe due to the contrast Waze stays very legible even with lower screen brightness.

**Comment by dvdmrtnz** [comment]
> I've tested it in the car. IMO it looks too bright and distracts the driver. In the master branch houses are almost invisible, only their numbers are conveniently seen if necessary.
> 
> But this patch does not change the vehicle style, right?

vehicle style does not change

**Comment by dvdmrtnz** [comment]
Rebased

**Pull request merged**
