### PR TITLE
[android] Refactor bookmark list settings layout

### PR DESCRIPTION
**Pull request by Jean-BaptisteC**
This PR implements:
- add a missing button to see the password in login fragment land layout, following changes #6544
- Replace edit_text_clear_btn button by [clear_text native button](https://github.com/material-components/material-components-android/blob/master/docs/components/TextField.md#adding-a-leading-icon-to-a-text-field) in bookmark_category_settings
- Refactor TextInput to following TextInputEditText main style

|Before|After|
|-|-|
|||

Tested in Pixel 6 - Android 14 in Light/Dark mode

### CODE REVIEW

**Review by biodranik — APPROVED** [review]
Merci !

**Comment by Jean-BaptisteC** [comment]
Clear button is is necessary?
That's the only field in app with this button

**Comment by biodranik** [comment]
Good points!

1. Can the "clear" icon (x) disappear when the field is empty, and appear back if it's not empty?
2. If yes, other fields may also have it (bookmarks and track names for example). But renaming automatically imported bookmarks or track lists is very important, and should be done easily using (x).
3. Pressing the (x) should automatically set edit focus on the cleared text field (now it's not selected).

**Comment by Jean-BaptisteC** [comment]
I have made improvements:
- I have added an end custom icon (same as default icon) in textview to be visible all the time -> like before
- I have created new function to clear and request focus -> tell me if you want I move function in UIUtils
- For other suggestions, I suggest doing this in separate PR to keep this PR only to refactor this screen

**Comment by biodranik** [comment]
On the master branch, there is another bug: When I open List Settings, the cursor is in the list name field, but the keyboard does not appear. Android 13.

**Comment by biodranik** [comment]
Am I correctly understanding that it is not possible to automatically hide the (x) icon when the field is empty, and automatically show it when user starts typing something?

**Comment by Jean-BaptisteC** [comment]
Yes, to hide icon, we need to add OnTextChanged listener and count how many characters we have in field.
For the issue about keyboard, I have added `InputUtils.showKeyboard()` but keyboard starts only when app is on lock screen, any idea why?

**Comment by biodranik** [comment]
Keyboard should be visible by default after a text field gained a focus. Manual function calls should not be required. There is some other issue that prevents keyboard from displaying.

**Comment by Jean-BaptisteC** [comment]
I have added a new property in manifest to trigger keyboard when activity is started

**Review by rtsisyk — APPROVED** [review]

**Comment by rtsisyk** [comment]
Changes LGTM. @Jean-BaptisteC, what was the source of `ic_clear_rounded.xml`? It looks pretty simple, but I have to ask you to avoid guys like FlatIcons to sink in (see #3311).

**Comment by Jean-BaptisteC** [comment]
Here https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Acancel%3AFILL%401%3Bwght%40400%3BGRAD%400%3Bopsz%4024

**Review by biodranik — APPROVED** [review]
Merci!

**Pull request merged**
