### PR TITLE
[android] Fix Monkey

### PR DESCRIPTION
**Pull request by rtsisyk**
Crashlytics has been removed from all debug versions. Let's test betas instead.

### CODE REVIEW

**Comment by rtsisyk** [comment]
@biodranik let's push it. It is better to have any automating testing than not to have it.

**Comment by vng** [comment]
Try to run the current debug master. Should be ok now.

**Comment by biodranik** [comment]
Debug versions have way more asserts than release/beta ones. I would prefer to have automated tests with debug asserts enabled. What are the benefits of using beta instead?

**Comment by rtsisyk** [comment]
I reverted to the debug version.

**Review by vng — APPROVED** [review]

**Pull request merged**
