### PR TITLE
[xcode] Do not use precompiled headers

### PR DESCRIPTION
**Pull request by biodranik**
Looks like there are no benefits of using them with XCode builds

### CODE REVIEW

**Review by vng — APPROVED** [review]

**Comment by vng** [comment]
Don't know how it is significant, but Release build is slower than https://github.com/organicmaps/organicmaps/actions/runs/3837035330/jobs/6531883630

Debug is faster.

**Comment by biodranik** [comment]
Github agents may run in virtual environments and may have different resources between runs. 

Can you please test it locally?

**Comment by biodranik** [comment]
@vng смотрел? Стало быстрее?

**Comment by vng** [comment]
У меня на лаптопе Release 192 vs 189 секунд.

**Pull request merged**
