### PR TITLE
[android-auto] Navigation Screen refactoring

### PR DESCRIPTION
**Pull request by AndrewShkrob**
- Added `trip_finished` string to android.
- `trip_finished` toast is displayed only when you have arrived. Previously it was displayed even when the user finished navigation manually.
- `Stop` button replaced with `X` icon to save space.
- `RoutingUtils` class doesn't store static variables now.

### CODE REVIEW

**Review by Jean-BaptisteC — APPROVED** [review]
✅ Pixel 6 - Android 14 + AA Emulator

Just a crash is present when I started routing with POI near of me (few meters)

```
FATAL EXCEPTION: main
Process: app.organicmaps.beta, PID: 9872
android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{30b83a9 u0 app.organicmaps.beta/app.organicmaps.routing.NavigationService}
at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2104)
at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2075)
at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2369)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.app.ActivityThread.main(ActivityThread.java:8177)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by AndrewShkrob** [comment]
> Just a crash is present when I started routing with POI near of me (few meters)

Nice catch, thanks.
@rtsisyk PTAL
I guess, this bug can also be reproduced on a device and it's somehow related to the crashes we got before.
I've also found this issue: https://issuetracker.google.com/issues/76112072

**Comment by AndrewShkrob** [comment]
@Jean-BaptisteC could you please recheck? I rebased this PR on master. The bug should be fixed. I wasn't able to reproduce.

**Comment by Jean-BaptisteC** [comment]
Did you have test on Android 14, I'm not able to reproduce on Android 13 ?

**Comment by AndrewShkrob** [comment]
I don't have Android 14 :)

**Comment by biodranik** [comment]
Is there Emulator on Android 14 already available?

**Comment by AndrewShkrob** [comment]
> Is there Emulator on Android 14 already available?

It's not possible to run Android Auto on Emulator

**Comment by Jean-BaptisteC** [comment]
I have retry, I'm not able to reproduce

**Review by rtsisyk — APPROVED** [review]

**Pull request merged**
