### PR TITLE
[Strings] rename  the `continue_download` key to the `continue`

### PR DESCRIPTION
**Pull request by kirylkaveryn**
To make this string reusable in the different `Continue` contexts (downloading/recording etc).

### CODE REVIEW

**Comment by biodranik** [comment]
@kirylkaveryn why closed?

**Comment by kirylkaveryn** [comment]
I've got an android liner failure:

`  /home/runner/work/organicmaps/organicmaps/android/app/src/main/res/values-es/strings.xml: Error: continue is not a valid resource name (reserved Java keyword)`

I found that several string such as "continue" couldn't be used in Java as a localized strings...

**Comment by biodranik** [comment]
@kirylkaveryn what about continue_verb or continue_button ?

**Comment by kirylkaveryn** [comment]
> continue_button

Thanks! I think this one will be OK.

**Comment by kirylkaveryn** [comment]
I renamed the branch and the PR was automatically closed 🙁. I'll create a new one...

**Pull request closed without merging**
