### PR TITLE
Move buildings below parkings priorities 

### LINKED ISSUE #5801: Parking not rendered when combined with building
**Describe the issue**
Since the parking rework #3896 in the latest (2023.08.18) release parking facilites are not rendered any more when combined with `building=*`

**Screenshots**
|    | Before | After | OSM |
|------|--------|-------|-----|
| amenity=parking | Screenshot_2023-08-22-12-22-51-020_app organicmaps beta | Screenshot_2023-08-21-16-59-13-200_app organicmaps | [OSM](https://www.openstreetmap.org/way/31126743) |
| amenity=bicycle_parking | Screenshot_2023-08-22-12-23-18-951_app organicmaps beta | Screenshot_2023-08-22-21-38-43-796_app organicmaps | [OSM](https://www.openstreetmap.org/way/200576778)

### PR DESCRIPTION
**Pull request by pastk**
Fixes #5801 .

A simple fix.

The only minor downside is that parkings will displace buildings captions, but its a rare occasion.
If it proves to be a real issue then we might 
- hardcode an exception to make a `building` type lowest priority when a part of a multi-type feature
- or maybe separate buildings into two types: `building-named` for cases w/o POIs and `building` for multi-type cases (it'll contain an area drule only, no caption)

### CODE REVIEW

**Review by vng — APPROVED** [review]

**Comment by pastk** [comment]
> And one more concern: if a Feature has 2 types (parking + building), it gets 3 rules: symbol, text, text. Why the text priority matter here if a symbol + a text from one Feature should always be aligned to stay visible together (a symbol on the top and a text on the bottom)?

And this is exactly what happens indeed.
Before this PR:
- Stylist chooses to display overlays (caption) from the main building type only, because its overlays (caption) have higher priority than parkings' overlays.
After:
- Stylist considers the parking type as main and displays its overlays only (icon + caption) as its priority is higher than building's.

For area drules we also choose one with the highest priority (plus possibly hatching drules), but here we have only one area drule from the building, so its rendered always.
Overlays and areas are in independent priority tiers indeed, hence main overlay type (and its drules) and main area drule are chosen independently.

**Comment by vng** [comment]
Yes, but what is the problem to draw text from building style and symbol from parking style?

**Comment by pastk** [comment]
> Yes, but what is the problem to draw text from building style and symbol from parking style? AFAIR, it worked like that before styles refactoring, no?

Yes, and there were some issues with that behavior: #4590

**Comment by vng** [comment]
> For area drules we also choose one with the highest priority (plus possibly hatching drules), but here we have only one area drule from the building, so its rendered always.
Overlays and areas are in independent priority tiers indeed, hence main overlay type (and its drules) and main area drule are chosen independently.

It looks controversial for me. I don't understand why we can't take area filling from one classifier type and symbol from the other one.

**Comment by pastk** [comment]
> It looks controversial for me. I don't understand why we can't take area filling from one classifier type and symbol from the other one. 

We do take area drule from the building type and caption + icon drules from the parking type.

**Comment by vng** [comment]
Ok then again. What went wrong with bicycle parking from https://github.com/organicmaps/organicmaps/issues/5801 ?
And how this PR with the caption's priority fixes will fix that one bug?

**Comment by pastk** [comment]
> Before this PR:
> - Stylist chooses to display overlays (caption) from the main building type only, because its overlays (caption) have higher priority than parkings' overlays.
> 
> After:
> - Stylist considers the parking type as main and displays its overlays only (icon + caption) as its priority is higher than building's.
>

**Pull request merged**
