### PR TITLE
[editor] Replace PP business string with place string

### LINKED ISSUE #4321: Consider removal of "Add business" button in favor of "Add a place"
> when I press on a building there is the string [placepage_add_business_button] en = Add business
when I long press anywhere else there is the string [placepage_add_place_button] en = Add a place to the map

> both seem to open the editor in the same way, I don't see why we need two different strings, and moreover, a building does not necessarily contains a business (school, amenity, association, etc...)

_Originally posted by @Kazing in https://github.com/organicmaps/organicmaps/pull/4292#discussion_r1082668126_

### PR DESCRIPTION
**Pull request by meenbeese**
Is this the right approach? Please take a look. 
We might not even need the [plagepage_add_business_button] string anymore.

Closes #4321

### CODE REVIEW

**Comment by biodranik** [comment]
"Add business" looks somehow better for buildings. I think an even better solution could be to promote map editing and make these add buttons more discoverable, maybe located in other places, even on the bottom Place Page panel.

**Comment by meenbeese** [comment]
I don't really agree that "Add business" looks better. I think the separation of place and business adds unnecessary confusion for users as stated in the original issue.

Maybe we can improve the wording altogether if none of them are particularly good? Wdyt about some that I came up with:

1. Add new location to OpenStreetMap
2. Contribute a new spot to OpenStreetMap
3. Register a new place on OpenStreetMap
4. Introduce a new place to OpenStreetMap

**Comment by biodranik** [comment]
The motivation beyond "Add business" was for non-geek users who may never discover a long-tap. It is clear for them what it means to "Add business", and not as clear "Add a place to OSM".

One of our goals is to educate our users, no doubt, but another goal is to motivate users to update the map and contribute to OSM. It's better to keep the whole picture in mind when redesigning this UX. If we had real statistics about clicks, edits, and following OSM registrations, then it would be easier. But we don't have it...

I'm open to experimenting and improvements that are targeting our grandparents, not geeks. OM should be easy to use for anyone. It would be great to speak with non-experienced users and see what would be clearer for them.

**Comment by meenbeese** [comment]
Now that the behavior of a long tap and a short tap has been changed, does it make sense to move forward with this PR? Because I think the current situation makes even less sense for regular users and experienced users alike. For example, tapping on a residential building reveals the option to `Add business`, which makes little sense and seems confusing. The reason why I prefer the `Add Place to OpenStreetMap` string is because it associates this action with OpenStreetMap, and `place` is a generalized or friendlier term that simply applies to more locations than `business` would.

**Comment by biodranik** [comment]
Ok, let's do an experiment and see if the frequency of adding new features in OSM will change. @map-per is it possible to track?

@meenbeese please also change the same string on iOS. Or maybe @kirylkaveryn can help?

**Comment by dvdmrtnz** [comment]
Isn't this string already like this on iOS? Latest master:

**Comment by biodranik** [comment]
@meenbeese please remove the unused string from the strings.txt file and make a separate strings regeneration commit.

**Comment by map-per** [comment]
> Ok, let's do an experiment and see if the frequency of adding new features in OSM will change. @map-per is it possible to track?

From my gut feeling I would say that the change won't affect the number of OSM edits.
Getting numbers sounds difficult as the OM user base is still growing, so we can't just compare the number of edits from one month to the ones in the previous month.

**Comment by biodranik** [comment]
Please remove the regeneration commit, then rebase and fix merge conflict, then make regeneration commit again by running translations script.

**Comment by meenbeese** [comment]
@biodranik PTAL and sorry for the delays. I wasn't expecting merge conflicts.

**Review by biodranik — APPROVED** [review]
Thanks!

**Pull request merged**
