### PR TITLE
[3party] Switch to tagged, released pugixml v1.13

### PR DESCRIPTION
**Pull request by Ferenc-**
Signed-off-by: Ferenc Géczi <ferenc.gm@gmail.com>

### CODE REVIEW

**Comment by Ferenc-** [comment]
Probably relevant for the effort in https://github.com/organicmaps/organicmaps/pull/2863

**Comment by biodranik** [comment]
Should we undo our own patches?

**Comment by Ferenc-** [comment]
> Should we undo our own patches?

Which patches do you mean exactly?

**Comment by biodranik** [comment]
> Which patches do you mean exactly?

Ok, my bad, you've already switched from our fork with our patches to the original one in 8ba922916c1bc8e217ecf926d834b3d394f69589

**Review by biodranik — APPROVED** [review]

**Pull request merged**
