### PR TITLE
[styles][ios] Update UI bookmark icons to match map icons

### PR DESCRIPTION
**Pull request by dvdmrtnz**
This PR updates the iOS UI bookmark icons with the same bookmark icons used on the map

* https://github.com/organicmaps/organicmaps/issues/9470

---

Map icons for reference:

---

UI icons before/after:

### CODE REVIEW

**Comment by biodranik** [comment]
Can please someone test it on iOS 12?

**Comment by vng** [comment]
Are they _100%_ the same? Is it possible to use symlink (on data/styles icons) instead of coping?

**Comment by dvdmrtnz** [comment]
@vng They are not the same. Bookmark icons on `data/styles` have the bookmark teardrop around them. For these we need only the icon themselves.

bookmark-bar-m

ic_bm_bar

**Review by vng — COMMENTED** [review]
LGTM.
Github shows some strange file renamings instead of delete, add. Looks like it is his bug ...

**Review by vng — APPROVED** [review]

**Pull request merged**
