### PR TITLE
Display website in Place Page without http(s):// prefixes and trailing slashes

### PR DESCRIPTION
**Pull request by biodranik**
Let's make OM a bit more beautiful.

|Before | After|
|---|---|
|выява|выява|

### CODE REVIEW

**Review by Jean-BaptisteC — APPROVED** [review]
✅ Pixel 6 - Android 14

**Comment by jfitie** [comment]
Nice, why not strip 'www' as well?

**Comment by Misalf-git** [comment]
`http(s)://` defines the protocol.
`www.` is part of the domain.

**Comment by jfitie** [comment]
> `http(s)://` defines the protocol. `www.` is part of the domain.

Yes, correct. But '_www._' does not bring any information for the user and clutters the display. Chrome, for example, also hides '_www._' in the address bar.

**Comment by Misalf-git** [comment]
Is `example.com` the same as `another.example.com`?

Is really Chrome hiding `www.` or do the sites where you've seen it do a redirect?

If Chrome does hide `www.`, does it do so for any website or only for known / selected ones?

**Comment by jfitie** [comment]
> Is `example.com` the same as `another.example.com`?
> 
> Is really Chrome hiding `www.` or do the sites where you've seen it do a redirect?
> 
> If Chrome does hide `www.`, does it do so for any website or only for known / selected ones?

No, `_example.com_` the not same as `_another.example.com_`.

I think you misunderstand. I'm not talking about always hiding the **host** name from the **domain** name. Just about hiding the host name in case that would specifically be `_www_`.

So, for example:
https://www.google.com → google.com
https://mail.google.com → mail.google.com

Also, I'm not defending Google's choice about hiding `_www_` in Chrome - I am merely suggesting the same for OM.

**Comment by Misalf-git** [comment]
My surface scratching on that matter makes me think `www.` is automatically part of the registered domain and my concerns seem unjustified.
Don't quote me, thogh - I'm still de-learning.

**Review by vng — APPROVED** [review]

**Comment by biodranik** [comment]
Stripping www is controversial, a site may not work properly if typed manually.

**Pull request merged**
