### PR TITLE
[styles] Make park, forest, scrub colors different

### PR DESCRIPTION
**Pull request by pastk**
Made scrubs ligher, than forests; parks lighter than scrubs. Grass is lighter than park still, but the difference is little now (which is fine IMO as parks are open-grassy often).

Grass, scrub, forest. And a park below.
scrubs_1

A garden in the park.
scrubs_2

Forest patches in the park.
scrubs_3

Grass, forest, scrub patches in parks.. Note in the right park (with grass-only patches) the colors are much more similar now, which is fine IMO.
scrubs_4

Didn't touch the vehicle style as extra vegetation detalisation is not needed there.

### CODE REVIEW

**Comment by biodranik** [comment]
What is the color gradation for these types in some other popular maps?

**Comment by ivanbarsukov** [comment]
@pastk Maybe you should also check how landuse=orchad, leisure=garden and barrier=hedge will look in combination with new colors. They are often used near

**Comment by ivanbarsukov** [comment]
> What is the color gradation for these types in some other popular maps?

I made a small palette for comparison. I may not know good places on google, but the rendering of parks looks very poor

2gis
ya
ggl

**Comment by ivanbarsukov** [comment]
> Google does it right: on some zoom levels using only one green color for many types helps to read the map easier. We can use the same approach to avoid "too colorful" maps and show them differently after zooming-in.

It seems more likely that their maps are more for business than tourism. Especially for non-urban tourism. And for the urban, according to my long experience of using them, they have nothing but points of interest. As for parks and forests, they don't have any color designations at all. Only on survey zooms there is something like processed satellite images of forests, but apart from beauty, this does not give anything. The darker spots in the screenshots are not trees, as you might think, but sports grounds, which is strange.

I agree that the abundance of colors can be confusing sometimes, but on the other hand, as a rule, the objects under discussion are quite large, and at close zooms there cannot be a lot of them at once. And at medium and far zooms, they will give important information about the terrain.

image
image

**Comment by biodranik** [comment]
When you "overview" the map at the whole city level, you usually don't need detailed info about shrubs, trees, or even grass. "Something green" is often enough. Then, after zooming in, OM can show a distinction by colors.

It would be interesting to try this approach...

**Comment by ivanbarsukov** [comment]
Yeah, this decision is probably ideal. But, I suspect, before there are switchable styles, non-urban tourists may have worse readability of the map

**Comment by biodranik** [comment]
Let's check how it will look :)

**Comment by pastk** [comment]
This PR is just a rather quick attempt to make things incrementally better, though not ideal. So I'd rather keep its scope limited.

I intentionally didn't change the colors (just re-applied the ones we had already) and didn't touch the current OM behavior of darkening the colors while zooming in (notice that e.g. forests are lighter at overview zooms). I guess the idea behind this was to make overview zooms less contrast. But it complicates distinguishing different vegetation fills a lot. So in my opinion dropping this approach and making an overhaul of vegetation fills would be better. If anyone feels like doing it and tuning the colors palette - you're very welcome; and I can help with integrating it into the app and testing it if needed.

My idea is that 3 colors are probably enough (for a universal style) to distinguish vegetation based on density / passability.
- lighter green for open areas like grass, parks
- medium green for smaller vegetation like scrubs and small bushes
- darker green for trees / forests

Combined with @biodranik's suggestion to combine them into just 1 color on overview zooms should result in a good balance of cleanness and detalisation for the universal style (outdoors style will be different obviously).

**Comment by pastk** [comment]
> @pastk Maybe you should also check how landuse=orchad, leisure=garden and barrier=hedge will look in combination with new colors. They are often used near

Hedges have a quite distinct color hue, so should be visible fine against all those fills (it was tested before - when the current hedges color was introduced).

I left gardens to be same as forests in this PR. Gardens look nice inside of parks now (they were not visible before).

Orchards are same as grass (didn't touch it in this PR too). Actually ATM we have many types sharing the grass color:
```
area|z12-13[landuse=grass],
area|z12-13[natural=grassland],
area|z12-13[leisure=golf_course],
area|z12-13[natural=heath],
area|z12-13[landuse=allotments],
area|z12-13[landuse=orchard],
area|z12-13[landuse=vineyard],
area|z12-13[landuse=meadow],
area|z12-13[landuse=recreation_ground],
area|z12-13[landuse=village_green],
area|z12-13[landuse=field],
{fill-color: @green0;}
```

But see my comment above re this PR's scope and general styling ideas.

**Comment by endim8** [comment]
Screenshot_20230313-182513_Organic Maps
It'd be good to make leisure-garden-residential have the same colour as grass, currently it's too prominent

**Review by biodranik — COMMENTED** [review]
@pastk so should we make a separate issue to try using fewer of the same/similar colors on overview zooms?

**Comment by pastk** [comment]
> @pastk so should we make a separate issue to try using fewer of the same/similar colors on overview zooms?

Yeap I suggest to do it separately.
It'll need some testing because potentially it could be worse for larger country-side areas.

**Review by biodranik — APPROVED** [review]
LGTM. @pastk are you able to merge yourself?

**Comment by pastk** [comment]
> LGTM. @pastk are you able to merge yourself?

Nope, I don't have master merge permissions.

**Comment by biodranik** [comment]
@vng merge?

**Review by vng — APPROVED** [review]

**Comment by biodranik** [comment]
@pastk let's rebase and merge it. Sorry for the delay.

**Pull request merged**
