### PR TITLE
Use more geographically significant names for Oregon data files

### PR DESCRIPTION
**Pull request by zyphlar**
Talent, Winston, Mill City, Warrenton, Barlow, Rufus, John Day, and Halfway are some of the smallest, least-significant cities in Oregon which don't even really describe the area encompassed by each map. This PR amends the map border/polygon descriptions to use cities that residents would be more familiar with, and which help distinguish the borders of each file.

For example, the coastal cities of Newport and Coos Bay sit on either side of a map divide. The eastern towns of Government Camp, Bend, and The Dalles sit along a divide. Klamath Falls and Medford sit across a divide. Salem and Albany sit across a divide. All these names have at least been heard of by locals, which is an improvement.

Translations are from Wikipedia page names associated with each town.

### CODE REVIEW

**Review by biodranik — APPROVED** [review]
Thanks! Can you please run tools/unix/generate_localizations.sh and commit the updated files in a separate commit "[strings] Regenerated countries names"?

In general, we need to get rid of this manual approach. All translations and names should be automatically taken from OSM, and the largest cities should be also taken by their population, for example.

**Review by rtsisyk — APPROVED** [review]

**Comment by biodranik** [comment]
> One advantage of hardcoded names is that the optimal balance of large city and geographic importance can be tuned.

This is a lot of manual work. I'm sure we can algorithmically detect the popularity, not only based on population. This metric is also very useful for the search. And of course, the search of any city should work in the downloader, not only the search of some hard-coded strings.

**Comment by zyphlar** [comment]
Done. FYI the script output a lot of changes to subway.lisbon, type.aerialway, etc, that aren't part of this PR, so I only included the countries-names files that were relevant. Maybe upstream needs to run this script as well.

**Comment by biodranik** [comment]
Thanks for the reminder, here is the upstream fix: #3699

**Review by vng — APPROVED** [review]

**Pull request merged**
