### PR TITLE
[style] Kothic on python3.

### PR DESCRIPTION
**Pull request by vng**
Ascending order of rules by priority.

UPD: All below not in this PR.

Made residential shields from z18 and tertiary shields from z15. Secondary shields remains at z12.

z14 now:
Screenshot 2022-05-16 at 19 50 43

z15 now:
Screenshot 2022-05-16 at 19 53 05

@VladimirMorozov @biodranik

### CODE REVIEW

**Comment by biodranik** [comment]
It doesn't look right. We already have city borders, what about deleting shields in cities for these types of roads at the generation stage? Or maybe a simple dirty hack `if (Estonia) ...`?

**Comment by biodranik** [comment]
Let's merge python3 part separately.

**Comment by vng** [comment]
And wait until somebody will add refs in the next country ..
I'm pretty sure that we shouldn't draw refs for residential roads starting from z12. We can argue here about starting zoom, but why deleting shields is better?

**Comment by vng** [comment]
Left python3 only changes.

**Pull request merged**
