### PR TITLE
[android][ui] Remove shadow from compass to match rest of UI

### PR DESCRIPTION
**Pull request by endim8**
Before/after:
Stitch1842e70f1ea

Light/dark:
ffhjgjhgjh

### CODE REVIEW

**Comment by vng** [comment]
Is it our existing tool to generate from vector-icons to predefined PNGs? Or you did it manually with some third party?

**Comment by endim8** [comment]
> Is it our existing tool to generate from vector-icons to predefined PNGs? Or you did it manually with some third party?

I manually exported from inkscape, I was gonna make a script for it but didn't have time to look into it properly

**Comment by vng** [comment]
Don't waste time for a script. We should treat this icons as regular symbols and generate directly into final symbols.png
I don't know why it was made via intermediate pngs.

**Comment by endim8** [comment]
> Don't waste time for a script. We should treat this icons as regular symbols and generate directly into final symbols.png I don't know why it was made via intermediate pngs.

I think it might be because they all have different sizes and aspect ratios, so you'd have to have a table of values for the sizes. but they should definitely be generated in the standard way 👍

**Comment by biodranik** [comment]
Won't it look strange on iOS?

**Comment by endim8** [comment]
> Won't it look strange on iOS?

hmm, i can't build for iOS but i'll try and make a mock-up to test

**Comment by endim8** [comment]
index
i think it still looks ok on iOS, but i can make iOS use the old icons if not

**Comment by biodranik** [comment]
Looks ok:
image

**Review by biodranik — APPROVED** [review]
Can we find/draw a similar svg?

**Comment by endim8** [comment]
> Can we find/draw a similar svg?

i committed a new folder in style-clear/night called vector-icons where vector versions of those icons can be collected 👍

the SVGs i drew for the compass are in there (https://github.com/organicmaps/organicmaps/pull/3780/commits/77be4df382a2efb1093e7f5e299b680976b42e5e#diff-f84ab71880cfa493a1467224f193fd6e45512f478cd441ffc4366a534841c992)

**Comment by endim8** [comment]
> Don't we have too many different folders for svgs? 4 already?

It'd be good to restructure the icon folders, but AFAIK they all serve different purposes; one's for on-map icons, one's for place page things etc

**Pull request merged**
