### PR TITLE
[android] Add `website:booking` key

### PR DESCRIPTION
**Pull request by Arthur-GYT**
All is in the title ^^.

https://wiki.openstreetmap.org/wiki/Key:website:booking

### CODE REVIEW

**Comment by biodranik** [comment]
There are 738 tags worldwide tags with this value. Is it really useful? Any website of a bookable place usually have a large Booking button on it.

**Comment by Arthur-GYT** [comment]
> There are 738 tags worldwide tags with this value. Is it really useful? Any website of a bookable place usually have a large Booking button on it.

Not necessarily. Typically, some restaurants use a third-party service to manage reservations, like this one

https://www.openstreetmap.org/node/6296221506

**Comment by Arthur-GYT** [comment]
BTW, it's ready for review ^^

**Comment by Arthur-GYT** [comment]
> > There are 738 tags worldwide tags with this value. Is it really useful? Any website of a bookable place usually have a large Booking button on it.
> 
> Not necessarily. Typically, some restaurants use a third-party service to manage reservations, like this one
> 
> https://www.openstreetmap.org/node/6296221506

And @biodranik , not all restaurants have websites, but they can use third-party services for bookings.

**Comment by biodranik** [comment]
> And @biodranik , not all restaurants have websites, but they can use third-party services for bookings.

Did you study existing tags? Is it a popular case? How many cases where the website tag is missing, but website:booking is present? Won't it be logical for the restaurant to add a booking link into website tag if a restaurant doesn't have its own website?

**Comment by Arthur-GYT** [comment]
> Did you study existing tags? Is it a popular case? How many cases where the website tag is missing, but website:booking is present? Won't it be logical for the restaurant to add a booking link into website tag if a restaurant doesn't have its own website?

I'll take another case I know. A hairdresser who has a site but their booking system is not up to date on the site and does not link to the current (and working) one. 

https://www.openstreetmap.org/node/8775652782
https://les-barbiers.com/
https://maps.app.goo.gl/HSCuyTWgVUG4PdL1A

**Comment by Arthur-GYT** [comment]
@biodranik 

At present, I don't think the number of nodes with this tag is very representative. If Organic Maps supports it, maybe it will encourage people to map the tag and maybe we'll get more cases where the booking system is dissociated from the website.

**Comment by Arthur-GYT** [comment]
And I think the youth of this tag, as well as its late standardization, means there aren't many knots with it ¯\_(ツ)_/¯

**Comment by biodranik** [comment]
In your example, the right thing is to ask the website owner to update the booking link.

Organic Maps tries to focus on the most important and most popular use cases for _most_ users first. Imagine that many insignificant/unnecessary fields are added to Organic Maps Editor. Would it be easier/better to use in this case?

To optimize the process, it makes sense to create and discuss an issue before implementing it (and also get/discuss stats about its use cases).

**Comment by Arthur-GYT** [comment]
As far as I'm concerned, if we allow this tag to be edited, maybe people will add it to OSM using the editor. 

I know it's still a little-used tag, but it could be useful if, for example, the business doesn't have a website but a booking site used with another service (and if we assume that this booking site can be put in the website tag, why have you accepted website:menu?) 😉.

After all, I'm not the one with the last word 🤪.

**Pull request closed without merging**
