### PR TITLE
[android] recompressed android platform drawables

### PR DESCRIPTION
**Pull request by Endem10n**
Recompressed all Android platform drawables. Conwerted png to webp format, where it was profitable. For F-Droid build reduced build size by 500-600 kb, for other stores a bit less.

### CODE REVIEW

**Comment by biodranik** [comment]
Why fighting for kilobytes?

**Comment by Endem10n** [comment]
@biodranik In case of F-Droid it will help us to fit the build size limit for F-Droid without any additional agreements with F-Droid team. In common case we should use simple resources optimisations, that do not take much time and effort,  where it's possible to reduce common amount of useless internet traffic, IMHO.

**Comment by biodranik** [comment]
There are many more important features for the expensive engineering time :) The app is already in FDroid, and it's current size 66Mb would not decrease significantly after this patch.

**Comment by biodranik** [comment]
Does it work properly on Android 5?

**Comment by Endem10n** [comment]
@biodranik Yes, it works properly on any Android 5+ version. Webp format with lossless compression is supported starting from version 4.3: https://developer.android.com/studio/write/convert-webp

**Comment by biodranik** [comment]
I read the spec, but wanted to check on the emulator or a real device.

**Comment by Endem10n** [comment]
I tested on emulator with api level 21, all is fine. Used this format many times before on different projects, it's safe.

**Review by biodranik — APPROVED** [review]

**Pull request merged**
