### PR TITLE
[styles] Fix tourism-information-office icon

### PR DESCRIPTION
**Pull request by pastk**
ATM the icon changes from a circled `i` to an ordinary office icon from z18-.

That's because `[office]` style rule overrides it on higher zooms.
And that's because 
```
tourism|information|office;[tourism=information][office],[tourism=information][information=office];;name;int_name;313;
```
so its defined as `[tourism=information][office]` also and hence kothic erroneously applies the office style to it.

### CODE REVIEW

**Comment by pastk** [comment]
Depends on https://github.com/organicmaps/kothic/pull/7 which should be merged first.

**Comment by pastk** [comment]
Also I think its better to delete the `[tourism=information][office]` match from mapcss-mapping? As it looks bogus to me.

**Review by vng — COMMENTED** [review]
Agree to remove [office] matching from tourism.
It breaks when some POI is tourism=information and lets say office=company.

**Comment by pastk** [comment]
> Agree to remove [office] matching from tourism. It breaks when some POI is tourism=information and lets say office=company.

Removed. It affected priorities a little.

**Comment by vng** [comment]
Merged kothic, so please put updated submodule ref as first commit here.

**Review by vng — APPROVED** [review]

**Pull request merged**
