### PR TITLE
[android] Adjust resize on FeatureCategoryActivity

### PR DESCRIPTION
**Pull request by icharkas**
Adjust resize on FeatureCategoryActivity while opening on-screen keyboard.

Fixes: #5128

### CODE REVIEW

**Review by biodranik — APPROVED** [review]
@icharkas did you reproduce the issue? What is your Android version?

@Jean-BaptisteC can you please test it?

**Review by Jean-BaptisteC — APPROVED** [review]
✅ Pixel 6 - Android 13

**Review by biodranik — APPROVED** [review]
Thank you!

**Comment by simonschaufi** [comment]
Works well in the latest beta release. Thanks!

**Pull request merged**
