### PR TITLE
Removed Italian;Pizza merged value.

### PR DESCRIPTION
**Pull request by patepelo**
I remove the following text as it is already registered as either "pizza" or "italian": # cuisine-italian_pizza
# en:Italian Pizza
# ru:Итальянская пиццерия
# bg:Италянска пицария
# ar:مطبخ إيطالي؛بيتزا
# cs:Italská, pizza
# da:Italiensk, pizza
# nl:Italiaans, pizza
# fi:Italialainen, pizza
# fr:Italien, pizza
# de:Italienische Pizza
# hu:Olasz konyha, pizza
# id:Italia, pizza
# it:Cucina italiana, pizza
# ja:イタリア料理；ピザ
# ko:이탈리아식, 피자
# nb:Italiensk mat;pizza
# pl:Włoska, pizza
# pt:Piza italiana|pizza italiana
# pt-BR:Pizza italiana|Piza italiana
# ro:Italian, pizza
# es:Cocina italiana, pizzas
# eu:Italiako sukaldaritza, pizzak
# sv:Italiensk, pizza
# th:อาหารอิตาเลียน; พิซซ่า
# tr:Italyan, pizza
# uk:Італійська кухня, піцерія
# vi:Ẩm thực ý, bánh pizza
# zh-Hans:意大利菜；匹萨
# zh-Hant:義大利料理；披薩
# el:Ιταλική Πίτσα
# he:מטבח איטלקי;פיצה
# sk:Talianska kuchyňa; pizza

### CODE REVIEW

**Comment by patepelo** [comment]
Hello, please understand this is my first pull request.

**Comment by Jean-BaptisteC** [comment]
Thanks for your contribution :)
I'm not sure remove this translation is good thing, because italian_pizza value exist in OSM
I think, it's better to improve translation foreach languages
Example in French replace `Italien, pizza` by `Pizza Italienne`

**Comment by biodranik** [comment]
Is there a non-italian pizza?

Another solution could be to replace this tag with just pizza or italian and pizza at the generator stage (and filter the same duplicates if necessary). @vng WDYT?

**Comment by matkoniecz** [comment]
> Is there a non-italian pizza?

Yes, for example https://en.wikipedia.org/wiki/New_York-style_pizza

**Comment by biodranik** [comment]
It's mapped separately and won't be affected by the proposed change. And there are only a few values like this in osm:
image

**Comment by matkoniecz** [comment]
yeas, for now in OSM `italian_pizza` looks like synonymeable to `pizza` for data consumers

**Comment by biodranik** [comment]
So let's try to filter it out at the generator stage (and remove it from translations):
1. italian_pizza => pizza
2. Filter out duplicate pizza if necessary (in cases of `italian_pizza;pizza`

**Comment by patepelo** [comment]
> yeas, for now in OSM `italian_pizza` looks like synonymeable to `pizza` for data consumers

Do you think we should update the wiki and disencourage people to use this tag? According to TagInfo is only 3% against cuisine=pizza.

**Comment by biodranik** [comment]
If there is no value from it, then the wiki can be updated. For us, it shouldn't be hard to support what's there in the OSM now. When someone edits cuisines, they will be uploaded "normalized" to OSM.

**Comment by Kazing** [comment]
I would not modify the wiki, there is no need to oversimplify the data source & there is non-italian pizza (https://en.wikipedia.org/wiki/Pizza_in_the_United_States)

Personally I always considered that:
* `cuisine=pizza` correspond to general pizza (including chains like Dominos, Pizza Hut...)
* `cuisine=italian_pizza` correspond to italian traditional pizza (e.g. [Neapolitan pizza](https://en.wikipedia.org/wiki/Neapolitan_pizza), Roman Pizza)

OM can just merge `italian_pizza` with `pizza` for its use, there no need to encourage OSM contributor to stop using `italian_pizza`

**Comment by vng** [comment]
- # in categories.txt means _commented_, so this patch actually changes nothing.
- still have cuisine|italian_pizza;1273; type in classifier

I think it can be replaced with simple "pizza". As described here: https://wiki.openstreetmap.org/wiki/Tag:cuisine%3Dpizza

**Comment by valerio-bozzolan** [comment]
Premising it's very important _also_ for Italian people to be able to distinguish between a traditional Italian pizza ✨, and just a generic unknown pizza 🎃

(and premising Tag discussions should be done in OpenStreetMap wiki and not here as a general approach)

Premising that the current change unfortunately does not change anything as mentioned (since we are changing just comments)

So the Tag in OpenStreeetMap should be kept indeed.

Now: I would like to help there, but I do not understand what was the root problem.

Can you clarify the root problem in the description (and ping me again please)?

(For example: <I searched "pizza" in Naples but I was not able to find an Italian Pizza but only stuff like Domino's Pizza)

Thanks

**Comment by muralito** [comment]
> They way I interpretate the cuisine=* tag on its defacto use is that it has both, countries and specialities. Meaning that if you would like to specify by italian pizza you would put italian;pizza. The same as if you would do it with: argentinian;beef or american;burger.
I think you are interpreting them wrong.
The tags are as like sets, both of them are the union, not the intersection. That's the meaning of multivalued tags in OSM.
Just like the tag addr:housenumber with several numbers.
An example, a restaurant tagged with cuisine="steak_house;vegan,vegetarian" is a place that serves grilled meat but also some dishes with only vegetables for vegans and vegetarians.

**Comment by patepelo** [comment]
It's been stuck under discussion. I'll close the request for merge.

**Pull request closed without merging**
