### PR TITLE
Remove parking_space icons

### LINKED ISSUE #684: parking_space is rendered incorrectly
we should follow the same rendering method that cartocss / the osm.org map uses

https://t.me/organicmaps/4298

https://t.me/organicmaps/4299

### PR DESCRIPTION
**Pull request by endim8**
1 of 2 to close #684 (i'm gonna work on adding an outline for parking_space areas)

I'm not sure if PRs are meant to include the regenerated drules, so they need to be regenerated if this is merged

noparkingspaceicons

Thank you pastk for describing how to fix this :)

### CODE REVIEW

**Review by pastk — APPROVED** [review]

**Comment by pastk** [comment]
> I'm not sure if PRs are meant to include the regenerated drules, so they need to be regenerated if this is merged
> 

Yes please add drules change as a separate commit to this PR.
Reviewing actual changes happened in drules is also important because sometimes style changes lead to change in drules which were not anticipated :)

> Thank you pastk for describing how to fix this :)

Thanks for actually fixing it!!

**Comment by endim8** [comment]
> Yes please add drules change as a separate commit to this PR. Reviewing actual changes happened in drules is also important because sometimes style changes lead to change in drules which were not anticipated :)

i've added a commit with the drule updates :) my branch is ~45 commits behind main, is that an issue?

**Comment by pastk** [comment]
> > Yes please add drules change as a separate commit to this PR. Reviewing actual changes happened in drules is also important because sometimes style changes lead to change in drules which were not anticipated :)
> 
> i've added a commit with the drule updates :) my branch is ~45 commits behind main, is that an issue?

Yes I think so, because there were other style changes in those 45 commits.
Could you please rebase your branch onto master and force-push it?

**Comment by endim8** [comment]
It should be level with main now :)

**Comment by vng** [comment]
Thanks for contributing.

There are several issues that confusing me, but seems like they are not related to the PR:
- why captions appeared in z15-17 in drules_proto.txt, but they were removed in other files
- why do we have area fill style for parking_space in vehicle styles.

**Comment by biodranik** [comment]
Did you remove commits with regenerated files before the rebase, and then regenerated them again? Otherwise it can be an invalid merge issue.

**Comment by endim8** [comment]
> Did you remove commits with regenerated files before the rebase, and then regenerated them again? Otherwise, it can be an invalid merge issue.

i'm not sure unfortunately, i'll try re-doing it with a copy of the main repo, and see if i get different results

sorry this PR is so messy, i'm still very new to git :/

**Comment by biodranik** [comment]
That's easy, don't worry. If you have a terminal:
```
git checkout master
git pull
git checkout remove_parking_space_icon
git rebase -i master
# Here, remove all commits/lines with rules regeneration, save the file
# After successful rebase, regenerate rules again and commit them.
```

**Comment by endim8** [comment]
It should be right now, finally :)

**Pull request merged**
