### PR TITLE
Add -difficult and -expert hiking path grades

### LINKED ISSUE #6447: Hide trail_visibility=horrible paths
Organic Maps shows trail_visibility=bad, trail_visibility=horrible, trail_visibility=no the same way as regular paths.

Most users will see these as map errors. I for one got lost because of these paths multiple times.

### PR DESCRIPTION
**Pull request by pastk**
Depends on #7925 

- "expert" is dotted black (sac_scale T4+ or "horrible / no" visibility)
- "difficult" is dotted brown (sac_scale T3 or "bad" visibility)
- "normal" is brown dashed

A rough draft (z16, low dpi):
(check more fresh screenshots in later posts)
image

- closes https://github.com/organicmaps/organicmaps/issues/6593
- closes https://github.com/organicmaps/organicmaps/pull/7810
- closes #6447 
- related #7430

### CODE REVIEW

**Comment by biodranik** [comment]
How the map will look in Swiss hikes and in cities?

**Comment by pastk** [comment]
Nothing will change in cities as difficult hiking trails are not supposed to be there :)
What do you mean by Swiss hikes? The tagging is the same. If you want to see some particular Switzerland region then generate the map please, for my laptop its very heavy.

**Comment by pastk** [comment]
In future, marked routes highlighting could be implemented by colored underlines, a rough DEMO

image

**Comment by patepelo** [comment]
It would be cool in the future to add a functionality that when one zooms in to the desired path, the different characteristics appear on pair with the name label. It would act as an interactive legend.

For example:

Zoom 12: "Elephant path"
Zoom 15: "Elephant path / SAC T3"

**Comment by map-per** [comment]
I like this PR, it fits to the OM map style quite well and it is not as experimental as #7810.

I would add these changes to the main style as well, in order to highlight dangerous / difficult paths.

**Comment by pastk** [comment]
Higher dpi screenshots:
Screenshot_1713394052
Screenshot_1713394141

In the main style its the same pattern types but less fat and less visible just like as it is now
Screenshot_1713394280

**Comment by biodranik** [comment]
An important question: do we need many different styles/colors for similar paths in the main style?

**Comment by pastk** [comment]
> An important question: do we need many different styles/colors for similar paths in the main style?

Not really.

Actually initially I was going to display both difficult and expert trails as dotted black in the main style, but then
- users might be confused that translations are different (some "expert", some "difficult") while the looks are the same
- there might be confusion when users switch between styles and some paths change their looks suddenly while others don't
- all these patterns are not screaming different and not attracting attention, so the value of removing one of them doesn't worth the cons IMHO

**Comment by biodranik** [comment]
Conflicts?

Is this change only for outdoors style?

**Comment by pastk** [comment]
> Conflicts?

I'll rebase later when the test data is ready.

> Is this change only for outdoors style?

The last screenshot is for the main style.

**Review by vng — APPROVED** [review]

**Comment by biodranik** [comment]
I'm ok to test these changes in the Outdoor style, but have doubts about the generic main style.

**Comment by vng** [comment]
Regular highway=path is draw same as before.

**Comment by pastk** [comment]
> I'm ok to test these changes in the Outdoor style, but have doubts about the generic main style.

What do you propose for the main style?
The styles could be changed in a separate PR if needed.
But for the Outdoors style to work the new types should be merged and included into the data gen anyway.

**Comment by mpawelski** [comment]
This is a great change. I noticed it while I was in Slovenian mountains and it looks great there. Definitely an improvement. 
My only concern/feedback is that I was not sure what is the difference between these 3 different types of paths. I _guessed_ the brown dashed one is standard, easy path, and had _an intuition_ that the dotted ones are harder, but what is the different between brown and dark?, no idea, I just learned it from this PR. 

I tried selecting the path in hope of some more information but all of these 3 different path are just named "Path".
I think it's worth adding some text info with difficulty info. Even using "Path", "Difficult Path", "Very difficult path" instead of "Path" everywhere would be an improvement.

I think with a planned change that everything is clickable (no need for long tap) it would be quite discoverable for an user.

**Comment by biodranik** [comment]
Proper naming in https://github.com/organicmaps/organicmaps/pull/4242 may help.

Does single-tap work well now for selecting trails? It is in the master/in betas. @strump can it be improved? E.g. to highlight the selected trail in addition to showing a selection circle?

We also discussed an easiest patch to fix: append the trail's details/difficulty into its name.

**Comment by strump** [comment]
@biodranik  you can select a trail with single tap. If track has a name it would be shown on the map and in PlacePage. We don't highlight full track. Sometimes in OSM single track is splitted into multiple short ways. E.g. https://www.openstreetmap.org/way/167995915 Highlighing only short part of a track could be confusing.

**Comment by biodranik** [comment]
Let's create issues:
1. To highlight a tapped track/street
2. To merge reasonable segments when highlighting (tap from search already highlights found streets with names, it will benefit too). Note that similar segments may/should already be merged in generator. Are there cases where we can add to merge in generator?
3. Maybe an issue to make selected street/track transparent should also be created to improve readability.

**Comment by mpawelski** [comment]
> Does single-tap work well now for selecting trails? It is in the master/in betas

@biodranik I tested it on beta. Single-tap worked quite well, but not perfect. In this case sometimes it was a bit tricky, and instead of path, the area next to it was being selected (which was the whole national park in this case). In higher zoom it was a bit easier.

I think regular user should be able to single-tap the path after few tries without much problem. It's nothing terrible, just slight annoyance.

**Comment by biodranik** [comment]
@strump does the tap now use the same pixel radius on different zoom levels to find and select the closest feature?

**Comment by pastk** [comment]
Selecting a line is inconvenient / buggy still https://github.com/organicmaps/organicmaps/issues/8378

**Comment by pastk** [comment]
> Even using "Path", "Difficult Path", "Very difficult path" instead of "Path" everywhere would be an improvement.

Its like that already, but had been translated into a few languages only (e.g. not Polish).
Please check `type.highway.path.difficult` in `types_strings.txt` and feel free to open a PR :)

**Pull request merged**
