### PR TITLE
Flip colours for Porto metro icon

### PR DESCRIPTION
**Pull request by RedAuburn**
Fixes https://github.com/organicmaps/organicmaps/issues/6660

compare the old and new here: https://github.com/organicmaps/organicmaps/pull/6662/commits/32b32651ceea38300fc3f47898619328cd5dcd98

@matheusgomesms do you prefer left or right for dark mode?
image1

### CODE REVIEW

**Comment by matheusgomesms** [comment]
I don't have any preference here, but some people from PT community stated that they preferred the second version (black).

Anyway, thanks a lot for your super quick PR!!!

**Comment by RedAuburn** [comment]
in that case it's good to merge :)

**Review by vng — APPROVED** [review]

**Comment by rtsisyk** [comment]
@RedAuburn is new graphics created on your own?

**Comment by rtsisyk** [comment]
OK, I found https://www.metrodoporto.pt/layout/metroportologo.svg. This is a public graphic, should be ok.

**Review by rtsisyk — APPROVED** [review]

**Pull request merged**
