### PR TITLE
[android-auto] Display all categories on the CategoriesScreen

### PR DESCRIPTION
**Pull request by AndrewShkrob**
image
image
image
image
image
image

### CODE REVIEW

**Comment by biodranik** [comment]
Categories in AA should be 1) filtered out for "drivers only" and 2) sorted by priority like in other maps on cars (e.g. gas stations first, rest areas second, etc.).

**Comment by AndrewShkrob** [comment]
Then let's discuss :)

https://github.com/organicmaps/organicmaps/blob/eaa45903192faccc1e90fcbc0a70ecb2d821213d/android/app/src/main/java/app/organicmaps/car/screens/CategoriesScreen.java#L47-L56

**Comment by biodranik** [comment]
Can we create a Rest Area category for AA? It is critically important for longer drives.

**Review by Jean-BaptisteC — APPROVED** [review]
✅ Pixel 6 - Android 13

**Comment by biodranik** [comment]
> Let's discuss then :)

That list is a good start. LGTM.

**Comment by rtsisyk** [comment]
> Let's discuss then :)
> 
> https://github.com/organicmaps/organicmaps/blob/eaa45903192faccc1e90fcbc0a70ecb2d821213d/android/app/src/main/java/app/organicmaps/car/screens/CategoriesScreen.java#L47-L56

Do we need this PR then? It is already implemented.

**Comment by AndrewShkrob** [comment]
Is this list sufficient? Do we need to include additional categories? What about the ordering?

**Comment by rtsisyk** [comment]
> Is this list sufficient? Do we need to include additional categories? What about the ordering?

It looks good to me.

**Comment by AndrewShkrob** [comment]
I'm closing it because we agreed that the current category list is suitable.

**Pull request closed without merging**
