### PR TITLE
[android]Resolving space at top of pp

### PR DESCRIPTION
**Pull request by unsuman**
Fixes: #4565
I have made the changes by placing the pull icon at the mid, have a look! If it's not ok then I will only reduce the vertical height.

| Before  | After |
| ------------- | ------------- |
| Before | After |
| BeforeGIF | AfterGIF |

### CODE REVIEW

**Comment by matkoniecz** [comment]
At least for me it stops looking like a pull icon.

**Comment by ANS-UXI** [comment]
> At least for me it stops looking like a pull icon.

Noted. Thanks for the feedback!

**Comment by biodranik** [comment]
Interesting, your device has a bigger margin because of the central camera block. How to get its height in Android and compare it with the height of the system toolbar?

**Comment by ANS-UXI** [comment]
> Interesting, your device has a bigger margin because of the central camera block. How to get its height in Android and compare it with the height of the system toolbar?

Ok, let me tinker with this but what exactly do you mean by the height of the system toolbar?

**Comment by arnaudvergnet** [comment]
The status bar size on recent android devices can vary greatly so we should not base the pull icon size on it.

A better way would be to dynamically increase the pull icon area height when we reach fullscreen to the statusbar height. This way we have a small pull icon area when collapsed, but still manage to get a fullscreen view taking into account the varying status bar sizes. But this may be tricky to implement.

**Comment by ANS-UXI** [comment]
> Interesting, your device has a bigger margin because of the central camera block. How to get its height in Android and compare it with the height of the system toolbar?

I got Status bar height of my device to be 89 px but unable to figure out the height of notch!

**Comment by arnaudvergnet** [comment]
To get the statusbar height, you can use `WindowInsetsCompat.getInsets(WindowInsetsCompat.Type.systemBars()).top` (take a look at https://github.com/organicmaps/organicmaps/blob/master/android/src/app/organicmaps/MwmActivity.java#L421). On devices with a notch, this call will return its height.

**Comment by biodranik** [comment]
> The status bar size on recent android devices can vary greatly so we should not base the pull icon size on it.

I meant that we should get the height of the system top bar/notch, and use it dynamically for the Place Page top margin. Or does it already work like this now?

The idea to have a small top margin and increase it only in the full-screen mode is good, but what will be the behavior for longer Place Pages, when they can be scrolled up even further? Should we apply Google's approach here then?

**Comment by arnaudvergnet** [comment]
Right now it is fixed, but if we use the notch size, then for some devices it may be too large again (see the screenshots in README.MD). Using a top header like on google apps may be a good idea but complex to implement.

**Comment by ANS-UXI** [comment]
> To get the statusbar height, you can use `WindowInsetsCompat.getInsets(WindowInsetsCompat.Type.systemBars()).top` (take a look at https://github.com/organicmaps/organicmaps/blob/master/android/src/app/organicmaps/MwmActivity.java#L421). On devices with a notch, this call will return its height.

Thanks but where should I call this?

**Comment by arnaudvergnet** [comment]
I got an idea which could fix both issues. We could reduce the handle view height to a size we find visually nice, and then block the place page from opening behind the statusbar. We can set its max height to notch size + some padding. Users will still be able to scroll the content when this max height is reached, just like it is right now when going fullscreen.

Using this approach we have a pretty handle and we avoid the status bar/notch. I can make a new pr for the max height and we keep this one for the handle height.

**Comment by ANS-UXI** [comment]
> I got an idea which could fix both issues. We could reduce the handle view height to a size we find visually nice, and then block the place page from opening behind the statusbar. We can set its max height to notch size + some padding. Users will still be able to scroll the content when this max height is reached, just like it is right now when going fullscreen.
> 
> 
> 
> Using this approach we have a pretty handle and we avoid the status bar/notch. I can make a new pr for the max height and we keep this one for the handle height.

I like the idea👍🏻

**Comment by biodranik** [comment]
It doesn't look good. Would it be easier to hide the status bar if PP touches it?

**Comment by biodranik** [comment]
@ANS-UXI how Google Maps renders its Place Page on your device with a top-notch?

**Comment by ANS-UXI** [comment]
> @ANS-UXI how Google Maps renders its fully opened Place Page on your device with a top-notch?


https://user-images.githubusercontent.com/79016311/221891232-95f4e784-1e56-4f5d-987e-626a348785ed.mp4

**Comment by ANS-UXI** [comment]
> Thanks! That would be acceptable behavior for OM too. We may even display a piece of the map on the left and on the right from the notch as Apple Maps does.

If OM gonna adapt what Apple Maps does, how about we lower the exposure/brightness of map shown on both side of the notch when PP is fully opened?

**Comment by Jean-BaptisteC** [comment]
Already fixed by Arnaud in other version
Checked on 2023.09.19-15-Google-beta version

**Pull request closed without merging**
