### PR TITLE
[Android] Move layers button to bottom

### PR DESCRIPTION
**Pull request by RedAuburn**
and move help button to hamburger menu

fixes https://github.com/organicmaps/organicmaps/issues/8845

### CODE REVIEW

**Comment by RedAuburn** [comment]
still needs consideration, but hopefully this will make it easier to consider pros/cons :)

**Comment by Misalf-git** [comment]
> maybe merge `About Organic Maps` and `Donate` to `About & Donate`

👍︎

**Comment by biodranik** [comment]
Removal of the About/Help button from the map is not an option, at least now, for many reasons, mentioned many times in the chat and likely on Github too.

What about adding the 5th button, as it was before?

**Comment by RedAuburn** [comment]
> Removal of the About/Help button from the map is not an option, at least now, for many reasons, mentioned many times in the chat and likely on Github too.

I'm not sure which bit of the help page is actually helpful, other than the link to the FAQ. It's times like these where analytics would actually be pretty handy 🙃

**Comment by biodranik** [comment]
For those who missed many discussions with reasons about the presence of the About button on the main screen:

- It helps users to understand that the project is free, open, and built by enthusiasts and thus reduces the number of complaints/demands
- It helps users to understand that it's based on OpenStreetMap data (and reduces a number of "map data is wrong!!! fix it ASAP!!!" or "your maps are fuuuuuuu!" complaints to support)
- It has a FAQ/help section with some answers (we'll add more! and sync it with the website, it [has been done](https://github.com/organicmaps/organicmaps.github.io/pull/246) recently, only adding and translating of the FAQ content should be done now)
- It has Report a bug button to immediately tell us about an issue, and avoid app uninstall/bad rating in any app store
- It has news link, and we plan to get fresh/important news into the app too (About button will be highlighted when important news are there)
- It has contacts/social networks to follow app updates and news
- It has donate button to support the project and increase the chances of building the best maps on the market

We WANT users to press this button and check the content there. Especially new users, who are not aware of OSM, open source, free software, privacy, etc.

**Comment by RedAuburn** [comment]
with all at bottom:


not a fan, personally..

**Comment by RedAuburn** [comment]
i think having the button at the top is the least-worst option at the moment, as it's not pressed that often

**Comment by biodranik** [comment]
@RedAuburn to improve how 5 buttons look at the bottom, you may try to position them like in iOS, equally aligned from any side. Now there are large gaps on the left and on the right.

**Comment by biodranik** [comment]
In the context of switching layers/map styles depending on the user's activity, this button will be more important and used way more frequently.

**Pull request closed without merging**
