### PR TITLE
[android] Migrate Webp images to SVG - Part 1

### PR DESCRIPTION
**Pull request by Jean-BaptisteC**
This PR replace Webp images with SVG like mentionned [here](https://github.com/organicmaps/organicmaps/issues/6196).
I have using [Material Symbols](https://fonts.google.com/icons?icon.set=Material+Symbols)
This changes reduce size of Android app and increase quality of drawables especially on Android Auto (Maybe in the futur on Android Automotive).
I didn't have migrate everything because, I don't want generates regressions (drawables not visible or wrong color in dark mode)

|Before|After|
|-|-|
|ic_arrow_down|arrow_drop_down_FILL0_wght400_GRAD0_opsz24|
|[ic_cancel](https://github.com/organicmaps/organicmaps/raw/a4d62e6022a257313f6d342e797340900b9a2420/android/app/src/main/res/drawable-hdpi/ic_cancel.webp)|close_FILL0_wght400_GRAD0_opsz24|
|[ic_checkbox_add](https://github.com/organicmaps/organicmaps/raw/a4d62e6022a257313f6d342e797340900b9a2420/android/app/src/main/res/drawable-hdpi/ic_checkbox_add.webp)|add_box_FILL0_wght400_GRAD0_opsz24|
|[ic_checkmark](https://github.com/organicmaps/organicmaps/raw/a4d62e6022a257313f6d342e797340900b9a2420/android/app/src/main/res/drawable-hdpi/ic_checkmark.webp)|check_FILL0_wght400_GRAD0_opsz24|
|[ic_done](https://github.com/organicmaps/organicmaps/raw/a4d62e6022a257313f6d342e797340900b9a2420/android/app/src/main/res/drawable-hdpi/ic_done.webp)|done_FILL0_wght400_GRAD0_opsz24|
|[ic_down](https://github.com/organicmaps/organicmaps/raw/a4d62e6022a257313f6d342e797340900b9a2420/android/app/src/main/res/drawable-hdpi/ic_down.webp)|expand_more_FILL0_wght400_GRAD0_opsz24|
|[ic_email](https://github.com/organicmaps/organicmaps/raw/a4d62e6022a257313f6d342e797340900b9a2420/android/app/src/main/res/drawable-hdpi/ic_email.webp)|alternate_email_FILL0_wght400_GRAD0_opsz24|
|[ic_error_white](https://github.com/organicmaps/organicmaps/raw/a4d62e6022a257313f6d342e797340900b9a2420/android/app/src/main/res/drawable-hdpi/ic_error_white.webp)|warning_FILL1_wght400_GRAD0_opsz24|
[ic_expand_less](https://github.com/organicmaps/organicmaps/raw/a4d62e6022a257313f6d342e797340900b9a2420/android/app/src/main/res/drawable-hdpi/ic_expand_less.webp)|expand_less_FILL1_wght400_GRAD0_opsz24|
|[ic_expand_more](https://github.com/organicmaps/organicmaps/raw/a4d62e6022a257313f6d342e797340900b9a2420/android/app/src/main/res/drawable-hdpi/ic_expand_more.webp)|expand_more_FILL1_wght400_GRAD0_opsz24|
|[ic_explore](https://github.com/organicmaps/organicmaps/raw/a4d62e6022a257313f6d342e797340900b9a2420/android/app/src/main/res/drawable-hdpi/ic_explore.webp)|explore_FILL1_wght400_GRAD0_opsz24|
|[ic_lock](https://github.com/organicmaps/organicmaps/raw/a4d62e6022a257313f6d342e797340900b9a2420/android/app/src/main/res/drawable-hdpi/ic_lock.webp)|lock_FILL1_wght400_GRAD0_opsz24|
|[ic_mic_white](https://github.com/organicmaps/organicmaps/raw/a4d62e6022a257313f6d342e797340900b9a2420/android/app/src/main/res/drawable-hdpi/ic_mic_white.webp)|mic_FILL1_wght400_GRAD0_opsz24|

Tested on Pixel 6 - Android 14 in light and dark mode
With this change, we save 30 Ko in apk size

### CODE REVIEW

**Comment by biodranik** [comment]
Thanks! It's a great idea. But it is also important to keep icons consistent to avoid confusing users. Let's carefully compare what was replaced with what.

**Comment by Jean-BaptisteC** [comment]
I have fixed all issues about icon colors in light and dark mode
Tell me, if you want before/after screenshots in the app.
All icons I have updated have the same dimensions and the same look (except ic_lock, but this icon is not visible in app), I have also respected when icons are filled or not.

**Comment by biodranik** [comment]
It's easier to test it on the device, right? Thank you for your work, save your time for other tasks )

**Comment by Jean-BaptisteC** [comment]
Yes, icons updated are used in the editor, bookmark, downloader and routing plan fragment

**Review by biodranik — APPROVED** [review]
Merci !

**Comment by Jean-BaptisteC** [comment]
I have noticed a wrong icon color in layout used to remove closed hours.
I fixed this in a few days.

**Pull request merged**
