### PR TITLE
[android] Modify Storage Path Fragment to use Progress Bar instead of Progress Dialog

### PR DESCRIPTION
**Pull request by Arthur-GYT**
All is in the title ^^.

### CODE REVIEW

**Comment by biodranik** [comment]
What does this change improve? How it looks like?

**Comment by Arthur-GYT** [comment]
#3629

And for the UI :

**Comment by Jean-BaptisteC** [comment]
When progress bar is shown, is it possible to select another storage?
Please use Material Linear progress indicator instead appcompat progress bar
Can you check similar dialog in bookmarks activity?

**Comment by Arthur-GYT** [comment]
> When progress bar is shown, is it possible to select another storage? Please use Material Linear progress indicator instead appcompat progress bar Can you check similar dialog in bookmarks activity?

In my tests, it's not possible to select another storage when progress bar is shown.

**Pull request closed without merging**
