### PR TITLE
Added Search Privacy feature

### PR DESCRIPTION
**Pull request by sandy99405**
Here is the screen recording of the output

https://github.com/organicmaps/organicmaps/assets/55664068/ea814611-e591-4cc8-aeab-44950c860d5f

- The switch is enabled by default
- When enabled, the search window will show History and Categories tabs
- When disabled, both History and Categories tabs will be hidden and all the Recent Searches will be cleared

### CODE REVIEW

**Comment by Jean-BaptisteC** [comment]
Please do not close PR to open another PR, if you have need help with Git, we can help you :)

**Comment by sandy99405** [comment]
I'm sorry about that. There were few conflicts while rebasing, so the entire code has changed while resolving. That's why i had to close the PR.

**Comment by Jean-BaptisteC** [comment]
Check this to reduce indexing on Android Studio
https://github.com/organicmaps/organicmaps/blob/master/docs/INSTALL.md#reduce-resource-usage

**Comment by sandy99405** [comment]
@Jean-BaptisteC  Can you please help me with Git?

There seems to be no conflicts 

(should I still fetch and rebase) or ( just add them to the staging area and push them to the remote ?)

**Pull request closed without merging**
