### PR TITLE
[Android] button for bug report on fatal error

### PR DESCRIPTION
**Pull request by RedAuburn**
Allows people to send logs about the fatal errors, hopefully will help solve the case of the phantom MicroSD card 🕵️‍♂️

bitmap

### CODE REVIEW

**Review by biodranik — COMMENTED** [review]
@RedAuburn thanks! You've tested it, right? Do logs in .zip collected properly?

OK button doesn't make any sense here, so let's remove it and replace by Report a bug.

**Comment by RedAuburn** [comment]
> @RedAuburn thanks! You've tested it, right? Do logs in .zip collected properly?

The log doesn't seem to collect any info about the IOException, but it still has useful info like device, version, android version etc. the SD issue stacktrace is sent in the email content.

> OK button doesn't make any sense here, so let's remove it and replace by Report a bug.

good point, will do :)

**Comment by biodranik** [comment]
If the exception itself is also present in the body of the email, then we're fine. This is the only missing part now. We don't know what causes this exception in all reported cases.

**Comment by RedAuburn** [comment]
removed OK button

**Review by biodranik — COMMENTED** [review]
And what happens now after sending a bug report? )

**Review by biodranik — APPROVED** [review]
Thanks!

**Comment by biodranik** [comment]
@RedAuburn Do you see these errors on the master?

```
/Users/alex/Developer/omim/omim/android/app/src/main/java/app/organicmaps/SplashActivity.java:116: error: method sendBugReport in class Utils cannot be applied to given types;
          (dialog, which) -> Utils.sendBugReport(
                                  ^
  required: ActivityResultLauncher<SharingIntent>,Activity,String,String
  found:    SplashActivity,String,String
  reason: actual and formal argument lists differ in length
/Users/alex/Developer/omim/omim/android/app/src/main/java/app/organicmaps/SplashActivity.java:117: error: incompatible types: SplashActivity cannot be converted to ActivityResultLauncher<SharingIntent>
            this,
            ^

```

**Comment by RedAuburn** [comment]
> @RedAuburn Do you see these errors on the master?

mm.. am looking now

**Pull request merged**
