### PR TITLE
[linux] Use OpenGL ES 3.0 instead of desktop OpenGL

### PR DESCRIPTION
**Pull request by Ferenc-**
Fixes:
1. https://github.com/flathub/app.organicmaps.desktop/issues/50
2. The annoying `drape/gl_functions.cpp:1150 CheckGLError(): SrcPoint  drape/gl_functions.cpp:1126 glLineWidth():  GLError: GL_INVALID_VALUE` on the current `master` , which flooded the logs in debug mode.

### CODE REVIEW

**Review by biodranik — COMMENTED** [review]
There are so many ifdefs and cases, it becomes harder to understand and maintain. Do you have any ideas on how this ogl related logic can be simplified for all platforms?

It would be also great to reuse Metal from iOS implementation on MacOS, but that's another story.

**Comment by Ferenc-** [comment]
There are so many ifdefs and cases, it becomes harder to understand and maintain.

This PR only adds `3` new ones, the rest of the if statements were already there, only the condition changed.
At a cost of some extra code duplication, perhaps we could reasonably reduce the number of new ones to `2`.
Alternatives to the code duplication, is using runtime polimorphism to re-use the common parts but that comes at the cost of efficiency, or using parametric polimorphism which will require a bit more skills in template metaprogramming to maintain.

And not using ogl on MacOS (but Metal), would reduce the ifdefs that this commit adds by one.
Although it will introduce a few new one instead... But as you said, that is another story.

**Comment by Ferenc-** [comment]
@biodranik Your kind input here is appreciated.

**Review by biodranik — COMMENTED** [review]
Need to check it on MacOS first.

**Comment by Ferenc-** [comment]
> Need to check it on MacOS first.

@vng Would you have capacity to test on MacOS?

**Comment by Ferenc-** [comment]
@pastk Could you provide feedback?

**Comment by vng** [comment]
Will check. I have a general concern here why do we treat all Linux as ES (3) capable? For example, MacOS has 4+ core version and only 2 ES version drivers.

Are there any pros, except the glWidth warnings? Should we support Core GL profile in future or ES will be enough for all our needs?

**Comment by Ferenc-** [comment]
> why do we treat all Linux as ES (3) capable?

@biodranik commented [here](https://github.com/organicmaps/organicmaps/pull/2947#discussion_r1254637796), that: `"it would be much easier to support only mobile ES versions + Vulkan and Metal."` 
And I can't help but agree.
Currently the completely confusing and misleading ES 3 code path on Linux relies on Desktop OpenGL 3.2 and not ES.
The users who were using this code path, will now either use OpenGL ES 2 or 3. (Wayland dynamically selects it, and X11 uses the hardcoded 3.0, but we can change it to 2.0 if there is at least a single user who needs that, or make it cli switchable).

I have never seen a Linux driver which was capable of Desktop OpenGL 3.2, and not capable of at least ES 2 or even ES 3.
For the long term goal Vulkan is in the making, but that seems to be a little bit bigger beast to tackle, so first let's focus on the lack of proper ES 3 which is fixed by this PR.

> For example, MacOS has 4+ Core version and only 2 ES version drivers.

The MacOS code path is not impacted in this PR. The long term future plan is to use Metal instead of OpenGL on MacOS.

> Are there any pros, except the glWidth warnings? 

1.  The simplification of the codebase
2.  Covering mobile hardware where ES 3 is supported but desktop OpenGL 3 is not. I think these are the very same reason why the Android codebase is also ES 3 and not desktop OpenGL 3.

> Should we support Core GL profile in future or ES will be enough for all our needs?

In my understanding, the plan is that instead of Core GL, Vulkan would be used, which is more future proof.
In general I am not against Core GL support, I am just not sure it is worth the investment, when Vulkan is more future proof,
and the rest of the codebase already supports Vulkan to an extent.

**Comment by pastk** [comment]
This PR works well on my Ubuntu 18.04.

Moreover, the rendering looks faster with it!! (subjective, I didn't do any measurements)
So maybe it fixes what "was broken" by a Qt6 migration? https://github.com/organicmaps/organicmaps/issues/5391

Startup logs changes.
"Before" (master):
```
LOG TID(1) INFO      1.17841 qt_common/map_widget.cpp:366 initializeGL(): Vendor: Intel 
Renderer: Mesa Intel(R) HD Graphics 5500 (BDW GT2) 
Version: 4.6 (Core Profile) Mesa 22.3.7 
Shading language version:
 4.60 
Extensions: 
LOG TID(1) INFO      1.17845 qt_common/map_widget.cpp:385 initializeGL(): Contex is LibGL
LOG TID(1) INFO      1.17846 qt_common/map_widget.cpp:394 initializeGL(): OpenGL version is at least 3.2, enabling GLSL '#version 150 core'
LOG TID(1) INFO      1.18067 drape_frontend/visual_params.cpp:58 Init(): Visual scale = 1 ; Tile size = 512
...
LOG TID(3) INFO      1.18526 drape/support_manager.cpp:35 Init(): Renderer = Mesa Intel(R) HD Graphics 5500 (BDW GT2) | Api = OpenGLES3 | Version = 4.6 (Core Profile) Mesa 22.3.7
LOG TID(3) INFO       1.1853 drape/support_manager.cpp:79 Init(): Max line width = 7 | Max texture size = 16384
```

"After" / this PR:
```
LOG TID(1) INFO      1.07128 qt_common/map_widget.cpp:403 initializeGL(): Vendor: Intel 
Renderer: Mesa Intel(R) HD Graphics 5500 (BDW GT2) 
Version: OpenGL ES 3.2 Mesa 22.3.7 
Shading language version:
 OpenGL ES GLSL ES 3.20 
Extensions: GL_EXT_blend_minmax GL_EXT_multi_draw_arrays GL_EXT_texture_filter_anisotropic GL_EXT_texture_compression_s3tc GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_format_BGRA8888 GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth24 GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_mapbuffer GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_stencil8 GL_OES_texture_3D GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_half_float GL_EXT_draw_instanced GL_EXT_texture_sRGB_decode GL_OES_EGL_image GL_OES_depth_texture GL_AMD_performance_monitor GL_OES_packed_depth_stencil GL_EXT_texture_type_2_10_10_10_REV GL_NV_conditional_render GL_OES_get_program_binary GL_APPLE_texture_max_level GL_EXT_discard_framebuffer GL_EXT_read_format_bgra GL_NV_pack_subimage GL_EXT_frag_depth GL_NV_fbo_color_attachments GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_array_object GL_OES_viewport_array GL_ANGLE_pack_reverse_row_order GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_EXT_occlusion_query_boolean GL_EXT_robustness GL_EXT_texture_rg GL_EXT_unpack_subimage GL_NV_draw_buffers GL_NV_read_buffer GL_NV_read_depth GL_NV_read_depth_stencil GL_NV_read_stencil GL_EXT_draw_buffers GL_EXT_map_buffer_range GL_KHR_debug GL_KHR_robustness GL_KHR_texture_compression_astc_ldr GL_NV_pixel_buffer_object GL_OES_depth_texture_cube_map GL_OES_required_internalformat GL_OES_surfaceless_context GL_EXT_color_buffer_float GL_EXT_debug_label GL_EXT_sRGB_write_control GL_EXT_separate_shader_objects GL_EXT_shader_group_vote GL_EXT_shader_implicit_conversions GL_EXT_shader_integer_mix GL_EXT_tessellation_point_size GL_EXT_tessellation_shader GL_INTEL_performance_query GL_ANDROID_extension_pack_es31a GL_EXT_base_instance GL_EXT_compressed_ETC1_RGB8_sub_texture GL_EXT_copy_image GL_EXT_draw_buffers_indexed GL_EXT_draw_elements_base_vertex GL_EXT_gpu_shader5 GL_EXT_polygon_offset_clamp GL_EXT_primitive_bounding_box GL_EXT_render_snorm GL_EXT_shader_io_blocks GL_EXT_texture_border_clamp GL_EXT_texture_buffer GL_EXT_texture_cube_map_array GL_EXT_texture_norm16 GL_EXT_texture_view GL_KHR_blend_equation_advanced GL_KHR_context_flush_control GL_KHR_robust_buffer_access_behavior GL_NV_image_formats GL_NV_shader_noperspective_interpolation GL_OES_copy_image GL_OES_draw_buffers_indexed GL_OES_draw_elements_base_vertex GL_OES_gpu_shader5 GL_OES_primitive_bounding_box GL_OES_sample_shading GL_OES_sample_variables GL_OES_shader_io_blocks GL_OES_shader_multisample_interpolation GL_OES_tessellation_point_size GL_OES_tessellation_shader GL_OES_texture_border_clamp GL_OES_texture_buffer GL_OES_texture_cube_map_array GL_OES_texture_stencil8 GL_OES_texture_storage_multisample_2d_array GL_OES_texture_view GL_EXT_blend_func_extended GL_EXT_buffer_storage GL_EXT_float_blend GL_EXT_geometry_point_size GL_EXT_geometry_shader GL_EXT_shader_samples_identical GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_KHR_texture_compression_astc_sliced_3d GL_OES_EGL_image_external_essl3 GL_OES_geometry_point_size GL_OES_geometry_shader GL_OES_shader_image_atomic GL_EXT_clear_texture GL_EXT_clip_cull_distance GL_EXT_disjoint_timer_query GL_EXT_texture_compression_s3tc_srgb GL_MESA_shader_integer_functions GL_EXT_clip_control GL_EXT_color_buffer_half_float GL_EXT_memory_object GL_EXT_memory_object_fd GL_EXT_semaphore GL_EXT_semaphore_fd GL_EXT_texture_compression_bptc GL_EXT_texture_mirror_clamp_to_edge GL_KHR_parallel_shader_compile GL_EXT_EGL_image_storage GL_EXT_shader_framebuffer_fetch_non_coherent GL_EXT_texture_shadow_lod GL_INTEL_blackhole_render GL_MESA_framebuffer_flip_y GL_NV_compute_shader_derivatives GL_EXT_demote_to_helper_invocation GL_EXT_depth_clamp GL_EXT_texture_query_lod GL_MESA_bgra 
LOG TID(1) INFO      1.07137 qt_common/map_widget.cpp:430 initializeGL(): OpenGL version is at least 3.0, enabling GLSL '#version 300 es'
LOG TID(1) INFO      1.07432 drape_frontend/visual_params.cpp:58 Init(): Visual scale = 1 ; Tile size = 512
...
LOG TID(3) INFO      1.08019 drape/support_manager.cpp:35 Init(): Renderer = Mesa Intel(R) HD Graphics 5500 (BDW GT2) | Api = OpenGLES3 | Version = OpenGL ES 3.2 Mesa 22.3.7
LOG TID(3) INFO      1.08072 drape/support_manager.cpp:79 Init(): Max line width = 7 | Max texture size = 16384
```

**Comment by pastk** [comment]
> Moreover, the rendering looks faster with it!! (subjective, I didn't do any measurements) So maybe it fixes what "was broken" by a Qt6 migration? #5391

I've measured a bit more objectively and there seems to be no speed up actually.

**Comment by Ferenc-** [comment]
> > Moreover, the rendering looks faster with it!! (subjective, I didn't do any measurements) So maybe it fixes what "was broken" by a Qt6 migration? #5391
> 
> I've measured a bit more objectively and there seems to be no speed up actually.

Thanks for testing. Any veto on merging this?

**Review by biodranik — APPROVED** [review]
Ok, let's see how it works.

**Pull request merged**
