### PR TITLE
[android] Map buttons fixes

### PR DESCRIPTION
**Pull request by arnaudvergnet**
Replaces https://github.com/organicmaps/organicmaps/pull/3392

Makes all map buttons background 80% alpha as requested in https://github.com/organicmaps/organicmaps/pull/2905#issuecomment-1243056354.

Also replaces search and menu icons with better SVGs. Finally makes sure the position icon is fully opaque.

| Day mode | Night mode |
|-|-|
| Screenshot_1663069953 | Screenshot_1663069964 |

### CODE REVIEW

**Review by vng — APPROVED** [review]

**Review by biodranik — APPROVED** [review]
Thanks! It looks great!

1. Is the white color on buttons at night mode exactly the same as it is in stores now? Subjectively, it looks brighter in your change (maybe I'm wrong).
2. Buttons are hardly visible now in the night mode. Would it be possible to make some (barely visible) gray contour around them? This is probably for another PR.

**Comment by arnaudvergnet** [comment]
1. In the stores, the map buttons are a bit grey, only the bottom bar is white. In light mode they both use the same color. I don't know why there was a difference but I prefer how it is in this PR, it is easier to see.
2. I can try to experiment in another PR with the opacity and contour.

**Comment by biodranik** [comment]
Found a few more issues after testing (they can be fixed later separately):

0. THE IMPORTANT ONE! Location button icons changed and become non-intuitive/different from what it was before. Users will highly likely be confused. Previous icons (non-vertical filled arrow and vertical filled arrow with a vertical line) were very intuitive for corresponding modes. We need to find corresponding icons in vector form or ask someone to draw them.
1. In the market version zoom buttons are brighter in the night mode, but layers and crosshair are a bit darker.
2. + and - in zoom buttons should be slightly larger.
3. Menu lines should be slightly larger and bolder.
4. Star icon has different shape now, it would be great to find a similar shape :)

**Review by rtsisyk — APPROVED** [review]

**Comment by biodranik** [comment]
@arnaudvergnet not sure that "the same stule" is a proper case here. We need different icons, and if nobody can draw them, then let's use different sources to unblock the development.

The rounded star can be used from Android Studio icons (they actually match most of the Material Icons).

Different colors were probably better to visually distinguish plus and minus zoom buttons. But let's see how it goes with real users.

**Comment by biodranik** [comment]
I would also add that the dark style is mainly designed now for driving a car at night. It would be great if someone tries it and says if buttons are too bright or not.

**Comment by arnaudvergnet** [comment]
@biodranik I updated the navigation icons what do you think ? https://github.com/organicmaps/organicmaps/pull/3407

**Pull request merged**
