### PR TITLE
[ios] Making headers bold

### PR DESCRIPTION
**Pull request by angelina-p09**
* fixes: #3280
Signed-off-by: Angelina Perez <perezangelina.0907@gmail.com>

### CODE REVIEW

**Comment by angelina-p09** [comment]
There are pictures of the changes posted on the issue.

**Review by vng — APPROVED** [review]
I like new screenshots. Probably, worth checking languages where these strings are long ..

**Comment by angelina-p09** [comment]
> I like new screenshots. Probably, worth checking languages where these strings are long ..

Thank you for pointing that out. I checked on different devices and the only one with the length issue is the iPhone 5s. I attached two screenshots. the first image is bold and 20 size font then the second one is bold 18. The two languages that I found that had long strings were greek(26 chars) and Italian(28 chars). They both looked great with bold 18 instead of bold 20.

**Comment by biodranik** [comment]
> I checked on different devices and the only one with the length issue is the iPhone 5s.

Would it be possible to automatically shrink the text to fit the width in such cases?

**Comment by angelina-p09** [comment]
This [documentation](https://developer.apple.com/documentation/uikit/uifont/scaling_fonts_automatically) covers automatic font scaling. The suggested way was to use `UIFont.preferredFont(forTextStyle: ... )` in code. I used  `UIFont.preferredFont(forTextStyle: .headline)` to achieve the screenshots below. This [documentation](https://developer.apple.com/design/human-interface-guidelines/foundations/typography#specifications) covers the font styles within the `UIFont.preferredFont(forTextStyle: ... )`. Headline is the only semi-bold font. It gives the font size 17.00 pt for iPhone13 and iPhone 5. But for iPad, it gives the font size 21.00 pt. Let me know if this is the preferred style. 

Although the heaviest weight for `UIFont.preferredFont(forTextStyle: )` is semibold, we can override different text styles to display a bigger font as bold. For example,  `UIFont.preferredFont(forTextStyle: .title3 , compatibleWith: UITraitCollection(legibilityWeight: .bold))`. `UITraitCollection(legibilityWeight: ... )`  is only available for iOS 13.0 or newer, but I noticed that the app supports iOS 12. For simplicity, I did not use this approach. 

iPhone13:


IPhone 5s:


iPad Pro (5th generation):

**Comment by biodranik** [comment]
There is no need to force bold style. It would be better if our dialogs will look more similar to other iOS dialogs, e.g. the "standard" semibold style will be used.

**Review by biodranik — COMMENTED** [review]
@angelina-p09 thanks! Does it look good in dark mode?

**Comment by angelina-p09** [comment]
Sorry, I am not that well-versed in git. I wanted to add the sign-off to the commits that were missing it by using the DCO instructions but it also added all the other commits in the process. would you recommend I open a different pr for this change or how could I clean up the added commits?

**Comment by angelina-p09** [comment]
>  Does it look good in dark mode?

Yea it looks good in dark mode. I attached an image below.

**Comment by biodranik** [comment]
1. Please, do not open a new PR!
2. Learn about `git rebase` command, and rebase your branch on top of the master branch.
3. Squash all your commits with the interactive rebase into one.
4. Sign it with `git commit --amend -s`.
5. Force-push your branch here with `git push -f`

**Comment by biodranik** [comment]
Please do not close the PR!

**Comment by angelina-p09** [comment]
The UI on github allowed me to discard commits, unfortunately I didn't count the amount and it also discarded my changes. Reopening with a single commit, sorry about the headache!

**Review by biodranik — APPROVED** [review]
Thank you for your contribution! And welcome to the club ;-)

**Comment by biodranik** [comment]
It's better to master git from the command line ;-)

**Comment by angelina-p09** [comment]
Thank you for the welcome and the advice! :))

**Pull request merged**
