### PR TITLE
[drape] do not enable antialiasing in subway layer

### LINKED ISSUE #3526: Subway layer is slow/laggy
When enabling the subway layer, the map looses a lot of FPS. It does not matter if we are in a city with metro or in the middle of nowhere, the performance is heavily impacted by this layer. This is not the case with the elevation layer.

Tried on Android 10.

### PR DESCRIPTION
**Pull request by arnaudvergnet**
Fixes performance issues on some Android devices

Fixes #3526

### CODE REVIEW

**Comment by biodranik** [comment]
Please check if something else should be reverted from this commit: https://github.com/mapsme/omim/commit/ec47c41a1654a5c95dd6c5c905adc3b900e6f6f1

**Comment by biodranik** [comment]
@arnaudvergnet ^^^

@vng 
```
Running world_feed_tests.cpp::Transit_GTFS_ProjectStopToLine_Simple
FAILED
world_feed_tests/world_feed_tests.cpp:237 TEST(ResT(5, false) == PrepareNearestPointOnTrack(point_C, std::nullopt, shape.size() , Direction::Backward, shape)) (5, 0) (6, 0) 
```

**Comment by arnaudvergnet** [comment]
I'm not familiar with the C++ codebase but it seems the other changes allow remembering the AA state.

**Review by vng — APPROVED** [review]
Well, I agree that FPS (everywhere) is better than some artifacts on low res devices.

**Comment by vng** [comment]
The only thing is that I'd leave AA when m_isAntialiasingEnabled var is true.

**Comment by arnaudvergnet** [comment]
That line is only here to force AA in case it was not enabled before, and to not disable it when hiding the layer if it was globally on.
If the goal is to keep AA as it was, then completely removing the line will do the trick I guess.

Regarding the `ifndef`, it is also present in `case Message::Type::SetPosteffectEnabled`, so I guess the iphone simulator is not compatible with AA.

**Comment by vng** [comment]
Ah, ok.

**Comment by biodranik** [comment]
Why m_isAntialiasingEnabled can't be removed? It was introduced in the original Mapsme commit that forced AA for subways, right?

**Comment by vng** [comment]
Don't remove. This is a general AA flag for the whole app.

**Comment by arnaudvergnet** [comment]
Removed references to that variable. Instead of commenting out the code, I simply removed it and added comments.

**Review by biodranik — APPROVED** [review]
Almost great! I would also shift comments to indent them with the code :)

**Pull request merged**
