### PR TITLE
Update app screenshots with latest UI

### PR DESCRIPTION
**Pull request by Jean-BaptisteC**
This PR is a temporary solution, while we wait development to generate automatically app screenshots.
- I have already worked on app screenshots on the website (https://github.com/organicmaps/organicmaps.github.io/pull/145), but I have wasted a lot of time generating exactly which screenshots you want.
- I have tried to do the same screenshots but the styles are very different from the start and it seems the device used for the first screenshots has a quad HD resolution.
- The size of screenshots is different, I have tried to resize but the looks are not good.
- Screenshots are in full quality, not compressed

Todo:

- [ ] Add tablet screenshots

[Google Guidelines](https://support.google.com/googleplay/android-developer/answer/9866151?hl=en#zippy=%2Cscreenshots)

### CODE REVIEW

**Comment by biodranik** [comment]
Thanks! What are Google Play requirements? Which resolutions are missing? How many screenshots are possible? Is there a way to also add a video screen recording (a short features demo for example)?

**Comment by Jean-BaptisteC** [comment]
I don't have device with Quad HD resolution :)

**Comment by biodranik** [comment]
Can simulator be used for that? A beta build should not print debug info.

**Comment by Jean-BaptisteC** [comment]
There are no emulators with the same resolution.

**Comment by Jean-BaptisteC** [comment]
Old screenshots has been made with Samsung phone

**Comment by biodranik** [comment]
> There are no emulators with the same resolution.

I saw an option to create a custom device with a custom resolution in the Emulator. Won't it work?

**Comment by Jean-BaptisteC** [comment]
I can try but with custom resolution, but screenshots in Quad HD doesn't take all space of screen, when we check screenshots from Play store.
You can compare on your mobile, these apps
- https://play.google.com/store/apps/details?
id=org.eu.exodus_privacy.exodusprivacy
- https://play.google.com/store/apps/details?id=app.organicmaps

**Comment by biodranik** [comment]
As far as we meet Google Play requirements, and screenshots looks good in store on different devices, it should be fine:
https://support.google.com/googleplay/android-developer/answer/9866151?hl=en#zippy=%2Cscreenshots

```
Requirements

To publish your store listing, you must provide a minimum of two screenshots across form factors that meet the following requirements:

    JPEG or 24-bit PNG (no alpha)
    Minimum dimension: 320px
    Maximum dimension: 3840px 
        The maximum dimension of your screenshot can't be more than twice as long as the minimum dimension.

Highly recommended

    Some sections of Google Play show groups of recommended apps and games in a large format using screenshots. To be eligible for recommendations in formats that use screenshots, the following guidelines are a requirement:
        For apps, you must provide at least four screenshots with minimum 1080px resolution. These should be 16:9 for landscape (minimum 1920x1080px) screenshots and 9:16 for portrait screenshots (minimum 1080x1920px).
        For games you must provide at least three 16:9 landscape screenshots (minimum 1920x1080px) or three 9:16 portrait screenshots (minimum 1080x1920px). Make sure that these screenshots depict the in-game experience so users can get a sense of what the gameplay will be like if they download and play
    Screenshots must demonstrate the actual in-app or in-game experience, focusing on the core features and content so users can anticipate what the app or game experience will be like.
        Use captured footage of the app or game itself. Do not include people interacting with the device (for example, fingers tapping on the device), unless the core gameplay or app usage is off-device.
    Stylized screenshots that break UI across multiple uploaded images are allowed, but prioritize UI in the first three screenshots as much as possible.
```

```
Large screens:

    For Chromebook and tablets, you can add a minimum of 4 screenshots to demonstrate your in-app experience.
    Upload screenshots between 1,080 and 7,680px
    Use a 16:9 aspect ratio for landscape and a 9:16 aspect ratio for portrait
    Exclude additional text that is not part of your core app experience, as this can get cut off on Play homepages on certain screen sizes
    Don't forget to optimize your app quality for large screens by [reviewing our app quality checklist](https://developer.android.com/distribute/googleplay/quality/tablet.html)
```

**Comment by Jean-BaptisteC** [comment]
I have created an emulator with custom dimensions and I have generated new screenshots.
But it's not easy, because I need to use an app to do native screenshots and Organic Maps crash few seconds after start routing :(
Please review

**Comment by biodranik** [comment]
@Jean-BaptisteC wow, what kind of crash? Let's fix it.

**Review by biodranik — APPROVED** [review]
Thanks! @rtsisyk can you please double check so these screenshots will be properly updated in every store?

@Jean-BaptisteC is it possible to automate screenshots creation for different languages?

**Comment by Jean-BaptisteC** [comment]
I have this error few second after routing has started. I use Pixel 6 pro like emulator. I have 4 Go of RAM
```
2024-05-18 21:35:53.507  2345-2724  OMcore app.organicmaps.web  E vulkan/vulkan_object_manager.cpp:347 FlushUnsafe(): CHECK(statusCode == VK_SUCCESS) Vulkan error: vkFlushMappedMemoryRanges(m_device, 1, &mappedRange) finished with code VK_ERROR_OUT_OF_HOST_MEMORY
2024-05-18 21:35:53.507  2345-2724  libc app.organicmaps.web A Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 2724 (Thread-19), pid 2345 (organicmaps.web)
```

**Comment by biodranik** [comment]
@Jean-BaptisteC does it also reproduce with these changes? https://github.com/organicmaps/organicmaps/pull/8139

**Comment by Jean-BaptisteC** [comment]
I want finish this PR, for tablet do you want ?
- Landscape screenshots
- Portrait screenshots
- Landscape + portrait screenshots (It's already the case on Play Store)

**Comment by biodranik** [comment]
@Jean-BaptisteC vulkan issue should be fixed if you use two related PRs.

The more screenshots the better! Google Play requirements are here: https://support.google.com/googleplay/android-developer/answer/9866151?hl=en#zippy=%2Cscreenshots

Btw, do we use feature graphics? It's also listed there.

**Pull request merged**
