### PR TITLE
[android] Migrate AnchorBottomSheetBehavior to BottomSheetBehavior

### PR DESCRIPTION
**Pull request by arnaudvergnet**
This MR is continuing the work to solve #1745. This is a small refactoring to replace usages of [AnchorBottomSheetBehavior](https://github.com/trafi/anchor-bottom-sheet-behavior) by Google's [BottomSheetBehavior](https://developer.android.com/reference/com/google/android/material/bottomsheet/BottomSheetBehavior). Conversion has been simple as both components use the same API. The only noticeable change is the `anchored` state from AnchorBottomSheetBehavior: it is called `half_expanded` in BottomSheetBehavior.

I was thus able to remove the `com.trafi:anchor-bottom-sheet-behavior` dependency.

I also removed any usage of the anchored/half expanded state. Now the sheets can only be hidden, collapsed (only the top visible) or expanded which gives better UX. I was only able to reproduce the anchored/half expanded state on POIs with Wikipedia articles. Here is a before/after comparison:

### Before

When the sheet is fully open (takes the full height), doing a small swipe will make it go to the anchored state, requiring the user to do a second swipe to enter the collapsed state and finally a third swipe for the hidden state.

https://user-images.githubusercontent.com/80701113/175771768-19df06f8-36a2-4352-a1a6-5e20070583a5.mp4

### After

Even when the sheet is fully opened, doing a small swipe will make the sheet go directly in collapsed state. The user only needs one more swipe to collapse the sheet.

https://user-images.githubusercontent.com/80701113/175771770-32b86e0b-1430-450f-a6fa-176d96b080f8.mp4

### Elevation profile

When looking through the place page code, I found references to an **elevation profile place page**, but I was not able to find a way to open it. Does anyone know what is this used for? If it is not used, removing it would greatly simplify the place page code.

### Styling

The place page style has not been changed in this PR. The goal is to use the same styling as in the other bottom sheets from my previous PRs. Do you want me to create a new PR or include the changes in this one?

### CODE REVIEW

**Comment by biodranik** [comment]
1. Am I correctly understood that opening the PP will stop at the screen's maximum height? And then the user needs to manually scroll PP?
2. Isn't the elevation profile the same that is reused when the foot/cycling route is built? If it is, then it makes sense to split it up, e.g. Place Page for a map object should be different from the Route Preview information panel.

**Comment by arnaudvergnet** [comment]
1. Yes this works exactly as before. The only UX change is that there are now only 3 possible positions (hidden, collapsed, expanded) for the sheet, not 4.

2. This is what the layout `elevation_profile_bottom_sheet` looks like. Never seen this in the app.
Screenshot_20220625_150452

**Comment by arnaudvergnet** [comment]
Editing the style was simpler than I thought. Here is the result:

| Portrait | Landscape |
|-|-|
| Screenshot_1656167235 | Screenshot_1656167252 |
| Screenshot_1656167240 | Screenshot_1656167257 |

If you like this design I can add it to this PR.

**Comment by biodranik** [comment]
Wow, that's probably an unfinished feature for hiking. Is it possible to enable it / finish it?

I assume that this info can be displayed in the PP if an imported track is selected, or if we allow to select existing tracks on the map.
Also displaying these values in the current routing preview also would be great, users requested it.

**Comment by arnaudvergnet** [comment]
> Wow, that's probably an unfinished feature for hiking. Is it possible to enable it / finish it?
> 
> I assume that this info can be displayed in the PP if an imported track is selected, or if we allow to select existing tracks on the map. Also displaying these values in the current routing preview also would be great, users requested it.

I have not looked into it yet so I will leave it as it is. Maybe someone can make it work in another PR.

**Comment by arnaudvergnet** [comment]
I pushed the updated style for the place page. If everything is good for you we can merge. Should I create an issue for the elevation profile page?

**Comment by biodranik** [comment]
Yes please!

**Review by biodranik — APPROVED** [review]

**Pull request merged**
