### PR TITLE
[styles] Remove transparent circles & fix some night icon colours

### PR DESCRIPTION
**Pull request by endim8**
### Changed icons:

**Removed circle:**
- defibrillator-m.svg 
- firehydrant-m.svg 
- phone-m.svg 
- picnic_table-m.svg
- postbox-m.svg 
- recycling-m.svg 
- shower-m.svg 
- geyser-s/m/l.svg
- waterfall-s/m.svg
- vending-m.svg
- picnic_site/shelter
- drinking_water

**fixed night icon colour:**
- picnic_table-m.svg
- shower-m.svg
- storage_tank.svg
- vending-m.svg

discussed at https://github.com/organicmaps/organicmaps/issues/2181#issuecomment-1055310182

edit:
this is what i used to find the circles, it may be useful in the future: 

``` bash
grep -lnr "opacity=\"0.2\"" *;
```

### CODE REVIEW

**Comment by biodranik** [comment]
Thanks! It looks better now. tourism:picnic_site and shelter icons are still drawn in (dark) circles. @pastk should we draw them in the same way as tables? It would be (probably) easier for people if only businesses are drawn in circle icons. The same question is for information icons.

Also, I would try to remove a circle from a drinking water/fountain icon, it's too attractive now, especially on the dark background. Probably, it makes sense to also make it a bit lighter for the dark theme.

**Comment by endim8** [comment]
> Thanks! It looks better now. tourism:picnic_site and shelter icons are still drawn in (dark) circles. @pastk should we draw them in the same way as tables? It would be (probably) easier for people if only businesses are drawn in circle icons. The same question is for information icons.

These two use the same icon (picnic-m.svg), I'll remove the dark circle, but it'll make it hard to differentiate between a picnic_site and a picnic bench as they would be the same. For the shelter, I think switching to a hut icon would be better, something like this:


> Also, I would try to remove a circle from a drinking water/fountain icon, it's too attractive now, especially on the dark background. Probably, it makes sense to also make it a bit lighter for the dark theme.

I'll fix the drinking water & fountain icons for sure 👍 thank you for the feedback :)

Maybe it'd be a good idea to write up a style specification? Then icon elements wouldn't have inconsistent meanings etc

**Comment by biodranik** [comment]
> Maybe it'd be a good idea to write up a style specification? Then icon elements wouldn't have inconsistent meanings etc

That is a good idea, I think we can gradually create it by incremental changes. Writing a full spec now is hard. Here are some raw ideas:

- Support different styles where the same icons may be highlighted (e.g. water/shelter icons can be more attractive on a hiking/cycling style)
- Try to make this base "generic" style as universal and convenient as possible for many users and use cases.
- Round icons are great for businesses. Some color coding is already used, it would be great to make it consistent.
- Square icons are for transport.
- "No geometry" icons are some simple and popular objects, usually required only on the detailed zoom levels.

It would be great to aggregate some best ideas from other maps. Let's brainstorm!

**Comment by endim8** [comment]
@biodranik this can be merged now btw :)

**Comment by pastk** [comment]
Let me test how it looks on different backgrounds first, please...

**Comment by pastk** [comment]
> For the shelter, I think switching to a hut icon would be better, something like this: 
> 

Yes shelter needs a different icon definitely.
However I'd suggest an icon depicting a roof only (and perhaps a rain above it), i.e. there should be no tables etc. depicted inside.

**Comment by biodranik** [comment]
> However I'd suggest an icon depicting a roof only (and perhaps a rain above it), i.e. there should be no tables etc. depicted inside.

Agree, something like this:

image

**Comment by endim8** [comment]
> > However I'd suggest an icon depicting a roof only (and perhaps a rain above it), i.e. there should be no tables etc. depicted inside.
> 
> Agree, something like this:
> 
> image

I'll try making one similar to this 👍 should it be included in this PR?

**Comment by endim8** [comment]
> However I'd suggest an icon depicting a roof only (and perhaps a rain above it), i.e. there should be no tables etc. depicted inside.

How is this? 

Day: shelter-m-day Night: shelter-m-night

i've added it to my survey_point branch  (https://github.com/endim8/organicmaps/commit/dec30c6cf4a2fa4f1bf26cdb85138841234490ec)

**Comment by biodranik** [comment]
Let's improve shelters in another PR. Also, I would change information point signs from filled round circles to something else. Maybe "i" inside an unfilled circle? Or something like this? Would it be correct if the information point doesn't show a direction?

image

**Comment by biodranik** [comment]
@endim Users complain that they can't see waterfall icons on the map. Let's make them in a more dark blue (maybe like in OSM) and increase a bit (if possible).

**Pull request merged**
