### PR TITLE
[styles] Add commemorative plaque icon

### PR DESCRIPTION
**Pull request by j13m126**
What do you think? 

Bildschirmfoto vom 2022-05-28 20-08-34
Bildschirmfoto vom 2022-05-28 20-09-08

[source](https://github.com/gravitystorm/openstreetmap-carto/tree/master/symbols)

### CODE REVIEW

**Comment by biodranik** [comment]
1. Let's remove the round background for the icon. The goal is to make the map less polluted, and to make a shape-coding: round background means a business/govt place of some kind.

**Comment by j13m126** [comment]
I like this even more!

**Review by biodranik — APPROVED** [review]
@vng I'm ok to merge

**Review by vng — APPROVED** [review]

**Comment by vng** [comment]
Agree, don't want to make squash here, but can't make rebase-merge. Please, delete middle commits:
- regenerated
- revert regenerated
And leave only last regenerated commit.

**Comment by vng** [comment]
I  can help you with that and make force push into your j13m126:master branch.
BTW, better to make different dev branches rather than master.

**Comment by j13m126** [comment]
> I can help you with that and make force push into your j13m126:master branch. BTW, better to make different dev branches rather than master.

Please do. Thank you, I'll use a different branch in the future.

**Pull request merged**
