### PR TITLE
[android-auto] FreeDrive Screen

### PR DESCRIPTION
**Pull request by AndrewShkrob**
Closes: https://github.com/organicmaps/organicmaps/issues/7501
Closes: https://github.com/organicmaps/organicmaps/issues/7064

Screenshot 2024-03-11 at 19 23 38
Screenshot 2024-03-11 at 20 37 49

Icon: https://www.svgrepo.com/svg/81709/steering-wheel
License: [CC0 License](https://www.svgrepo.com/page/licensing/#CC0)

### CODE REVIEW

**Review by Jean-BaptisteC — APPROVED** [review]
✅ Pixel 6 - Android 14 + AA Emulator
One suggestion: Is it possible to keep same place for settings button?

**Comment by AndrewShkrob** [comment]
> Is it possible to keep same place for settings button?

Done.

**Review by biodranik — APPROVED** [review]
That's great, thank you @AndrewShkrob and @Jean-BaptisteC !

**Comment by Miq1** [comment]
Brilliant! thanks a lot! 👍🏻

**Pull request merged**
