### PR TITLE
Revert "[editor] Fix parsing of 'off' opening hours (#7652)"

### PR DESCRIPTION
**Pull request by kirylkaveryn**
This reverts commit ff703e83d60a5f9c3cee9b97919397c9b08f6e2d.

Reopens #1612

### CODE REVIEW

**Comment by biodranik** [comment]
@kirylkaveryn is DCO missing?

**Comment by kirylkaveryn** [comment]
@biodranik fixed

**Review by biodranik — APPROVED** [review]
Дзякуй!

**Comment by vng** [comment]
Seems like we can make a better fix by checking on empty string (like in Android) and ASSERT ...

**Pull request merged**
