### PR TITLE
Restore WunderLINQ Support

### PR DESCRIPTION
**Pull request by blackboxembedded**
Hi,

A few years back I had submitted some PRs([1](https://github.com/mapsme/omim/pull/13198) & [2](https://github.com/mapsme/omim/pull/12316)) to Maps.me to add WunderLINQ hardware control support.  They were accepted but at some point after the ability to launch the requesting app with ESCAPE broke in the Android and iOS apps

I've recently discovered this awesome project and wanted to fix up WunderLINQ support and start promoting and suggesting it to our customers.

The WunderLINQ enables you to use your motorcycle's handlebar controls to control your smartphone. Essentially the device acts as a Bluetooth keyboard.  Our apps are also open source.

Here is a video of the integration in action: https://youtu.be/2QHUiheVF5c

### CODE REVIEW

**Review by biodranik — CHANGES_REQUESTED** [review]
1. Why did you touch icu submodule?
2. There is already BACK_URL in android/src/com/mapswithme/maps/MwmActivity.java
3. Our core API always used backurl, not back_url (see `map/map_tests/mwm_url_tests.cpp` for examples), only in 2019 mapsme team added back_url for Android only. Why do you need it with the underscore?

**Comment by blackboxembedded** [comment]
> 1. Why did you touch icu submodule?
Weird, I didn't mean to touch the icu module.
> 2. There is already BACK_URL in android/src/com/mapswithme/maps/MwmActivity.java
It was not working, so I just mimicked the Mapsme patch.  I can look deeper to see what the problem is.
> 3. Our core API always used backurl, not back_url (see `map/map_tests/mwm_url_tests.cpp` for examples), only in 2019 mapsme team added back_url for Android only. Why do you need it with the underscore?
I changed to match Android for consistency.

**Comment by biodranik** [comment]
Please carefully check existing code to avoid any unnecessary "patches".

Regarding the underscore, it is a bad situation. We need to either support both variants, with and without the underscore or drop one variant, potentially breaking other apps' compatibility. You can not ignore the fact that the core works without the underscore.

**Comment by blackboxembedded** [comment]
> Please carefully check existing code to avoid any unnecessary "patches".
> 
> Regarding the underscore, it is a bad situation. We need to either support both variants, with and without the underscore or drop one variant, potentially breaking other apps' compatibility. You can not ignore the fact that the core works without the underscore.

Thanks for the advice.  I will redo my PR.

**Comment by blackboxembedded** [comment]
> 2. There is already BACK_URL in android/src/com/mapswithme/maps/MwmActivity.java

It looks like BACK_URL in android/src/com/mapswithme/maps/MwmActivity.java relies on it being added to the intent, which doesn't appear to be happening anymore.  What is the proper way to get the "backurl" or "back_url" parameter now?

**Comment by blackboxembedded** [comment]
Reopened new one here: https://github.com/organicmaps/organicmaps/pull/3039

**Pull request closed without merging**
