### PR TITLE
[search] Treat "taxi" as Transport.

### PR DESCRIPTION
**Pull request by vng**
Closes https://github.com/organicmaps/organicmaps/issues/9302

### CODE REVIEW

**Comment by dvdmrtnz** [comment]
Taxi seems to be fixed. 👍

However playground/toy stores still make each other disappear when selecting "Family Holiday" category as shown [here](https://github.com/organicmaps/organicmaps/issues/9302#issuecomment-2365172259).

**Review by dvdmrtnz — APPROVED** [review]
Now it works correctly! Thanks!

**Comment by pastk** [comment]
Looking at the code its hard to say why making "playground as Attraction" fixes the issue :)

But if it works then its OK :)

**Comment by dvdmrtnz** [comment]
> Looking at the code its hard to say why making "playground as Attraction" fixes the issue :)

I also don't understand why that's necessary. In fact, I have tried removing that change and it seems to work fine too. What seems to have fixed the bug here is the commit `[search] Conform kCategoriesHasName with kViewportDiffThreshold`

**Comment by vng** [comment]
Ok, do not treat a "playground" as an Attraction.

**Pull request merged**
