### PR TITLE
show water POI later in main style

### PR DESCRIPTION
**Pull request by RedAuburn**
fixes https://github.com/organicmaps/organicmaps/issues/7169 and #7164 

before
Screenshot from 2024-01-17 15-36-05

after
Screenshot from 2024-01-17 15-39-25

### CODE REVIEW

**Comment by dvdmrtnz** [comment]
It looks like your regeneration script didn't recompile after the changes in https://github.com/organicmaps/organicmaps/pull/7118 and the icons are 0.75x downscaled. Can you try to delete the organicmaps/out folder and run again the tools/unix/generate_styles.sh script?

**Comment by RedAuburn** [comment]
> It looks like your regeneration script didn't recompile after the changes in #7118 and the icons are 0.75x downscaled.

good catch, is it right now?

**Comment by dvdmrtnz** [comment]
> > It looks like your regeneration script didn't recompile after the changes in #7118 and the icons are 0.75x downscaled.
> 
> good catch, is it right now?

It's good now 👍

**Comment by pastk** [comment]
I've reduced water sources visibilities in https://github.com/organicmaps/organicmaps/pull/7056 already from z15- to z16-.

Let's discuss if they should be made even less visible.

E.g. on my phone screen when water appears at z16 its about 600 meters of distance fitting into a screen horizontally, which I consider a walking distance.
There was a lot of positive feedback with people appreciating OM helping them to find water easily in the cities on hot days.
So we need to find a good balance between not cluttering the map and keeping a nice and appreciated feature usable.

Making water sources visible on z18- looks too much for me.

Making them z17- might be OK, but I'm not sure either. Let's discuss!

Also lowering the springs and hot springs that much... Its not something encountered in urban areas often, right?

**Comment by biodranik** [comment]
The tests should be done on mobile screens, not on the desktop. The release looks like this:

telegram-cloud-photo-size-2-5289570267808517886-y

**Review by vng — APPROVED** [review]
What is the status here? @biodranik screenshot definitely shows the current problem, IMO.

**Comment by biodranik** [comment]
I want to understand the change better. The issue on my screenshot should be fixed by likely increasing the zoom level by one, no?

Why other types are changing their zoom level?

**Comment by pastk** [comment]
> What is the status here? @biodranik screenshot definitely shows the current problem, IMO.

Zurich is well and densely mapped, there it looks like too many water sources indeed...
In other areas mapped water sources could be scarce, hence the change could be detrimental.
I would be great if someone could make some more screenshots (using the current master or last release) of different areas...

I've started working on a PR to reduce visibilities of many outdoors-specific POIs in the main style already, so I can incorporate the change in there, no prob. But better to test more first.

**Comment by pastk** [comment]
Looks like the current balance of opinions is to leave it as is.
(https://t.me/organicmaps/37788)

image

**Pull request closed without merging**
