### PR TITLE
Use NotoSans for Hebrew instead of Serif

### PR DESCRIPTION
**Pull request by biodranik**
See https://github.com/organicmaps/organicmaps/issues/8779#issuecomment-2282868981

Before | After
-|-
выява|выява

@NeatNit is it better now?

### CODE REVIEW

**Comment by NeatNit** [comment]
It's better, but the kerning seems bad in various places.

**Comment by biodranik** [comment]
> It's better, but the kerning seems bad in various places.

@NeatNit hm, interesting! Can you please highlight where exactly?

**Comment by NeatNit** [comment]
I don't know if it's the font or if the rendering engine is doing it a disservice. It's obvious to me in these places: 
הגימנסיה העברית הרצליה
סביבת ככר המדינה

hold on, I'll go to my computer where it's easier to look stuff up

**Comment by NeatNit** [comment]
This page https://fonts.google.com/noto/specimen/Noto+Sans?preview.text=%D7%94%D7%92%D7%99%D7%9E%D7%A0%D7%A1%D7%99%D7%94%20%D7%94%D7%A2%D7%91%D7%A8%D7%99%D7%AA%20%D7%94%D7%A8%D7%A6%D7%9C%D7%99%D7%94 lists about a million languages but not Hebrew. Are you sure that's the font being used? Maybe it's falling back to something else?

That preview text fails to display anything.

**Comment by NeatNit** [comment]
Oh, probably this I guess https://fonts.google.com/noto/specimen/Noto+Sans+Hebrew?preview.text=%D7%94%D7%92%D7%99%D7%9E%D7%A0%D7%A1%D7%99%D7%94%20%D7%94%D7%A2%D7%91%D7%A8%D7%99%D7%AA%20%D7%94%D7%A8%D7%A6%D7%9C%D7%99%D7%94 shapes seem to match.

The kerning in this preview looks good, so the rendering of it might be wrong. My uneducated guess: whatever rules control the kerning are being applied backwards. The kerning that's supposed to come *after* a letter is being applied *to the right* of it (i.e. before it), and vice versa.

**Comment by NeatNit** [comment]
image
image

**Comment by NeatNit** [comment]
FWIW I think the bad kerning affects the previous font as well. I didn't notice before because the font itself was awful by itself. You could consider the bad kerning a separate issue.

I think I'm done now :)

**Comment by biodranik** [comment]
So the issue is with י character being too far from ל character, right?

выява
выява

**Comment by NeatNit** [comment]
> So the issue is with י character being too far from ל character, right?

Exactly. The ס too in הגימנ**סי**ה (GH's font makes it look like a lowercase O, but it's Samech)

**Comment by biodranik** [comment]
Interesting, our code takes shaping values from the font, with one caveat: the same font size is used, and then kerning values are scaled to the necessary real size.

Which other font may look better?

**Comment by NeatNit** [comment]
> Which other font may look better?

I really have no idea, never been a topography geek. The only font I can name is Arial, lol.

Who's to say that the same issue wouldn't happen with every other font? Did you consider my theory that basically the kerning might be applied incorrectly for RTL text? If so, IMHO you should stick with NotoSans, merge this PR, and consider the bad kerning a separate issue. 

It's not unreadable. It's fine.

**Comment by biodranik** [comment]
If the issue was caused by a wrong direction processing, then it would break significantly in other languages like Arabic and Hindi.

@vng PTAL

**Review by vng — APPROVED** [review]

**Pull request merged**
