### PR TITLE
Community feedback for :hungary: 

### PR DESCRIPTION
**Pull request by d4f5409d**
No. 1 https://matrix.to/#/!kzBidywONsbbZNRSrP:matrix.org/$sm2Jxq2C3xQQILdf_pGovFW5TBHlS8whg0rIWRjCwiI?via=matrix.org&via=grin.hu&via=beeper.com 
No. 2 https://matrix.to/#/!kzBidywONsbbZNRSrP:matrix.org/$UZtI2M0-Exv0DsPWYnSjeBW3ZDh0dWdQkM5nzWthxs0?via=matrix.org&via=grin.hu&via=beeper.com 
No. 3 https://matrix.to/#/!kzBidywONsbbZNRSrP:matrix.org/$afurYF52XwVynyO0cWaoGsEaum3DLGrLhyFOYmZoJgU?via=matrix.org&via=grin.hu&via=beeper.com 
No. 4 https://matrix.to/#/!kzBidywONsbbZNRSrP:matrix.org/$GLz2K4YHKMQ9oq0JC1x417W7cA6qRgT88NtSkvQOXzQ?via=matrix.org&via=grin.hu&via=beeper.com 
No. 5 https://matrix.to/#/!kzBidywONsbbZNRSrP:matrix.org/$leLIAV_PWGiMxRVkPvDaOnNDWUTnHvHiN38Vyfk3OHY?via=matrix.org&via=grin.hu&via=beeper.com

### CODE REVIEW

**Comment by biodranik** [comment]
@d4f5409d thanks! Can you please sign your commit with
```
git commit --amend -s
git push -f
```
?

**Comment by d4f5409d** [comment]
I was afraid of that sentence.

Let me try tomorrow. Can't promise anything though.

**Comment by d4f5409d** [comment]
Everything's fine now I guess. I wonder why it didn't let me do that yesterday. :thinking:

**Review by biodranik — APPROVED** [review]
Igen, köszönöm!

**Pull request merged**
