### PR TITLE
[docs] Use the new Play Store badge

### PR DESCRIPTION
**Pull request by meenbeese**
Signed-off-by: meenbeese <meenbeese@tutanota.com>

### CODE REVIEW

**Review by biodranik — COMMENTED** [review]
1. Why do you want to change it?
2. Why is the size different from the old version/other badges?

**Comment by meenbeese** [comment]
1. Google recently changed the logo (and consequently the badge) of the Play Store, which means that the one we currently use is outdated. I just added the new one to fix this.
2. This is because I could not find a different size of this badge. However, this does not affect the look of it in the README as it looks perfectly aligned with other badges.

**Review by rtsisyk — CHANGES_REQUESTED** [review]
Please use the same size.

**Comment by meenbeese** [comment]
The resizing is done!

**Comment by RedAuburn** [comment]
It looks like the lower resolution image was upscaled, could you use this native resolution one?
google-play-badge

**Comment by meenbeese** [comment]
> It looks like the lower resolution image was upscaled, could you use this native resolution one? google-play-badge

Thank you for this. It looks much better now!

**Review by biodranik — APPROVED** [review]
Thank you!

**Pull request merged**
