### PR TITLE
Render oneway arrows more often

### LINKED ISSUE #2351: 1-way roads are not visualised properly in some situations
IMHO 1-way roads should be visualised much more intense. Compare OM vs GM at
https://www.openstreetmap.org/query?lat=35.15716&lon=33.35381#map=18/35.15716/33.35381
image
image

### PR DESCRIPTION
**Pull request by pastk**
Fixes #2351 and a part of #1241

### CODE REVIEW

**Comment by pastk** [comment]
oneway

I didn't touch the priorities.
Also it seems that the arrows are not affected by the features displacement logic.

**Review by vng — COMMENTED** [review]
Good, but I suspect that more often arrows can cause rare street names (Seems like arrows always displace names).
IMHO, we should make complex fix for arrows and street names. Or I can't check drawing quality otherwise.

**Comment by pastk** [comment]
> Good, but I suspect that more often arrows can cause rare street names (Seems like arrows always displace names). IMHO, we should make complex fix for arrows and street names. Or I can't check drawing quality otherwise.

Nope, the arrows do not displace street names:
overlap

It seems they're rendered at the same layer / as part of street lines themselves, contrary to street names which are a collection of displaceable glyph objects drawn on top of the street lines.

**Review by biodranik — APPROVED** [review]
@vng Let's merge it as is, it makes the map better.

**Pull request merged**
