### PR TITLE
[Android] refactor opening uris (open in another app now in new activity)

### PR DESCRIPTION
**Pull request by RedAuburn**
fixes https://github.com/organicmaps/organicmaps/issues/9327

https://developer.android.com/guide/components/intents-common says that StartActivity will fail if no apps are available, so need to call ResolveActivity() first.
StartActivity() doesn't throw AndroidRuntimeException, looks like it was a hack to get around not having ResolveActivity.

Also adds a toast to inform the user that no apps were found to handle the intent:

### CODE REVIEW

**Comment by RedAuburn** [comment]
hang on, gonna do it better

**Review by vng — APPROVED** [review]

**Comment by map-per** [comment]
I think the string "No App installed that can open the location" would be clearer than "Your device can't find anything to open this with"

**Comment by RedAuburn** [comment]
> I think the string "No App installed that can open the location" would be clearer than "Your device can't find anything to open this with"

as i mentioned above, openUri() is used in multiple places, so the easiest way is to use a generic message. But i'll refactor openUri() to pass a fail message argument 👍️

**Comment by RedAuburn** [comment]
now using string suggested by map-per 👍️

**Pull request merged**
