### PR TITLE
[Android] Debug and Beta app icon

### PR DESCRIPTION
**Pull request by strump**
Added custom icon for Debug build type.
Changed Beta build type backgound color.
Added icons for Android 7.1 and older.

## Android 13
android-13

## Android 13 Tablet
android-13-tablet

## Android 7.1
android-7 1

### CODE REVIEW

**Review by vng — APPROVED** [review]

**Review by biodranik — APPROVED** [review]
Thank you! It looks cool )

**Comment by Jean-BaptisteC** [comment]
Looks is bad with themed icon on Android 13

**Comment by biodranik** [comment]
@Jean-BaptisteC do you have screenshots? How it can be improved?

**Comment by strump** [comment]
@Jean-BaptisteC  I created an issue #6565
Do you have the same icon problem?

**Comment by Jean-BaptisteC** [comment]
Yes

**Pull request merged**
