### PR TITLE
Pass NextStreet to TTS for pedestrians as well as "cars" (everyone else)

### LINKED ISSUE #8887: TTS should announce street names for walking directions
Currently when on foot and "announce street names" is checked, street names are still never announced. 

Part of this problem is the case where a footway near a street has no name, but that is partially solved already (the name still appears at the top of the screen.)

The majority of the problem is that the street announcing code simply doesn't run in foot instructions mode. If I recall correctly there's a simple if-else at the top of the file that should be removed.

### PR DESCRIPTION
**Pull request by zyphlar**
Fixes #8887

### CODE REVIEW

**Comment by zyphlar** [comment]
Should be ready to beta test, a pretty simple change

**Review by biodranik — APPROVED** [review]
Thanks! Let's test it.

**Comment by matheusgomesms** [comment]
Can this also be used for cycling? :)

**Comment by zyphlar** [comment]
@matheusgomesms it should already work for cycling (I've been using spoken street names on bicycle for months in release) there was just an if-else for `turn.m_turn != CarDirection::None` that output the `m_pedestrianTurn` case that I think was only used for pedestrian directions.

**Pull request merged**
