### PR TITLE
[tools] Remove unused python tools

### PR DESCRIPTION
**Pull request by dbf256**
I started initial review of python2 scripts to update them to python3 to remove dependency on outdated python.
I discovered these 3 python2 scripts, that looks outdated and are not referenced anywhere in sh scripts/build process, so I have an idea just to remove them. Looks like opentable is related to some partner data and po_parser/categories_converter is for some outdated translations method.
Let me know if they are still required so I can convert them to python3.

### CODE REVIEW

**Comment by pastk** [comment]
`categories_converter.py` could be possibly used later to merge categories.txt and strings.txt (#1841) and / or to re-format categories.txt (sort languages, etc..)
`po_parser.py` could be possibly used for weblate migration #659 (`po` files could be used as a bridge between weblate and OM)

Both are not likely to happen soon I think, so we can remove the scripts and possibly pull the code from the history if we need it. Or add comments to the scripts' headers with links to issues they could be used in.

**Comment by dbf256** [comment]
@pastk I can restore removed files, but looks like they are broken now - they use import of find_untranslated_strings that I was not able to find in code base.

**Comment by pastk** [comment]
Yeap I know they're broken. I don't mind if you remove them now - if we ever need them we can restore from the history and there are mentions in related issues to remind that they existed.

**Review by pastk — APPROVED** [review]

**Review by biodranik — COMMENTED** [review]
Conversion may be useful if it's easy to convert.

Is there any open opentable data available?

**Review by vng — COMMENTED** [review]
I don't think that we should delete this outdated/unused scripts. They look more/less reasonable for the future and will be updated when needed.

**Comment by dbf256** [comment]
> Conversion may be useful if it's easy to convert.

Based on your and @vng comments I see that you want to keep these scripts in repo.
As I mentioned categories_converter.py and po_parser.py are a bit broken now (imports are not valid) I can try to fix them.

> 
> Is there any open opentable data available?

Looks like there is some affiliate program https://dev.opentable.com/ and docs are not available without login https://dev.opentable.com/partner-portal/#/?referrer=documentation and accounts are approved manually https://dev.opentable.com/affiliate-partners/ so doesn't looks like some partner program, not a very open datasource.

**Comment by pastk** [comment]
> 
> Based on your and @vng comments I see that you want to keep these scripts in repo. As I mentioned categories_converter.py and po_parser.py are a bit broken now (imports are not valid) I can try to fix them.
> 

They're broken because no one had used them for a long time (so no one cared about updating them while changing their dependencies). Its likely we will not need them any more. So I suggest to just add a comment there stating that they need to be fixed and migrated to python 3 if there is a need in the code.

**Comment by dbf256** [comment]
Ok, looks like there are different opinions mentioned above on it (while I personally prefer not to keep unused code in repo), so I'll just leave it as is.

**Pull request closed without merging**
