### PR TITLE
[ios] Remove unused banner-related code

### PR DESCRIPTION
**Pull request by cyber-toad**
Some banner-related code, looks unused. I am not able to test iOS version, but I tried using actions: https://github.com/cyber-toad/organicmaps/actions/runs/4518919606

### CODE REVIEW

**Comment by biodranik** [comment]
Need to test it on a real device or in the simulator to confirm that nothing broke (it shouldn't, but who knows?)

**Comment by cyber-toad** [comment]
Yep, I don't have apple devices, so would be good if someone could have a look

**Comment by Jean-BaptisteC** [comment]
@matheusgomesms can you test with simulator? :)

**Comment by matheusgomesms** [comment]
> @matheusgomesms can you test with simulator? :)

What I should look at, exactly? Didn't quite understand the PR :(

**Comment by Jean-BaptisteC** [comment]
Just check downloader IHM and bookmarks IHM works properly on IOS

**Comment by biodranik** [comment]
It's ok. Also, maybe try something like this? 
image

**Comment by matheusgomesms** [comment]
> Just check downloader IHM and bookmarks IHM works properly on IOS

I checked it and it seems normal to me, didn’t see any issues. If there’s anything special to be seen, let me know!

**Comment by cyber-toad** [comment]
@biodranik please take a look - looks like it was checked for ios in emulator.

**Review by biodranik — APPROVED** [review]
Thank you!

**Pull request merged**
